name = "LeanBridge"
defaultTargets = ["LeanBridge"]

[leanOptions]
pp.unicode.fun = true
autoImplicit = false
relaxedAutoImplicit = false

[[require]]
name = "checkdecls"
git = "https://github.com/PatrickMassot/checkdecls.git"

[[require]]
name = "«doc-gen4»"
git = "https://github.com/leanprover/doc-gen4"
rev = "v4.30.0-rc2"

[[require]]
name = "mathlib"
git = "https://github.com/CBirkbeck/mathlib4.git"
rev = "combined-e4e6-sturm"

[[lean_lib]]
name = "LeanBridge"
