import Mathlib.AlgebraicGeometry.EllipticCurve.Affine.Point
import Mathlib.AlgebraicGeometry.EllipticCurve.NormalForms
import Mathlib.AlgebraicGeometry.EllipticCurve.Reduction
import Mathlib.Analysis.SpecialFunctions.Log.Basic
import Mathlib.RingTheory.Radical.NatInt

/-!
# Elliptic curve definitions for LeanBridge (chapter 4)

Definitions from the LMFDB elliptic-curve knowls that are not (yet) in mathlib, written here in
mathlib style for the LeanBridge blueprint audit.
-/

namespace WeierstrassCurve

open IsLocalRing

section FiniteField

variable {F : Type*} [Field F] [Finite F]

/-- The **trace of Frobenius** `a = #F + 1 - #E(F)` of a Weierstrass curve over a finite field
`F`. -/
noncomputable def traceOfFrobenius (E : WeierstrassCurve F) : ℤ :=
  (Nat.card F : ℤ) + 1 - Nat.card E.toAffine.Point

/-- A Weierstrass curve over a finite field is **supersingular** if its characteristic divides its
trace of Frobenius. In characteristic `2` and `3` this is not equivalent to the vanishing of the
trace (Silverman, *The Arithmetic of Elliptic Curves*, V.3.1). -/
def IsSupersingular (E : WeierstrassCurve F) : Prop :=
  (ringChar F : ℤ) ∣ traceOfFrobenius E

/-- A Weierstrass curve over a finite field is **ordinary** if it is not supersingular. -/
def IsOrdinary (E : WeierstrassCurve F) : Prop :=
  ¬ E.IsSupersingular

end FiniteField

section Reduction

universe u v
variable (R : Type v) [CommRing R] [IsDomain R] [IsDiscreteValuationRing R]
variable {K : Type u} [Field K] [Algebra R K] [IsFractionRing R K]

/-- A minimal Weierstrass curve over `K` has **bad reduction** (LMFDB `ec.bad_reduction`) if it
does not have good reduction, i.e. its reduction over the residue field of `R` is singular. -/
def IsBadReduction (W : WeierstrassCurve K) [IsMinimal R W] : Prop :=
  ¬ HasGoodReduction R W

/-- An elliptic curve over `K` has **potential good reduction** (LMFDB
`ec.potential_good_reduction`) if it has good reduction over some finite extension of `K`,
formalized via the equivalent condition that its `j`-invariant is integral over `R`
(Silverman, *The Arithmetic of Elliptic Curves*, VII.5.5). -/
def IsPotentialGoodReduction (W : WeierstrassCurve K) [W.IsElliptic] : Prop :=
  ∃ r : R, algebraMap R K r = W.j

/-- A Weierstrass curve over `K` with good reduction has **good ordinary reduction** (LMFDB
`ec.good_ordinary_reduction`) if its reduction over the finite residue field of `R` is
ordinary. -/
def IsGoodOrdinaryReduction [Finite (ResidueField R)] (W : WeierstrassCurve K)
    [HasGoodReduction R W] : Prop :=
  IsOrdinary (W.reduction R)

/-- A Weierstrass curve over `K` with good reduction has **good supersingular reduction** (LMFDB
`ec.good_supersingular_reduction`) if its reduction over the finite residue field of `R` is
supersingular. -/
def IsGoodSupersingularReduction [Finite (ResidueField R)] (W : WeierstrassCurve K)
    [HasGoodReduction R W] : Prop :=
  IsSupersingular (W.reduction R)

/-- A minimal Weierstrass curve over `K` has **non-split multiplicative reduction** (LMFDB
`ec.nonsplit_multiplicative_reduction`) if it has multiplicative reduction that is not split. -/
def IsNonsplitMultiplicativeReduction (W : WeierstrassCurve K) [IsMinimal R W] : Prop :=
  HasMultiplicativeReduction R W ∧ ¬ HasSplitMultiplicativeReduction R W

/-- The **local minimal discriminant** (LMFDB `ec.local_minimal_discriminant`) of a Weierstrass
curve over `K`: the ideal of `R` generated by the discriminant of a local minimal model. -/
noncomputable def localMinimalDiscriminant (W : WeierstrassCurve K) : Ideal R :=
  Ideal.span {(integralModel R (W.minimal R)).Δ}

/-- The **reduction type** (LMFDB `ec.reduction_type`) of an elliptic curve at a prime: **good**,
**multiplicative** (split or non-split), or **additive**. -/
inductive ReductionType
  | good
  | multiplicative (split : Bool)
  | additive

end Reduction

section GlobalMinimal

open IsDedekindDomain

variable {O : Type*} [CommRing O] [IsDedekindDomain O]

/-- A Weierstrass curve over `FractionRing O` is a **global minimal model** (LMFDB
`ec.global_minimal_model`) if it is integral over `O` and minimal over the discrete valuation ring
`Localization.AtPrime v.asIdeal` at every height-one prime `v` of `O`. -/
def IsGlobalMinimalModel (W : WeierstrassCurve (FractionRing O)) : Prop :=
  IsIntegral O W ∧ ∀ v : HeightOneSpectrum O,
    haveI : IsDiscreteValuationRing (Localization.AtPrime v.asIdeal) :=
      IsLocalization.AtPrime.isDiscreteValuationRing_of_dedekind_domain O v.ne_bot _
    IsMinimal (Localization.AtPrime v.asIdeal) W

/-- A Weierstrass curve over `FractionRing O` is a **semi-global minimal model** (LMFDB
`ec.semi_global_minimal_model`) if it is integral over `O` and minimal at every height-one prime
of `O` except possibly one. An elliptic curve over a number field of class number greater than one
need not admit a global minimal model, but it always admits a semi-global one. -/
def IsSemiGlobalMinimalModel (W : WeierstrassCurve (FractionRing O)) : Prop :=
  IsIntegral O W ∧ ∃ v₀ : HeightOneSpectrum O, ∀ v : HeightOneSpectrum O, v ≠ v₀ →
    haveI : IsDiscreteValuationRing (Localization.AtPrime v.asIdeal) :=
      IsLocalization.AtPrime.isDiscreteValuationRing_of_dedekind_domain O v.ne_bot _
    IsMinimal (Localization.AtPrime v.asIdeal) W

/-- The **minimal discriminant ideal** (LMFDB `ec.minimal_discriminant`) of a Weierstrass curve
over `FractionRing O`: the finite product `∏ᵥ 𝔭ᵥ ^ eᵥ` over the height-one primes `v` of `O`,
where `eᵥ` is the `v`-adic valuation of the discriminant of a local minimal model at `v`. If `W`
admits a global minimal model, this is the principal ideal generated by its discriminant. -/
noncomputable def minimalDiscriminantIdeal (W : WeierstrassCurve (FractionRing O)) : Ideal O :=
  ∏ᶠ v : HeightOneSpectrum O,
    let R := Localization.AtPrime v.asIdeal
    haveI : IsDiscreteValuationRing R :=
      IsLocalization.AtPrime.isDiscreteValuationRing_of_dedekind_domain O v.ne_bot _
    v.asIdeal ^ (-WithZero.log (v.valuation (FractionRing O) (W.minimal R).Δ)).toNat

/-- A Weierstrass curve over `FractionRing ℤ` is a **reduced minimal model** (LMFDB
`ec.q.minimal_weierstrass_equation`) if it is a global minimal model with `a₁, a₃ ∈ {0, 1}` and
`a₂ ∈ {-1, 0, 1}`. These normalizations single out a unique global minimal model of an elliptic
curve over `ℚ`. -/
def IsReducedMinimalModel (W : WeierstrassCurve (FractionRing ℤ)) : Prop :=
  IsGlobalMinimalModel W ∧
    (W.a₁ = 0 ∨ W.a₁ = 1) ∧ (W.a₂ = -1 ∨ W.a₂ = 0 ∨ W.a₂ = 1) ∧ (W.a₃ = 0 ∨ W.a₃ = 1)

/-- A Weierstrass curve over `FractionRing O` is **semistable** (LMFDB `ec.semistable`) if it does
not have additive reduction at any height-one prime of `O`, the reduction at `v` being that of a
local minimal model at `v`. -/
def IsSemistable (W : WeierstrassCurve (FractionRing O)) : Prop :=
  ∀ v : HeightOneSpectrum O,
    haveI : IsDiscreteValuationRing (Localization.AtPrime v.asIdeal) :=
      IsLocalization.AtPrime.isDiscreteValuationRing_of_dedekind_domain O v.ne_bot _
    ¬ HasAdditiveReduction (Localization.AtPrime v.asIdeal)
        (W.minimal (Localization.AtPrime v.asIdeal))

/-- The **obstruction exponent** `fᵥ = (v(Δ) - eᵥ) / 12` of an integral Weierstrass curve `W` over
`O` at a height-one prime `v`: the `v`-adic valuation of the discriminant of `W` minus that of a
local minimal model, divided by `12` (the difference is a nonnegative multiple of `12`). -/
noncomputable def obstructionExponent (W : WeierstrassCurve O) (v : HeightOneSpectrum O) : ℕ :=
  let R := Localization.AtPrime v.asIdeal
  haveI : IsDiscreteValuationRing R :=
    IsLocalization.AtPrime.isDiscreteValuationRing_of_dedekind_domain O v.ne_bot _
  ((-WithZero.log (v.valuation (FractionRing O) (algebraMap O (FractionRing O) W.Δ))).toNat -
    (-WithZero.log (v.valuation (FractionRing O)
      ((W.baseChange (FractionRing O)).minimal R).Δ)).toNat) / 12

/-- The **obstruction class** (LMFDB `ec.obstruction_class`; Silverman's *Weierstrass class*) of
an integral Weierstrass curve `W` over `O`: the class of the ideal `∏ᵥ 𝔭ᵥ ^ fᵥ` in `ClassGroup O`,
where `fᵥ` is the obstruction exponent at `v`. It is trivial if and only if the curve admits a
global minimal model (Silverman, *The Arithmetic of Elliptic Curves*, VIII.8.2). -/
noncomputable def obstructionClass (W : WeierstrassCurve O) : ClassGroup O :=
  ClassGroup.mk0 (∏ᶠ v : HeightOneSpectrum O,
    (⟨v.asIdeal ^ obstructionExponent W v,
      pow_mem (mem_nonZeroDivisors_of_ne_zero (by simpa using v.ne_bot)) _⟩ :
        nonZeroDivisors (Ideal O)))

end GlobalMinimal

section Height

/-- The **naive height** (LMFDB `ec.q.naive_height`) of an elliptic curve over `ℚ` in short
Weierstrass form `y² = x³ + a₄x + a₆`: the maximum of `4|a₄|³` and `27a₆²`. -/
def naiveHeight (W : WeierstrassCurve ℚ) [W.IsShortNF] : ℚ :=
  max (4 * |W.a₄| ^ 3) (27 * W.a₆ ^ 2)

/-- The **naive height** of a rational point on a Weierstrass curve over `ℚ`: the logarithm of the
maximum of the absolute value of the numerator and the denominator of its `x`-coordinate, and `0`
at the point at infinity. -/
noncomputable def naivePointHeight {W : WeierstrassCurve ℚ} : W.toAffine.Point → ℝ
  | .zero => 0
  | .some (x := x) .. => Real.log (max (x.num.natAbs : ℝ) (x.den : ℝ))

open Filter in
/-- The **canonical height**, or Néron–Tate height, (LMFDB `ec.q.canonical_height`) of a rational
point `P` on an elliptic curve over `ℚ`: the limit of `naivePointHeight (n • P) / n ^ 2`. This is
LMFDB's normalization, twice that of some authors. The limit is taken via `limUnder`, whose value
is unspecified when the sequence does not converge; convergence is the content of the Néron–Tate
theorem, which is not proved here. -/
noncomputable def canonicalHeight {W : WeierstrassCurve ℚ} [W.IsElliptic]
    (P : W.toAffine.Point) : ℝ :=
  limUnder atTop (fun n : ℕ => naivePointHeight (n • P) / (n : ℝ) ^ 2)

end Height

section Frey

/-- The **Frey–Hellegouarch curve** (LMFDB `ec.q.frey`) `y² = x * (x - A) * (x + B)` of a pair
`A B : R`: the Weierstrass curve with `a₂ = B - A`, `a₄ = -A * B` and `a₁ = a₃ = a₆ = 0`. Its
discriminant is `16A²B²(A + B)²`, so it is an elliptic curve exactly when `A`, `B` and `A + B` are
all nonzero. -/
def freyCurve {R : Type*} [CommRing R] (A B : R) : WeierstrassCurve R where
  a₁ := 0
  a₂ := B - A
  a₃ := 0
  a₄ := -(A * B)
  a₆ := 0

end Frey

section Quality

/-- The **abc quality** (LMFDB `ec.q.abc_quality`) of an elliptic curve over `ℚ`: the quotient
`log max(|a|, |b|, |c|) / log rad(abc)`, where `j / 1728 = a / c` in lowest terms, `b = c - a` and
`rad` is the radical of an integer. The quality is mathematically undefined when `j = 0` or
`j = 1728`: there `abc = 0`, so the denominator `log (rad 0) = log 1` vanishes and the expression
evaluates to `0`, an artifact of division by zero in Lean rather than a meaningful value. -/
noncomputable def abcQuality (E : WeierstrassCurve ℚ) [E.IsElliptic] : ℝ :=
  let a := (E.j / 1728).num
  let c := ((E.j / 1728).den : ℤ)
  let b := c - a
  Real.log ↑(max (max a.natAbs b.natAbs) c.natAbs) /
    Real.log ↑(UniqueFactorizationMonoid.radical (a * b * c).natAbs)

end Quality

section Points

/-- The **integral points** (LMFDB `ec.q.integral_points`) of a Weierstrass curve over `ℚ`: the
affine points whose coordinates are integers. This depends on the choice of model; the LMFDB
lists integral points on a reduced minimal model. -/
def integralPoints (W : WeierstrassCurve ℚ) : Set W.toAffine.Point :=
  {P | ∃ (x y : ℤ) (h : W.toAffine.Nonsingular (x : ℚ) (y : ℚ)),
    P = Affine.Point.some (x : ℚ) (y : ℚ) h}

end Points

end WeierstrassCurve
