import Mathlib.Analysis.SpecialFunctions.Gamma.Digamma
import Mathlib.FieldTheory.Relrank
import Mathlib.LinearAlgebra.Charpoly.Basic
import Mathlib.NumberTheory.DirichletCharacter.Basic
import Mathlib.NumberTheory.LSeries.DirichletContinuation
import Mathlib.NumberTheory.ModularForms.Basic
import Mathlib.NumberTheory.ModularForms.CongruenceSubgroups
import Mathlib.NumberTheory.ModularForms.CuspFormSubmodule
import Mathlib.NumberTheory.ModularForms.QExpansion
import Mathlib.NumberTheory.ModularForms.SlashActions

/-!
# Classical modular form definitions for LeanBridge (chapter 5)

Definitions from the LMFDB classical-modular-form knowls that are not (yet) in mathlib, written
here in mathlib style for the LeanBridge blueprint audit.
-/

open scoped MatrixGroups

namespace CongruenceSubgroup

/-- A positive integer `N` is a **level** of a subgroup `Γ` of `SL(2, ℤ)` if `Γ` contains the
principal congruence subgroup `Γ(N)`; a modular form on `Γ` is then said to have level `N`
(LMFDB [`cmf.level`](https://www.lmfdb.org/knowledge/show/cmf.level)). -/
def IsLevel (N : ℕ) (Γ : Subgroup SL(2, ℤ)) : Prop :=
  N ≠ 0 ∧ Gamma N ≤ Γ

/-- The **level** of a subgroup `Γ` of `SL(2, ℤ)`: the least positive integer `N` such that `Γ`
contains the principal congruence subgroup `Γ(N)`, or `0` if there is no such `N`, i.e. if `Γ` is
not a congruence subgroup. The LMFDB defines the level of a newform as the least level of its
group of invariance (LMFDB [`cmf.level`](https://www.lmfdb.org/knowledge/show/cmf.level)). -/
noncomputable def level (Γ : Subgroup SL(2, ℤ)) : ℕ :=
  sInf {N | IsLevel N Γ}

/-- A prime `p` is a **bad prime** for a modular form on a subgroup `Γ` of `SL(2, ℤ)` when it
divides the level of `Γ`
(LMFDB [`cmf.bad_prime`](https://www.lmfdb.org/knowledge/show/cmf.bad_prime)). -/
def IsBadPrime (p : ℕ) (Γ : Subgroup SL(2, ℤ)) : Prop :=
  p.Prime ∧ p ∣ level Γ

/-- A prime `p` is a **good prime** for a modular form on a subgroup `Γ` of `SL(2, ℤ)` when it
does not divide the level of `Γ`, i.e. when it is not a bad prime
(LMFDB [`cmf.bad_prime`](https://www.lmfdb.org/knowledge/show/cmf.bad_prime)). -/
def IsGoodPrime (p : ℕ) (Γ : Subgroup SL(2, ℤ)) : Prop :=
  p.Prime ∧ ¬ p ∣ level Γ

end CongruenceSubgroup

namespace DirichletCharacter

/-- The **character field** `ℚ(χ)` of a Dirichlet character `χ` with values in `ℂ`: the number
field generated over `ℚ` by the values of `χ`. This is the base field over which the LMFDB
measures the relative dimension of a newform
(LMFDB [`cmf.relative_dimension`](https://www.lmfdb.org/knowledge/show/cmf.relative_dimension)). -/
noncomputable def valueField {N : ℕ} (χ : DirichletCharacter ℂ N) : IntermediateField ℚ ℂ :=
  IntermediateField.adjoin ℚ (Set.range χ)

end DirichletCharacter

namespace ModularForm

open UpperHalfPlane CongruenceSubgroup

/-- A function `f : ℍ → ℂ` transforms with **character** (or nebentypus) `χ` mod `N` in weight `k`
under a subgroup `Γ` of `SL(2, ℤ)` if `f(γz) = χ(d)(cz+d)^k f(z)` for all `γ = !![*, *; c, d]` in
`Γ`, that is, `f ∣[k] γ = χ(d) • f`. The LMFDB states this for a modular form on a group `Γ`
containing `Γ(N)` (see `CongruenceSubgroup.IsLevel`), typically `Γ₀(N)`
(LMFDB [`cmf.character`](https://www.lmfdb.org/knowledge/show/cmf.character)). -/
def HasCharacter (Γ : Subgroup SL(2, ℤ)) (k : ℤ) {N : ℕ} (χ : DirichletCharacter ℂ N)
    (f : ℍ → ℂ) : Prop :=
  ∀ γ ∈ Γ, f ∣[k] γ = χ (γ 1 1 : ZMod N) • f

/-- The **analytic conductor** of a newform of level `N` and weight `k`: the real number
`N * (exp (ψ (k / 2)) / (2 * π)) ^ 2`, where `ψ = Γ'/Γ` is the digamma function. Mathlib defines
the digamma function only on `ℂ`; for `k ≥ 1` its value at `k / 2` is real, and this definition
takes its real part
(LMFDB [`cmf.analytic_conductor`](https://www.lmfdb.org/knowledge/show/cmf.analytic_conductor)). -/
noncomputable def analyticConductor (N : ℕ) (k : ℤ) : ℝ :=
  N * (Real.exp (Complex.digamma (k / 2)).re / (2 * Real.pi)) ^ 2

/-- The **Sturm bound** of a space `M_k(N, χ)` of modular forms of weight `k`, level `N` and
character `χ`: the integer `⌊k * [SL(2, ℤ) : Γ₀(N)] / 12⌋`, where the index of `Γ₀(N)` is used
for every character `χ`. Two forms in `M_k(N, χ)` whose Fourier coefficients agree up to this
bound are equal
(LMFDB [`cmf.sturm_bound`](https://www.lmfdb.org/knowledge/show/cmf.sturm_bound)). -/
noncomputable def sturmBound (N : ℕ) (k : ℤ) : ℕ :=
  (k * (Gamma0 N).index / 12).toNat

/-- The **Sturm bound for `Γ₁(N)`** of a space `M_k(Γ₁(N))` of modular forms of weight `k` and
level `N`: the integer `⌊k * [SL(2, ℤ) : Γ₁(N)] / 12⌋`
(LMFDB [`cmf.sturm_bound_gamma1`](https://www.lmfdb.org/knowledge/show/cmf.sturm_bound_gamma1)). -/
noncomputable def sturmBoundGamma1 (N : ℕ) (k : ℤ) : ℕ :=
  (k * (Gamma1 N).index / 12).toNat

/-- The **relative dimension** of a newform in `S_k^new(Γ₀(N), χ)` with coefficient field `F`:
the degree of `F` over the character field `ℚ(χ)`. The coefficient field (the subfield of `ℂ`
generated by the Fourier coefficients, LMFDB `cmf.coefficient_field`) is taken here as an
explicit argument. `IntermediateField.relfinrank` computes `[F : ℚ(χ) ⊓ F]`, which agrees with
the degree `[F : ℚ(χ)]` since `ℚ(χ) ≤ F` for the coefficient field of a newform
(LMFDB [`cmf.relative_dimension`](https://www.lmfdb.org/knowledge/show/cmf.relative_dimension)). -/
noncomputable def relativeDimension {N : ℕ} (χ : DirichletCharacter ℂ N)
    (F : IntermediateField ℚ ℂ) : ℕ :=
  χ.valueField.relfinrank F

/-- The **coefficient ring** of a modular form `f`: the subring `ℤ[a₁, a₂, a₃, …]` of `ℂ`
generated by the coefficients `aₙ`, `n ≥ 1`, of its `q`-expansion `∑ aₙ qⁿ` at the infinite cusp
(taken with period `1`, i.e. `q = e^(2πiz)`, as for forms on `Γ₀(N)`). For a newform this is also
called the Hecke ring, the `aₙ` being Hecke eigenvalues
(LMFDB [`cmf.coefficient_ring`](https://www.lmfdb.org/knowledge/show/cmf.coefficient_ring)). -/
noncomputable def coefficientRing (f : ℍ → ℂ) : Subring ℂ :=
  Subring.closure (Set.range fun n : ℕ => (qExpansion 1 f).coeff (n + 1))

/-- The **coefficient field** of a modular form `f`: the subfield of `ℂ` generated over `ℚ` by
the coefficients `aₙ`, `n ≥ 1`, of its `q`-expansion `∑ aₙ qⁿ` at the infinite cusp (period `1`,
as in `ModularForm.coefficientRing`). For a Hecke eigenform this is a number field, also called
the Hecke field, and the relative dimension of a newform `f` in `S_k^new(Γ₀(N), χ)` is
`relativeDimension χ (coefficientField f)`
(LMFDB [`cmf.coefficient_field`](https://www.lmfdb.org/knowledge/show/cmf.coefficient_field)). -/
noncomputable def coefficientField (f : ℍ → ℂ) : IntermediateField ℚ ℂ :=
  IntermediateField.adjoin ℚ (Set.range fun n : ℕ => (qExpansion 1 f).coeff (n + 1))

/-- The **embedding** `ι(f)` of a modular form `f` along a field embedding `ι : F → ℂ`, where `F`
is a subfield of `ℂ` containing every `q`-expansion coefficient `aₙ` of `f` (for a newform, its
coefficient field): the function on `ℍ` with `q`-expansion `∑ ι(aₙ) qⁿ`, defined as the sum of
that series in `q = e^(2πiτ)`. Its value is junk where the series diverges; convergence on all of
`ℍ`, and modularity of `ι(f)`, are theorems about newforms and are not part of the definition
(LMFDB [`cmf.embedding`](https://www.lmfdb.org/knowledge/show/cmf.embedding)). -/
noncomputable def embeddedForm {F : IntermediateField ℚ ℂ} (f : ℍ → ℂ) (ι : F →+* ℂ)
    (hf : ∀ n, (qExpansion 1 f).coeff n ∈ F) : ℍ → ℂ :=
  fun τ => ∑' n : ℕ, ι ⟨(qExpansion 1 f).coeff n, hf n⟩ * Function.Periodic.qParam 1 τ ^ n

/-- Two cusp forms `f = ∑ aₙ qⁿ` and `g = ∑ bₙ qⁿ` on `Γ₁(N)` are **Galois conjugate** if there
is an automorphism `σ` with `bₙ = σ(aₙ)` for all `n ≥ 1`; since cusp forms have `a₀ = 0`, the
`q`-expansion of `g` is then the full coefficientwise image of that of `f`, i.e. `g = σ(f)`. The
LMFDB states this for newforms — newform-ness of `f` and `g` is not encoded — and takes
`σ ∈ Gal(ℚ̄/ℚ)`; here `σ` ranges over the `ℚ`-automorphisms of `ℂ`, which restrict to — and, by
the axiom of choice, extend from — automorphisms of `ℚ̄`, so for newforms, whose coefficients are
algebraic, the two formulations agree
(LMFDB [`cmf.galois_conjugate`](https://www.lmfdb.org/knowledge/show/cmf.galois_conjugate)). -/
def IsGaloisConjugate {N : ℕ} {k : ℤ} (f g : CuspForm ↑(Gamma1 N) k) : Prop :=
  ∃ σ : ℂ ≃ₐ[ℚ] ℂ, ∀ n : ℕ, n ≠ 0 → (qExpansion 1 ⇑g).coeff n = σ ((qExpansion 1 ⇑f).coeff n)

/-- The **Galois orbit** `[f]` of a newform `f`: the set `{σ(f) : σ ∈ Gal(ℚ̄/ℚ)}` of its
coefficientwise Galois conjugates within the cusp forms on `Γ₁(N)`, also called the newform
orbit. For a genuine newform this is the LMFDB's finite orbit `[f]`; its finiteness, and the
fact that it is a basis of the newform subspace it spans, are theorems and not part of the
definition
(LMFDB [`cmf.galois_orbit`](https://www.lmfdb.org/knowledge/show/cmf.galois_orbit)). -/
def galoisOrbit {N : ℕ} {k : ℤ} (f : CuspForm ↑(Gamma1 N) k) : Set (CuspForm ↑(Gamma1 N) k) :=
  {g | IsGaloisConjugate f g}

/-- The **trace form** `Tr(f)` of a newform `f` whose coefficient field is `F`: the sum
`∑ᵢ ι(f)` of the embeddings of `f` over all field embeddings `ι : F → ℂ`, equivalently the sum
of the distinct Galois conjugates of `f`. Its q-expansion is the coefficientwise field trace
`∑ Tr_{F/ℚ}(aₙ) qⁿ`, with integer coefficients and `a₁` the dimension of the newform — both
theorems, not encoded. The `finsum` is junk `0` unless `F` admits only finitely many embeddings,
as a number field does; and the sum counts each conjugate once only when `F` is exactly the
coefficient field of `f`, as the LMFDB prescribes
(LMFDB [`cmf.trace_form`](https://www.lmfdb.org/knowledge/show/cmf.trace_form)). -/
noncomputable def traceForm {F : IntermediateField ℚ ℂ} (f : ℍ → ℂ)
    (hf : ∀ n, (qExpansion 1 f).coeff n ∈ F) : ℍ → ℂ :=
  ∑ᶠ ι : F →+* ℂ, embeddedForm f ι hf

/-- The **Hecke operator** `T_n` on modular forms of weight `k`, level `N` and character `χ`, in
its `q`-expansion model: `T_n f` is the function on `ℍ` whose `q`-expansion has coefficients
`a_m(T_n f) = ∑_{d ∣ gcd(m,n)} χ(d) d^(k-1) a_(mn/d²)(f)`, summed here as a series in
`q = e^(2πiτ)`. Of the two equivalent classical models this implements the coefficient formula,
not the double-coset sum. That `T_n f` is again a modular form in `M_k(N, χ)`, linearity in `f`,
and the commutation and eigenbasis properties are theorems, not encoded; the sum is junk where
it diverges
(LMFDB [`cmf.hecke_operator`](https://www.lmfdb.org/knowledge/show/cmf.hecke_operator)). -/
noncomputable def heckeOperator {N : ℕ} (χ : DirichletCharacter ℂ N) (k : ℤ) (n : ℕ)
    (f : ℍ → ℂ) : ℍ → ℂ :=
  fun τ => ∑' m : ℕ,
    (∑ d ∈ (m.gcd n).divisors, χ d * (d : ℂ) ^ (k - 1) * (qExpansion 1 f).coeff (m * n / d ^ 2))
      * Function.Periodic.qParam 1 τ ^ m

/-- An **admissible Atkin-Lehner matrix** `W_Q` for level `N` and a divisor `Q` of `N`: the LMFDB
requires `Q` positive with `gcd(Q, N/Q) = 1`, and `W_Q = [[Qx, y], [Nz, Qt]]` of determinant `Q`
for some integers `x, y, z, t` — the existential shape is recorded equivalently as divisibility
of the entries, the witnesses being the quotients
(LMFDB [`cmf.atkin-lehner`](https://www.lmfdb.org/knowledge/show/cmf.atkin-lehner)). -/
structure IsAtkinLehnerMatrix (N Q : ℕ) (W : Matrix (Fin 2) (Fin 2) ℤ) : Prop where
  level_pos : 0 < N
  pos : 0 < Q
  dvd : Q ∣ N
  coprime : Nat.Coprime Q (N / Q)
  q_dvd_upper_left : (Q : ℤ) ∣ W 0 0
  n_dvd_lower_left : (N : ℤ) ∣ W 1 0
  q_dvd_lower_right : (Q : ℤ) ∣ W 1 1
  det_eq : W.det = Q

/-- The **Atkin-Lehner involution** `w_Q` of weight `k` attached to an admissible Atkin-Lehner
matrix `W_Q` for an exact divisor `Q` of `N`: the classical operator
`w_Q f = Q^(k/2) (Nz·τ + Qt)^(-k) f(W_Q·τ)`, written as the slash action `f ∣[k] W_Q` scaled by
`Q^(1 - k/2)` to convert mathlib's determinant normalization `det^(k-1)` into the classical
`det^(k/2)`, under which `w_Q` squares to the identity on `Γ₀(N)`-invariant forms. On a form of
`S_k(Γ₀(N))` — trivial character — that is an eigenform for every `T_p` with `p ∤ N`, it acts
with eigenvalue `±1`; for nontrivial nebentypus `w_Q` does not preserve the `χ`-space, and the
Atkin-Li pseudo-eigenvalues have modulus `1`, not `±1`. Independence of the choice of admissible
matrix and commutation with the Hecke operators `T_p`, `p ∤ Q`, are theorems, not encoded
(LMFDB [`cmf.atkin-lehner`](https://www.lmfdb.org/knowledge/show/cmf.atkin-lehner)). -/
noncomputable def atkinLehner (k : ℤ) {N Q : ℕ} {W : Matrix (Fin 2) (Fin 2) ℤ}
    (hW : IsAtkinLehnerMatrix N Q W) (f : ℍ → ℂ) : ℍ → ℂ :=
  (Q : ℂ) ^ (1 - (k : ℂ) / 2) •
    (f ∣[k] Matrix.GeneralLinearGroup.mkOfDetNeZero ((Int.castRingHom ℝ).mapMatrix W) (by
      rw [← RingHom.map_det, hW.det_eq, map_natCast]
      exact_mod_cast hW.pos.ne'))

/-- The **Fricke involution** `w_N` of weight `k` on forms of level `N`: the Atkin-Lehner
involution for the full level `Q = N`, represented by the admissible matrix `[[0, -1], [N, 0]]`.
For a newform in `S_k^new(Γ₀(N))`, the sign of the functional equation of its L-function is
`i^(-k)` times its `w_N`-eigenvalue — a theorem, not encoded
(LMFDB [`cmf.fricke`](https://www.lmfdb.org/knowledge/show/cmf.fricke)). -/
noncomputable def fricke (k : ℤ) {N : ℕ} (hN : 0 < N) (f : ℍ → ℂ) : ℍ → ℂ :=
  atkinLehner k (W := !![0, -1; (N : ℤ), 0])
    { level_pos := hN
      pos := hN
      dvd := dvd_rfl
      coprime := by simp [Nat.div_self hN]
      q_dvd_upper_left := by simp
      n_dvd_lower_left := by simp
      q_dvd_lower_right := by simp
      det_eq := by simp [Matrix.det_fin_two_of] }
    f

/-- The **Hecke orbit** of a cusp form `f` in `S_k(N, χ)` — a bundled cusp form on `Γ₁(N)`
together with nebentypus `χ` under `Γ₀(N)`: the subspace of functions on `ℍ` generated by the
images `T_p f` of `f` under the Hecke operators at all primes `p` coprime to the level `N`. The
orbit lives in the ambient space of functions since stability of cusp forms under the `T_p` is a
theorem, not encoded
(LMFDB [`cmf.hecke_orbit`](https://www.lmfdb.org/knowledge/show/cmf.hecke_orbit)). -/
noncomputable def heckeOrbit {N : ℕ} (χ : DirichletCharacter ℂ N) (k : ℤ)
    (f : CuspForm ↑(Gamma1 N) k) (_hf : HasCharacter (Gamma0 N) k χ ⇑f) :
    Submodule ℂ (ℍ → ℂ) :=
  Submodule.span ℂ {g | ∃ p : ℕ, p.Prime ∧ p.Coprime N ∧ g = heckeOperator χ k p ⇑f}

open Classical in
/-- The **Hecke characteristic polynomial** of a newform `f` at a prime `p`: the characteristic
polynomial of the Hecke operator `T_p` acting on the newform subspace `V_f`, the span of the
Galois orbit of `f` inside the cusp forms on `Γ₁(N)`. Finite-dimensionality of `V_f` is an
instance hypothesis (it holds for genuine newforms), and the action is the linear endomorphism
of `V_f` agreeing pointwise with `heckeOperator χ k p` — unique when it exists, since its values
are forced — with junk value `0` when no such endomorphism exists. Primality of `p` is not
required by the formula; the LMFDB uses good primes
(LMFDB [`cmf.heckecharpolys`](https://www.lmfdb.org/knowledge/show/cmf.heckecharpolys)). -/
noncomputable def heckeCharpoly {N : ℕ} (χ : DirichletCharacter ℂ N) (k : ℤ) (p : ℕ)
    (f : CuspForm ↑(Gamma1 N) k) (_hf : HasCharacter (Gamma0 N) k χ ⇑f)
    [Module.Finite ℂ (Submodule.span ℂ (galoisOrbit f))] : Polynomial ℂ :=
  if h : ∃ T : Submodule.span ℂ (galoisOrbit f) →ₗ[ℂ] Submodule.span ℂ (galoisOrbit f),
      ∀ v, ⇑(T v : CuspForm ↑(Gamma1 N) k) = heckeOperator χ k p ⇑(v : CuspForm ↑(Gamma1 N) k) then
    h.choose.charpoly
  else 0

/-- A finite set `P` of primes indexes **distinguishing Hecke operators** `𝒯 = {T_p : p ∈ P}`
for a family `f : ι → CuspForm (Γ₁(N)) k` of nonconjugate newforms with nebentypus `χ`: the
primes are good (`p ∤ N`, the LMFDB's convenience restriction), and the sets `X_(f i)(𝒯)` of
Hecke characteristic polynomials of the `T_p` on the newform subspaces are pairwise distinct.
If the family contains conjugate newforms the proposition is unsatisfiable, so `ι` should index
orbit representatives. The particular ordered sequence of such primes recorded by the LMFDB (via
its strictly increasing refinement count) is a database convention, not formalized
(LMFDB [`cmf.distinguishing_primes`](https://www.lmfdb.org/knowledge/show/cmf.distinguishing_primes)). -/
def DistinguishesNewforms {ι : Type*} {N : ℕ} (χ : DirichletCharacter ℂ N) (k : ℤ)
    (f : ι → CuspForm ↑(Gamma1 N) k) (hf : ∀ i, HasCharacter (Gamma0 N) k χ ⇑(f i))
    [∀ i, Module.Finite ℂ (Submodule.span ℂ (galoisOrbit (f i)))] (P : Finset ℕ) : Prop :=
  (∀ p ∈ P, p.Prime ∧ ¬ p ∣ N) ∧
    Function.Injective fun i => (fun p => heckeCharpoly χ k p (f i) (hf i)) '' (P : Set ℕ)

/-- The **coefficient ring generator bound** of a newform `f` with `q`-expansion `∑ aₙ qⁿ`: the
least positive integer `n` such that `ℤ[a₁, …, aₙ]` is the entire coefficient ring
`ℤ[a₁, a₂, a₃, …]`, or junk `0` if no finite prefix of the coefficients generates it
(LMFDB [`cmf.hecke_ring_generators`](https://www.lmfdb.org/knowledge/show/cmf.hecke_ring_generators)). -/
noncomputable def heckeRingGeneratorBound (f : ℍ → ℂ) : ℕ :=
  sInf {n | 0 < n ∧
    Subring.closure ((fun m => (qExpansion 1 f).coeff m) '' Set.Icc 1 n) = coefficientRing f}

/-- The **trace bound** of a family `f : ι → CuspForm (Γ₁(N)) k` of nonconjugate newforms with
nebentypus `χ` spanning the Galois orbits of a newspace: the least positive integer `m` such
that the traces down to `ℚ` of the coefficients `aₙ`, `n ≤ m`, distinguish the orbits — the
trace of `aₙ` being the sum of `ι(aₙ)` over the embeddings `ι` of the coefficient field, as in
`ModularForm.traceForm`. Unlike the universal Sturm bound this is the least such bound for the
particular space; it is junk `0` if no prefix separates the family, e.g. if `ι` contains
conjugate newforms, which share all traces
(LMFDB [`cmf.trace_bound`](https://www.lmfdb.org/knowledge/show/cmf.trace_bound)). -/
noncomputable def traceBound {ι : Type*} {N : ℕ} (χ : DirichletCharacter ℂ N) (k : ℤ)
    (f : ι → CuspForm ↑(Gamma1 N) k) (_hf : ∀ i, HasCharacter (Gamma0 N) k χ ⇑(f i)) : ℕ :=
  sInf {m | 0 < m ∧ Function.Injective fun i => fun j : Fin m =>
    ∑ᶠ e : coefficientField ⇑(f i) →+* ℂ,
      e ⟨(qExpansion 1 ⇑(f i)).coeff ((j : ℕ) + 1),
        IntermediateField.subset_adjoin ℚ _ ⟨(j : ℕ), rfl⟩⟩}

/-- The **level-raising map** (degeneracy map) `V_d = ι_d`: `(V_d f)(τ) = f(dτ)` for a positive
integer `d` — the classical normalization, with no stray power of `d`. For `d ∣ N/M` it maps
`S_k(M, χ_M)` into `S_k(N, χ)`, and its images from proper divisor levels span the old subspace
(LMFDB [`cmf.oldspace`](https://www.lmfdb.org/knowledge/show/cmf.oldspace)). -/
def levelRaisingMap (d : ℕ+) (f : ℍ → ℂ) : ℍ → ℂ :=
  fun τ => f ⟨((d : ℕ) : ℂ) * τ, by
    simpa [Complex.mul_im] using mul_pos (by exact_mod_cast d.pos : (0 : ℝ) < (d : ℕ)) τ.im_pos⟩

/-- The **old subspace** `S_k^old(N, χ)` of the cusp forms of weight `k`, level `N` and
character `χ`: the span of the images `f(dτ)` of the cusp forms `f ∈ S_k(M, χ_M)` over all
proper divisors `M` of `N` carrying a character `χ_M` that induces `χ` (which forces `M` to be
divisible by the conductor of `χ`), and all divisors `d` of `N/M`. The knowl's direct-sum
decomposition into newspaces is a theorem, not encoded; the span lives in the ambient functions
on `ℍ` since modularity of the raised forms at level `N` is likewise a theorem
(LMFDB [`cmf.oldspace`](https://www.lmfdb.org/knowledge/show/cmf.oldspace)). -/
noncomputable def oldspace {N : ℕ} (χ : DirichletCharacter ℂ N) (k : ℤ) :
    Submodule ℂ (ℍ → ℂ) :=
  Submodule.span ℂ
    {g | ∃ (M : ℕ) (hM : M ∣ N) (_ : M ≠ N) (χ' : DirichletCharacter ℂ M)
      (_ : DirichletCharacter.changeLevel hM χ' = χ) (d : ℕ+) (_ : (d : ℕ) ∣ N / M)
      (f : CuspForm ↑(Gamma1 M) k) (_ : HasCharacter (Gamma0 M) k χ' ⇑f),
      g = levelRaisingMap d ⇑f}

/-- The **new subspace** `S_k^new(N, χ)`: the orthogonal complement of the old subspace with
respect to the Petersson inner product, expressed relative to a pairing `B` — the space of `f`
with `B f g = 0` for every `g` in the old subspace, an intersection of kernels. Here `B f g`
stands for the Petersson pairing of `f` and `g` with the arguments ordered so that `B` is
linear in `f`: since the classical Petersson product is conjugate-linear in one slot, the
intended instantiation puts `f` in the linear slot (for mathlib's integrand, which conjugates
its first argument, this means `B f g = ⟨g, f⟩`). `B` is an input until the product is defined
(see `cmf.petersson_scalar_product`); the direct-sum decomposition `S_k = S_k^old ⊕ S_k^new`
and the newform basis are theorems, not encoded
(LMFDB [`cmf.newspace`](https://www.lmfdb.org/knowledge/show/cmf.newspace)). -/
noncomputable def newspace {N : ℕ} (χ : DirichletCharacter ℂ N) (k : ℤ)
    (B : (ℍ → ℂ) →ₗ[ℂ] ((ℍ → ℂ) → ℂ)) : Submodule ℂ (ℍ → ℂ) :=
  ⨅ g : ↥(oldspace χ k), LinearMap.ker ((LinearMap.proj (g : ℍ → ℂ)).comp B)

/-- The **plus subspace** of `S_k(Γ₀(N))`: the eigenspace of the Fricke involution `w_N` with
eigenvalue `+1`, here the set of functions fixed by `fricke k hN`. That it is a linear subspace
of the cusp forms — linearity of `w_N` — is a theorem, not encoded
(LMFDB [`cmf.plus_space`](https://www.lmfdb.org/knowledge/show/cmf.plus_space)). -/
def plusSpace (k : ℤ) {N : ℕ} (hN : 0 < N) :
    Set (CuspForm ↑(Gamma0 N) k) :=
  {f | fricke k hN ⇑f = ⇑f}

/-- The **minus subspace** of `S_k(Γ₀(N))`: the eigenspace of the Fricke involution `w_N` with
eigenvalue `-1`, here the set of functions negated by `fricke k hN`. That it is a linear
subspace of the cusp forms — linearity of `w_N` — is a theorem, not encoded
(LMFDB [`cmf.minus_space`](https://www.lmfdb.org/knowledge/show/cmf.minus_space)). -/
def minusSpace (k : ℤ) {N : ℕ} (hN : 0 < N) :
    Set (CuspForm ↑(Gamma0 N) k) :=
  {f | fricke k hN ⇑f = -⇑f}

/-- The **old subspace** `M_k^old(N, χ)` of the full space of modular forms of weight `k`,
level `N` and character `χ`: the span of the images `f(dτ)` of the modular forms
`f ∈ M_k(M, χ_M)` over proper divisors `M ∣ N` carrying a character `χ_M` that induces `χ`, and
divisors `d ∣ N/M` — the same degeneracy-map construction as the cuspidal `oldspace`. Of the
knowl's remaining content, the cuspidal subspace is mathlib's `ModularForm.cuspFormSubmodule`,
the Eisenstein subspace and its new part are `cmf.eisenstein_form`/`cmf.eisenstein_newspace`,
and the three direct-sum decompositions are theorems, not encoded
(LMFDB [`cmf.subspaces`](https://www.lmfdb.org/knowledge/show/cmf.subspaces)). -/
noncomputable def modularOldspace {N : ℕ} (χ : DirichletCharacter ℂ N) (k : ℤ) :
    Submodule ℂ (ℍ → ℂ) :=
  Submodule.span ℂ
    {g | ∃ (M : ℕ) (hM : M ∣ N) (_ : M ≠ N) (χ' : DirichletCharacter ℂ M)
      (_ : DirichletCharacter.changeLevel hM χ' = χ) (d : ℕ+) (_ : (d : ℕ) ∣ N / M)
      (f : ModularForm ↑(Gamma1 M) k) (_ : HasCharacter (Gamma0 M) k χ' ⇑f),
      g = levelRaisingMap d ⇑f}

/-- A **newform** of weight `k`, level `N` and character `χ`: a cusp form in the new subspace
`S_k^new(N, χ)` that is a Hecke eigenform, normalized so that its `q`-expansion has `a₁ = 1`.
The eigenform condition is stated for the operators `T_n` with `n` coprime to the level; that a
member of the new subspace eigen away from the level is automatically an eigenform for all
`T_n` — the knowl's phrasing — is Diamond–Shurman Thm 5.8.2, a theorem, not a definition field.
The pairing `B` is the stand-in for the Petersson product defining the new subspace (see
`ModularForm.newspace`), and that the newforms form a basis of it is likewise a theorem
(LMFDB [`cmf.newform`](https://www.lmfdb.org/knowledge/show/cmf.newform)). -/
structure IsNewform {N : ℕ} (χ : DirichletCharacter ℂ N) (k : ℤ)
    (B : (ℍ → ℂ) →ₗ[ℂ] ((ℍ → ℂ) → ℂ)) (f : CuspForm ↑(Gamma1 N) k) : Prop where
  level_pos : 0 < N
  hasCharacter : HasCharacter (Gamma0 N) k χ ⇑f
  mem_newspace : ⇑f ∈ newspace χ k B
  eigen_away : ∀ n : ℕ, 0 < n → n.Coprime N → ∃ c : ℂ, heckeOperator χ k n ⇑f = c • ⇑f
  normalized : (qExpansion 1 ⇑f).coeff 1 = 1

/-- The **newform subspace** `V_f` of a newform `f` in `S_k^new(N, χ)`: the subspace of the cusp
forms on `Γ₁(N)` generated by the Galois conjugates of `f` — the span already used by
`ModularForm.heckeCharpoly`. That every newspace decomposes canonically into newform subspaces
is a theorem (see `cmf.decomposition.new.gamma0chi`), not encoded
(LMFDB [`cmf.newform_subspace`](https://www.lmfdb.org/knowledge/show/cmf.newform_subspace)). -/
noncomputable def newformSubspace {N : ℕ} {χ : DirichletCharacter ℂ N} {k : ℤ}
    {B : (ℍ → ℂ) →ₗ[ℂ] ((ℍ → ℂ) → ℂ)} (f : CuspForm ↑(Gamma1 N) k)
    (_hf : IsNewform χ k B f) : Submodule ℂ (CuspForm ↑(Gamma1 N) k) :=
  Submodule.span ℂ (galoisOrbit f)

/-- The **Atkin-Lehner subspace of `f`** at level `N` and weight `k`: the functions satisfying
every Atkin-Lehner eigen-equation that `f` satisfies — `g` belongs when, for each admissible
`W_Q` and each `ε` with `w_Q f = ε • f`, also `w_Q g = ε • g`. Quantifying over all admissible
matrices avoids choosing one, but identifying this set with the classical Atkin-Lehner subspace
of a trivial-character newform relies on two theorems, not encoded: such a newform is an
eigenform of every `w_Q`, and all admissible matrices for a given `Q` induce the same operator
on the relevant forms
(LMFDB [`cmf.maximal`](https://www.lmfdb.org/knowledge/show/cmf.maximal)). -/
def atkinLehnerSubspaceOf (k : ℤ) (N : ℕ) (f : ℍ → ℂ) : Set (ℍ → ℂ) :=
  {g | ∀ {Q : ℕ} {W : Matrix (Fin 2) (Fin 2) ℤ} (hW : IsAtkinLehnerMatrix N Q W) (ε : ℂ),
    atkinLehner k hW f = ε • f → atkinLehner k hW g = ε • g}

/-- The newspace of the **character orbit** `[χ]`: the subspace `S_k^new(N, [χ])`, the span
`⨆_σ S_k^new(N, σ∘χ)` of the newspaces at all Galois conjugates of `χ`. Galois conjugation
sends a newform of nebentypus `χ` to one of nebentypus `σ∘χ`, so a full Galois orbit of
newforms spans a subspace of this space, not of the fixed-`χ` component; LMFDB newspaces are
labelled by character orbits accordingly
(LMFDB [`cmf.newspace`](https://www.lmfdb.org/knowledge/show/cmf.newspace)). -/
noncomputable def newspaceCharOrbit {N : ℕ} (χ : DirichletCharacter ℂ N) (k : ℤ)
    (B : (ℍ → ℂ) →ₗ[ℂ] ((ℍ → ℂ) → ℂ)) : Submodule ℂ (ℍ → ℂ) :=
  ⨆ σ : ℂ ≃ₐ[ℚ] ℂ, newspace (χ.ringHomComp (σ : ℂ →+* ℂ)) k B

/-- A newform `f` is **maximal** if its Galois orbit spans the ambient subspace containing it:
for nontrivial character the entire newspace of the character orbit `S_k^new(N, [χ])` — the full
Galois orbit meets every conjugate-character component, so the fixed-`χ` component would be too
small — and for trivial character its Atkin-Lehner subspace within the newspace (the
eigenvalue-matching set `atkinLehnerSubspaceOf`; the trivial character is Galois-stable). The
spans are taken in the ambient functions on `ℍ`, where the newspaces live
(LMFDB [`cmf.maximal`](https://www.lmfdb.org/knowledge/show/cmf.maximal)). -/
def IsMaximalNewform {N : ℕ} {χ : DirichletCharacter ℂ N} {k : ℤ}
    {B : (ℍ → ℂ) →ₗ[ℂ] ((ℍ → ℂ) → ℂ)} (f : CuspForm ↑(Gamma1 N) k)
    (_hf : IsNewform χ k B f) : Prop :=
  (χ ≠ 1 → Submodule.span ℂ ((fun g : CuspForm ↑(Gamma1 N) k => ⇑g) '' galoisOrbit f) =
    newspaceCharOrbit χ k B) ∧
  (χ = 1 →
    (Submodule.span ℂ ((fun g : CuspForm ↑(Gamma1 N) k => ⇑g) '' galoisOrbit f) :
      Set (ℍ → ℂ)) = ↑(newspace χ k B) ∩ atkinLehnerSubspaceOf k N ⇑f)

/-- A newform `f` is the **largest** newform in its ambient subspace if its dimension — the
dimension of its newform subspace — strictly exceeds that of every nonconjugate newform of the
same character in the same ambient subspace (for trivial character, sharing the Atkin-Lehner
subspace of `f`; for nontrivial character the ambient is the whole newspace)
(LMFDB [`cmf.maximal`](https://www.lmfdb.org/knowledge/show/cmf.maximal)). -/
def IsLargestNewform {N : ℕ} {χ : DirichletCharacter ℂ N} {k : ℤ}
    {B : (ℍ → ℂ) →ₗ[ℂ] ((ℍ → ℂ) → ℂ)} (f : CuspForm ↑(Gamma1 N) k)
    (hf : IsNewform χ k B f) : Prop :=
  ∀ g, ∀ hg : IsNewform χ k B g, ¬ IsGaloisConjugate f g →
    (χ = 1 → ⇑g ∈ atkinLehnerSubspaceOf k N ⇑f) →
    Module.finrank ℂ (newformSubspace g hg) < Module.finrank ℂ (newformSubspace f hf)

/-- The **decomposition of the newspace into newforms** along a family
`f : ι → CuspForm (Γ₁(N)) k` of newforms: the spans of their Galois orbits (taken in the ambient
functions, where the newspaces live) are independent and jointly span the character-orbit
newspace `S_k^new(N, [χ])` — full Galois orbits meet every conjugate-character component, so
the ambient is `newspaceCharOrbit`, not the fixed-`χ` component. The internal direct-sum
statement is phrased as a proposition about a supplied family rather than as definitional data;
that such a family exists, that each piece is irreducible and Hecke-stable, and that its
dimension equals the degree of the coefficient field of its newform are theorems, not encoded
(LMFDB [`cmf.decomposition.new.gamma0chi`](https://www.lmfdb.org/knowledge/show/cmf.decomposition.new.gamma0chi)). -/
def IsNewformDecomposition {ι : Type*} {N : ℕ} {χ : DirichletCharacter ℂ N} {k : ℤ}
    {B : (ℍ → ℂ) →ₗ[ℂ] ((ℍ → ℂ) → ℂ)} (f : ι → CuspForm ↑(Gamma1 N) k)
    (_hf : ∀ i, IsNewform χ k B (f i)) : Prop :=
  iSupIndep
    (fun i => Submodule.span ℂ
      ((fun g : CuspForm ↑(Gamma1 N) k => ⇑g) '' galoisOrbit (f i))) ∧
  ⨆ i, Submodule.span ℂ ((fun g : CuspForm ↑(Gamma1 N) k => ⇑g) '' galoisOrbit (f i)) =
    newspaceCharOrbit χ k B

/-- The **trace form of a newspace**: the modular form obtained by summing its canonical basis
of newforms, expressed as the sum `∑ᵢ Tr(fᵢ)` of the orbit trace forms over a finite family of
newforms decomposing the character-orbit newspace — the canonical basis is the union of the
Galois orbits, and summing within each orbit gives its trace form `ModularForm.traceForm`. The
coefficient-field membership of the `q`-coefficients is an input; for a genuine cusp form it is
provable, the constant term vanishing by `qExpansion_coeff_zero` with the `Γ₁(N)` period lemma
`strictPeriods_Gamma1` and the higher coefficients being generators
(LMFDB [`cmf.space_trace_form`](https://www.lmfdb.org/knowledge/show/cmf.space_trace_form)). -/
noncomputable def spaceTraceForm {ι : Type*} [Fintype ι] {N : ℕ}
    {χ : DirichletCharacter ℂ N} {k : ℤ} {B : (ℍ → ℂ) →ₗ[ℂ] ((ℍ → ℂ) → ℂ)}
    (f : ι → CuspForm ↑(Gamma1 N) k) (hf : ∀ i, IsNewform χ k B (f i))
    (_hdec : IsNewformDecomposition f hf)
    (hmem : ∀ i n, (qExpansion 1 ⇑(f i)).coeff n ∈ coefficientField ⇑(f i)) : ℍ → ℂ :=
  ∑ i, traceForm ⇑(f i) (hmem i)

open Classical in
/-- The **holomorphic Eisenstein series** `E_k^(χ₁,χ₂)` of weight `k` attached to primitive
Dirichlet characters `χ₁` mod `N₁` and `χ₂` mod `N₂`:
`½ (δ_(χ₁=1) L(1-k, χ₂) + δ_(k=1) δ_(χ₂=1) L(0, χ₁)) + ∑_(n≥1) σ_(k-1)^(χ₁,χ₂)(n) qⁿ`, where
`σ_(k-1)^(χ₁,χ₂)(n) = ∑_(m∣n) χ₁(n/m) χ₂(m) m^(k-1)` and `L` is the analytically continued
Dirichlet L-function `DirichletCharacter.LFunction`. This character-pair series is deliberately
distinct from mathlib's residue-pair-indexed `EisensteinSeries.eisensteinSeries`; relating the
two, and modularity of this series in `M_k(N₁N₂, χ₁χ₂)`, are theorems, not encoded
(LMFDB [`cmf.eisenstein_series`](https://www.lmfdb.org/knowledge/show/cmf.eisenstein_series)). -/
noncomputable def eisensteinSeriesChar {N₁ N₂ : ℕ} [NeZero N₁] [NeZero N₂]
    (χ₁ : DirichletCharacter ℂ N₁) (χ₂ : DirichletCharacter ℂ N₂) (k : ℤ) (_hk : 0 < k)
    (_h₁ : χ₁.IsPrimitive) (_h₂ : χ₂.IsPrimitive) : ℍ → ℂ :=
  fun τ =>
    (1 / 2) * ((if χ₁ = 1 then DirichletCharacter.LFunction χ₂ (1 - (k : ℂ)) else 0) +
      (if k = 1 ∧ χ₂ = 1 then DirichletCharacter.LFunction χ₁ 0 else 0)) +
    ∑' n : ℕ, (∑ m ∈ (n + 1).divisors, χ₁ (((n + 1) / m : ℕ)) * χ₂ m * (m : ℂ) ^ (k - 1))
      * Function.Periodic.qParam 1 τ ^ (n + 1)

/-- The **Eisenstein subspace** `E_k(Γ)`: the orthogonal complement of the cusp forms
`S_k(Γ)` (mathlib's `cuspFormSubmodule`) inside `M_k(Γ)` with respect to the Petersson inner
product, expressed relative to a pairing `B`, as for `ModularForm.newspace` — the intersection
of the kernels `f ↦ B f g` over cusp forms `g`. Here `B f g` stands for the Petersson pairing
of `f` and `g` with the arguments ordered so that `B` is linear in `f`: since the classical
Petersson product is conjugate-linear in one slot, the intended instantiation puts `f` in the
linear slot (for mathlib's integrand, which conjugates its first argument, this means
`B f g = ⟨g, f⟩`). `B` is an input until the product is defined (see
`cmf.petersson_scalar_product`)
(LMFDB [`cmf.eisenstein_form`](https://www.lmfdb.org/knowledge/show/cmf.eisenstein_form)). -/
noncomputable def eisensteinSubspace (Γ : Subgroup (GL (Fin 2) ℝ)) (k : ℤ) [Γ.HasDetOne]
    (B : ModularForm Γ k →ₗ[ℂ] (ModularForm Γ k → ℂ)) : Submodule ℂ (ModularForm Γ k) :=
  ⨅ g : ↥(cuspFormSubmodule Γ k), LinearMap.ker ((LinearMap.proj (g : ModularForm Γ k)).comp B)

/-- An **Eisenstein form** of weight `k`, level `N` and character `χ`: a modular form in the
Eisenstein subspace `E_k(Γ₁(N))` that transforms with nebentypus `χ` — the membership predicate
of the space `E_k(N, χ)`. The knowl's spanning description of `E_k(N, χ)` by the series
`E_k^(χ₁,χ₂)(dτ)` with `χ₁χ₂ = χ` and `d·N₁·N₂ ∣ N` (with the non-holomorphic `E₂` correction
`E₂(τ) - d·E₂(dτ)` at `k = 2`, `χ = 1`) is a theorem, deliberately not the definition
(LMFDB [`cmf.eisenstein_form`](https://www.lmfdb.org/knowledge/show/cmf.eisenstein_form)). -/
def IsEisensteinForm {N : ℕ} (χ : DirichletCharacter ℂ N) (k : ℤ)
    (B : ModularForm ↑(Gamma1 N) k →ₗ[ℂ] (ModularForm ↑(Gamma1 N) k → ℂ))
    (f : ModularForm ↑(Gamma1 N) k) : Prop :=
  f ∈ eisensteinSubspace ↑(Gamma1 N) k B ∧ HasCharacter (Gamma0 N) k χ ⇑f

open Classical in
/-- The **new Eisenstein subspace** `E_k^new(N, χ)`: the span of the Eisenstein series
`E_k^(χ₁,χ₂)` over pairs of primitive characters with the parity compatibility
`χ₁(-1)χ₂(-1) = (-1)^k` (required for the series to be a modular form; given `χ₁χ₂ = χ` it is
equivalent to `χ(-1) = (-1)^k`, so the space is `⊥` for wrong-parity `(k, χ)`), with `χ₁χ₂ = χ`
(as characters mod `N`, via `changeLevel`) and `N₁N₂ = N` exactly — except in the case `k = 2`,
`χ = 1`, where
`E₂^new(N) = 0` for composite `N` and, for `N = p` prime, the space is spanned by the corrected
series `E₂^(1,1)(τ) - p E₂^(1,1)(pτ)`. The old Eisenstein subspace, span of the degeneracy
images from proper divisor levels, is the `cmf.oldspace`/`cmf.subspaces` construction at
Eisenstein level; the decomposition `E_k = E_k^old ⊕ E_k^new` is a theorem, not encoded
(LMFDB [`cmf.eisenstein_newspace`](https://www.lmfdb.org/knowledge/show/cmf.eisenstein_newspace)). -/
noncomputable def eisensteinNewspace {N : ℕ} [NeZero N] (χ : DirichletCharacter ℂ N) (k : ℤ) :
    Submodule ℂ (ℍ → ℂ) :=
  if k = 2 ∧ χ = 1 then
    if hN : N.Prime then
      Submodule.span ℂ
        {eisensteinSeriesChar 1 1 2 two_pos DirichletCharacter.isPrimitive_one_level_one
            DirichletCharacter.isPrimitive_one_level_one -
          (N : ℂ) • levelRaisingMap ⟨N, hN.pos⟩
            (eisensteinSeriesChar 1 1 2 two_pos DirichletCharacter.isPrimitive_one_level_one
              DirichletCharacter.isPrimitive_one_level_one)}
    else ⊥
  else
    Submodule.span ℂ
      {g | ∃ (N₁ N₂ : ℕ) (h₁ : NeZero N₁) (h₂ : NeZero N₂) (_ : N₁ * N₂ = N)
        (χ₁ : DirichletCharacter ℂ N₁) (χ₂ : DirichletCharacter ℂ N₂)
        (hp₁ : χ₁.IsPrimitive) (hp₂ : χ₂.IsPrimitive) (hk : 0 < k)
        (hd₁ : N₁ ∣ N) (hd₂ : N₂ ∣ N),
        χ₁ (-1) * χ₂ (-1) = (-1) ^ k ∧
        DirichletCharacter.changeLevel hd₁ χ₁ * DirichletCharacter.changeLevel hd₂ χ₂ = χ ∧
        g = @eisensteinSeriesChar N₁ N₂ h₁ h₂ χ₁ χ₂ k hk hp₁ hp₂}

/-- An **Eisenstein newform** of weight `k`, level `N` and character `χ`: a form in the new
Eisenstein subspace `E_k^new(N, χ)` that is a Hecke eigenform, normalized so that its
`q`-expansion has `a₁ = 1`. As in `ModularForm.IsNewform`, the eigenform condition is stated for
the operators `T_n` with `n` positive and coprime to the level, the full-eigenform statement of
the knowl being the analogous theorem of Eisenstein newform theory; that the Eisenstein
newforms are a basis of `E_k^new(N, χ)` is likewise a theorem, not encoded
(LMFDB [`cmf.eisenstein_newform`](https://www.lmfdb.org/knowledge/show/cmf.eisenstein_newform)). -/
structure IsEisensteinNewform {N : ℕ} [NeZero N] (χ : DirichletCharacter ℂ N) (k : ℤ)
    (f : ℍ → ℂ) : Prop where
  mem_newspace : f ∈ eisensteinNewspace χ k
  eigen_away : ∀ n : ℕ, 0 < n → n.Coprime N → ∃ c : ℂ, heckeOperator χ k n f = c • f
  normalized : (qExpansion 1 f).coeff 1 = 1

end ModularForm
