import Mathlib.Analysis.SpecialFunctions.Gamma.Digamma
import Mathlib.FieldTheory.Relrank
import Mathlib.LinearAlgebra.Charpoly.Basic
import Mathlib.NumberTheory.DirichletCharacter.Basic
import Mathlib.NumberTheory.ModularForms.Basic
import Mathlib.NumberTheory.ModularForms.CongruenceSubgroups
import Mathlib.NumberTheory.ModularForms.QExpansion
import Mathlib.NumberTheory.ModularForms.SlashActions

/-!
# Classical modular form definitions for LeanBridge (chapter 5)

Definitions from the LMFDB classical-modular-form knowls that are not (yet) in mathlib, written
here in mathlib style for the LeanBridge blueprint audit.
-/

open scoped MatrixGroups

namespace CongruenceSubgroup

/-- A positive integer `N` is a **level** of a subgroup `Γ` of `SL(2, ℤ)` if `Γ` contains the
principal congruence subgroup `Γ(N)`; a modular form on `Γ` is then said to have level `N`
(LMFDB [`cmf.level`](https://www.lmfdb.org/knowledge/show/cmf.level)). -/
def IsLevel (N : ℕ) (Γ : Subgroup SL(2, ℤ)) : Prop :=
  N ≠ 0 ∧ Gamma N ≤ Γ

/-- The **level** of a subgroup `Γ` of `SL(2, ℤ)`: the least positive integer `N` such that `Γ`
contains the principal congruence subgroup `Γ(N)`, or `0` if there is no such `N`, i.e. if `Γ` is
not a congruence subgroup. The LMFDB defines the level of a newform as the least level of its
group of invariance (LMFDB [`cmf.level`](https://www.lmfdb.org/knowledge/show/cmf.level)). -/
noncomputable def level (Γ : Subgroup SL(2, ℤ)) : ℕ :=
  sInf {N | IsLevel N Γ}

/-- A prime `p` is a **bad prime** for a modular form on a subgroup `Γ` of `SL(2, ℤ)` when it
divides the level of `Γ`
(LMFDB [`cmf.bad_prime`](https://www.lmfdb.org/knowledge/show/cmf.bad_prime)). -/
def IsBadPrime (p : ℕ) (Γ : Subgroup SL(2, ℤ)) : Prop :=
  p.Prime ∧ p ∣ level Γ

/-- A prime `p` is a **good prime** for a modular form on a subgroup `Γ` of `SL(2, ℤ)` when it
does not divide the level of `Γ`, i.e. when it is not a bad prime
(LMFDB [`cmf.bad_prime`](https://www.lmfdb.org/knowledge/show/cmf.bad_prime)). -/
def IsGoodPrime (p : ℕ) (Γ : Subgroup SL(2, ℤ)) : Prop :=
  p.Prime ∧ ¬ p ∣ level Γ

end CongruenceSubgroup

namespace DirichletCharacter

/-- The **character field** `ℚ(χ)` of a Dirichlet character `χ` with values in `ℂ`: the number
field generated over `ℚ` by the values of `χ`. This is the base field over which the LMFDB
measures the relative dimension of a newform
(LMFDB [`cmf.relative_dimension`](https://www.lmfdb.org/knowledge/show/cmf.relative_dimension)). -/
noncomputable def valueField {N : ℕ} (χ : DirichletCharacter ℂ N) : IntermediateField ℚ ℂ :=
  IntermediateField.adjoin ℚ (Set.range χ)

end DirichletCharacter

namespace ModularForm

open UpperHalfPlane CongruenceSubgroup

/-- A function `f : ℍ → ℂ` transforms with **character** (or nebentypus) `χ` mod `N` in weight `k`
under a subgroup `Γ` of `SL(2, ℤ)` if `f(γz) = χ(d)(cz+d)^k f(z)` for all `γ = !![*, *; c, d]` in
`Γ`, that is, `f ∣[k] γ = χ(d) • f`. The LMFDB states this for a modular form on a group `Γ`
containing `Γ(N)` (see `CongruenceSubgroup.IsLevel`), typically `Γ₀(N)`
(LMFDB [`cmf.character`](https://www.lmfdb.org/knowledge/show/cmf.character)). -/
def HasCharacter (Γ : Subgroup SL(2, ℤ)) (k : ℤ) {N : ℕ} (χ : DirichletCharacter ℂ N)
    (f : ℍ → ℂ) : Prop :=
  ∀ γ ∈ Γ, f ∣[k] γ = χ (γ 1 1 : ZMod N) • f

/-- The **analytic conductor** of a newform of level `N` and weight `k`: the real number
`N * (exp (ψ (k / 2)) / (2 * π)) ^ 2`, where `ψ = Γ'/Γ` is the digamma function. Mathlib defines
the digamma function only on `ℂ`; for `k ≥ 1` its value at `k / 2` is real, and this definition
takes its real part
(LMFDB [`cmf.analytic_conductor`](https://www.lmfdb.org/knowledge/show/cmf.analytic_conductor)). -/
noncomputable def analyticConductor (N : ℕ) (k : ℤ) : ℝ :=
  N * (Real.exp (Complex.digamma (k / 2)).re / (2 * Real.pi)) ^ 2

/-- The **Sturm bound** of a space `M_k(N, χ)` of modular forms of weight `k`, level `N` and
character `χ`: the integer `⌊k * [SL(2, ℤ) : Γ₀(N)] / 12⌋`, where the index of `Γ₀(N)` is used
for every character `χ`. Two forms in `M_k(N, χ)` whose Fourier coefficients agree up to this
bound are equal
(LMFDB [`cmf.sturm_bound`](https://www.lmfdb.org/knowledge/show/cmf.sturm_bound)). -/
noncomputable def sturmBound (N : ℕ) (k : ℤ) : ℕ :=
  (k * (Gamma0 N).index / 12).toNat

/-- The **Sturm bound for `Γ₁(N)`** of a space `M_k(Γ₁(N))` of modular forms of weight `k` and
level `N`: the integer `⌊k * [SL(2, ℤ) : Γ₁(N)] / 12⌋`
(LMFDB [`cmf.sturm_bound_gamma1`](https://www.lmfdb.org/knowledge/show/cmf.sturm_bound_gamma1)). -/
noncomputable def sturmBoundGamma1 (N : ℕ) (k : ℤ) : ℕ :=
  (k * (Gamma1 N).index / 12).toNat

/-- The **relative dimension** of a newform in `S_k^new(Γ₀(N), χ)` with coefficient field `F`:
the degree of `F` over the character field `ℚ(χ)`. The coefficient field (the subfield of `ℂ`
generated by the Fourier coefficients, LMFDB `cmf.coefficient_field`) is taken here as an
explicit argument. `IntermediateField.relfinrank` computes `[F : ℚ(χ) ⊓ F]`, which agrees with
the degree `[F : ℚ(χ)]` since `ℚ(χ) ≤ F` for the coefficient field of a newform
(LMFDB [`cmf.relative_dimension`](https://www.lmfdb.org/knowledge/show/cmf.relative_dimension)). -/
noncomputable def relativeDimension {N : ℕ} (χ : DirichletCharacter ℂ N)
    (F : IntermediateField ℚ ℂ) : ℕ :=
  χ.valueField.relfinrank F

/-- The **coefficient ring** of a modular form `f`: the subring `ℤ[a₁, a₂, a₃, …]` of `ℂ`
generated by the coefficients `aₙ`, `n ≥ 1`, of its `q`-expansion `∑ aₙ qⁿ` at the infinite cusp
(taken with period `1`, i.e. `q = e^(2πiz)`, as for forms on `Γ₀(N)`). For a newform this is also
called the Hecke ring, the `aₙ` being Hecke eigenvalues
(LMFDB [`cmf.coefficient_ring`](https://www.lmfdb.org/knowledge/show/cmf.coefficient_ring)). -/
noncomputable def coefficientRing (f : ℍ → ℂ) : Subring ℂ :=
  Subring.closure (Set.range fun n : ℕ => (qExpansion 1 f).coeff (n + 1))

/-- The **coefficient field** of a modular form `f`: the subfield of `ℂ` generated over `ℚ` by
the coefficients `aₙ`, `n ≥ 1`, of its `q`-expansion `∑ aₙ qⁿ` at the infinite cusp (period `1`,
as in `ModularForm.coefficientRing`). For a Hecke eigenform this is a number field, also called
the Hecke field, and the relative dimension of a newform `f` in `S_k^new(Γ₀(N), χ)` is
`relativeDimension χ (coefficientField f)`
(LMFDB [`cmf.coefficient_field`](https://www.lmfdb.org/knowledge/show/cmf.coefficient_field)). -/
noncomputable def coefficientField (f : ℍ → ℂ) : IntermediateField ℚ ℂ :=
  IntermediateField.adjoin ℚ (Set.range fun n : ℕ => (qExpansion 1 f).coeff (n + 1))

/-- The **embedding** `ι(f)` of a modular form `f` along a field embedding `ι : F → ℂ`, where `F`
is a subfield of `ℂ` containing every `q`-expansion coefficient `aₙ` of `f` (for a newform, its
coefficient field): the function on `ℍ` with `q`-expansion `∑ ι(aₙ) qⁿ`, defined as the sum of
that series in `q = e^(2πiτ)`. Its value is junk where the series diverges; convergence on all of
`ℍ`, and modularity of `ι(f)`, are theorems about newforms and are not part of the definition
(LMFDB [`cmf.embedding`](https://www.lmfdb.org/knowledge/show/cmf.embedding)). -/
noncomputable def embeddedForm {F : IntermediateField ℚ ℂ} (f : ℍ → ℂ) (ι : F →+* ℂ)
    (hf : ∀ n, (qExpansion 1 f).coeff n ∈ F) : ℍ → ℂ :=
  fun τ => ∑' n : ℕ, ι ⟨(qExpansion 1 f).coeff n, hf n⟩ * Function.Periodic.qParam 1 τ ^ n

/-- Two cusp forms `f = ∑ aₙ qⁿ` and `g = ∑ bₙ qⁿ` on `Γ₁(N)` are **Galois conjugate** if there
is an automorphism `σ` with `bₙ = σ(aₙ)` for all `n ≥ 1`; since cusp forms have `a₀ = 0`, the
`q`-expansion of `g` is then the full coefficientwise image of that of `f`, i.e. `g = σ(f)`. The
LMFDB states this for newforms — newform-ness of `f` and `g` is not encoded — and takes
`σ ∈ Gal(ℚ̄/ℚ)`; here `σ` ranges over the `ℚ`-automorphisms of `ℂ`, which restrict to — and, by
the axiom of choice, extend from — automorphisms of `ℚ̄`, so for newforms, whose coefficients are
algebraic, the two formulations agree
(LMFDB [`cmf.galois_conjugate`](https://www.lmfdb.org/knowledge/show/cmf.galois_conjugate)). -/
def IsGaloisConjugate {N : ℕ} {k : ℤ} (f g : CuspForm ↑(Gamma1 N) k) : Prop :=
  ∃ σ : ℂ ≃ₐ[ℚ] ℂ, ∀ n : ℕ, n ≠ 0 → (qExpansion 1 ⇑g).coeff n = σ ((qExpansion 1 ⇑f).coeff n)

/-- The **Galois orbit** `[f]` of a newform `f`: the set `{σ(f) : σ ∈ Gal(ℚ̄/ℚ)}` of its
coefficientwise Galois conjugates within the cusp forms on `Γ₁(N)`, also called the newform
orbit. For a genuine newform this is the LMFDB's finite orbit `[f]`; its finiteness, and the
fact that it is a basis of the newform subspace it spans, are theorems and not part of the
definition
(LMFDB [`cmf.galois_orbit`](https://www.lmfdb.org/knowledge/show/cmf.galois_orbit)). -/
def galoisOrbit {N : ℕ} {k : ℤ} (f : CuspForm ↑(Gamma1 N) k) : Set (CuspForm ↑(Gamma1 N) k) :=
  {g | IsGaloisConjugate f g}

/-- The **trace form** `Tr(f)` of a newform `f` whose coefficient field is `F`: the sum
`∑ᵢ ι(f)` of the embeddings of `f` over all field embeddings `ι : F → ℂ`, equivalently the sum
of the distinct Galois conjugates of `f`. Its q-expansion is the coefficientwise field trace
`∑ Tr_{F/ℚ}(aₙ) qⁿ`, with integer coefficients and `a₁` the dimension of the newform — both
theorems, not encoded. The `finsum` is junk `0` unless `F` admits only finitely many embeddings,
as a number field does; and the sum counts each conjugate once only when `F` is exactly the
coefficient field of `f`, as the LMFDB prescribes
(LMFDB [`cmf.trace_form`](https://www.lmfdb.org/knowledge/show/cmf.trace_form)). -/
noncomputable def traceForm {F : IntermediateField ℚ ℂ} (f : ℍ → ℂ)
    (hf : ∀ n, (qExpansion 1 f).coeff n ∈ F) : ℍ → ℂ :=
  ∑ᶠ ι : F →+* ℂ, embeddedForm f ι hf

/-- The **Hecke operator** `T_n` on modular forms of weight `k`, level `N` and character `χ`, in
its `q`-expansion model: `T_n f` is the function on `ℍ` whose `q`-expansion has coefficients
`a_m(T_n f) = ∑_{d ∣ gcd(m,n)} χ(d) d^(k-1) a_(mn/d²)(f)`, summed here as a series in
`q = e^(2πiτ)`. Of the two equivalent classical models this implements the coefficient formula,
not the double-coset sum. That `T_n f` is again a modular form in `M_k(N, χ)`, linearity in `f`,
and the commutation and eigenbasis properties are theorems, not encoded; the sum is junk where
it diverges
(LMFDB [`cmf.hecke_operator`](https://www.lmfdb.org/knowledge/show/cmf.hecke_operator)). -/
noncomputable def heckeOperator {N : ℕ} (χ : DirichletCharacter ℂ N) (k : ℤ) (n : ℕ)
    (f : ℍ → ℂ) : ℍ → ℂ :=
  fun τ => ∑' m : ℕ,
    (∑ d ∈ (m.gcd n).divisors, χ d * (d : ℂ) ^ (k - 1) * (qExpansion 1 f).coeff (m * n / d ^ 2))
      * Function.Periodic.qParam 1 τ ^ m

/-- An **admissible Atkin-Lehner matrix** `W_Q` for level `N` and a divisor `Q` of `N`: the LMFDB
requires `Q` positive with `gcd(Q, N/Q) = 1`, and `W_Q = [[Qx, y], [Nz, Qt]]` of determinant `Q`
for some integers `x, y, z, t` — the existential shape is recorded equivalently as divisibility
of the entries, the witnesses being the quotients
(LMFDB [`cmf.atkin-lehner`](https://www.lmfdb.org/knowledge/show/cmf.atkin-lehner)). -/
structure IsAtkinLehnerMatrix (N Q : ℕ) (W : Matrix (Fin 2) (Fin 2) ℤ) : Prop where
  level_pos : 0 < N
  pos : 0 < Q
  dvd : Q ∣ N
  coprime : Nat.Coprime Q (N / Q)
  q_dvd_upper_left : (Q : ℤ) ∣ W 0 0
  n_dvd_lower_left : (N : ℤ) ∣ W 1 0
  q_dvd_lower_right : (Q : ℤ) ∣ W 1 1
  det_eq : W.det = Q

/-- The **Atkin-Lehner involution** `w_Q` of weight `k` attached to an admissible Atkin-Lehner
matrix `W_Q` for an exact divisor `Q` of `N`: the classical operator
`w_Q f = Q^(k/2) (Nz·τ + Qt)^(-k) f(W_Q·τ)`, written as the slash action `f ∣[k] W_Q` scaled by
`Q^(1 - k/2)` to convert mathlib's determinant normalization `det^(k-1)` into the classical
`det^(k/2)`, under which `w_Q` squares to the identity on `Γ₀(N)`-invariant forms. On a form of
`S_k(Γ₀(N))` — trivial character — that is an eigenform for every `T_p` with `p ∤ N`, it acts
with eigenvalue `±1`; for nontrivial nebentypus `w_Q` does not preserve the `χ`-space, and the
Atkin-Li pseudo-eigenvalues have modulus `1`, not `±1`. Independence of the choice of admissible
matrix and commutation with the Hecke operators `T_p`, `p ∤ Q`, are theorems, not encoded
(LMFDB [`cmf.atkin-lehner`](https://www.lmfdb.org/knowledge/show/cmf.atkin-lehner)). -/
noncomputable def atkinLehner (k : ℤ) {N Q : ℕ} {W : Matrix (Fin 2) (Fin 2) ℤ}
    (hW : IsAtkinLehnerMatrix N Q W) (f : ℍ → ℂ) : ℍ → ℂ :=
  (Q : ℂ) ^ (1 - (k : ℂ) / 2) •
    (f ∣[k] Matrix.GeneralLinearGroup.mkOfDetNeZero ((Int.castRingHom ℝ).mapMatrix W) (by
      rw [← RingHom.map_det, hW.det_eq, map_natCast]
      exact_mod_cast hW.pos.ne'))

/-- The **Fricke involution** `w_N` of weight `k` on forms of level `N`: the Atkin-Lehner
involution for the full level `Q = N`, represented by the admissible matrix `[[0, -1], [N, 0]]`.
For a newform in `S_k^new(Γ₀(N))`, the sign of the functional equation of its L-function is
`i^(-k)` times its `w_N`-eigenvalue — a theorem, not encoded
(LMFDB [`cmf.fricke`](https://www.lmfdb.org/knowledge/show/cmf.fricke)). -/
noncomputable def fricke (k : ℤ) {N : ℕ} (hN : 0 < N) (f : ℍ → ℂ) : ℍ → ℂ :=
  atkinLehner k (W := !![0, -1; (N : ℤ), 0])
    { level_pos := hN
      pos := hN
      dvd := dvd_rfl
      coprime := by simp [Nat.div_self hN]
      q_dvd_upper_left := by simp
      n_dvd_lower_left := by simp
      q_dvd_lower_right := by simp
      det_eq := by simp [Matrix.det_fin_two_of] }
    f

/-- The **Hecke orbit** of a cusp form `f` in `S_k(N, χ)` — a bundled cusp form on `Γ₁(N)`
together with nebentypus `χ` under `Γ₀(N)`: the subspace of functions on `ℍ` generated by the
images `T_p f` of `f` under the Hecke operators at all primes `p` coprime to the level `N`. The
orbit lives in the ambient space of functions since stability of cusp forms under the `T_p` is a
theorem, not encoded
(LMFDB [`cmf.hecke_orbit`](https://www.lmfdb.org/knowledge/show/cmf.hecke_orbit)). -/
noncomputable def heckeOrbit {N : ℕ} (χ : DirichletCharacter ℂ N) (k : ℤ)
    (f : CuspForm ↑(Gamma1 N) k) (_hf : HasCharacter (Gamma0 N) k χ ⇑f) :
    Submodule ℂ (ℍ → ℂ) :=
  Submodule.span ℂ {g | ∃ p : ℕ, p.Prime ∧ p.Coprime N ∧ g = heckeOperator χ k p ⇑f}

open Classical in
/-- The **Hecke characteristic polynomial** of a newform `f` at a prime `p`: the characteristic
polynomial of the Hecke operator `T_p` acting on the newform subspace `V_f`, the span of the
Galois orbit of `f` inside the cusp forms on `Γ₁(N)`. Finite-dimensionality of `V_f` is an
instance hypothesis (it holds for genuine newforms), and the action is the linear endomorphism
of `V_f` agreeing pointwise with `heckeOperator χ k p` — unique when it exists, since its values
are forced — with junk value `0` when no such endomorphism exists. Primality of `p` is not
required by the formula; the LMFDB uses good primes
(LMFDB [`cmf.heckecharpolys`](https://www.lmfdb.org/knowledge/show/cmf.heckecharpolys)). -/
noncomputable def heckeCharpoly {N : ℕ} (χ : DirichletCharacter ℂ N) (k : ℤ) (p : ℕ)
    (f : CuspForm ↑(Gamma1 N) k) (_hf : HasCharacter (Gamma0 N) k χ ⇑f)
    [Module.Finite ℂ (Submodule.span ℂ (galoisOrbit f))] : Polynomial ℂ :=
  if h : ∃ T : Submodule.span ℂ (galoisOrbit f) →ₗ[ℂ] Submodule.span ℂ (galoisOrbit f),
      ∀ v, ⇑(T v : CuspForm ↑(Gamma1 N) k) = heckeOperator χ k p ⇑(v : CuspForm ↑(Gamma1 N) k) then
    h.choose.charpoly
  else 0

/-- A finite set `P` of primes indexes **distinguishing Hecke operators** `𝒯 = {T_p : p ∈ P}`
for a family `f : ι → CuspForm (Γ₁(N)) k` of nonconjugate newforms with nebentypus `χ`: the
primes are good (`p ∤ N`, the LMFDB's convenience restriction), and the sets `X_(f i)(𝒯)` of
Hecke characteristic polynomials of the `T_p` on the newform subspaces are pairwise distinct.
If the family contains conjugate newforms the proposition is unsatisfiable, so `ι` should index
orbit representatives. The particular ordered sequence of such primes recorded by the LMFDB (via
its strictly increasing refinement count) is a database convention, not formalized
(LMFDB [`cmf.distinguishing_primes`](https://www.lmfdb.org/knowledge/show/cmf.distinguishing_primes)). -/
def DistinguishesNewforms {ι : Type*} {N : ℕ} (χ : DirichletCharacter ℂ N) (k : ℤ)
    (f : ι → CuspForm ↑(Gamma1 N) k) (hf : ∀ i, HasCharacter (Gamma0 N) k χ ⇑(f i))
    [∀ i, Module.Finite ℂ (Submodule.span ℂ (galoisOrbit (f i)))] (P : Finset ℕ) : Prop :=
  (∀ p ∈ P, p.Prime ∧ ¬ p ∣ N) ∧
    Function.Injective fun i => (fun p => heckeCharpoly χ k p (f i) (hf i)) '' (P : Set ℕ)

/-- The **coefficient ring generator bound** of a newform `f` with `q`-expansion `∑ aₙ qⁿ`: the
least positive integer `n` such that `ℤ[a₁, …, aₙ]` is the entire coefficient ring
`ℤ[a₁, a₂, a₃, …]`, or junk `0` if no finite prefix of the coefficients generates it
(LMFDB [`cmf.hecke_ring_generators`](https://www.lmfdb.org/knowledge/show/cmf.hecke_ring_generators)). -/
noncomputable def heckeRingGeneratorBound (f : ℍ → ℂ) : ℕ :=
  sInf {n | 0 < n ∧
    Subring.closure ((fun m => (qExpansion 1 f).coeff m) '' Set.Icc 1 n) = coefficientRing f}

/-- The **trace bound** of a family `f : ι → CuspForm (Γ₁(N)) k` of nonconjugate newforms with
nebentypus `χ` spanning the Galois orbits of a newspace: the least positive integer `m` such
that the traces down to `ℚ` of the coefficients `aₙ`, `n ≤ m`, distinguish the orbits — the
trace of `aₙ` being the sum of `ι(aₙ)` over the embeddings `ι` of the coefficient field, as in
`ModularForm.traceForm`. Unlike the universal Sturm bound this is the least such bound for the
particular space; it is junk `0` if no prefix separates the family, e.g. if `ι` contains
conjugate newforms, which share all traces
(LMFDB [`cmf.trace_bound`](https://www.lmfdb.org/knowledge/show/cmf.trace_bound)). -/
noncomputable def traceBound {ι : Type*} {N : ℕ} (χ : DirichletCharacter ℂ N) (k : ℤ)
    (f : ι → CuspForm ↑(Gamma1 N) k) (_hf : ∀ i, HasCharacter (Gamma0 N) k χ ⇑(f i)) : ℕ :=
  sInf {m | 0 < m ∧ Function.Injective fun i => fun j : Fin m =>
    ∑ᶠ e : coefficientField ⇑(f i) →+* ℂ,
      e ⟨(qExpansion 1 ⇑(f i)).coeff ((j : ℕ) + 1),
        IntermediateField.subset_adjoin ℚ _ ⟨(j : ℕ), rfl⟩⟩}

end ModularForm
