#!/usr/bin/env sage
"""
Generate a Lean file certifying the q-expansion of a level-1 LMFDB modular form
via the polynomial-in-(E₄, E₆) framework. Supports arbitrary-degree Hecke fields
by decomposing each K-coefficient as a ℚ-polynomial in the algebraic generator α.

Emits:
- Polynomial decomposition (one rational `polyData` per power of α)
- Form definition `lmfdb_1_k_a_orbit := f_0 + α · f_1 + α² · f_2 + …`
- Bridge lemmas connecting each rational piece to its `evalEisPS`
- Coefficient decomposition lemma
- Named per-coefficient lemmas for every i ∈ {0, 1, …, sturm-1}
- Uniqueness theorem `identifies_lmfdb_1_k_a_orbit` via `eq_of_sturm_bound`

Usage:
    sage scripts/lmfdb_qexp_to_e4e6_v3.sage <weight> [<form_index>] [<output_path>]
"""


# This file was *autogenerated* from the file scripts/lmfdb_qexp_to_e4e6_v3.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_10 = Integer(10); _sage_const_12 = Integer(12); _sage_const_5 = Integer(5); _sage_const_4 = Integer(4); _sage_const_6 = Integer(6); _sage_const_2 = Integer(2); _sage_const_3 = Integer(3)
import sys
import os


def fmt_rat(c):
    n = c.numerator()
    d = c.denominator()
    if d == _sage_const_1 :
        return f"({n})" if n < _sage_const_0  else f"{n}"
    return f"((-({-n} / {d})))" if n < _sage_const_0  else f"({n} / {d})"


MIN_CERTIFY = _sage_const_10   # certify at least this many q-coefficients (Sturm bound takes precedence if larger)


def newform_decomposition(k, form_idx=_sage_const_0 ):
    sturm = k // _sage_const_12  + _sage_const_1 
    n_certify = max(sturm, MIN_CERTIFY)
    M = ModularForms(_sage_const_1 , k)
    cusp = M.cuspidal_subspace()
    if cusp.dimension() == _sage_const_0 :
        raise ValueError(f"S_{k} is zero-dimensional")
    forms = cusp.newforms('a')
    f = forms[form_idx]
    K = f.hecke_eigenvalue_field()
    d = K.degree()

    prec = n_certify + _sage_const_5 
    qexp = f.qexp(prec)
    if qexp[_sage_const_1 ] != _sage_const_0 :
        qexp = qexp / K(qexp[_sage_const_1 ])

    minpoly = K.gen().minpoly()
    minpoly_coeffs = list(minpoly)

    basis_pairs = [(a, b) for a in range(k // _sage_const_4  + _sage_const_1 ) for b in range(k // _sage_const_6  + _sage_const_1 )
                   if _sage_const_4  * a + _sage_const_6  * b == k]
    n_basis = len(basis_pairs)

    E4 = eisenstein_series_qexp(_sage_const_4 , prec, normalization='constant')
    E6 = eisenstein_series_qexp(_sage_const_6 , prec, normalization='constant')

    R = PowerSeriesRing(K, 'q', prec)
    E4_K = R(E4)
    E6_K = R(E6)
    basis_qexps = [E4_K ** a * E6_K ** b for (a, b) in basis_pairs]

    A = matrix(K, n_basis, n_basis,
               [[K(basis_qexps[j][i]) for j in range(n_basis)]
                for i in range(n_basis)])
    b_vec = vector(K, [K(qexp[i]) for i in range(n_basis)])
    coeffs = A.solve_right(b_vec)

    poly_per_power = [[] for _ in range(d)]
    for (a, b), c in zip(basis_pairs, coeffs):
        c_parts = c.list()
        while len(c_parts) < d:
            c_parts.append(QQ(_sage_const_0 ))
        for j in range(d):
            if c_parts[j] != _sage_const_0 :
                poly_per_power[j].append((int(a), int(b), c_parts[j]))

    qexp_decomp = []
    for n in range(prec):
        c_parts = K(qexp[n]).list()
        while len(c_parts) < d:
            c_parts.append(QQ(_sage_const_0 ))
        qexp_decomp.append(c_parts)

    return poly_per_power, minpoly_coeffs, sturm, qexp_decomp


def emit_alpha_block(weight, minpoly_coeffs, alpha_name):
    d = len(minpoly_coeffs) - _sage_const_1 
    # Build the polynomial as Polynomial ℂ
    poly_terms = []
    poly_terms.append("Polynomial.X ^ " + str(d) if d > _sage_const_1  else "Polynomial.X")
    if d == _sage_const_1 :
        poly_terms = ["Polynomial.X"]
    else:
        poly_terms = [f"Polynomial.X ^ {d}"]
    for i in range(d):
        c = minpoly_coeffs[i]
        if c == _sage_const_0 :
            continue
        if i == _sage_const_0 :
            poly_terms.append(f"Polynomial.C {fmt_rat(c)}")
        elif i == _sage_const_1 :
            poly_terms.append(f"Polynomial.C {fmt_rat(c)} * Polynomial.X")
        else:
            poly_terms.append(f"Polynomial.C {fmt_rat(c)} * Polynomial.X ^ {i}")
    poly_def = " +\n    ".join(poly_terms)

    # Concrete polynomial relation (used in α_is_root)
    rel_terms = [f"{alpha_name} ^ {d}"] if d > _sage_const_1  else [f"{alpha_name}"]
    if d == _sage_const_1 :
        rel_terms = [f"{alpha_name}"]
    else:
        rel_terms = [f"{alpha_name} ^ {d}"]
    for i in range(d):
        c = minpoly_coeffs[i]
        if c == _sage_const_0 :
            continue
        if i == _sage_const_0 :
            rel_terms.append(fmt_rat(c))
        elif i == _sage_const_1 :
            rel_terms.append(f"{fmt_rat(c)} * {alpha_name}")
        else:
            rel_terms.append(f"{fmt_rat(c)} * {alpha_name} ^ {i}")
    rel_expr = " +\n      ".join(rel_terms)

    return f"""/-- Minimal polynomial of α (degree {d}) as `Polynomial ℂ`. -/
noncomputable def {alpha_name}_minpoly : Polynomial ℂ :=
  {poly_def}

lemma {alpha_name}_minpoly_natDegree : {alpha_name}_minpoly.natDegree = {d} := by
  unfold {alpha_name}_minpoly
  compute_degree!

lemma {alpha_name}_minpoly_degree_ne_zero : {alpha_name}_minpoly.degree ≠ 0 := by
  rw [Polynomial.degree_eq_natDegree (fun h => by
    have := {alpha_name}_minpoly_natDegree
    rw [h, Polynomial.natDegree_zero] at this
    exact absurd this (by decide))]
  rw [{alpha_name}_minpoly_natDegree]
  decide

/-- α is some root of the degree-{d} minimal polynomial in ℂ. -/
noncomputable def {alpha_name} : ℂ :=
  (IsAlgClosed.exists_root {alpha_name}_minpoly {alpha_name}_minpoly_degree_ne_zero).choose

lemma {alpha_name}_isRoot : Polynomial.IsRoot {alpha_name}_minpoly {alpha_name} :=
  (IsAlgClosed.exists_root {alpha_name}_minpoly {alpha_name}_minpoly_degree_ne_zero).choose_spec

/-- Explicit polynomial relation: minpoly evaluated at α is zero. -/
lemma {alpha_name}_is_root :
    {rel_expr} = 0 := by
  have h := {alpha_name}_isRoot
  unfold Polynomial.IsRoot {alpha_name}_minpoly at h
  simp only [Polynomial.eval_add, Polynomial.eval_mul, Polynomial.eval_pow,
    Polynomial.eval_C, Polynomial.eval_X] at h
  linear_combination h"""


def emit_polydata(name, poly):
    if not poly:
        return f"def {name} : List (ℕ × ℕ × ℚ) := []"
    entries = ", ".join(f"({a}, {b}, {fmt_rat(c)})" for (a, b, c) in poly)
    return f"def {name} : List (ℕ × ℕ × ℚ) :=\n  [{entries}]"


def emit_form_def(name, weight, poly):
    if not poly:
        return f"noncomputable def {name} : ModularForm 𝒮ℒ {weight} := 0"
    terms = []
    for (a, b, c) in poly:
        terms.append(f"({fmt_rat(c)} : ℂ) • mkMonomForm {a} {b} {weight} (by decide)")
    body = " +\n  ".join(terms)
    return f"noncomputable def {name} : ModularForm 𝒮ℒ {weight} :=\n  {body}"


def emit_bridge_lemma(name, polydata_name, form_name, n_monoms):
    if n_monoms == _sage_const_0 :
        return f"""lemma {name} :
    qExpansion 1 ({form_name} : ℍ → ℂ) = evalEisPS {polydata_name} := by
  unfold {form_name} {polydata_name} evalEisPS
  simp [qExpansion_zero]"""

    rw_lines = []
    for _ in range(n_monoms - _sage_const_1 ):
        rw_lines.append("ModularForm.coe_add")
        rw_lines.append("ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL")
    for _ in range(n_monoms):
        rw_lines.append("ModularForm.IsGLPos.coe_smul")
    for _ in range(n_monoms):
        rw_lines.append("ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL")
    for _ in range(n_monoms):
        rw_lines.append("qExpansion_mkMonomForm")
    rw_chain = ",\n    ".join(rw_lines)

    return f"""lemma {name} :
    qExpansion 1 ({form_name} : ℍ → ℂ) = evalEisPS {polydata_name} := by
  unfold {form_name}
  rw [{rw_chain}]
  unfold evalEisPS {polydata_name} monomialEisPS
  simp only [List.foldr_cons, List.foldr_nil, add_zero]
  push_cast
  module"""


def emit_combined_form(weight, n_pieces, alpha_name):
    terms = [f"f_{weight}_part_0"]
    for j in range(_sage_const_1 , n_pieces):
        if j == _sage_const_1 :
            terms.append(f"{alpha_name} • f_{weight}_part_{j}")
        else:
            terms.append(f"{alpha_name} ^ {j} • f_{weight}_part_{j}")
    body = " +\n  ".join(terms)
    return f"""noncomputable def lmfdb_1_{weight}_a_orbit : ModularForm 𝒮ℒ {weight} :=
  {body}"""


def emit_coeff_decomp(weight, n_pieces, alpha_name):
    rhs_terms = []
    for j in range(n_pieces):
        coeff_term = f"(PowerSeries.coeff (R := ℂ) n) (qExpansion 1 (f_{weight}_part_{j} : ℍ → ℂ))"
        if j == _sage_const_0 :
            rhs_terms.append(coeff_term)
        elif j == _sage_const_1 :
            rhs_terms.append(f"{alpha_name} * {coeff_term}")
        else:
            rhs_terms.append(f"{alpha_name} ^ {j} * {coeff_term}")
    rhs = "\n        + ".join(rhs_terms)

    if n_pieces <= _sage_const_1 :
        # Single-piece (degree-1 Hecke field): orbit IS just the unique form
        return f"""lemma lmfdb_1_{weight}_a_orbit_coeff_decomp (n : ℕ) :
    (PowerSeries.coeff (R := ℂ) n) (qExpansion 1 (lmfdb_1_{weight}_a_orbit : ℍ → ℂ))
      = {rhs} := by
  rfl"""

    n_smuls = n_pieces - _sage_const_1 
    rw_lines = []
    for _ in range(n_pieces - _sage_const_1 ):
        rw_lines.append("ModularForm.coe_add")
        rw_lines.append("ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL")
    for _ in range(n_smuls):
        rw_lines.append("ModularForm.IsGLPos.coe_smul")
    for _ in range(n_smuls):
        rw_lines.append("ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL")
    rw_chain = ",\n    ".join(rw_lines)

    return f"""lemma lmfdb_1_{weight}_a_orbit_coeff_decomp (n : ℕ) :
    (PowerSeries.coeff (R := ℂ) n) (qExpansion 1 (lmfdb_1_{weight}_a_orbit : ℍ → ℂ))
      = {rhs} := by
  unfold lmfdb_1_{weight}_a_orbit
  rw [{rw_chain}]
  simp [smul_eq_mul]"""


def emit_precomputed_list(weight, j, n_certify, piece_qexp):
    """Emit the precomputed q-expansion list for piece j + the one-shot equality lemma.
    piece_qexp is a list of length n_certify of rationals (the q-coefficients of f_j)."""
    entries = ", ".join(fmt_rat(c) for c in piece_qexp)
    return f"""/-- Precomputed first {n_certify} q-coefficients of `f_{weight}_part_{j}` (rational). -/
def f_{weight}_part_{j}_qExpList : List ℚ :=
  [{entries}]

/-- One-shot bridge: the symbolic `evalEisList` equals the precomputed list (verified by
`decide +kernel` once instead of N times). -/
lemma f_{weight}_part_{j}_evalEisList_eq :
    evalEisList f_{weight}_part_{j}_polyData {n_certify} = f_{weight}_part_{j}_qExpList := by
  decide +kernel"""


def emit_named_coeff_lemma(weight, n, n_certify, qexp_decomp_n, n_pieces, alpha_name):
    """Named lemma for coefficient n of `lmfdb_1_{weight}_a_orbit`.
    Uses the precomputed `_qExpList` (cheap list lookup) instead of `evalEisList` (slow)."""
    rhs_parts = []
    for j, c in enumerate(qexp_decomp_n):
        if c == _sage_const_0 :
            continue
        cs = fmt_rat(c)
        if j == _sage_const_0 :
            rhs_parts.append(cs)
        elif j == _sage_const_1 :
            rhs_parts.append(f"{cs} * {alpha_name}")
        else:
            rhs_parts.append(f"{cs} * {alpha_name} ^ {j}")
    rhs = " + ".join(rhs_parts) if rhs_parts else "0"

    coeff_thm_rws = ",\n    ".join(
        f"f_{weight}_part_{j}_qExpansion_coeff {n_certify} {n} (by decide)"
        for j in range(n_pieces))
    eval_eq_rws = ",\n    ".join(
        f"f_{weight}_part_{j}_evalEisList_eq"
        for j in range(n_pieces))
    list_value_rws = []
    for j in range(n_pieces):
        c = qexp_decomp_n[j] if j < len(qexp_decomp_n) else _sage_const_0 
        list_value_rws.append(
            f"show f_{weight}_part_{j}_qExpList.getD {n} 0 = "
            f"({fmt_rat(c)} : ℚ) from by decide +kernel"
        )
    list_rws = ",\n    ".join(list_value_rws)

    return f"""lemma lmfdb_1_{weight}_a_orbit_qExpansion_coeff_{n} :
    (PowerSeries.coeff (R := ℂ) {n})
      (qExpansion 1 (lmfdb_1_{weight}_a_orbit : ℍ → ℂ)) = {rhs} := by
  rw [lmfdb_1_{weight}_a_orbit_coeff_decomp,
    {coeff_thm_rws},
    {eval_eq_rws},
    {list_rws}]
  push_cast; ring"""


def emit_uniqueness_theorem(weight, sturm, qexp_decomp, n_pieces, alpha_name):
    """Uniqueness theorem: f = lmfdb_1_{weight}_a_orbit if first sturm coeffs match."""
    # Hypotheses: one per i ∈ {0, …, sturm-1}
    hypotheses = []
    for i in range(sturm):
        rhs_parts = []
        for j, c in enumerate(qexp_decomp[i]):
            if c == _sage_const_0 :
                continue
            cs = fmt_rat(c)
            if j == _sage_const_0 :
                rhs_parts.append(cs)
            elif j == _sage_const_1 :
                rhs_parts.append(f"{cs} * {alpha_name}")
            else:
                rhs_parts.append(f"{cs} * {alpha_name} ^ {j}")
        rhs = " + ".join(rhs_parts) if rhs_parts else "0"
        hypotheses.append(
            f"    (h_{i} : (PowerSeries.coeff (R := ℂ) {i}) (qExpansion 1 (f : ℍ → ℂ)) = {rhs})")
    hyp_block = "\n".join(hypotheses)

    # Cases: one per i
    case_lines = []
    for i in range(sturm):
        case_lines.append(
            f"  · rw [h_{i}, lmfdb_1_{weight}_a_orbit_qExpansion_coeff_{i}]")
    cases = "\n".join(case_lines)

    return f"""/-- **Uniqueness theorem.** Any level-1 weight-{weight} modular form `f` whose first {sturm}
q-coefficients match the LMFDB-published values for `1.{weight}.a.{{a..}}` is equal to our
explicit construction `lmfdb_1_{weight}_a_orbit`. Proven via `ModularForm.eq_of_sturm_bound`. -/
theorem identifies_lmfdb_1_{weight}_a_orbit (f : ModularForm 𝒮ℒ {weight})
{hyp_block} :
    f = lmfdb_1_{weight}_a_orbit := by
  apply ModularForm.eq_of_sturm_bound
  intro i hi
  have : i ≤ {sturm - _sage_const_1 } := by omega
  interval_cases i
{cases}"""


def emit_full(weight, form_idx=_sage_const_0 ):
    poly_per_power, minpoly_coeffs, sturm, qexp_decomp = newform_decomposition(weight, form_idx)
    n_pieces = len(poly_per_power)
    alpha_name = f"α_{weight}"

    parts = [f"""import LeanBridge.ForMathlib.QExpansion.Generic
import LeanBridge.ForMathlib.QExpansion.Sturm
import Mathlib.Analysis.Complex.Polynomial.Basic

/-!
# LMFDB level-1 modular form orbit `1.{weight}.a.{{a..}}` (Hecke field degree {n_pieces})

The Hecke field `K = ℚ(α)` is degree {n_pieces} over ℚ. The LMFDB lists q-coefficients as
elements of `K`, which we decompose as `c_0 + c_1 · α + … + c_{{{n_pieces - _sage_const_1 }}} · α^{n_pieces - _sage_const_1 }`.
The combined form is `f = f_0 + α · f_1 + … + α^{n_pieces - _sage_const_1 } · f_{{{n_pieces - _sage_const_1 }}}`, with each
`f_j` a level-1 weight-{weight} form with rational coefficients in `(E₄, E₆)`.

The Sturm bound for weight {weight} is `⌊{weight}/12⌋ + 1 = {sturm}`. After certifying agreement
on the first {sturm} q-coefficients, `ModularForm.eq_of_sturm_bound` lets us conclude that any
form with the same coefficients equals our explicit `lmfdb_1_{weight}_a_orbit`.

Generated by `scripts/lmfdb_qexp_to_e4e6_v3.sage`.
-/

namespace LeanBridge.QExpansion.LMFDB.W{weight}

open LeanBridge.QExpansion ModularForm EisensteinSeries PowerSeries UpperHalfPlane
open scoped MatrixGroups
"""]

    parts.append(emit_alpha_block(weight, minpoly_coeffs, alpha_name))

    for j in range(n_pieces):
        parts.append(f"\n/-! ## Piece {j}: coefficient of α^{j} -/\n")
        parts.append(emit_polydata(f"f_{weight}_part_{j}_polyData", poly_per_power[j]))
        n_monoms = len(poly_per_power[j])
        parts.append(emit_form_def(f"f_{weight}_part_{j}", weight, poly_per_power[j]))
        parts.append(emit_bridge_lemma(
            f"f_{weight}_part_{j}_qExpansion_eq_evalEisPS",
            f"f_{weight}_part_{j}_polyData",
            f"f_{weight}_part_{j}",
            n_monoms))
        parts.append(f"""theorem f_{weight}_part_{j}_qExpansion_coeff (N n : ℕ) (hn : n < N) :
    (PowerSeries.coeff (R := ℂ) n) (qExpansion 1 (f_{weight}_part_{j} : ℍ → ℂ))
      = ((evalEisList f_{weight}_part_{j}_polyData N).getD n 0 : ℚ) :=
  qexp_coeff_via_E4E6 _ _ f_{weight}_part_{j}_qExpansion_eq_evalEisPS N n hn""")
        # Precomputed q-expansion list + one-shot equality
        n_certify = max(sturm, MIN_CERTIFY)
        piece_qexp = [qexp_decomp[n][j] if j < len(qexp_decomp[n]) else _sage_const_0 
                      for n in range(n_certify)]
        parts.append(emit_precomputed_list(weight, j, n_certify, piece_qexp))

    parts.append("\n/-! ## Combined LMFDB form -/\n")
    parts.append(emit_combined_form(weight, n_pieces, alpha_name))
    parts.append(emit_coeff_decomp(weight, n_pieces, alpha_name))

    n_certify = max(sturm, MIN_CERTIFY)
    parts.append(f"\n/-! ## Coefficient lemmas (n = 0, …, {n_certify - _sage_const_1 })\n\n"
                 f"Sturm bound is {sturm}; we certify {n_certify} coefficients for added\n"
                 f"redundancy beyond the minimum mathematically required for uniqueness. -/\n")
    for n in range(n_certify):
        parts.append(emit_named_coeff_lemma(
            weight, n, n_certify, qexp_decomp[n], n_pieces, alpha_name))

    parts.append("\n/-! ## Uniqueness theorem -/\n")
    parts.append(emit_uniqueness_theorem(weight, sturm, qexp_decomp, n_pieces, alpha_name))

    parts.append(f"\nend LeanBridge.QExpansion.LMFDB.W{weight}")
    return "\n\n".join(parts)


def main():
    if len(sys.argv) < _sage_const_2 :
        print(__doc__, file=sys.stderr)
        sys.exit(_sage_const_1 )
    weight = int(sys.argv[_sage_const_1 ])
    form_idx = int(sys.argv[_sage_const_2 ]) if len(sys.argv) >= _sage_const_3  else _sage_const_0 
    out_path = sys.argv[_sage_const_3 ] if len(sys.argv) >= _sage_const_4  else None

    code = emit_full(weight, form_idx)

    if out_path:
        os.makedirs(os.path.dirname(os.path.abspath(out_path)), exist_ok=True)
        with open(out_path, 'w') as f:
            f.write(code)
        print(f"Wrote {out_path}", file=sys.stderr)
    else:
        sys.stdout.write(code)


main()

