import LeanBridge.ForMathlib.QExpansion.IntEval

set_option maxHeartbeats 0
set_option maxRecDepth 4000

/-!
# LMFDB level-1 weight-68 form `1.68.a`, piece 1: integer q-coefficient certificate

Heavy `decide +kernel` over `ℤ` (denominators cleared by the scale `D = 32622830240152991493200157868032`), isolated in its own
module so `lake` schedules it in parallel with the other pieces. Generated by
`scripts/lmfdb_qexp_to_e4e6_v3.sage`.
-/

namespace LeanBridge.QExpansion.LMFDB.W68

open LeanBridge.QExpansion

def f_68_part_1_polyDataZ : List (ℕ × ℕ × ℤ) :=
  [(2, 10, (-203204679002166410081097934579)), (5, 8, 1009797878025073775833306055387), (8, 6, (-2012955494663586304293616664206)), (11, 4, 2012136931181821373577368547334), (14, 2, (-1008575495462346887201621650703)), (17, 0, 202800859921204452165661646767)]

def f_68_part_1_scale : ℤ := 32622830240152991493200157868032

def f_68_part_1_qExpListZ : List ℤ :=
  [0, 0, 32622830240152991493200157868032, 30066868589775093432105324930284912640, 0, 3114373430192401238655737204876994672574070784, 1121394639747713224602379315711226756136645427200, 36081722698256866433823064493496446222141434626048, (-9628560006402799109692858482496288595216851525435392), 737883075804982747062563945743697407926485264420044800]

/-- Integer-arithmetic certificate (the heavy kernel computation). -/
lemma f_68_part_1_evalEisListZ_eq :
    evalEisListZ f_68_part_1_polyDataZ 10 = f_68_part_1_qExpListZ := by
  decide +kernel

end LeanBridge.QExpansion.LMFDB.W68
