import LeanBridge.ForMathlib.QExpansion.IntEval

set_option maxHeartbeats 0
set_option maxRecDepth 4000

/-!
# LMFDB level-1 weight-28 form `1.28.a`, piece 0: integer q-coefficient certificate

Heavy `decide +kernel` over `ℤ` (denominators cleared by the scale `D = 41472`), isolated in its own
module so `lake` schedules it in parallel with the other pieces. Generated by
`scripts/lmfdb_qexp_to_e4e6_v3.sage`.
-/

namespace LeanBridge.QExpansion.LMFDB.W28

open LeanBridge.QExpansion

def f_28_part_0_polyDataZ : List (ℕ × ℕ × ℤ) :=
  [(1, 4, (-13)), (4, 2, 2), (7, 0, 11)]

def f_28_part_0_scale : ℤ := 41472

def f_28_part_0_qExpListZ : List ℤ :=
  [0, 41472, 0, 6292961280, 2531137683456, 138151607270400, 1554703737421824, (-2350689111429120), (-67046598676316160), (-16790767367763456)]

/-- Integer-arithmetic certificate (the heavy kernel computation). -/
lemma f_28_part_0_evalEisListZ_eq :
    evalEisListZ f_28_part_0_polyDataZ 10 = f_28_part_0_qExpListZ := by
  decide +kernel

end LeanBridge.QExpansion.LMFDB.W28
