import LeanBridge.ForMathlib.QExpansion.IntEval

set_option maxHeartbeats 0
set_option maxRecDepth 4000

/-!
# LMFDB level-1 weight-66 form `1.66.a`, piece 1: integer q-coefficient certificate

Heavy `decide +kernel` over `ℤ` (denominators cleared by the scale `D = 206328977372801902873411584`), isolated in its own
module so `lake` schedules it in parallel with the other pieces. Generated by
`scripts/lmfdb_qexp_to_e4e6_v3.sage`.
-/

namespace LeanBridge.QExpansion.LMFDB.W66

open LeanBridge.QExpansion

def f_66_part_1_polyDataZ : List (ℕ × ℕ × ℤ) :=
  [(0, 11, (-1151015911511173776001295)), (3, 9, 5865406711190529377860633), (6, 7, (-11730771335076198830939186)), (9, 5, 11510101952354210669774486), (12, 3, (-5534437186686073478167471)), (15, 1, 1040715769728706037472833)]

def f_66_part_1_scale : ℤ := 206328977372801902873411584

def f_66_part_1_qExpListZ : List ℤ :=
  [0, 0, 206328977372801902873411584, (-1138413143485482654579799039672320), 0, 17772457365114654542193618934238281728000, (-11072281697324426029365732389253367726080000), 942218094736908656817337749001461441931247616, (-15224391362345142690222903324292983459441278976), 3419607248581072312864167408895081512535326720000]

/-- Integer-arithmetic certificate (the heavy kernel computation). -/
lemma f_66_part_1_evalEisListZ_eq :
    evalEisListZ f_66_part_1_polyDataZ 10 = f_66_part_1_qExpListZ := by
  decide +kernel

end LeanBridge.QExpansion.LMFDB.W66
