import LeanBridge.ForMathlib.QExpansion.IntEval

set_option maxHeartbeats 0
set_option maxRecDepth 4000

/-!
# LMFDB level-1 weight-62 form `1.62.a`, piece 2: integer q-coefficient certificate

Heavy `decide +kernel` over `ℤ` (denominators cleared by the scale `D = 7647938801734508347392`), isolated in its own
module so `lake` schedules it in parallel with the other pieces. Generated by
`scripts/lmfdb_qexp_to_e4e6_v3.sage`.
-/

namespace LeanBridge.QExpansion.LMFDB.W62

open LeanBridge.QExpansion

def f_62_part_2_polyDataZ : List (ℕ × ℕ × ℤ) :=
  [(2, 9, 777136357), (5, 7, (-3331830928)), (8, 5, 5332674642), (11, 3, (-3778401928)), (14, 1, 1000421857)]

def f_62_part_2_scale : ℤ := 7647938801734508347392

def f_62_part_2_qExpListZ : List ℤ :=
  [0, 0, 0, 1152104135786496000, 7647938801734508347392, (-926255184730245342167040), (-1503387579276994370693234688), (-196498191508664651188273152000), 0, (-557720689363935010923236164632576)]

/-- Integer-arithmetic certificate (the heavy kernel computation). -/
lemma f_62_part_2_evalEisListZ_eq :
    evalEisListZ f_62_part_2_polyDataZ 10 = f_62_part_2_qExpListZ := by
  decide +kernel

end LeanBridge.QExpansion.LMFDB.W62
