import LeanBridge.ForMathlib.QExpansion.IntEval

set_option maxHeartbeats 0
set_option maxRecDepth 4000

/-!
# LMFDB level-1 weight-48 form `1.48.a`, piece 3: integer q-coefficient certificate

Heavy `decide +kernel` over `ℤ` (denominators cleared by the scale `D = 293733154428203040768`), isolated in its own
module so `lake` schedules it in parallel with the other pieces. Generated by
`scripts/lmfdb_qexp_to_e4e6_v3.sage`.
-/

namespace LeanBridge.QExpansion.LMFDB.W48

open LeanBridge.QExpansion

def f_48_part_3_polyDataZ : List (ℕ × ℕ × ℤ) :=
  [(0, 8, (-3)), (3, 6, 4), (6, 4, 6), (9, 2, (-12)), (12, 0, 5)]

def f_48_part_3_scale : ℤ := 293733154428203040768

def f_48_part_3_qExpListZ : List ℤ :=
  [0, 0, 0, 41278242816, 0, 7930871348723712, 119198356214906880, (-13628172603179925504), 293733154428203040768, (-2502115178740407336960)]

/-- Integer-arithmetic certificate (the heavy kernel computation). -/
lemma f_48_part_3_evalEisListZ_eq :
    evalEisListZ f_48_part_3_polyDataZ 10 = f_48_part_3_qExpListZ := by
  decide +kernel

end LeanBridge.QExpansion.LMFDB.W48
