import LeanBridge.ForMathlib.QExpansion.IntEval

set_option maxHeartbeats 0
set_option maxRecDepth 4000

/-!
# LMFDB level-1 weight-76 form `1.76.a`, piece 4: integer q-coefficient certificate

Heavy `decide +kernel` over `ℤ` (denominators cleared by the scale `D = 1535009397005662263031626974693746913699020007312464722756894720`), isolated in its own
module so `lake` schedules it in parallel with the other pieces. Generated by
`scripts/lmfdb_qexp_to_e4e6_v3.sage`.
-/

namespace LeanBridge.QExpansion.LMFDB.W76

open LeanBridge.QExpansion

def f_76_part_4_polyDataZ : List (ℕ × ℕ × ℤ) :=
  [(1, 12, 4564645861801509958138021415), (4, 10, (-34182620268337082050042397898)), (7, 8, 102816776492810129803334019465), (10, 6, (-160456685043213191044601915980)), (13, 4, 137825910929126965442155288905), (16, 2, (-62023646528978526462457046730)), (19, 0, 11455618556790194353474030823)]

def f_76_part_4_scale : ℤ := 1535009397005662263031626974693746913699020007312464722756894720

def f_76_part_4_qExpListZ : List ℤ :=
  [0, 0, 0, (-1429958208089345374542322794391142400), 0, 106466035551092108348199713445154094887993344, 210839678373617190071608513745353475544443781120, 37847829663707929011983713495574630973419657625600, 0, 157804048137639208639274092774469217649876647920271360]

/-- Integer-arithmetic certificate (the heavy kernel computation). -/
lemma f_76_part_4_evalEisListZ_eq :
    evalEisListZ f_76_part_4_polyDataZ 10 = f_76_part_4_qExpListZ := by
  decide +kernel

end LeanBridge.QExpansion.LMFDB.W76
