import LeanBridge.ForMathlib.QExpansion.IntEval

set_option maxHeartbeats 0
set_option maxRecDepth 4000

/-!
# LMFDB level-1 weight-74 form `1.74.a`, piece 2: integer q-coefficient certificate

Heavy `decide +kernel` over `ℤ` (denominators cleared by the scale `D = 901932900326786904812728577112932352`), isolated in its own
module so `lake` schedules it in parallel with the other pieces. Generated by
`scripts/lmfdb_qexp_to_e4e6_v3.sage`.
-/

namespace LeanBridge.QExpansion.LMFDB.W74

open LeanBridge.QExpansion

def f_74_part_2_polyDataZ : List (ℕ × ℕ × ℤ) :=
  [(2, 11, 165592367373808864318177), (5, 9, (-646598238886215518515925)), (8, 7, 1033591051717904354877946), (11, 5, (-877107395574508596720058)), (14, 3, 411872754671121881279093), (17, 1, (-87350539302110985239233))]

def f_74_part_2_scale : ℤ := 901932900326786904812728577112932352

def f_74_part_2_qExpListZ : List ℤ :=
  [0, 0, 0, (-532085682250918127734248683077632), 901932900326786904812728577112932352, (-1871729950565569012463522166766867316736), 260264507106866670847055580937666361819136, 308638261384896527629353151448551547662761984, 0, (-4293314508725449649816231575348976590087853703168)]

/-- Integer-arithmetic certificate (the heavy kernel computation). -/
lemma f_74_part_2_evalEisListZ_eq :
    evalEisListZ f_74_part_2_polyDataZ 10 = f_74_part_2_qExpListZ := by
  decide +kernel

end LeanBridge.QExpansion.LMFDB.W74
