import LeanBridge.ForMathlib.QExpansion.IntEval

set_option maxHeartbeats 0
set_option maxRecDepth 4000

/-!
# LMFDB level-1 weight-74 form `1.74.a`, piece 4: integer q-coefficient certificate

Heavy `decide +kernel` over `ℤ` (denominators cleared by the scale `D = 66497708875293344918032852533382276448256`), isolated in its own
module so `lake` schedules it in parallel with the other pieces. Generated by
`scripts/lmfdb_qexp_to_e4e6_v3.sage`.
-/

namespace LeanBridge.QExpansion.LMFDB.W74

open LeanBridge.QExpansion

def f_74_part_4_polyDataZ : List (ℕ × ℕ × ℤ) :=
  [(2, 11, 86453), (5, 9, (-735673)), (8, 7, 1688066), (11, 5, (-1514690)), (14, 3, 475609), (17, 1, 235)]

def f_74_part_4_scale : ℤ := 66497708875293344918032852533382276448256

def f_74_part_4_qExpListZ : List ℤ :=
  [0, 0, 0, 2012809676193792, 0, (-1855515032965720571904), 266129468940744294137856, 334432822206896998025527296, 0, (-21765008629028472429093907857408)]

/-- Integer-arithmetic certificate (the heavy kernel computation). -/
lemma f_74_part_4_evalEisListZ_eq :
    evalEisListZ f_74_part_4_polyDataZ 10 = f_74_part_4_qExpListZ := by
  decide +kernel

end LeanBridge.QExpansion.LMFDB.W74
