import LeanBridge.ForMathlib.QExpansion.IntEval
import LeanBridge.ForMathlib.QExpansion.Sturm
import Mathlib.Analysis.Complex.Polynomial.Basic
import LeanBridge.ForMathlib.QExpansion.LMFDB.Weight_64_part_0
import LeanBridge.ForMathlib.QExpansion.LMFDB.Weight_64_part_1
import LeanBridge.ForMathlib.QExpansion.LMFDB.Weight_64_part_2
import LeanBridge.ForMathlib.QExpansion.LMFDB.Weight_64_part_3
import LeanBridge.ForMathlib.QExpansion.LMFDB.Weight_64_part_4

set_option maxHeartbeats 0
set_option maxRecDepth 2000

/-!
# LMFDB level-1 modular form orbit `1.64.a.{a..}` (Hecke field degree 5)

The Hecke field `K = ℚ(α)` is degree 5 over ℚ. The LMFDB lists q-coefficients as
elements of `K`, which we decompose as `c_0 + c_1 · α + … + c_{4} · α^4`.
The combined form is `f = f_0 + α · f_1 + … + α^4 · f_{4}`, with each
`f_j` a level-1 weight-64 form with rational coefficients in `(E₄, E₆)`.

The Sturm bound for weight 64 is `⌊64/12⌋ + 1 = 6`. After certifying agreement
on the first 6 q-coefficients, `ModularForm.eq_of_sturm_bound` lets us conclude that any
form with the same coefficients equals our explicit `lmfdb_1_64_a_orbit`.

Generated by `scripts/lmfdb_qexp_to_e4e6_v3.sage`.
-/

namespace LeanBridge.QExpansion.LMFDB.W64

open LeanBridge.QExpansion ModularForm EisensteinSeries PowerSeries UpperHalfPlane
open scoped MatrixGroups


/-- Minimal polynomial of α (degree 5) as `Polynomial ℂ`. -/
noncomputable def α_64_minpoly : Polynomial ℂ :=
  Polynomial.X ^ 5 +
    Polynomial.C 59899702063757157544982491709928053576589901824 +
    Polynomial.C 93356730870958242939964792647614201856 * Polynomial.X +
    Polynomial.C 7816999697067374824780726272 * Polynomial.X ^ 2 +
    Polynomial.C (-26316207229657439232) * Polynomial.X ^ 3 +
    Polynomial.C (-507315096) * Polynomial.X ^ 4

lemma α_64_minpoly_natDegree : α_64_minpoly.natDegree = 5 := by
  unfold α_64_minpoly
  compute_degree!

lemma α_64_minpoly_degree_ne_zero : α_64_minpoly.degree ≠ 0 := by
  rw [Polynomial.degree_eq_natDegree (fun h => by
    have := α_64_minpoly_natDegree
    rw [h, Polynomial.natDegree_zero] at this
    exact absurd this (by decide))]
  rw [α_64_minpoly_natDegree]
  decide

/-- α is some root of the degree-5 minimal polynomial in ℂ. -/
noncomputable def α_64 : ℂ :=
  (IsAlgClosed.exists_root α_64_minpoly α_64_minpoly_degree_ne_zero).choose

lemma α_64_isRoot : Polynomial.IsRoot α_64_minpoly α_64 :=
  (IsAlgClosed.exists_root α_64_minpoly α_64_minpoly_degree_ne_zero).choose_spec

/-- Explicit polynomial relation: minpoly evaluated at α is zero. -/
lemma α_64_is_root :
    α_64 ^ 5 +
      59899702063757157544982491709928053576589901824 +
      93356730870958242939964792647614201856 * α_64 +
      7816999697067374824780726272 * α_64 ^ 2 +
      (-26316207229657439232) * α_64 ^ 3 +
      (-507315096) * α_64 ^ 4 = 0 := by
  have h := α_64_isRoot
  unfold Polynomial.IsRoot α_64_minpoly at h
  simp only [Polynomial.eval_add, Polynomial.eval_mul, Polynomial.eval_pow,
    Polynomial.eval_C, Polynomial.eval_X] at h
  linear_combination h


/-! ## Piece 0: coefficient of α^0 -/


def f_64_part_0_polyData : List (ℕ × ℕ × ℚ) :=
  [(1, 10, ((-(76955901528692931639325218707 / 12472841601860881489920)))), (4, 8, (78296266683921673689100675925 / 2494568320372176297984)), (7, 6, ((-(77529878166414038365000574717 / 1247284160186088148992)))), (10, 4, (74656735974876786399856662035 / 1247284160186088148992)), (13, 2, ((-(74840859408657673955576789 / 2679450397821886464)))), (16, 0, (8941455795965507872638702671 / 1781834514551554498560))]

noncomputable def f_64_part_0 : ModularForm 𝒮ℒ 64 :=
  (((-(76955901528692931639325218707 / 12472841601860881489920))) : ℂ) • mkMonomForm 1 10 64 (by decide) +
  ((78296266683921673689100675925 / 2494568320372176297984) : ℂ) • mkMonomForm 4 8 64 (by decide) +
  (((-(77529878166414038365000574717 / 1247284160186088148992))) : ℂ) • mkMonomForm 7 6 64 (by decide) +
  ((74656735974876786399856662035 / 1247284160186088148992) : ℂ) • mkMonomForm 10 4 64 (by decide) +
  (((-(74840859408657673955576789 / 2679450397821886464))) : ℂ) • mkMonomForm 13 2 64 (by decide) +
  ((8941455795965507872638702671 / 1781834514551554498560) : ℂ) • mkMonomForm 16 0 64 (by decide)

lemma f_64_part_0_qExpansion_eq_evalEisPS :
    qExpansion 1 (f_64_part_0 : ℍ → ℂ) = evalEisPS f_64_part_0_polyData := by
  unfold f_64_part_0
  rw [ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm]
  unfold evalEisPS f_64_part_0_polyData monomialEisPS
  simp only [List.foldr_cons, List.foldr_nil, add_zero]
  push_cast
  module

theorem f_64_part_0_qExpansion_coeff (N n : ℕ) (hn : n < N) :
    (PowerSeries.coeff (R := ℂ) n) (qExpansion 1 (f_64_part_0 : ℍ → ℂ))
      = ((evalEisList f_64_part_0_polyData N).getD n 0 : ℚ) :=
  qexp_coeff_via_E4E6 _ _ f_64_part_0_qExpansion_eq_evalEisPS N n hn

/-- Precomputed first 10 q-coefficients of `f_64_part_0` (rational). -/
def f_64_part_0_qExpList : List ℚ :=
  [0, 1, 0, ((-(404496705296989095162023821572 / 46412549065757))), (-9223372036854775808), (20782946576056375227107038231991365038 / 232062745328785), (418165013796315143153844089456676569088 / 46412549065757), ((-(16900827355460864007534964684577061008792 / 6630364152251))), 0, ((-(631680390812853082804326926555887008486309 / 49852362047)))]

/-- Bridge: the symbolic `evalEisList` (over ℚ) equals the precomputed list. The heavy kernel work
is the integer certificate `f_64_part_0_evalEisListZ_eq`; the steps here are cheap rational
list checks. -/
lemma f_64_part_0_evalEisList_eq :
    evalEisList f_64_part_0_polyData 10 = f_64_part_0_qExpList := by
  have h : f_64_part_0_polyData
      = f_64_part_0_polyDataZ.map
          (fun t => (t.1, t.2.1, (t.2.2 : ℚ) / f_64_part_0_scale)) := by
    decide +kernel
  rw [h, evalEisList_eq_intCast_div, f_64_part_0_evalEisListZ_eq]
  decide +kernel


/-! ## Piece 1: coefficient of α^1 -/


def f_64_part_1_polyData : List (ℕ × ℕ × ℚ) :=
  [(1, 10, ((-(6311387116289093663445997 / 2207034397492797769173172224)))), (4, 8, (67638453406570612739772643 / 4414068794985595538346344448)), (7, 6, ((-(8716406494430700902163839 / 275879299686599721146646528)))), (10, 4, (69393005940870104415606913 / 2207034397492797769173172224)), (13, 2, ((-(35781124862619918734261 / 2370606227167344542613504)))), (16, 0, (1755038192765266981960133 / 630581256426513648335192064))]

noncomputable def f_64_part_1 : ModularForm 𝒮ℒ 64 :=
  (((-(6311387116289093663445997 / 2207034397492797769173172224))) : ℂ) • mkMonomForm 1 10 64 (by decide) +
  ((67638453406570612739772643 / 4414068794985595538346344448) : ℂ) • mkMonomForm 4 8 64 (by decide) +
  (((-(8716406494430700902163839 / 275879299686599721146646528))) : ℂ) • mkMonomForm 7 6 64 (by decide) +
  ((69393005940870104415606913 / 2207034397492797769173172224) : ℂ) • mkMonomForm 10 4 64 (by decide) +
  (((-(35781124862619918734261 / 2370606227167344542613504))) : ℂ) • mkMonomForm 13 2 64 (by decide) +
  ((1755038192765266981960133 / 630581256426513648335192064) : ℂ) • mkMonomForm 16 0 64 (by decide)

lemma f_64_part_1_qExpansion_eq_evalEisPS :
    qExpansion 1 (f_64_part_1 : ℍ → ℂ) = evalEisPS f_64_part_1_polyData := by
  unfold f_64_part_1
  rw [ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm]
  unfold evalEisPS f_64_part_1_polyData monomialEisPS
  simp only [List.foldr_cons, List.foldr_nil, add_zero]
  push_cast
  module

theorem f_64_part_1_qExpansion_coeff (N n : ℕ) (hn : n < N) :
    (PowerSeries.coeff (R := ℂ) n) (qExpansion 1 (f_64_part_1 : ℍ → ℂ))
      = ((evalEisList f_64_part_1_polyData N).getD n 0 : ℚ) :=
  qexp_coeff_via_E4E6 _ _ f_64_part_1_qExpansion_eq_evalEisPS N n hn

/-- Precomputed first 10 q-coefficients of `f_64_part_1` (rational). -/
def f_64_part_1_qExpList : List ℚ :=
  [0, 0, 1, ((-(67521601525164741914955 / 11881612560833792))), 0, (135651488643513059526938376325 / 2970403140208448), (247234727541868598133433957500 / 46412549065757), ((-(950375289221305198722301204677753 / 848686611488128))), (-18446744073709551616), ((-(12913430252219027127208020605011875 / 1595275585504)))]

/-- Bridge: the symbolic `evalEisList` (over ℚ) equals the precomputed list. The heavy kernel work
is the integer certificate `f_64_part_1_evalEisListZ_eq`; the steps here are cheap rational
list checks. -/
lemma f_64_part_1_evalEisList_eq :
    evalEisList f_64_part_1_polyData 10 = f_64_part_1_qExpList := by
  have h : f_64_part_1_polyData
      = f_64_part_1_polyDataZ.map
          (fun t => (t.1, t.2.1, (t.2.2 : ℚ) / f_64_part_1_scale)) := by
    decide +kernel
  rw [h, evalEisList_eq_intCast_div, f_64_part_1_evalEisListZ_eq]
  decide +kernel


/-! ## Piece 2: coefficient of α^2 -/


def f_64_part_2_polyData : List (ℕ × ℕ × ℚ) :=
  [(1, 10, (2089210978391491166777 / 813601160291744969627998208655360)), (4, 8, ((-(4360315240521445737559 / 325440464116697987851199283462144)))), (7, 6, (34569239927064074069 / 1271251812955851515043747201024)), (10, 4, ((-(4372064367211249563373 / 162720232058348993925599641731072)))), (13, 2, (2256670359915461861 / 174780055916593978437808422912)), (16, 0, ((-(559204319931174678037 / 232457474369069991322285202472960))))]

noncomputable def f_64_part_2 : ModularForm 𝒮ℒ 64 :=
  ((2089210978391491166777 / 813601160291744969627998208655360) : ℂ) • mkMonomForm 1 10 64 (by decide) +
  (((-(4360315240521445737559 / 325440464116697987851199283462144))) : ℂ) • mkMonomForm 4 8 64 (by decide) +
  ((34569239927064074069 / 1271251812955851515043747201024) : ℂ) • mkMonomForm 7 6 64 (by decide) +
  (((-(4372064367211249563373 / 162720232058348993925599641731072))) : ℂ) • mkMonomForm 10 4 64 (by decide) +
  ((2256670359915461861 / 174780055916593978437808422912) : ℂ) • mkMonomForm 13 2 64 (by decide) +
  (((-(559204319931174678037 / 232457474369069991322285202472960))) : ℂ) • mkMonomForm 16 0 64 (by decide)

lemma f_64_part_2_qExpansion_eq_evalEisPS :
    qExpansion 1 (f_64_part_2 : ℍ → ℂ) = evalEisPS f_64_part_2_polyData := by
  unfold f_64_part_2
  rw [ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm]
  unfold evalEisPS f_64_part_2_polyData monomialEisPS
  simp only [List.foldr_cons, List.foldr_nil, add_zero]
  push_cast
  module

theorem f_64_part_2_qExpansion_coeff (N n : ℕ) (hn : n < N) :
    (PowerSeries.coeff (R := ℂ) n) (qExpansion 1 (f_64_part_2 : ℍ → ℂ))
      = ((evalEisList f_64_part_2_polyData N).getD n 0 : ℚ) :=
  qexp_coeff_via_E4E6 _ _ f_64_part_2_qExpansion_eq_evalEisPS N n hn

/-- Precomputed first 10 q-coefficients of `f_64_part_2` (rational). -/
def f_64_part_2_qExpList : List ℚ :=
  [0, 0, 0, (1086535311071367229 / 292002510295051272192), 1, ((-(4836572597772089598089493 / 121667712622938030080))), ((-(13387846610452679727099 / 2970403140208448))), (6779578511691331518751116149 / 6952440721310744576), 0, (73919027646542806069645732023 / 13068497596448768)]

/-- Bridge: the symbolic `evalEisList` (over ℚ) equals the precomputed list. The heavy kernel work
is the integer certificate `f_64_part_2_evalEisListZ_eq`; the steps here are cheap rational
list checks. -/
lemma f_64_part_2_evalEisList_eq :
    evalEisList f_64_part_2_polyData 10 = f_64_part_2_qExpList := by
  have h : f_64_part_2_polyData
      = f_64_part_2_polyDataZ.map
          (fun t => (t.1, t.2.1, (t.2.2 : ℚ) / f_64_part_2_scale)) := by
    decide +kernel
  rw [h, evalEisList_eq_intCast_div, f_64_part_2_evalEisListZ_eq]
  decide +kernel


/-! ## Piece 3: coefficient of α^3 -/


def f_64_part_3_polyData : List (ℕ × ℕ × ℚ) :=
  [(1, 10, (23873894105857 / 187453707331218041002290787274194944)), (4, 8, ((-(256831282240843 / 374907414662436082004581574548389888)))), (7, 6, (2071893480269 / 1464482088525140945330396775579648)), (10, 4, ((-(263852190759337 / 187453707331218041002290787274194944)))), (13, 2, (135757657409 / 201346624415916263160355303194624)), (16, 0, ((-(6628230499517 / 53558202094633726000654510649769984))))]

noncomputable def f_64_part_3 : ModularForm 𝒮ℒ 64 :=
  ((23873894105857 / 187453707331218041002290787274194944) : ℂ) • mkMonomForm 1 10 64 (by decide) +
  (((-(256831282240843 / 374907414662436082004581574548389888))) : ℂ) • mkMonomForm 4 8 64 (by decide) +
  ((2071893480269 / 1464482088525140945330396775579648) : ℂ) • mkMonomForm 7 6 64 (by decide) +
  (((-(263852190759337 / 187453707331218041002290787274194944))) : ℂ) • mkMonomForm 10 4 64 (by decide) +
  ((135757657409 / 201346624415916263160355303194624) : ℂ) • mkMonomForm 13 2 64 (by decide) +
  (((-(6628230499517 / 53558202094633726000654510649769984))) : ℂ) • mkMonomForm 16 0 64 (by decide)

lemma f_64_part_3_qExpansion_eq_evalEisPS :
    qExpansion 1 (f_64_part_3 : ℍ → ℂ) = evalEisPS f_64_part_3_polyData := by
  unfold f_64_part_3
  rw [ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm]
  unfold evalEisPS f_64_part_3_polyData monomialEisPS
  simp only [List.foldr_cons, List.foldr_nil, add_zero]
  push_cast
  module

theorem f_64_part_3_qExpansion_coeff (N n : ℕ) (hn : n < N) :
    (PowerSeries.coeff (R := ℂ) n) (qExpansion 1 (f_64_part_3 : ℍ → ℂ))
      = ((evalEisList f_64_part_3_polyData N).getD n 0 : ℚ) :=
  qexp_coeff_via_E4E6 _ _ f_64_part_3_qExpansion_eq_evalEisPS N n hn

/-- Precomputed first 10 q-coefficients of `f_64_part_3` (rational). -/
def f_64_part_3_qExpList : List ℚ :=
  [0, 0, 0, (90011647673 / 336386891859899065565184), 0, ((-(6347637419650325 / 3114693443147213570048))), ((-(270719085323125 / 1140634805840044032))), (44961980774422715721 / 889912412327775305728), 1, (629911023701409961875 / 1672767692345442304)]

/-- Bridge: the symbolic `evalEisList` (over ℚ) equals the precomputed list. The heavy kernel work
is the integer certificate `f_64_part_3_evalEisListZ_eq`; the steps here are cheap rational
list checks. -/
lemma f_64_part_3_evalEisList_eq :
    evalEisList f_64_part_3_polyData 10 = f_64_part_3_qExpList := by
  have h : f_64_part_3_polyData
      = f_64_part_3_polyDataZ.map
          (fun t => (t.1, t.2.1, (t.2.2 : ℚ) / f_64_part_3_scale)) := by
    decide +kernel
  rw [h, evalEisList_eq_intCast_div, f_64_part_3_evalEisListZ_eq]
  decide +kernel


/-! ## Piece 4: coefficient of α^4 -/


def f_64_part_4_polyData : List (ℕ × ℕ × ℚ) :=
  [(1, 10, ((-(6943199 / 67483334639238494760824683418710179840)))), (4, 8, (14618641 / 26993333855695397904329873367484071936)), (7, 6, ((-(116855 / 105442710373810148063788567841734656)))), (10, 4, (14902795 / 13496666927847698952164936683742035968)), (13, 2, ((-(7763 / 14496956957945970947545581830012928)))), (16, 0, (1944739 / 19280952754068141360235623833917194240))]

noncomputable def f_64_part_4 : ModularForm 𝒮ℒ 64 :=
  (((-(6943199 / 67483334639238494760824683418710179840))) : ℂ) • mkMonomForm 1 10 64 (by decide) +
  ((14618641 / 26993333855695397904329873367484071936) : ℂ) • mkMonomForm 4 8 64 (by decide) +
  (((-(116855 / 105442710373810148063788567841734656))) : ℂ) • mkMonomForm 7 6 64 (by decide) +
  ((14902795 / 13496666927847698952164936683742035968) : ℂ) • mkMonomForm 10 4 64 (by decide) +
  (((-(7763 / 14496956957945970947545581830012928))) : ℂ) • mkMonomForm 13 2 64 (by decide) +
  ((1944739 / 19280952754068141360235623833917194240) : ℂ) • mkMonomForm 16 0 64 (by decide)

lemma f_64_part_4_qExpansion_eq_evalEisPS :
    qExpansion 1 (f_64_part_4 : ℍ → ℂ) = evalEisPS f_64_part_4_polyData := by
  unfold f_64_part_4
  rw [ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm]
  unfold evalEisPS f_64_part_4_polyData monomialEisPS
  simp only [List.foldr_cons, List.foldr_nil, add_zero]
  push_cast
  module

theorem f_64_part_4_qExpansion_coeff (N n : ℕ) (hn : n < N) :
    (PowerSeries.coeff (R := ℂ) n) (qExpansion 1 (f_64_part_4 : ℍ → ℂ))
      = ((evalEisList f_64_part_4_polyData N).getD n 0 : ℚ) :=
  qexp_coeff_via_E4E6 _ _ f_64_part_4_qExpansion_eq_evalEisPS N n hn

/-- Precomputed first 10 q-coefficients of `f_64_part_4` (rational). -/
def f_64_part_4_qExpList : List ℚ :=
  [0, 0, 0, ((-(3643 / 24219856213912732720693248))), 0, (202800051 / 124587737725888542801920), (15708719 / 82125706020483170304), ((-(269544437843 / 7119299298622202445824))), 0, ((-(3105118262369 / 13382141538763538432)))]

/-- Bridge: the symbolic `evalEisList` (over ℚ) equals the precomputed list. The heavy kernel work
is the integer certificate `f_64_part_4_evalEisListZ_eq`; the steps here are cheap rational
list checks. -/
lemma f_64_part_4_evalEisList_eq :
    evalEisList f_64_part_4_polyData 10 = f_64_part_4_qExpList := by
  have h : f_64_part_4_polyData
      = f_64_part_4_polyDataZ.map
          (fun t => (t.1, t.2.1, (t.2.2 : ℚ) / f_64_part_4_scale)) := by
    decide +kernel
  rw [h, evalEisList_eq_intCast_div, f_64_part_4_evalEisListZ_eq]
  decide +kernel


/-! ## Combined LMFDB form -/


noncomputable def lmfdb_1_64_a_orbit : ModularForm 𝒮ℒ 64 :=
  f_64_part_0 +
  α_64 • f_64_part_1 +
  α_64 ^ 2 • f_64_part_2 +
  α_64 ^ 3 • f_64_part_3 +
  α_64 ^ 4 • f_64_part_4

lemma lmfdb_1_64_a_orbit_coeff_decomp (n : ℕ) :
    (PowerSeries.coeff (R := ℂ) n) (qExpansion 1 (lmfdb_1_64_a_orbit : ℍ → ℂ))
      = (PowerSeries.coeff (R := ℂ) n) (qExpansion 1 (f_64_part_0 : ℍ → ℂ))
        + α_64 * (PowerSeries.coeff (R := ℂ) n) (qExpansion 1 (f_64_part_1 : ℍ → ℂ))
        + α_64 ^ 2 * (PowerSeries.coeff (R := ℂ) n) (qExpansion 1 (f_64_part_2 : ℍ → ℂ))
        + α_64 ^ 3 * (PowerSeries.coeff (R := ℂ) n) (qExpansion 1 (f_64_part_3 : ℍ → ℂ))
        + α_64 ^ 4 * (PowerSeries.coeff (R := ℂ) n) (qExpansion 1 (f_64_part_4 : ℍ → ℂ)) := by
  unfold lmfdb_1_64_a_orbit
  rw [ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL]
  simp [smul_eq_mul]


/-! ## Coefficient lemmas (n = 0, …, 9)

Sturm bound is 6; we certify 10 coefficients for added
redundancy beyond the minimum mathematically required for uniqueness. -/


lemma lmfdb_1_64_a_orbit_qExpansion_coeff_0 :
    (PowerSeries.coeff (R := ℂ) 0)
      (qExpansion 1 (lmfdb_1_64_a_orbit : ℍ → ℂ)) = 0 := by
  rw [lmfdb_1_64_a_orbit_coeff_decomp,
    f_64_part_0_qExpansion_coeff 10 0 (by decide),
    f_64_part_1_qExpansion_coeff 10 0 (by decide),
    f_64_part_2_qExpansion_coeff 10 0 (by decide),
    f_64_part_3_qExpansion_coeff 10 0 (by decide),
    f_64_part_4_qExpansion_coeff 10 0 (by decide),
    f_64_part_0_evalEisList_eq,
    f_64_part_1_evalEisList_eq,
    f_64_part_2_evalEisList_eq,
    f_64_part_3_evalEisList_eq,
    f_64_part_4_evalEisList_eq,
    show f_64_part_0_qExpList.getD 0 0 = (0 : ℚ) from by decide +kernel,
    show f_64_part_1_qExpList.getD 0 0 = (0 : ℚ) from by decide +kernel,
    show f_64_part_2_qExpList.getD 0 0 = (0 : ℚ) from by decide +kernel,
    show f_64_part_3_qExpList.getD 0 0 = (0 : ℚ) from by decide +kernel,
    show f_64_part_4_qExpList.getD 0 0 = (0 : ℚ) from by decide +kernel]
  push_cast; ring

lemma lmfdb_1_64_a_orbit_qExpansion_coeff_1 :
    (PowerSeries.coeff (R := ℂ) 1)
      (qExpansion 1 (lmfdb_1_64_a_orbit : ℍ → ℂ)) = 1 := by
  rw [lmfdb_1_64_a_orbit_coeff_decomp,
    f_64_part_0_qExpansion_coeff 10 1 (by decide),
    f_64_part_1_qExpansion_coeff 10 1 (by decide),
    f_64_part_2_qExpansion_coeff 10 1 (by decide),
    f_64_part_3_qExpansion_coeff 10 1 (by decide),
    f_64_part_4_qExpansion_coeff 10 1 (by decide),
    f_64_part_0_evalEisList_eq,
    f_64_part_1_evalEisList_eq,
    f_64_part_2_evalEisList_eq,
    f_64_part_3_evalEisList_eq,
    f_64_part_4_evalEisList_eq,
    show f_64_part_0_qExpList.getD 1 0 = (1 : ℚ) from by decide +kernel,
    show f_64_part_1_qExpList.getD 1 0 = (0 : ℚ) from by decide +kernel,
    show f_64_part_2_qExpList.getD 1 0 = (0 : ℚ) from by decide +kernel,
    show f_64_part_3_qExpList.getD 1 0 = (0 : ℚ) from by decide +kernel,
    show f_64_part_4_qExpList.getD 1 0 = (0 : ℚ) from by decide +kernel]
  push_cast; ring

lemma lmfdb_1_64_a_orbit_qExpansion_coeff_2 :
    (PowerSeries.coeff (R := ℂ) 2)
      (qExpansion 1 (lmfdb_1_64_a_orbit : ℍ → ℂ)) = 1 * α_64 := by
  rw [lmfdb_1_64_a_orbit_coeff_decomp,
    f_64_part_0_qExpansion_coeff 10 2 (by decide),
    f_64_part_1_qExpansion_coeff 10 2 (by decide),
    f_64_part_2_qExpansion_coeff 10 2 (by decide),
    f_64_part_3_qExpansion_coeff 10 2 (by decide),
    f_64_part_4_qExpansion_coeff 10 2 (by decide),
    f_64_part_0_evalEisList_eq,
    f_64_part_1_evalEisList_eq,
    f_64_part_2_evalEisList_eq,
    f_64_part_3_evalEisList_eq,
    f_64_part_4_evalEisList_eq,
    show f_64_part_0_qExpList.getD 2 0 = (0 : ℚ) from by decide +kernel,
    show f_64_part_1_qExpList.getD 2 0 = (1 : ℚ) from by decide +kernel,
    show f_64_part_2_qExpList.getD 2 0 = (0 : ℚ) from by decide +kernel,
    show f_64_part_3_qExpList.getD 2 0 = (0 : ℚ) from by decide +kernel,
    show f_64_part_4_qExpList.getD 2 0 = (0 : ℚ) from by decide +kernel]
  push_cast; ring

lemma lmfdb_1_64_a_orbit_qExpansion_coeff_3 :
    (PowerSeries.coeff (R := ℂ) 3)
      (qExpansion 1 (lmfdb_1_64_a_orbit : ℍ → ℂ)) = ((-(404496705296989095162023821572 / 46412549065757))) + ((-(67521601525164741914955 / 11881612560833792))) * α_64 + (1086535311071367229 / 292002510295051272192) * α_64 ^ 2 + (90011647673 / 336386891859899065565184) * α_64 ^ 3 + ((-(3643 / 24219856213912732720693248))) * α_64 ^ 4 := by
  rw [lmfdb_1_64_a_orbit_coeff_decomp,
    f_64_part_0_qExpansion_coeff 10 3 (by decide),
    f_64_part_1_qExpansion_coeff 10 3 (by decide),
    f_64_part_2_qExpansion_coeff 10 3 (by decide),
    f_64_part_3_qExpansion_coeff 10 3 (by decide),
    f_64_part_4_qExpansion_coeff 10 3 (by decide),
    f_64_part_0_evalEisList_eq,
    f_64_part_1_evalEisList_eq,
    f_64_part_2_evalEisList_eq,
    f_64_part_3_evalEisList_eq,
    f_64_part_4_evalEisList_eq,
    show f_64_part_0_qExpList.getD 3 0 = (((-(404496705296989095162023821572 / 46412549065757))) : ℚ) from by decide +kernel,
    show f_64_part_1_qExpList.getD 3 0 = (((-(67521601525164741914955 / 11881612560833792))) : ℚ) from by decide +kernel,
    show f_64_part_2_qExpList.getD 3 0 = ((1086535311071367229 / 292002510295051272192) : ℚ) from by decide +kernel,
    show f_64_part_3_qExpList.getD 3 0 = ((90011647673 / 336386891859899065565184) : ℚ) from by decide +kernel,
    show f_64_part_4_qExpList.getD 3 0 = (((-(3643 / 24219856213912732720693248))) : ℚ) from by decide +kernel]
  push_cast; ring

lemma lmfdb_1_64_a_orbit_qExpansion_coeff_4 :
    (PowerSeries.coeff (R := ℂ) 4)
      (qExpansion 1 (lmfdb_1_64_a_orbit : ℍ → ℂ)) = (-9223372036854775808) + 1 * α_64 ^ 2 := by
  rw [lmfdb_1_64_a_orbit_coeff_decomp,
    f_64_part_0_qExpansion_coeff 10 4 (by decide),
    f_64_part_1_qExpansion_coeff 10 4 (by decide),
    f_64_part_2_qExpansion_coeff 10 4 (by decide),
    f_64_part_3_qExpansion_coeff 10 4 (by decide),
    f_64_part_4_qExpansion_coeff 10 4 (by decide),
    f_64_part_0_evalEisList_eq,
    f_64_part_1_evalEisList_eq,
    f_64_part_2_evalEisList_eq,
    f_64_part_3_evalEisList_eq,
    f_64_part_4_evalEisList_eq,
    show f_64_part_0_qExpList.getD 4 0 = ((-9223372036854775808) : ℚ) from by decide +kernel,
    show f_64_part_1_qExpList.getD 4 0 = (0 : ℚ) from by decide +kernel,
    show f_64_part_2_qExpList.getD 4 0 = (1 : ℚ) from by decide +kernel,
    show f_64_part_3_qExpList.getD 4 0 = (0 : ℚ) from by decide +kernel,
    show f_64_part_4_qExpList.getD 4 0 = (0 : ℚ) from by decide +kernel]
  push_cast; ring

lemma lmfdb_1_64_a_orbit_qExpansion_coeff_5 :
    (PowerSeries.coeff (R := ℂ) 5)
      (qExpansion 1 (lmfdb_1_64_a_orbit : ℍ → ℂ)) = (20782946576056375227107038231991365038 / 232062745328785) + (135651488643513059526938376325 / 2970403140208448) * α_64 + ((-(4836572597772089598089493 / 121667712622938030080))) * α_64 ^ 2 + ((-(6347637419650325 / 3114693443147213570048))) * α_64 ^ 3 + (202800051 / 124587737725888542801920) * α_64 ^ 4 := by
  rw [lmfdb_1_64_a_orbit_coeff_decomp,
    f_64_part_0_qExpansion_coeff 10 5 (by decide),
    f_64_part_1_qExpansion_coeff 10 5 (by decide),
    f_64_part_2_qExpansion_coeff 10 5 (by decide),
    f_64_part_3_qExpansion_coeff 10 5 (by decide),
    f_64_part_4_qExpansion_coeff 10 5 (by decide),
    f_64_part_0_evalEisList_eq,
    f_64_part_1_evalEisList_eq,
    f_64_part_2_evalEisList_eq,
    f_64_part_3_evalEisList_eq,
    f_64_part_4_evalEisList_eq,
    show f_64_part_0_qExpList.getD 5 0 = ((20782946576056375227107038231991365038 / 232062745328785) : ℚ) from by decide +kernel,
    show f_64_part_1_qExpList.getD 5 0 = ((135651488643513059526938376325 / 2970403140208448) : ℚ) from by decide +kernel,
    show f_64_part_2_qExpList.getD 5 0 = (((-(4836572597772089598089493 / 121667712622938030080))) : ℚ) from by decide +kernel,
    show f_64_part_3_qExpList.getD 5 0 = (((-(6347637419650325 / 3114693443147213570048))) : ℚ) from by decide +kernel,
    show f_64_part_4_qExpList.getD 5 0 = ((202800051 / 124587737725888542801920) : ℚ) from by decide +kernel]
  push_cast; ring

lemma lmfdb_1_64_a_orbit_qExpansion_coeff_6 :
    (PowerSeries.coeff (R := ℂ) 6)
      (qExpansion 1 (lmfdb_1_64_a_orbit : ℍ → ℂ)) = (418165013796315143153844089456676569088 / 46412549065757) + (247234727541868598133433957500 / 46412549065757) * α_64 + ((-(13387846610452679727099 / 2970403140208448))) * α_64 ^ 2 + ((-(270719085323125 / 1140634805840044032))) * α_64 ^ 3 + (15708719 / 82125706020483170304) * α_64 ^ 4 := by
  rw [lmfdb_1_64_a_orbit_coeff_decomp,
    f_64_part_0_qExpansion_coeff 10 6 (by decide),
    f_64_part_1_qExpansion_coeff 10 6 (by decide),
    f_64_part_2_qExpansion_coeff 10 6 (by decide),
    f_64_part_3_qExpansion_coeff 10 6 (by decide),
    f_64_part_4_qExpansion_coeff 10 6 (by decide),
    f_64_part_0_evalEisList_eq,
    f_64_part_1_evalEisList_eq,
    f_64_part_2_evalEisList_eq,
    f_64_part_3_evalEisList_eq,
    f_64_part_4_evalEisList_eq,
    show f_64_part_0_qExpList.getD 6 0 = ((418165013796315143153844089456676569088 / 46412549065757) : ℚ) from by decide +kernel,
    show f_64_part_1_qExpList.getD 6 0 = ((247234727541868598133433957500 / 46412549065757) : ℚ) from by decide +kernel,
    show f_64_part_2_qExpList.getD 6 0 = (((-(13387846610452679727099 / 2970403140208448))) : ℚ) from by decide +kernel,
    show f_64_part_3_qExpList.getD 6 0 = (((-(270719085323125 / 1140634805840044032))) : ℚ) from by decide +kernel,
    show f_64_part_4_qExpList.getD 6 0 = ((15708719 / 82125706020483170304) : ℚ) from by decide +kernel]
  push_cast; ring

lemma lmfdb_1_64_a_orbit_qExpansion_coeff_7 :
    (PowerSeries.coeff (R := ℂ) 7)
      (qExpansion 1 (lmfdb_1_64_a_orbit : ℍ → ℂ)) = ((-(16900827355460864007534964684577061008792 / 6630364152251))) + ((-(950375289221305198722301204677753 / 848686611488128))) * α_64 + (6779578511691331518751116149 / 6952440721310744576) * α_64 ^ 2 + (44961980774422715721 / 889912412327775305728) * α_64 ^ 3 + ((-(269544437843 / 7119299298622202445824))) * α_64 ^ 4 := by
  rw [lmfdb_1_64_a_orbit_coeff_decomp,
    f_64_part_0_qExpansion_coeff 10 7 (by decide),
    f_64_part_1_qExpansion_coeff 10 7 (by decide),
    f_64_part_2_qExpansion_coeff 10 7 (by decide),
    f_64_part_3_qExpansion_coeff 10 7 (by decide),
    f_64_part_4_qExpansion_coeff 10 7 (by decide),
    f_64_part_0_evalEisList_eq,
    f_64_part_1_evalEisList_eq,
    f_64_part_2_evalEisList_eq,
    f_64_part_3_evalEisList_eq,
    f_64_part_4_evalEisList_eq,
    show f_64_part_0_qExpList.getD 7 0 = (((-(16900827355460864007534964684577061008792 / 6630364152251))) : ℚ) from by decide +kernel,
    show f_64_part_1_qExpList.getD 7 0 = (((-(950375289221305198722301204677753 / 848686611488128))) : ℚ) from by decide +kernel,
    show f_64_part_2_qExpList.getD 7 0 = ((6779578511691331518751116149 / 6952440721310744576) : ℚ) from by decide +kernel,
    show f_64_part_3_qExpList.getD 7 0 = ((44961980774422715721 / 889912412327775305728) : ℚ) from by decide +kernel,
    show f_64_part_4_qExpList.getD 7 0 = (((-(269544437843 / 7119299298622202445824))) : ℚ) from by decide +kernel]
  push_cast; ring

lemma lmfdb_1_64_a_orbit_qExpansion_coeff_8 :
    (PowerSeries.coeff (R := ℂ) 8)
      (qExpansion 1 (lmfdb_1_64_a_orbit : ℍ → ℂ)) = (-18446744073709551616) * α_64 + 1 * α_64 ^ 3 := by
  rw [lmfdb_1_64_a_orbit_coeff_decomp,
    f_64_part_0_qExpansion_coeff 10 8 (by decide),
    f_64_part_1_qExpansion_coeff 10 8 (by decide),
    f_64_part_2_qExpansion_coeff 10 8 (by decide),
    f_64_part_3_qExpansion_coeff 10 8 (by decide),
    f_64_part_4_qExpansion_coeff 10 8 (by decide),
    f_64_part_0_evalEisList_eq,
    f_64_part_1_evalEisList_eq,
    f_64_part_2_evalEisList_eq,
    f_64_part_3_evalEisList_eq,
    f_64_part_4_evalEisList_eq,
    show f_64_part_0_qExpList.getD 8 0 = (0 : ℚ) from by decide +kernel,
    show f_64_part_1_qExpList.getD 8 0 = ((-18446744073709551616) : ℚ) from by decide +kernel,
    show f_64_part_2_qExpList.getD 8 0 = (0 : ℚ) from by decide +kernel,
    show f_64_part_3_qExpList.getD 8 0 = (1 : ℚ) from by decide +kernel,
    show f_64_part_4_qExpList.getD 8 0 = (0 : ℚ) from by decide +kernel]
  push_cast; ring

lemma lmfdb_1_64_a_orbit_qExpansion_coeff_9 :
    (PowerSeries.coeff (R := ℂ) 9)
      (qExpansion 1 (lmfdb_1_64_a_orbit : ℍ → ℂ)) = ((-(631680390812853082804326926555887008486309 / 49852362047))) + ((-(12913430252219027127208020605011875 / 1595275585504))) * α_64 + (73919027646542806069645732023 / 13068497596448768) * α_64 ^ 2 + (629911023701409961875 / 1672767692345442304) * α_64 ^ 3 + ((-(3105118262369 / 13382141538763538432))) * α_64 ^ 4 := by
  rw [lmfdb_1_64_a_orbit_coeff_decomp,
    f_64_part_0_qExpansion_coeff 10 9 (by decide),
    f_64_part_1_qExpansion_coeff 10 9 (by decide),
    f_64_part_2_qExpansion_coeff 10 9 (by decide),
    f_64_part_3_qExpansion_coeff 10 9 (by decide),
    f_64_part_4_qExpansion_coeff 10 9 (by decide),
    f_64_part_0_evalEisList_eq,
    f_64_part_1_evalEisList_eq,
    f_64_part_2_evalEisList_eq,
    f_64_part_3_evalEisList_eq,
    f_64_part_4_evalEisList_eq,
    show f_64_part_0_qExpList.getD 9 0 = (((-(631680390812853082804326926555887008486309 / 49852362047))) : ℚ) from by decide +kernel,
    show f_64_part_1_qExpList.getD 9 0 = (((-(12913430252219027127208020605011875 / 1595275585504))) : ℚ) from by decide +kernel,
    show f_64_part_2_qExpList.getD 9 0 = ((73919027646542806069645732023 / 13068497596448768) : ℚ) from by decide +kernel,
    show f_64_part_3_qExpList.getD 9 0 = ((629911023701409961875 / 1672767692345442304) : ℚ) from by decide +kernel,
    show f_64_part_4_qExpList.getD 9 0 = (((-(3105118262369 / 13382141538763538432))) : ℚ) from by decide +kernel]
  push_cast; ring


/-! ## Uniqueness theorem -/


/-- **Uniqueness theorem.** Any level-1 weight-64 modular form `f` whose first 6
q-coefficients match the LMFDB-published values for `1.64.a.{a..}` is equal to our
explicit construction `lmfdb_1_64_a_orbit`. Proven via `ModularForm.eq_of_sturm_bound`. -/
theorem identifies_lmfdb_1_64_a_orbit (f : ModularForm 𝒮ℒ 64)
    (h_0 : (PowerSeries.coeff (R := ℂ) 0) (qExpansion 1 (f : ℍ → ℂ)) = 0)
    (h_1 : (PowerSeries.coeff (R := ℂ) 1) (qExpansion 1 (f : ℍ → ℂ)) = 1)
    (h_2 : (PowerSeries.coeff (R := ℂ) 2) (qExpansion 1 (f : ℍ → ℂ)) = 1 * α_64)
    (h_3 : (PowerSeries.coeff (R := ℂ) 3) (qExpansion 1 (f : ℍ → ℂ)) = ((-(404496705296989095162023821572 / 46412549065757))) + ((-(67521601525164741914955 / 11881612560833792))) * α_64 + (1086535311071367229 / 292002510295051272192) * α_64 ^ 2 + (90011647673 / 336386891859899065565184) * α_64 ^ 3 + ((-(3643 / 24219856213912732720693248))) * α_64 ^ 4)
    (h_4 : (PowerSeries.coeff (R := ℂ) 4) (qExpansion 1 (f : ℍ → ℂ)) = (-9223372036854775808) + 1 * α_64 ^ 2)
    (h_5 : (PowerSeries.coeff (R := ℂ) 5) (qExpansion 1 (f : ℍ → ℂ)) = (20782946576056375227107038231991365038 / 232062745328785) + (135651488643513059526938376325 / 2970403140208448) * α_64 + ((-(4836572597772089598089493 / 121667712622938030080))) * α_64 ^ 2 + ((-(6347637419650325 / 3114693443147213570048))) * α_64 ^ 3 + (202800051 / 124587737725888542801920) * α_64 ^ 4) :
    f = lmfdb_1_64_a_orbit := by
  apply ModularForm.eq_of_sturm_bound
  intro i hi
  have : i ≤ 5 := by omega
  interval_cases i
  · rw [h_0, lmfdb_1_64_a_orbit_qExpansion_coeff_0]
  · rw [h_1, lmfdb_1_64_a_orbit_qExpansion_coeff_1]
  · rw [h_2, lmfdb_1_64_a_orbit_qExpansion_coeff_2]
  · rw [h_3, lmfdb_1_64_a_orbit_qExpansion_coeff_3]
  · rw [h_4, lmfdb_1_64_a_orbit_qExpansion_coeff_4]
  · rw [h_5, lmfdb_1_64_a_orbit_qExpansion_coeff_5]


end LeanBridge.QExpansion.LMFDB.W64