import LeanBridge.ForMathlib.QExpansion.IntEval

set_option maxHeartbeats 0
set_option maxRecDepth 4000

/-!
# LMFDB level-1 weight-50 form `1.50.a`, piece 1: integer q-coefficient certificate

Heavy `decide +kernel` over `ℤ` (denominators cleared by the scale `D = 1146617856`), isolated in its own
module so `lake` schedules it in parallel with the other pieces. Generated by
`scripts/lmfdb_qexp_to_e4e6_v3.sage`.
-/

namespace LeanBridge.QExpansion.LMFDB.W50

open LeanBridge.QExpansion

def f_50_part_1_polyDataZ : List (ℕ × ℕ × ℤ) :=
  [(2, 7, 155), (5, 5, (-81)), (8, 3, (-303)), (11, 1, 229)]

def f_50_part_1_scale : ℤ := 1146617856

def f_50_part_1_qExpListZ : List ℤ :=
  [0, 0, 1146617856, (-56757583872), 0, (-35057898278092800), (-45350868799350374400), (-10244170816147199361024), (-641134785407580289105920), (-11772281902609318595788800)]

/-- Integer-arithmetic certificate (the heavy kernel computation). -/
lemma f_50_part_1_evalEisListZ_eq :
    evalEisListZ f_50_part_1_polyDataZ 10 = f_50_part_1_qExpListZ := by
  decide +kernel

end LeanBridge.QExpansion.LMFDB.W50
