import LeanBridge.ForMathlib.QExpansion.IntEval

set_option maxHeartbeats 0
set_option maxRecDepth 4000

/-!
# LMFDB level-1 weight-70 form `1.70.a`, piece 0: integer q-coefficient certificate

Heavy `decide +kernel` over `ℤ` (denominators cleared by the scale `D = 12476581296690567684096`), isolated in its own
module so `lake` schedules it in parallel with the other pieces. Generated by
`scripts/lmfdb_qexp_to_e4e6_v3.sage`.
-/

namespace LeanBridge.QExpansion.LMFDB.W70

open LeanBridge.QExpansion

def f_70_part_0_polyDataZ : List (ℕ × ℕ × ℤ) :=
  [(1, 11, 1162295630045105008246473679043), (4, 9, (-6564833013876910963321779151517)), (7, 7, 14750111853799292509176318005982), (10, 5, (-16484293778598292195771948683722)), (13, 3, 9166105901073605432263736370719), (16, 1, (-2029386592442799790592800220505))]

def f_70_part_0_scale : ℤ := 12476581296690567684096

def f_70_part_0_qExpListZ : List ℤ :=
  [0, 12476581296690567684096, 0, (-586853287629673621436896404955665235968), (-7364873667036229195610412547686902217572352), (-20489467098490469996727208184382102793591209984), 8218330951428629370080140785050187888715653709824, 2598412404812127313061865940978000275351604680523776, 0, 15749290317595213175342970814768701711742296772053245952]

/-- Integer-arithmetic certificate (the heavy kernel computation). -/
lemma f_70_part_0_evalEisListZ_eq :
    evalEisListZ f_70_part_0_polyDataZ 10 = f_70_part_0_qExpListZ := by
  decide +kernel

end LeanBridge.QExpansion.LMFDB.W70
