import LeanBridge.ForMathlib.QExpansion.IntEval

set_option maxHeartbeats 0
set_option maxRecDepth 4000

/-!
# LMFDB level-1 weight-56 form `1.56.a`, piece 1: integer q-coefficient certificate

Heavy `decide +kernel` over `ℤ` (denominators cleared by the scale `D = 982488884661190656`), isolated in its own
module so `lake` schedules it in parallel with the other pieces. Generated by
`scripts/lmfdb_qexp_to_e4e6_v3.sage`.
-/

namespace LeanBridge.QExpansion.LMFDB.W56

open LeanBridge.QExpansion

def f_56_part_1_polyDataZ : List (ℕ × ℕ × ℤ) :=
  [(2, 8, 55983646009661), (5, 6, (-137912610810908)), (8, 4, 78164989914342), (11, 2, 33473268565396), (14, 0, (-29709293678491))]

def f_56_part_1_scale : ℤ := 982488884661190656

def f_56_part_1_qExpListZ : List ℤ :=
  [0, 0, 982488884661190656, (-442015268108656485335040), 0, (-30817176911284829408590823424), (-38173794904558440322414065745920), (-6321811503253788741568277822570496), (-70795785197692679384782684884566016), 5319875331792877668917690569787965440]

/-- Integer-arithmetic certificate (the heavy kernel computation). -/
lemma f_56_part_1_evalEisListZ_eq :
    evalEisListZ f_56_part_1_polyDataZ 10 = f_56_part_1_qExpListZ := by
  decide +kernel

end LeanBridge.QExpansion.LMFDB.W56
