import LeanBridge.ForMathlib.QExpansion.IntEval

set_option maxHeartbeats 0
set_option maxRecDepth 4000

/-!
# LMFDB level-1 weight-86 form `1.86.a`, piece 4: integer q-coefficient certificate

Heavy `decide +kernel` over `ℤ` (denominators cleared by the scale `D = 7839012546500689715736535964953625818119068852694841893357545664282624`), isolated in its own
module so `lake` schedules it in parallel with the other pieces. Generated by
`scripts/lmfdb_qexp_to_e4e6_v3.sage`.
-/

namespace LeanBridge.QExpansion.LMFDB.W86

open LeanBridge.QExpansion

def f_86_part_4_polyDataZ : List (ℕ × ℕ × ℤ) :=
  [(2, 13, 66277381263315180808019655059933), (5, 11, (-265300196176932059698256185407222)), (8, 9, 332505750998412156263069137109715), (11, 7, (-2430118507253399669294091030100)), (14, 5, (-328902907649119853708265521394765)), (17, 3, 263909860131120495015299764117482), (20, 1, (-66059770059542519010572758455043))]

def f_86_part_4_scale : ℤ := 7839012546500689715736535964953625818119068852694841893357545664282624

def f_86_part_4_qExpListZ : List ℤ :=
  [0, 0, 0, (-714882322224640869137421793058252390400), 0, (-2038599210997587201312626873156179235194030522368), 590227112664949604384382453896131731101419478974464, (-69875689540886681995273567892737817760496170408345600), 0, 72486168169419913853780888414732876478551034394077453877248]

/-- Integer-arithmetic certificate (the heavy kernel computation). -/
lemma f_86_part_4_evalEisListZ_eq :
    evalEisListZ f_86_part_4_polyDataZ 10 = f_86_part_4_qExpListZ := by
  decide +kernel

end LeanBridge.QExpansion.LMFDB.W86
