import LeanBridge.ForMathlib.QExpansion.IntEval

set_option maxHeartbeats 0
set_option maxRecDepth 4000

/-!
# LMFDB level-1 weight-54 form `1.54.a`, piece 0: integer q-coefficient certificate

Heavy `decide +kernel` over `ℤ` (denominators cleared by the scale `D = 7214098526208`), isolated in its own
module so `lake` schedules it in parallel with the other pieces. Generated by
`scripts/lmfdb_qexp_to_e4e6_v3.sage`.
-/

namespace LeanBridge.QExpansion.LMFDB.W54

open LeanBridge.QExpansion

def f_54_part_0_polyDataZ : List (ℕ × ℕ × ℤ) :=
  [(0, 9, (-7360793223482207)), (3, 7, 28567342451608088), (6, 5, (-41537271956821806)), (9, 3, 26815685277922640), (12, 1, (-6484962549226715))]

def f_54_part_0_scale : ℤ := 7214098526208

def f_54_part_0_qExpListZ : List ℤ :=
  [0, 7214098526208, 0, 4519089094139507815464960, (-64978822868888786343963918336), 38413821309879416716517402419200, (-2695896684180586644094548826914816), 34540647720551665187107730467553280, 0, (-7315664271299229253321633586174300160)]

/-- Integer-arithmetic certificate (the heavy kernel computation). -/
lemma f_54_part_0_evalEisListZ_eq :
    evalEisListZ f_54_part_0_polyDataZ 10 = f_54_part_0_qExpListZ := by
  decide +kernel

end LeanBridge.QExpansion.LMFDB.W54
