import LeanBridge.ForMathlib.QExpansion.IntEval

set_option maxHeartbeats 0
set_option maxRecDepth 4000

/-!
# LMFDB level-1 weight-42 form `1.42.a`, piece 0: integer q-coefficient certificate

Heavy `decide +kernel` over `ℤ` (denominators cleared by the scale `D = 40310784`), isolated in its own
module so `lake` schedules it in parallel with the other pieces. Generated by
`scripts/lmfdb_qexp_to_e4e6_v3.sage`.
-/

namespace LeanBridge.QExpansion.LMFDB.W42

open LeanBridge.QExpansion

def f_42_part_0_polyDataZ : List (ℕ × ℕ × ℤ) :=
  [(0, 7, (-29826353)), (3, 5, 89466747), (6, 3, (-89477763)), (9, 1, 29837369)]

def f_42_part_0_scale : ℤ := 40310784

def f_42_part_0_qExpListZ : List ℤ :=
  [0, 40310784, 0, 153895783082582016, (-88644351465533472768), 3406023449005797642240, (-36422159882436118315008), (-847320964444227463888896), 20979164092283204149444608, (-890258525106922451418531840)]

/-- Integer-arithmetic certificate (the heavy kernel computation). -/
lemma f_42_part_0_evalEisListZ_eq :
    evalEisListZ f_42_part_0_polyDataZ 10 = f_42_part_0_qExpListZ := by
  decide +kernel

end LeanBridge.QExpansion.LMFDB.W42
