import LeanBridge.ForMathlib.QExpansion.IntEval

set_option maxHeartbeats 0
set_option maxRecDepth 4000

/-!
# LMFDB level-1 weight-66 form `1.66.a`, piece 2: integer q-coefficient certificate

Heavy `decide +kernel` over `ℤ` (denominators cleared by the scale `D = 91273337062451632170305335590912`), isolated in its own
module so `lake` schedules it in parallel with the other pieces. Generated by
`scripts/lmfdb_qexp_to_e4e6_v3.sage`.
-/

namespace LeanBridge.QExpansion.LMFDB.W66

open LeanBridge.QExpansion

def f_66_part_2_polyDataZ : List (ℕ × ℕ × ℤ) :=
  [(0, 11, (-18279368699039238523)), (3, 9, 106865999799559538165), (6, 7, (-234205823911025478634)), (9, 5, 244215159926111592142), (12, 3, (-121880003822188708427)), (15, 1, 23284036706582295277)]

def f_66_part_2_scale : ℤ := 91273337062451632170305335590912

def f_66_part_2_qExpListZ : List ℤ :=
  [0, 0, 0, (-53994461107667270204566536192), 91273337062451632170305335590912, 294420319930293334254507129248415744, (-195803756998422665128593443131012153344), 10256169318187975316664015463963252752384, 0, 160643870654189367121616843756870393829261312]

/-- Integer-arithmetic certificate (the heavy kernel computation). -/
lemma f_66_part_2_evalEisListZ_eq :
    evalEisListZ f_66_part_2_polyDataZ 10 = f_66_part_2_qExpListZ := by
  decide +kernel

end LeanBridge.QExpansion.LMFDB.W66
