import LeanBridge.ForMathlib.QExpansion.IntEval

set_option maxHeartbeats 0
set_option maxRecDepth 4000

/-!
# LMFDB level-1 weight-68 form `1.68.a`, piece 0: integer q-coefficient certificate

Heavy `decide +kernel` over `ℤ` (denominators cleared by the scale `D = 3733386639421805361923235840`), isolated in its own
module so `lake` schedules it in parallel with the other pieces. Generated by
`scripts/lmfdb_qexp_to_e4e6_v3.sage`.
-/

namespace LeanBridge.QExpansion.LMFDB.W68

open LeanBridge.QExpansion

def f_68_part_0_polyDataZ : List (ℕ × ℕ × ℤ) :=
  [(2, 10, 133534031086741016507778567519383627), (5, 8, (-709635550916815877833396577783201830)), (8, 6, 1521741783709066518608632266099461570), (11, 4, (-1642752356497885466818680698933147360)), (14, 2, 891151410099969281930566750556389915), (17, 0, (-194039317481075472394900307458885922))]

def f_68_part_0_scale : ℤ := 3733386639421805361923235840

def f_68_part_0_qExpListZ : List ℤ :=
  [0, 3733386639421805361923235840, 0, (-95661764854482110682786728422140856293949440), (-550950622924964853841372975301530185425768939520), (-2613392489346767195338935517606302821079178737893376), (-984839803483953273430492415687458972349683051674992640), (-78906260313618089035934150608128306380941502047899156480), 0, (-836087205769540952780211735362121158968635313611752809390080)]

/-- Integer-arithmetic certificate (the heavy kernel computation). -/
lemma f_68_part_0_evalEisListZ_eq :
    evalEisListZ f_68_part_0_polyDataZ 10 = f_68_part_0_qExpListZ := by
  decide +kernel

end LeanBridge.QExpansion.LMFDB.W68
