import LeanBridge.ForMathlib.QExpansion.IntEval

set_option maxHeartbeats 0
set_option maxRecDepth 4000

/-!
# LMFDB level-1 weight-32 form `1.32.a`, piece 0: integer q-coefficient certificate

Heavy `decide +kernel` over `ℤ` (denominators cleared by the scale `D = 124416`), isolated in its own
module so `lake` schedules it in parallel with the other pieces. Generated by
`scripts/lmfdb_qexp_to_e4e6_v3.sage`.
-/

namespace LeanBridge.QExpansion.LMFDB.W32

open LeanBridge.QExpansion

def f_32_part_0_polyDataZ : List (ℕ × ℕ × ℤ) :=
  [(2, 4, (-49)), (5, 2, 26), (8, 0, 23)]

def f_32_part_0_scale : ℤ := 124416

def f_32_part_0_qExpListZ : List ℤ :=
  [0, 124416, 0, 6248171520, 10931982041088, 2320012497392640, 120144948879163392, 2061063324360069120, 11113407771322613760, (-24945521573091230208)]

/-- Integer-arithmetic certificate (the heavy kernel computation). -/
lemma f_32_part_0_evalEisListZ_eq :
    evalEisListZ f_32_part_0_polyDataZ 10 = f_32_part_0_qExpListZ := by
  decide +kernel

end LeanBridge.QExpansion.LMFDB.W32
