import LeanBridge.ForMathlib.QExpansion.IntEval
import LeanBridge.ForMathlib.QExpansion.Sturm
import Mathlib.Analysis.Complex.Polynomial.Basic
import LeanBridge.ForMathlib.QExpansion.LMFDB.Weight_54_part_0
import LeanBridge.ForMathlib.QExpansion.LMFDB.Weight_54_part_1
import LeanBridge.ForMathlib.QExpansion.LMFDB.Weight_54_part_2
import LeanBridge.ForMathlib.QExpansion.LMFDB.Weight_54_part_3

set_option maxHeartbeats 0
set_option maxRecDepth 2000

/-!
# LMFDB level-1 modular form orbit `1.54.a.{a..}` (Hecke field degree 4)

The Hecke field `K = ℚ(α)` is degree 4 over ℚ. The LMFDB lists q-coefficients as
elements of `K`, which we decompose as `c_0 + c_1 · α + … + c_{3} · α^3`.
The combined form is `f = f_0 + α · f_1 + … + α^3 · f_{3}`, with each
`f_j` a level-1 weight-54 form with rational coefficients in `(E₄, E₆)`.

The Sturm bound for weight 54 is `⌊54/12⌋ + 1 = 5`. After certifying agreement
on the first 5 q-coefficients, `ModularForm.eq_of_sturm_bound` lets us conclude that any
form with the same coefficients equals our explicit `lmfdb_1_54_a_orbit`.

Generated by `scripts/lmfdb_qexp_to_e4e6_v3.sage`.
-/

namespace LeanBridge.QExpansion.LMFDB.W54

open LeanBridge.QExpansion ModularForm EisensteinSeries PowerSeries UpperHalfPlane
open scoped MatrixGroups


/-- Minimal polynomial of α (degree 4) as `Polynomial ℂ`. -/
noncomputable def α_54_minpoly : Polynomial ℂ :=
  Polynomial.X ^ 4 +
    Polynomial.C 39446133467662904714689328971776 +
    Polynomial.C (-1083312724663489297121280) * Polynomial.X +
    Polynomial.C (-19584715019010048) * Polynomial.X ^ 2 +
    Polynomial.C 68476320 * Polynomial.X ^ 3

lemma α_54_minpoly_natDegree : α_54_minpoly.natDegree = 4 := by
  unfold α_54_minpoly
  compute_degree!

lemma α_54_minpoly_degree_ne_zero : α_54_minpoly.degree ≠ 0 := by
  rw [Polynomial.degree_eq_natDegree (fun h => by
    have := α_54_minpoly_natDegree
    rw [h, Polynomial.natDegree_zero] at this
    exact absurd this (by decide))]
  rw [α_54_minpoly_natDegree]
  decide

/-- α is some root of the degree-4 minimal polynomial in ℂ. -/
noncomputable def α_54 : ℂ :=
  (IsAlgClosed.exists_root α_54_minpoly α_54_minpoly_degree_ne_zero).choose

lemma α_54_isRoot : Polynomial.IsRoot α_54_minpoly α_54 :=
  (IsAlgClosed.exists_root α_54_minpoly α_54_minpoly_degree_ne_zero).choose_spec

/-- Explicit polynomial relation: minpoly evaluated at α is zero. -/
lemma α_54_is_root :
    α_54 ^ 4 +
      39446133467662904714689328971776 +
      (-1083312724663489297121280) * α_54 +
      (-19584715019010048) * α_54 ^ 2 +
      68476320 * α_54 ^ 3 = 0 := by
  have h := α_54_isRoot
  unfold Polynomial.IsRoot α_54_minpoly at h
  simp only [Polynomial.eval_add, Polynomial.eval_mul, Polynomial.eval_pow,
    Polynomial.eval_C, Polynomial.eval_X] at h
  linear_combination h


/-! ## Piece 0: coefficient of α^0 -/


def f_54_part_0_polyData : List (ℕ × ℕ × ℚ) :=
  [(0, 9, ((-(7360793223482207 / 7214098526208)))), (3, 7, (3570917806451011 / 901762315776)), (6, 5, ((-(6922878659470301 / 1202349754368)))), (9, 3, (1675980329870165 / 450881157888)), (12, 1, ((-(6484962549226715 / 7214098526208))))]

noncomputable def f_54_part_0 : ModularForm 𝒮ℒ 54 :=
  (((-(7360793223482207 / 7214098526208))) : ℂ) • mkMonomForm 0 9 54 (by decide) +
  ((3570917806451011 / 901762315776) : ℂ) • mkMonomForm 3 7 54 (by decide) +
  (((-(6922878659470301 / 1202349754368))) : ℂ) • mkMonomForm 6 5 54 (by decide) +
  ((1675980329870165 / 450881157888) : ℂ) • mkMonomForm 9 3 54 (by decide) +
  (((-(6484962549226715 / 7214098526208))) : ℂ) • mkMonomForm 12 1 54 (by decide)

lemma f_54_part_0_qExpansion_eq_evalEisPS :
    qExpansion 1 (f_54_part_0 : ℍ → ℂ) = evalEisPS f_54_part_0_polyData := by
  unfold f_54_part_0
  rw [ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm]
  unfold evalEisPS f_54_part_0_polyData monomialEisPS
  simp only [List.foldr_cons, List.foldr_nil, add_zero]
  push_cast
  module

theorem f_54_part_0_qExpansion_coeff (N n : ℕ) (hn : n < N) :
    (PowerSeries.coeff (R := ℂ) n) (qExpansion 1 (f_54_part_0 : ℍ → ℂ))
      = ((evalEisList f_54_part_0_polyData N).getD n 0 : ℚ) :=
  qexp_coeff_via_E4E6 _ _ f_54_part_0_qExpansion_eq_evalEisPS N n hn

/-- Precomputed first 10 q-coefficients of `f_54_part_0` (rational). -/
def f_54_part_0_qExpList : List ℚ :=
  [0, 1, 0, (18684367827971740 / 29827), (-9007199254740992), (158823593002968373246050 / 29827), ((-(11146300553968331998101504 / 29827))), (20401398650516178775426760 / 4261), 0, ((-(4320989704640367423481774095 / 4261)))]

/-- Bridge: the symbolic `evalEisList` (over ℚ) equals the precomputed list. The heavy kernel work
is the integer certificate `f_54_part_0_evalEisListZ_eq`; the steps here are cheap rational
list checks. -/
lemma f_54_part_0_evalEisList_eq :
    evalEisList f_54_part_0_polyData 10 = f_54_part_0_qExpList := by
  have h : f_54_part_0_polyData
      = f_54_part_0_polyDataZ.map
          (fun t => (t.1, t.2.1, (t.2.2 : ℚ) / f_54_part_0_scale)) := by
    decide +kernel
  rw [h, evalEisList_eq_intCast_div, f_54_part_0_evalEisListZ_eq]
  decide +kernel


/-! ## Piece 1: coefficient of α^1 -/


def f_54_part_1_polyData : List (ℕ × ℕ × ℚ) :=
  [(0, 9, (14757510607 / 6331917335003136)), (3, 7, (14854150087 / 791489666875392)), (6, 5, ((-(73820686571 / 1055319555833856)))), (9, 3, (14697456073 / 197872416718848)), (12, 1, ((-(160985186213 / 6331917335003136))))]

noncomputable def f_54_part_1 : ModularForm 𝒮ℒ 54 :=
  ((14757510607 / 6331917335003136) : ℂ) • mkMonomForm 0 9 54 (by decide) +
  ((14854150087 / 791489666875392) : ℂ) • mkMonomForm 3 7 54 (by decide) +
  (((-(73820686571 / 1055319555833856))) : ℂ) • mkMonomForm 6 5 54 (by decide) +
  ((14697456073 / 197872416718848) : ℂ) • mkMonomForm 9 3 54 (by decide) +
  (((-(160985186213 / 6331917335003136))) : ℂ) • mkMonomForm 12 1 54 (by decide)

lemma f_54_part_1_qExpansion_eq_evalEisPS :
    qExpansion 1 (f_54_part_1 : ℍ → ℂ) = evalEisPS f_54_part_1_polyData := by
  unfold f_54_part_1
  rw [ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm]
  unfold evalEisPS f_54_part_1_polyData monomialEisPS
  simp only [List.foldr_cons, List.foldr_nil, add_zero]
  push_cast
  module

theorem f_54_part_1_qExpansion_coeff (N n : ℕ) (hn : n < N) :
    (PowerSeries.coeff (R := ℂ) n) (qExpansion 1 (f_54_part_1 : ℍ → ℂ))
      = ((evalEisList f_54_part_1_polyData N).getD n 0 : ℚ) :=
  qexp_coeff_via_E4E6 _ _ f_54_part_1_qExpansion_eq_evalEisPS N n hn

/-- Precomputed first 10 q-coefficients of `f_54_part_1` (rational). -/
def f_54_part_1_qExpList : List ℚ :=
  [0, 0, 1, ((-(14731126495 / 102264))), 0, (155676562563025 / 8522), (46399460891726980 / 4261), (13059075515055628491 / 17044), (-18014398509481984), ((-(1618195165769997187665 / 4261)))]

/-- Bridge: the symbolic `evalEisList` (over ℚ) equals the precomputed list. The heavy kernel work
is the integer certificate `f_54_part_1_evalEisListZ_eq`; the steps here are cheap rational
list checks. -/
lemma f_54_part_1_evalEisList_eq :
    evalEisList f_54_part_1_polyData 10 = f_54_part_1_qExpList := by
  have h : f_54_part_1_polyData
      = f_54_part_1_polyDataZ.map
          (fun t => (t.1, t.2.1, (t.2.2 : ℚ) / f_54_part_1_scale)) := by
    decide +kernel
  rw [h, evalEisList_eq_intCast_div, f_54_part_1_evalEisListZ_eq]
  decide +kernel


/-! ## Piece 2: coefficient of α^2 -/


def f_54_part_2_polyData : List (ℕ × ℕ × ℚ) :=
  [(0, 9, (7712177 / 68080775185953718272)), (3, 7, ((-(3741391 / 8510096898244214784)))), (6, 5, (7253387 / 11346795864325619712)), (9, 3, ((-(877999 / 2127524224561053696)))), (12, 1, (6794597 / 68080775185953718272))]

noncomputable def f_54_part_2 : ModularForm 𝒮ℒ 54 :=
  ((7712177 / 68080775185953718272) : ℂ) • mkMonomForm 0 9 54 (by decide) +
  (((-(3741391 / 8510096898244214784))) : ℂ) • mkMonomForm 3 7 54 (by decide) +
  ((7253387 / 11346795864325619712) : ℂ) • mkMonomForm 6 5 54 (by decide) +
  (((-(877999 / 2127524224561053696))) : ℂ) • mkMonomForm 9 3 54 (by decide) +
  ((6794597 / 68080775185953718272) : ℂ) • mkMonomForm 12 1 54 (by decide)

lemma f_54_part_2_qExpansion_eq_evalEisPS :
    qExpansion 1 (f_54_part_2 : ℍ → ℂ) = evalEisPS f_54_part_2_polyData := by
  unfold f_54_part_2
  rw [ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm]
  unfold evalEisPS f_54_part_2_polyData monomialEisPS
  simp only [List.foldr_cons, List.foldr_nil, add_zero]
  push_cast
  module

theorem f_54_part_2_qExpansion_coeff (N n : ℕ) (hn : n < N) :
    (PowerSeries.coeff (R := ℂ) n) (qExpansion 1 (f_54_part_2 : ℍ → ℂ))
      = ((evalEisList f_54_part_2_polyData N).getD n 0 : ℚ) :=
  qexp_coeff_via_E4E6 _ _ f_54_part_2_qExpansion_eq_evalEisPS N n hn

/-- Precomputed first 10 q-coefficients of `f_54_part_2` (rational). -/
def f_54_part_2_qExpList : List ℚ :=
  [0, 0, 0, ((-(76465 / 1099542528))), 1, ((-(18056169675 / 30542848))), (3712432946 / 89481), ((-(4638964972495 / 8726528))), 0, (245402038444189 / 2181632)]

/-- Bridge: the symbolic `evalEisList` (over ℚ) equals the precomputed list. The heavy kernel work
is the integer certificate `f_54_part_2_evalEisListZ_eq`; the steps here are cheap rational
list checks. -/
lemma f_54_part_2_evalEisList_eq :
    evalEisList f_54_part_2_polyData 10 = f_54_part_2_qExpList := by
  have h : f_54_part_2_polyData
      = f_54_part_2_polyDataZ.map
          (fun t => (t.1, t.2.1, (t.2.2 : ℚ) / f_54_part_2_scale)) := by
    decide +kernel
  rw [h, evalEisList_eq_intCast_div, f_54_part_2_evalEisListZ_eq]
  decide +kernel


/-! ## Piece 3: coefficient of α^3 -/


def f_54_part_3_polyData : List (ℕ × ℕ × ℚ) :=
  [(0, 9, ((-(1 / 6535754417851556954112)))), (3, 7, ((-(1 / 816969302231444619264)))), (6, 5, (5 / 1089292402975259492352)), (9, 3, ((-(1 / 204242325557861154816)))), (12, 1, (11 / 6535754417851556954112))]

noncomputable def f_54_part_3 : ModularForm 𝒮ℒ 54 :=
  (((-(1 / 6535754417851556954112))) : ℂ) • mkMonomForm 0 9 54 (by decide) +
  (((-(1 / 816969302231444619264))) : ℂ) • mkMonomForm 3 7 54 (by decide) +
  ((5 / 1089292402975259492352) : ℂ) • mkMonomForm 6 5 54 (by decide) +
  (((-(1 / 204242325557861154816))) : ℂ) • mkMonomForm 9 3 54 (by decide) +
  ((11 / 6535754417851556954112) : ℂ) • mkMonomForm 12 1 54 (by decide)

lemma f_54_part_3_qExpansion_eq_evalEisPS :
    qExpansion 1 (f_54_part_3 : ℍ → ℂ) = evalEisPS f_54_part_3_polyData := by
  unfold f_54_part_3
  rw [ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm]
  unfold evalEisPS f_54_part_3_polyData monomialEisPS
  simp only [List.foldr_cons, List.foldr_nil, add_zero]
  push_cast
  module

theorem f_54_part_3_qExpansion_coeff (N n : ℕ) (hn : n < N) :
    (PowerSeries.coeff (R := ℂ) n) (qExpansion 1 (f_54_part_3 : ℍ → ℂ))
      = ((evalEisList f_54_part_3_polyData N).getD n 0 : ℚ) :=
  qexp_coeff_via_E4E6 _ _ f_54_part_3_qExpansion_eq_evalEisPS N n hn

/-- Precomputed first 10 q-coefficients of `f_54_part_3` (rational). -/
def f_54_part_3_qExpList : List ℚ :=
  [0, 0, 0, (1 / 105556082688), 0, ((-(1175 / 977371136))), ((-(3085 / 4295088))), ((-(14392107 / 279248896))), 1, (2967693395 / 209436672)]

/-- Bridge: the symbolic `evalEisList` (over ℚ) equals the precomputed list. The heavy kernel work
is the integer certificate `f_54_part_3_evalEisListZ_eq`; the steps here are cheap rational
list checks. -/
lemma f_54_part_3_evalEisList_eq :
    evalEisList f_54_part_3_polyData 10 = f_54_part_3_qExpList := by
  have h : f_54_part_3_polyData
      = f_54_part_3_polyDataZ.map
          (fun t => (t.1, t.2.1, (t.2.2 : ℚ) / f_54_part_3_scale)) := by
    decide +kernel
  rw [h, evalEisList_eq_intCast_div, f_54_part_3_evalEisListZ_eq]
  decide +kernel


/-! ## Combined LMFDB form -/


noncomputable def lmfdb_1_54_a_orbit : ModularForm 𝒮ℒ 54 :=
  f_54_part_0 +
  α_54 • f_54_part_1 +
  α_54 ^ 2 • f_54_part_2 +
  α_54 ^ 3 • f_54_part_3

lemma lmfdb_1_54_a_orbit_coeff_decomp (n : ℕ) :
    (PowerSeries.coeff (R := ℂ) n) (qExpansion 1 (lmfdb_1_54_a_orbit : ℍ → ℂ))
      = (PowerSeries.coeff (R := ℂ) n) (qExpansion 1 (f_54_part_0 : ℍ → ℂ))
        + α_54 * (PowerSeries.coeff (R := ℂ) n) (qExpansion 1 (f_54_part_1 : ℍ → ℂ))
        + α_54 ^ 2 * (PowerSeries.coeff (R := ℂ) n) (qExpansion 1 (f_54_part_2 : ℍ → ℂ))
        + α_54 ^ 3 * (PowerSeries.coeff (R := ℂ) n) (qExpansion 1 (f_54_part_3 : ℍ → ℂ)) := by
  unfold lmfdb_1_54_a_orbit
  rw [ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL]
  simp [smul_eq_mul]


/-! ## Coefficient lemmas (n = 0, …, 9)

Sturm bound is 5; we certify 10 coefficients for added
redundancy beyond the minimum mathematically required for uniqueness. -/


lemma lmfdb_1_54_a_orbit_qExpansion_coeff_0 :
    (PowerSeries.coeff (R := ℂ) 0)
      (qExpansion 1 (lmfdb_1_54_a_orbit : ℍ → ℂ)) = 0 := by
  rw [lmfdb_1_54_a_orbit_coeff_decomp,
    f_54_part_0_qExpansion_coeff 10 0 (by decide),
    f_54_part_1_qExpansion_coeff 10 0 (by decide),
    f_54_part_2_qExpansion_coeff 10 0 (by decide),
    f_54_part_3_qExpansion_coeff 10 0 (by decide),
    f_54_part_0_evalEisList_eq,
    f_54_part_1_evalEisList_eq,
    f_54_part_2_evalEisList_eq,
    f_54_part_3_evalEisList_eq,
    show f_54_part_0_qExpList.getD 0 0 = (0 : ℚ) from by decide +kernel,
    show f_54_part_1_qExpList.getD 0 0 = (0 : ℚ) from by decide +kernel,
    show f_54_part_2_qExpList.getD 0 0 = (0 : ℚ) from by decide +kernel,
    show f_54_part_3_qExpList.getD 0 0 = (0 : ℚ) from by decide +kernel]
  push_cast; ring

lemma lmfdb_1_54_a_orbit_qExpansion_coeff_1 :
    (PowerSeries.coeff (R := ℂ) 1)
      (qExpansion 1 (lmfdb_1_54_a_orbit : ℍ → ℂ)) = 1 := by
  rw [lmfdb_1_54_a_orbit_coeff_decomp,
    f_54_part_0_qExpansion_coeff 10 1 (by decide),
    f_54_part_1_qExpansion_coeff 10 1 (by decide),
    f_54_part_2_qExpansion_coeff 10 1 (by decide),
    f_54_part_3_qExpansion_coeff 10 1 (by decide),
    f_54_part_0_evalEisList_eq,
    f_54_part_1_evalEisList_eq,
    f_54_part_2_evalEisList_eq,
    f_54_part_3_evalEisList_eq,
    show f_54_part_0_qExpList.getD 1 0 = (1 : ℚ) from by decide +kernel,
    show f_54_part_1_qExpList.getD 1 0 = (0 : ℚ) from by decide +kernel,
    show f_54_part_2_qExpList.getD 1 0 = (0 : ℚ) from by decide +kernel,
    show f_54_part_3_qExpList.getD 1 0 = (0 : ℚ) from by decide +kernel]
  push_cast; ring

lemma lmfdb_1_54_a_orbit_qExpansion_coeff_2 :
    (PowerSeries.coeff (R := ℂ) 2)
      (qExpansion 1 (lmfdb_1_54_a_orbit : ℍ → ℂ)) = 1 * α_54 := by
  rw [lmfdb_1_54_a_orbit_coeff_decomp,
    f_54_part_0_qExpansion_coeff 10 2 (by decide),
    f_54_part_1_qExpansion_coeff 10 2 (by decide),
    f_54_part_2_qExpansion_coeff 10 2 (by decide),
    f_54_part_3_qExpansion_coeff 10 2 (by decide),
    f_54_part_0_evalEisList_eq,
    f_54_part_1_evalEisList_eq,
    f_54_part_2_evalEisList_eq,
    f_54_part_3_evalEisList_eq,
    show f_54_part_0_qExpList.getD 2 0 = (0 : ℚ) from by decide +kernel,
    show f_54_part_1_qExpList.getD 2 0 = (1 : ℚ) from by decide +kernel,
    show f_54_part_2_qExpList.getD 2 0 = (0 : ℚ) from by decide +kernel,
    show f_54_part_3_qExpList.getD 2 0 = (0 : ℚ) from by decide +kernel]
  push_cast; ring

lemma lmfdb_1_54_a_orbit_qExpansion_coeff_3 :
    (PowerSeries.coeff (R := ℂ) 3)
      (qExpansion 1 (lmfdb_1_54_a_orbit : ℍ → ℂ)) = (18684367827971740 / 29827) + ((-(14731126495 / 102264))) * α_54 + ((-(76465 / 1099542528))) * α_54 ^ 2 + (1 / 105556082688) * α_54 ^ 3 := by
  rw [lmfdb_1_54_a_orbit_coeff_decomp,
    f_54_part_0_qExpansion_coeff 10 3 (by decide),
    f_54_part_1_qExpansion_coeff 10 3 (by decide),
    f_54_part_2_qExpansion_coeff 10 3 (by decide),
    f_54_part_3_qExpansion_coeff 10 3 (by decide),
    f_54_part_0_evalEisList_eq,
    f_54_part_1_evalEisList_eq,
    f_54_part_2_evalEisList_eq,
    f_54_part_3_evalEisList_eq,
    show f_54_part_0_qExpList.getD 3 0 = ((18684367827971740 / 29827) : ℚ) from by decide +kernel,
    show f_54_part_1_qExpList.getD 3 0 = (((-(14731126495 / 102264))) : ℚ) from by decide +kernel,
    show f_54_part_2_qExpList.getD 3 0 = (((-(76465 / 1099542528))) : ℚ) from by decide +kernel,
    show f_54_part_3_qExpList.getD 3 0 = ((1 / 105556082688) : ℚ) from by decide +kernel]
  push_cast; ring

lemma lmfdb_1_54_a_orbit_qExpansion_coeff_4 :
    (PowerSeries.coeff (R := ℂ) 4)
      (qExpansion 1 (lmfdb_1_54_a_orbit : ℍ → ℂ)) = (-9007199254740992) + 1 * α_54 ^ 2 := by
  rw [lmfdb_1_54_a_orbit_coeff_decomp,
    f_54_part_0_qExpansion_coeff 10 4 (by decide),
    f_54_part_1_qExpansion_coeff 10 4 (by decide),
    f_54_part_2_qExpansion_coeff 10 4 (by decide),
    f_54_part_3_qExpansion_coeff 10 4 (by decide),
    f_54_part_0_evalEisList_eq,
    f_54_part_1_evalEisList_eq,
    f_54_part_2_evalEisList_eq,
    f_54_part_3_evalEisList_eq,
    show f_54_part_0_qExpList.getD 4 0 = ((-9007199254740992) : ℚ) from by decide +kernel,
    show f_54_part_1_qExpList.getD 4 0 = (0 : ℚ) from by decide +kernel,
    show f_54_part_2_qExpList.getD 4 0 = (1 : ℚ) from by decide +kernel,
    show f_54_part_3_qExpList.getD 4 0 = (0 : ℚ) from by decide +kernel]
  push_cast; ring

lemma lmfdb_1_54_a_orbit_qExpansion_coeff_5 :
    (PowerSeries.coeff (R := ℂ) 5)
      (qExpansion 1 (lmfdb_1_54_a_orbit : ℍ → ℂ)) = (158823593002968373246050 / 29827) + (155676562563025 / 8522) * α_54 + ((-(18056169675 / 30542848))) * α_54 ^ 2 + ((-(1175 / 977371136))) * α_54 ^ 3 := by
  rw [lmfdb_1_54_a_orbit_coeff_decomp,
    f_54_part_0_qExpansion_coeff 10 5 (by decide),
    f_54_part_1_qExpansion_coeff 10 5 (by decide),
    f_54_part_2_qExpansion_coeff 10 5 (by decide),
    f_54_part_3_qExpansion_coeff 10 5 (by decide),
    f_54_part_0_evalEisList_eq,
    f_54_part_1_evalEisList_eq,
    f_54_part_2_evalEisList_eq,
    f_54_part_3_evalEisList_eq,
    show f_54_part_0_qExpList.getD 5 0 = ((158823593002968373246050 / 29827) : ℚ) from by decide +kernel,
    show f_54_part_1_qExpList.getD 5 0 = ((155676562563025 / 8522) : ℚ) from by decide +kernel,
    show f_54_part_2_qExpList.getD 5 0 = (((-(18056169675 / 30542848))) : ℚ) from by decide +kernel,
    show f_54_part_3_qExpList.getD 5 0 = (((-(1175 / 977371136))) : ℚ) from by decide +kernel]
  push_cast; ring

lemma lmfdb_1_54_a_orbit_qExpansion_coeff_6 :
    (PowerSeries.coeff (R := ℂ) 6)
      (qExpansion 1 (lmfdb_1_54_a_orbit : ℍ → ℂ)) = ((-(11146300553968331998101504 / 29827))) + (46399460891726980 / 4261) * α_54 + (3712432946 / 89481) * α_54 ^ 2 + ((-(3085 / 4295088))) * α_54 ^ 3 := by
  rw [lmfdb_1_54_a_orbit_coeff_decomp,
    f_54_part_0_qExpansion_coeff 10 6 (by decide),
    f_54_part_1_qExpansion_coeff 10 6 (by decide),
    f_54_part_2_qExpansion_coeff 10 6 (by decide),
    f_54_part_3_qExpansion_coeff 10 6 (by decide),
    f_54_part_0_evalEisList_eq,
    f_54_part_1_evalEisList_eq,
    f_54_part_2_evalEisList_eq,
    f_54_part_3_evalEisList_eq,
    show f_54_part_0_qExpList.getD 6 0 = (((-(11146300553968331998101504 / 29827))) : ℚ) from by decide +kernel,
    show f_54_part_1_qExpList.getD 6 0 = ((46399460891726980 / 4261) : ℚ) from by decide +kernel,
    show f_54_part_2_qExpList.getD 6 0 = ((3712432946 / 89481) : ℚ) from by decide +kernel,
    show f_54_part_3_qExpList.getD 6 0 = (((-(3085 / 4295088))) : ℚ) from by decide +kernel]
  push_cast; ring

lemma lmfdb_1_54_a_orbit_qExpansion_coeff_7 :
    (PowerSeries.coeff (R := ℂ) 7)
      (qExpansion 1 (lmfdb_1_54_a_orbit : ℍ → ℂ)) = (20401398650516178775426760 / 4261) + (13059075515055628491 / 17044) * α_54 + ((-(4638964972495 / 8726528))) * α_54 ^ 2 + ((-(14392107 / 279248896))) * α_54 ^ 3 := by
  rw [lmfdb_1_54_a_orbit_coeff_decomp,
    f_54_part_0_qExpansion_coeff 10 7 (by decide),
    f_54_part_1_qExpansion_coeff 10 7 (by decide),
    f_54_part_2_qExpansion_coeff 10 7 (by decide),
    f_54_part_3_qExpansion_coeff 10 7 (by decide),
    f_54_part_0_evalEisList_eq,
    f_54_part_1_evalEisList_eq,
    f_54_part_2_evalEisList_eq,
    f_54_part_3_evalEisList_eq,
    show f_54_part_0_qExpList.getD 7 0 = ((20401398650516178775426760 / 4261) : ℚ) from by decide +kernel,
    show f_54_part_1_qExpList.getD 7 0 = ((13059075515055628491 / 17044) : ℚ) from by decide +kernel,
    show f_54_part_2_qExpList.getD 7 0 = (((-(4638964972495 / 8726528))) : ℚ) from by decide +kernel,
    show f_54_part_3_qExpList.getD 7 0 = (((-(14392107 / 279248896))) : ℚ) from by decide +kernel]
  push_cast; ring

lemma lmfdb_1_54_a_orbit_qExpansion_coeff_8 :
    (PowerSeries.coeff (R := ℂ) 8)
      (qExpansion 1 (lmfdb_1_54_a_orbit : ℍ → ℂ)) = (-18014398509481984) * α_54 + 1 * α_54 ^ 3 := by
  rw [lmfdb_1_54_a_orbit_coeff_decomp,
    f_54_part_0_qExpansion_coeff 10 8 (by decide),
    f_54_part_1_qExpansion_coeff 10 8 (by decide),
    f_54_part_2_qExpansion_coeff 10 8 (by decide),
    f_54_part_3_qExpansion_coeff 10 8 (by decide),
    f_54_part_0_evalEisList_eq,
    f_54_part_1_evalEisList_eq,
    f_54_part_2_evalEisList_eq,
    f_54_part_3_evalEisList_eq,
    show f_54_part_0_qExpList.getD 8 0 = (0 : ℚ) from by decide +kernel,
    show f_54_part_1_qExpList.getD 8 0 = ((-18014398509481984) : ℚ) from by decide +kernel,
    show f_54_part_2_qExpList.getD 8 0 = (0 : ℚ) from by decide +kernel,
    show f_54_part_3_qExpList.getD 8 0 = (1 : ℚ) from by decide +kernel]
  push_cast; ring

lemma lmfdb_1_54_a_orbit_qExpansion_coeff_9 :
    (PowerSeries.coeff (R := ℂ) 9)
      (qExpansion 1 (lmfdb_1_54_a_orbit : ℍ → ℂ)) = ((-(4320989704640367423481774095 / 4261))) + ((-(1618195165769997187665 / 4261))) * α_54 + (245402038444189 / 2181632) * α_54 ^ 2 + (2967693395 / 209436672) * α_54 ^ 3 := by
  rw [lmfdb_1_54_a_orbit_coeff_decomp,
    f_54_part_0_qExpansion_coeff 10 9 (by decide),
    f_54_part_1_qExpansion_coeff 10 9 (by decide),
    f_54_part_2_qExpansion_coeff 10 9 (by decide),
    f_54_part_3_qExpansion_coeff 10 9 (by decide),
    f_54_part_0_evalEisList_eq,
    f_54_part_1_evalEisList_eq,
    f_54_part_2_evalEisList_eq,
    f_54_part_3_evalEisList_eq,
    show f_54_part_0_qExpList.getD 9 0 = (((-(4320989704640367423481774095 / 4261))) : ℚ) from by decide +kernel,
    show f_54_part_1_qExpList.getD 9 0 = (((-(1618195165769997187665 / 4261))) : ℚ) from by decide +kernel,
    show f_54_part_2_qExpList.getD 9 0 = ((245402038444189 / 2181632) : ℚ) from by decide +kernel,
    show f_54_part_3_qExpList.getD 9 0 = ((2967693395 / 209436672) : ℚ) from by decide +kernel]
  push_cast; ring


/-! ## Uniqueness theorem -/


/-- **Uniqueness theorem.** Any level-1 weight-54 modular form `f` whose first 5
q-coefficients match the LMFDB-published values for `1.54.a.{a..}` is equal to our
explicit construction `lmfdb_1_54_a_orbit`. Proven via `ModularForm.eq_of_sturm_bound`. -/
theorem identifies_lmfdb_1_54_a_orbit (f : ModularForm 𝒮ℒ 54)
    (h_0 : (PowerSeries.coeff (R := ℂ) 0) (qExpansion 1 (f : ℍ → ℂ)) = 0)
    (h_1 : (PowerSeries.coeff (R := ℂ) 1) (qExpansion 1 (f : ℍ → ℂ)) = 1)
    (h_2 : (PowerSeries.coeff (R := ℂ) 2) (qExpansion 1 (f : ℍ → ℂ)) = 1 * α_54)
    (h_3 : (PowerSeries.coeff (R := ℂ) 3) (qExpansion 1 (f : ℍ → ℂ)) = (18684367827971740 / 29827) + ((-(14731126495 / 102264))) * α_54 + ((-(76465 / 1099542528))) * α_54 ^ 2 + (1 / 105556082688) * α_54 ^ 3)
    (h_4 : (PowerSeries.coeff (R := ℂ) 4) (qExpansion 1 (f : ℍ → ℂ)) = (-9007199254740992) + 1 * α_54 ^ 2) :
    f = lmfdb_1_54_a_orbit := by
  apply ModularForm.eq_of_sturm_bound
  intro i hi
  have : i ≤ 4 := by omega
  interval_cases i
  · rw [h_0, lmfdb_1_54_a_orbit_qExpansion_coeff_0]
  · rw [h_1, lmfdb_1_54_a_orbit_qExpansion_coeff_1]
  · rw [h_2, lmfdb_1_54_a_orbit_qExpansion_coeff_2]
  · rw [h_3, lmfdb_1_54_a_orbit_qExpansion_coeff_3]
  · rw [h_4, lmfdb_1_54_a_orbit_qExpansion_coeff_4]


end LeanBridge.QExpansion.LMFDB.W54