import LeanBridge.ForMathlib.QExpansion.IntEval

set_option maxHeartbeats 0
set_option maxRecDepth 4000

/-!
# LMFDB level-1 weight-64 form `1.64.a`, piece 2: integer q-coefficient certificate

Heavy `decide +kernel` over `ℤ` (denominators cleared by the scale `D = 1627202320583489939255996417310720`), isolated in its own
module so `lake` schedules it in parallel with the other pieces. Generated by
`scripts/lmfdb_qexp_to_e4e6_v3.sage`.
-/

namespace LeanBridge.QExpansion.LMFDB.W64

open LeanBridge.QExpansion

def f_64_part_2_polyDataZ : List (ℕ × ℕ × ℤ) :=
  [(1, 10, 4178421956782982333554), (4, 8, (-21801576202607228687795)), (7, 6, 44248627106642014808320), (10, 4, (-43720643672112495633730)), (13, 2, 21009601050812949925910), (16, 0, (-3914430239518222746259))]

def f_64_part_2_scale : ℤ := 1627202320583489939255996417310720

def f_64_part_2_qExpListZ : List ℤ :=
  [0, 0, 0, 6054786233805868593808555376640, 1627202320583489939255996417310720, (-64685050660527621678677285127755661312), (-7333932144515463655210831727646065295360), 1586744328935792940139966109091729537761280, 0, 9203905225832142000020226330225837187446865920]

/-- Integer-arithmetic certificate (the heavy kernel computation). -/
lemma f_64_part_2_evalEisListZ_eq :
    evalEisListZ f_64_part_2_polyDataZ 10 = f_64_part_2_qExpListZ := by
  decide +kernel

end LeanBridge.QExpansion.LMFDB.W64
