import LeanBridge.ForMathlib.QExpansion.IntEval

set_option maxHeartbeats 0
set_option maxRecDepth 4000

/-!
# LMFDB level-1 weight-12 form `1.12.a`, piece 0: integer q-coefficient certificate

Heavy `decide +kernel` over `ℤ` (denominators cleared by the scale `D = 1728`), isolated in its own
module so `lake` schedules it in parallel with the other pieces. Generated by
`scripts/lmfdb_qexp_to_e4e6_v3.sage`.
-/

namespace LeanBridge.QExpansion.LMFDB.W12

open LeanBridge.QExpansion

def f_12_part_0_polyDataZ : List (ℕ × ℕ × ℤ) :=
  [(0, 2, (-1)), (3, 0, 1)]

def f_12_part_0_scale : ℤ := 1728

def f_12_part_0_qExpListZ : List ℤ :=
  [0, 1728, (-41472), 435456, (-2543616), 8346240, (-10450944), (-28933632), 145981440, (-196375104)]

/-- Integer-arithmetic certificate (the heavy kernel computation). -/
lemma f_12_part_0_evalEisListZ_eq :
    evalEisListZ f_12_part_0_polyDataZ 10 = f_12_part_0_qExpListZ := by
  decide +kernel

end LeanBridge.QExpansion.LMFDB.W12
