import LeanBridge.ForMathlib.QExpansion.IntEval

set_option maxHeartbeats 0
set_option maxRecDepth 4000

/-!
# LMFDB level-1 weight-24 form `1.24.a`, piece 1: integer q-coefficient certificate

Heavy `decide +kernel` over `ℤ` (denominators cleared by the scale `D = 2985984`), isolated in its own
module so `lake` schedules it in parallel with the other pieces. Generated by
`scripts/lmfdb_qexp_to_e4e6_v3.sage`.
-/

namespace LeanBridge.QExpansion.LMFDB.W24

open LeanBridge.QExpansion

def f_24_part_1_polyDataZ : List (ℕ × ℕ × ℤ) :=
  [(0, 4, 1), (3, 2, (-2)), (6, 0, 1)]

def f_24_part_1_scale : ℤ := 2985984

def f_24_part_1_qExpListZ : List ℤ :=
  [0, 0, 2985984, (-143327232), 3224862720, (-44909199360), 429444218880, (-2943654690816), 14505671393280, (-48656728719360)]

/-- Integer-arithmetic certificate (the heavy kernel computation). -/
lemma f_24_part_1_evalEisListZ_eq :
    evalEisListZ f_24_part_1_polyDataZ 10 = f_24_part_1_qExpListZ := by
  decide +kernel

end LeanBridge.QExpansion.LMFDB.W24
