import LeanBridge.ForMathlib.QExpansion.IntEval

set_option maxHeartbeats 0
set_option maxRecDepth 4000

/-!
# LMFDB level-1 weight-86 form `1.86.a`, piece 5: integer q-coefficient certificate

Heavy `decide +kernel` over `ℤ` (denominators cleared by the scale `D = 50420528699092436251617399326581721262141850860533223058075733712665837568`), isolated in its own
module so `lake` schedules it in parallel with the other pieces. Generated by
`scripts/lmfdb_qexp_to_e4e6_v3.sage`.
-/

namespace LeanBridge.QExpansion.LMFDB.W86

open LeanBridge.QExpansion

def f_86_part_5_polyDataZ : List (ℕ × ℕ × ℤ) :=
  [(2, 13, (-147545337951926346475403)), (5, 11, 590755841271922731357114), (8, 9, (-740387777617671979477317)), (11, 7, 5076408898584587017804), (14, 5, 732719095569945999370395), (17, 3, (-587623486013013419818086)), (20, 1, 147005255842158428025493)]

def f_86_part_5_scale : ℤ := 50420528699092436251617399326581721262141850860533223058075733712665837568

def f_86_part_5_qExpListZ : List ℤ :=
  [0, 0, 0, (-913034013184045240003520888832), 0, 4538558777475438565895768121939603750912, (-1314021295289237624900471338276782027571200), 155563752944405633908043971484828624291364864, 0, (-161370081989159402934675158114907401850144895795200)]

/-- Integer-arithmetic certificate (the heavy kernel computation). -/
lemma f_86_part_5_evalEisListZ_eq :
    evalEisListZ f_86_part_5_polyDataZ 10 = f_86_part_5_qExpListZ := by
  decide +kernel

end LeanBridge.QExpansion.LMFDB.W86
