import LeanBridge.ForMathlib.QExpansion.IntEval

set_option maxHeartbeats 0
set_option maxRecDepth 4000

/-!
# LMFDB level-1 weight-34 form `1.34.a`, piece 1: integer q-coefficient certificate

Heavy `decide +kernel` over `ℤ` (denominators cleared by the scale `D = 2985984`), isolated in its own
module so `lake` schedules it in parallel with the other pieces. Generated by
`scripts/lmfdb_qexp_to_e4e6_v3.sage`.
-/

namespace LeanBridge.QExpansion.LMFDB.W34

open LeanBridge.QExpansion

def f_34_part_1_polyDataZ : List (ℕ × ℕ × ℤ) :=
  [(1, 5, 1), (4, 3, (-2)), (7, 1, 1)]

def f_34_part_1_scale : ℤ := 2985984

def f_34_part_1_qExpListZ : List ℤ :=
  [0, 0, 2985984, (-931627008), (-363334533120), 2997927936000, 113294264647680, (-2393549438386176), 18331533862502400, (-35327184348119040)]

/-- Integer-arithmetic certificate (the heavy kernel computation). -/
lemma f_34_part_1_evalEisListZ_eq :
    evalEisListZ f_34_part_1_polyDataZ 10 = f_34_part_1_qExpListZ := by
  decide +kernel

end LeanBridge.QExpansion.LMFDB.W34
