import LeanBridge.ForMathlib.QExpansion.IntEval

set_option maxHeartbeats 0
set_option maxRecDepth 4000

/-!
# LMFDB level-1 weight-18 form `1.18.a`, piece 0: integer q-coefficient certificate

Heavy `decide +kernel` over `ℤ` (denominators cleared by the scale `D = 1728`), isolated in its own
module so `lake` schedules it in parallel with the other pieces. Generated by
`scripts/lmfdb_qexp_to_e4e6_v3.sage`.
-/

namespace LeanBridge.QExpansion.LMFDB.W18

open LeanBridge.QExpansion

def f_18_part_0_polyDataZ : List (ℕ × ℕ × ℤ) :=
  [(0, 3, (-1)), (3, 1, 1)]

def f_18_part_0_scale : ℤ := 1728

def f_18_part_0_qExpListZ : List ℤ :=
  [0, 1728, (-912384), (-7402752), 255246336, (-1772668800), 3908653056, 5574514176, (-15182069760), (-191440812096)]

/-- Integer-arithmetic certificate (the heavy kernel computation). -/
lemma f_18_part_0_evalEisListZ_eq :
    evalEisListZ f_18_part_0_polyDataZ 10 = f_18_part_0_qExpListZ := by
  decide +kernel

end LeanBridge.QExpansion.LMFDB.W18
