import LeanBridge.ForMathlib.QExpansion.IntEval

set_option maxHeartbeats 0
set_option maxRecDepth 4000

/-!
# LMFDB level-1 weight-50 form `1.50.a`, piece 0: integer q-coefficient certificate

Heavy `decide +kernel` over `ℤ` (denominators cleared by the scale `D = 13436928`), isolated in its own
module so `lake` schedules it in parallel with the other pieces. Generated by
`scripts/lmfdb_qexp_to_e4e6_v3.sage`.
-/

namespace LeanBridge.QExpansion.LMFDB.W50

open LeanBridge.QExpansion

def f_50_part_0_polyDataZ : List (ℕ × ℕ × ℤ) :=
  [(2, 7, (-15270995581)), (5, 5, 45812980479), (8, 3, (-45812981991)), (11, 1, 15270997093)]

def f_50_part_0_scale : ℤ := 13436928

def f_50_part_0_qExpListZ : List ℤ :=
  [0, 13436928, 0, 78794979057882243072, (-7564317991725523009536), (-15161729922077068338647040), (-1908447335760663330208874496), 51839853487584064748773982208, 183210944233023679700051951616, (-22555965219043898635247653263360)]

/-- Integer-arithmetic certificate (the heavy kernel computation). -/
lemma f_50_part_0_evalEisListZ_eq :
    evalEisListZ f_50_part_0_polyDataZ 10 = f_50_part_0_qExpListZ := by
  decide +kernel

end LeanBridge.QExpansion.LMFDB.W50
