import LeanBridge.ForMathlib.QExpansion.IntEval

set_option maxHeartbeats 0
set_option maxRecDepth 4000

/-!
# LMFDB level-1 weight-72 form `1.72.a`, piece 5: integer q-coefficient certificate

Heavy `decide +kernel` over `ℤ` (denominators cleared by the scale `D = 5614849981617540004246644595567774076754644615065989493555200`), isolated in its own
module so `lake` schedules it in parallel with the other pieces. Generated by
`scripts/lmfdb_qexp_to_e4e6_v3.sage`.
-/

namespace LeanBridge.QExpansion.LMFDB.W72

open LeanBridge.QExpansion

def f_72_part_5_polyDataZ : List (ℕ × ℕ × ℤ) :=
  [(0, 12, (-189338610018025)), (3, 10, (-14322967272935012)), (6, 8, 74499944308725535), (9, 6, (-150946067096545920)), (12, 4, 151908287316905045), (15, 2, (-76227282554291260)), (18, 0, 15277423908159637)]

def f_72_part_5_scale : ℤ := 5614849981617540004246644595567774076754644615065989493555200

def f_72_part_5_qExpListZ : List ℤ :=
  [0, 0, 0, (-192280291382747411251200), 0, 238343696346359190527997395337216, 137961315409889437853132947193856000, 24534915600507700831916142987155865600, 0, (-133538754434000581695463403341266026496000)]

/-- Integer-arithmetic certificate (the heavy kernel computation). -/
lemma f_72_part_5_evalEisListZ_eq :
    evalEisListZ f_72_part_5_polyDataZ 10 = f_72_part_5_qExpListZ := by
  decide +kernel

end LeanBridge.QExpansion.LMFDB.W72
