import LeanBridge.ForMathlib.QExpansion.Generic
import LeanBridge.ForMathlib.QExpansion.Sturm
import Mathlib.Analysis.Complex.Polynomial.Basic

/-!
# LMFDB level-1 modular form orbit `1.48.a.{a..}` (Hecke field degree 4)

The Hecke field `K = ℚ(α)` is degree 4 over ℚ. The LMFDB lists q-coefficients as
elements of `K`, which we decompose as `c_0 + c_1 · α + … + c_{3} · α^3`.
The combined form is `f = f_0 + α · f_1 + … + α^3 · f_{3}`, with each
`f_j` a level-1 weight-48 form with rational coefficients in `(E₄, E₆)`.

The Sturm bound for weight 48 is `⌊48/12⌋ + 1 = 5`. After certifying agreement
on the first 5 q-coefficients, `ModularForm.eq_of_sturm_bound` lets us conclude that any
form with the same coefficients equals our explicit `lmfdb_1_48_a_orbit`.

Generated by `scripts/lmfdb_qexp_to_e4e6_v3.sage`.
-/

namespace LeanBridge.QExpansion.LMFDB.W48

open LeanBridge.QExpansion ModularForm EisensteinSeries PowerSeries UpperHalfPlane
open scoped MatrixGroups


/-- Minimal polynomial of α (degree 4) as `Polynomial ℂ`. -/
noncomputable def α_48_minpoly : Polynomial ℂ :=
  Polynomial.X ^ 4 +
    Polynomial.C 3297913828840214320807673856 +
    Polynomial.C 1426830562183253852160 * Polynomial.X +
    Polynomial.C (-467142374034432) * Polynomial.X ^ 2 +
    Polynomial.C (-5785560) * Polynomial.X ^ 3

lemma α_48_minpoly_natDegree : α_48_minpoly.natDegree = 4 := by
  unfold α_48_minpoly
  compute_degree!

lemma α_48_minpoly_degree_ne_zero : α_48_minpoly.degree ≠ 0 := by
  rw [Polynomial.degree_eq_natDegree (fun h => by
    have := α_48_minpoly_natDegree
    rw [h, Polynomial.natDegree_zero] at this
    exact absurd this (by decide))]
  rw [α_48_minpoly_natDegree]
  decide

/-- α is some root of the degree-4 minimal polynomial in ℂ. -/
noncomputable def α_48 : ℂ :=
  (IsAlgClosed.exists_root α_48_minpoly α_48_minpoly_degree_ne_zero).choose

lemma α_48_isRoot : Polynomial.IsRoot α_48_minpoly α_48 :=
  (IsAlgClosed.exists_root α_48_minpoly α_48_minpoly_degree_ne_zero).choose_spec

/-- Explicit polynomial relation: minpoly evaluated at α is zero. -/
lemma α_48_is_root :
    α_48 ^ 4 +
      3297913828840214320807673856 +
      1426830562183253852160 * α_48 +
      (-467142374034432) * α_48 ^ 2 +
      (-5785560) * α_48 ^ 3 = 0 := by
  have h := α_48_isRoot
  unfold Polynomial.IsRoot α_48_minpoly at h
  simp only [Polynomial.eval_add, Polynomial.eval_mul, Polynomial.eval_pow,
    Polynomial.eval_C, Polynomial.eval_X] at h
  linear_combination h


/-! ## Piece 0: coefficient of α^0 -/


def f_48_part_0_polyData : List (ℕ × ℕ × ℚ) :=
  [(0, 8, ((-(51698463068351 / 2593757085696)))), (3, 6, (44527066837111 / 648439271424)), (6, 4, ((-(461184936335 / 5336948736)))), (9, 2, (30184826832215 / 648439271424)), (12, 0, ((-(23013232550143 / 2593757085696))))]

noncomputable def f_48_part_0 : ModularForm 𝒮ℒ 48 :=
  (((-(51698463068351 / 2593757085696))) : ℂ) • mkMonomForm 0 8 48 (by decide) +
  ((44527066837111 / 648439271424) : ℂ) • mkMonomForm 3 6 48 (by decide) +
  (((-(461184936335 / 5336948736))) : ℂ) • mkMonomForm 6 4 48 (by decide) +
  ((30184826832215 / 648439271424) : ℂ) • mkMonomForm 9 2 48 (by decide) +
  (((-(23013232550143 / 2593757085696))) : ℂ) • mkMonomForm 12 0 48 (by decide)

lemma f_48_part_0_qExpansion_eq_evalEisPS :
    qExpansion 1 (f_48_part_0 : ℍ → ℂ) = evalEisPS f_48_part_0_polyData := by
  unfold f_48_part_0
  rw [ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm]
  unfold evalEisPS f_48_part_0_polyData monomialEisPS
  simp only [List.foldr_cons, List.foldr_nil, add_zero]
  push_cast
  module

theorem f_48_part_0_qExpansion_coeff (N n : ℕ) (hn : n < N) :
    (PowerSeries.coeff (R := ℂ) n) (qExpansion 1 (f_48_part_0 : ℍ → ℂ))
      = ((evalEisList f_48_part_0_polyData N).getD n 0 : ℚ) :=
  qexp_coeff_via_E4E6 _ _ f_48_part_0_qExpansion_eq_evalEisPS N n hn

/-- Precomputed first 10 q-coefficients of `f_48_part_0` (rational). -/
def f_48_part_0_qExpList : List ℚ :=
  [0, 1, 0, (458961863849380 / 8043), (-140737488355328), (65616225923827326366 / 2681), ((-(1242522752112952082432 / 2681))), ((-(2267109270676272440 / 383))), 0, (1340976751354492282550235 / 383)]

/-- One-shot bridge: the symbolic `evalEisList` equals the precomputed list (verified by
`decide +kernel` once instead of N times). -/
lemma f_48_part_0_evalEisList_eq :
    evalEisList f_48_part_0_polyData 10 = f_48_part_0_qExpList := by
  decide +kernel


/-! ## Piece 1: coefficient of α^1 -/


def f_48_part_1_polyData : List (ℕ × ℕ × ℚ) :=
  [(0, 8, (6894334813 / 1517718431858688)), (3, 6, ((-(6618942493 / 1138288823894016)))), (6, 4, ((-(7190979037 / 758859215929344)))), (9, 2, (6915586717 / 379429607964672)), (12, 0, ((-(34048400849 / 4553155295576064))))]

noncomputable def f_48_part_1 : ModularForm 𝒮ℒ 48 :=
  ((6894334813 / 1517718431858688) : ℂ) • mkMonomForm 0 8 48 (by decide) +
  (((-(6618942493 / 1138288823894016))) : ℂ) • mkMonomForm 3 6 48 (by decide) +
  (((-(7190979037 / 758859215929344))) : ℂ) • mkMonomForm 6 4 48 (by decide) +
  ((6915586717 / 379429607964672) : ℂ) • mkMonomForm 9 2 48 (by decide) +
  (((-(34048400849 / 4553155295576064))) : ℂ) • mkMonomForm 12 0 48 (by decide)

lemma f_48_part_1_qExpansion_eq_evalEisPS :
    qExpansion 1 (f_48_part_1 : ℍ → ℂ) = evalEisPS f_48_part_1_polyData := by
  unfold f_48_part_1
  rw [ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm]
  unfold evalEisPS f_48_part_1_polyData monomialEisPS
  simp only [List.foldr_cons, List.foldr_nil, add_zero]
  push_cast
  module

theorem f_48_part_1_qExpansion_coeff (N n : ℕ) (hn : n < N) :
    (PowerSeries.coeff (R := ℂ) n) (qExpansion 1 (f_48_part_1 : ℍ → ℂ))
      = ((evalEisList f_48_part_1_polyData N).getD n 0 : ℚ) :=
  qexp_coeff_via_E4E6 _ _ f_48_part_1_qExpansion_eq_evalEisPS N n hn

/-- Precomputed first 10 q-coefficients of `f_48_part_1` (rational). -/
def f_48_part_1_qExpList : List ℚ :=
  [0, 0, 1, ((-(6878487805 / 110304))), 0, ((-(36521357960821 / 3064))), ((-(164822448828740 / 1149))), (155441389884909327 / 6128), (-281474976710656), (6883778239715903065 / 1532)]

/-- One-shot bridge: the symbolic `evalEisList` equals the precomputed list (verified by
`decide +kernel` once instead of N times). -/
lemma f_48_part_1_evalEisList_eq :
    evalEisList f_48_part_1_polyData 10 = f_48_part_1_qExpList := by
  decide +kernel


/-! ## Piece 2: coefficient of α^2 -/


def f_48_part_2_polyData : List (ℕ × ℕ × ℚ) :=
  [(0, 8, (1734907 / 12238881434508460032)), (3, 6, ((-(1493417 / 3059720358627115008)))), (6, 4, (139103 / 226645952490897408)), (9, 2, ((-(1010437 / 3059720358627115008)))), (12, 0, (768947 / 12238881434508460032))]

noncomputable def f_48_part_2 : ModularForm 𝒮ℒ 48 :=
  ((1734907 / 12238881434508460032) : ℂ) • mkMonomForm 0 8 48 (by decide) +
  (((-(1493417 / 3059720358627115008))) : ℂ) • mkMonomForm 3 6 48 (by decide) +
  ((139103 / 226645952490897408) : ℂ) • mkMonomForm 6 4 48 (by decide) +
  (((-(1010437 / 3059720358627115008))) : ℂ) • mkMonomForm 9 2 48 (by decide) +
  ((768947 / 12238881434508460032) : ℂ) • mkMonomForm 12 0 48 (by decide)

lemma f_48_part_2_qExpansion_eq_evalEisPS :
    qExpansion 1 (f_48_part_2 : ℍ → ℂ) = evalEisPS f_48_part_2_polyData := by
  unfold f_48_part_2
  rw [ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm]
  unfold evalEisPS f_48_part_2_polyData monomialEisPS
  simp only [List.foldr_cons, List.foldr_nil, add_zero]
  push_cast
  module

theorem f_48_part_2_qExpansion_coeff (N n : ℕ) (hn : n < N) :
    (PowerSeries.coeff (R := ℂ) n) (qExpansion 1 (f_48_part_2 : ℍ → ℂ))
      = ((evalEisList f_48_part_2_polyData N).getD n 0 : ℚ) :=
  qexp_coeff_via_E4E6 _ _ f_48_part_2_qExpansion_eq_evalEisPS N n hn

/-- Precomputed first 10 q-coefficients of `f_48_part_2` (rational). -/
def f_48_part_2_qExpList : List ℚ :=
  [0, 0, 0, ((-(120745 / 296497152))), 1, ((-(478358379 / 2745344))), (79336781 / 24129), (542256295 / 784384), 0, ((-(13871641248509 / 588288)))]

/-- One-shot bridge: the symbolic `evalEisList` equals the precomputed list (verified by
`decide +kernel` once instead of N times). -/
lemma f_48_part_2_evalEisList_eq :
    evalEisList f_48_part_2_polyData 10 = f_48_part_2_qExpList := by
  decide +kernel


/-! ## Piece 3: coefficient of α^3 -/


def f_48_part_3_polyData : List (ℕ × ℕ × ℚ) :=
  [(0, 8, ((-(1 / 97911051476067680256)))), (3, 6, (1 / 73433288607050760192)), (6, 4, (1 / 48955525738033840128)), (9, 2, ((-(1 / 24477762869016920064)))), (12, 0, (5 / 293733154428203040768))]

noncomputable def f_48_part_3 : ModularForm 𝒮ℒ 48 :=
  (((-(1 / 97911051476067680256))) : ℂ) • mkMonomForm 0 8 48 (by decide) +
  ((1 / 73433288607050760192) : ℂ) • mkMonomForm 3 6 48 (by decide) +
  ((1 / 48955525738033840128) : ℂ) • mkMonomForm 6 4 48 (by decide) +
  (((-(1 / 24477762869016920064))) : ℂ) • mkMonomForm 9 2 48 (by decide) +
  ((5 / 293733154428203040768) : ℂ) • mkMonomForm 12 0 48 (by decide)

lemma f_48_part_3_qExpansion_eq_evalEisPS :
    qExpansion 1 (f_48_part_3 : ℍ → ℂ) = evalEisPS f_48_part_3_polyData := by
  unfold f_48_part_3
  rw [ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm]
  unfold evalEisPS f_48_part_3_polyData monomialEisPS
  simp only [List.foldr_cons, List.foldr_nil, add_zero]
  push_cast
  module

theorem f_48_part_3_qExpansion_coeff (N n : ℕ) (hn : n < N) :
    (PowerSeries.coeff (R := ℂ) n) (qExpansion 1 (f_48_part_3 : ℍ → ℂ))
      = ((evalEisList f_48_part_3_polyData N).getD n 0 : ℚ) :=
  qexp_coeff_via_E4E6 _ _ f_48_part_3_qExpansion_eq_evalEisPS N n hn

/-- Precomputed first 10 q-coefficients of `f_48_part_3` (rational). -/
def f_48_part_3_qExpList : List ℚ :=
  [0, 0, 0, (1 / 7115931648), 0, (593 / 21962752), (235 / 579096), ((-(291141 / 6275072))), 1, ((-(120269515 / 14118912)))]

/-- One-shot bridge: the symbolic `evalEisList` equals the precomputed list (verified by
`decide +kernel` once instead of N times). -/
lemma f_48_part_3_evalEisList_eq :
    evalEisList f_48_part_3_polyData 10 = f_48_part_3_qExpList := by
  decide +kernel


/-! ## Combined LMFDB form -/


noncomputable def lmfdb_1_48_a_orbit : ModularForm 𝒮ℒ 48 :=
  f_48_part_0 +
  α_48 • f_48_part_1 +
  α_48 ^ 2 • f_48_part_2 +
  α_48 ^ 3 • f_48_part_3

lemma lmfdb_1_48_a_orbit_coeff_decomp (n : ℕ) :
    (PowerSeries.coeff (R := ℂ) n) (qExpansion 1 (lmfdb_1_48_a_orbit : ℍ → ℂ))
      = (PowerSeries.coeff (R := ℂ) n) (qExpansion 1 (f_48_part_0 : ℍ → ℂ))
        + α_48 * (PowerSeries.coeff (R := ℂ) n) (qExpansion 1 (f_48_part_1 : ℍ → ℂ))
        + α_48 ^ 2 * (PowerSeries.coeff (R := ℂ) n) (qExpansion 1 (f_48_part_2 : ℍ → ℂ))
        + α_48 ^ 3 * (PowerSeries.coeff (R := ℂ) n) (qExpansion 1 (f_48_part_3 : ℍ → ℂ)) := by
  unfold lmfdb_1_48_a_orbit
  rw [ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL]
  simp [smul_eq_mul]


/-! ## Coefficient lemmas (n = 0, …, 9)

Sturm bound is 5; we certify 10 coefficients for added
redundancy beyond the minimum mathematically required for uniqueness. -/


lemma lmfdb_1_48_a_orbit_qExpansion_coeff_0 :
    (PowerSeries.coeff (R := ℂ) 0)
      (qExpansion 1 (lmfdb_1_48_a_orbit : ℍ → ℂ)) = 0 := by
  rw [lmfdb_1_48_a_orbit_coeff_decomp,
    f_48_part_0_qExpansion_coeff 10 0 (by decide),
    f_48_part_1_qExpansion_coeff 10 0 (by decide),
    f_48_part_2_qExpansion_coeff 10 0 (by decide),
    f_48_part_3_qExpansion_coeff 10 0 (by decide),
    f_48_part_0_evalEisList_eq,
    f_48_part_1_evalEisList_eq,
    f_48_part_2_evalEisList_eq,
    f_48_part_3_evalEisList_eq,
    show f_48_part_0_qExpList.getD 0 0 = (0 : ℚ) from by decide +kernel,
    show f_48_part_1_qExpList.getD 0 0 = (0 : ℚ) from by decide +kernel,
    show f_48_part_2_qExpList.getD 0 0 = (0 : ℚ) from by decide +kernel,
    show f_48_part_3_qExpList.getD 0 0 = (0 : ℚ) from by decide +kernel]
  push_cast; ring

lemma lmfdb_1_48_a_orbit_qExpansion_coeff_1 :
    (PowerSeries.coeff (R := ℂ) 1)
      (qExpansion 1 (lmfdb_1_48_a_orbit : ℍ → ℂ)) = 1 := by
  rw [lmfdb_1_48_a_orbit_coeff_decomp,
    f_48_part_0_qExpansion_coeff 10 1 (by decide),
    f_48_part_1_qExpansion_coeff 10 1 (by decide),
    f_48_part_2_qExpansion_coeff 10 1 (by decide),
    f_48_part_3_qExpansion_coeff 10 1 (by decide),
    f_48_part_0_evalEisList_eq,
    f_48_part_1_evalEisList_eq,
    f_48_part_2_evalEisList_eq,
    f_48_part_3_evalEisList_eq,
    show f_48_part_0_qExpList.getD 1 0 = (1 : ℚ) from by decide +kernel,
    show f_48_part_1_qExpList.getD 1 0 = (0 : ℚ) from by decide +kernel,
    show f_48_part_2_qExpList.getD 1 0 = (0 : ℚ) from by decide +kernel,
    show f_48_part_3_qExpList.getD 1 0 = (0 : ℚ) from by decide +kernel]
  push_cast; ring

lemma lmfdb_1_48_a_orbit_qExpansion_coeff_2 :
    (PowerSeries.coeff (R := ℂ) 2)
      (qExpansion 1 (lmfdb_1_48_a_orbit : ℍ → ℂ)) = 1 * α_48 := by
  rw [lmfdb_1_48_a_orbit_coeff_decomp,
    f_48_part_0_qExpansion_coeff 10 2 (by decide),
    f_48_part_1_qExpansion_coeff 10 2 (by decide),
    f_48_part_2_qExpansion_coeff 10 2 (by decide),
    f_48_part_3_qExpansion_coeff 10 2 (by decide),
    f_48_part_0_evalEisList_eq,
    f_48_part_1_evalEisList_eq,
    f_48_part_2_evalEisList_eq,
    f_48_part_3_evalEisList_eq,
    show f_48_part_0_qExpList.getD 2 0 = (0 : ℚ) from by decide +kernel,
    show f_48_part_1_qExpList.getD 2 0 = (1 : ℚ) from by decide +kernel,
    show f_48_part_2_qExpList.getD 2 0 = (0 : ℚ) from by decide +kernel,
    show f_48_part_3_qExpList.getD 2 0 = (0 : ℚ) from by decide +kernel]
  push_cast; ring

lemma lmfdb_1_48_a_orbit_qExpansion_coeff_3 :
    (PowerSeries.coeff (R := ℂ) 3)
      (qExpansion 1 (lmfdb_1_48_a_orbit : ℍ → ℂ)) = (458961863849380 / 8043) + ((-(6878487805 / 110304))) * α_48 + ((-(120745 / 296497152))) * α_48 ^ 2 + (1 / 7115931648) * α_48 ^ 3 := by
  rw [lmfdb_1_48_a_orbit_coeff_decomp,
    f_48_part_0_qExpansion_coeff 10 3 (by decide),
    f_48_part_1_qExpansion_coeff 10 3 (by decide),
    f_48_part_2_qExpansion_coeff 10 3 (by decide),
    f_48_part_3_qExpansion_coeff 10 3 (by decide),
    f_48_part_0_evalEisList_eq,
    f_48_part_1_evalEisList_eq,
    f_48_part_2_evalEisList_eq,
    f_48_part_3_evalEisList_eq,
    show f_48_part_0_qExpList.getD 3 0 = ((458961863849380 / 8043) : ℚ) from by decide +kernel,
    show f_48_part_1_qExpList.getD 3 0 = (((-(6878487805 / 110304))) : ℚ) from by decide +kernel,
    show f_48_part_2_qExpList.getD 3 0 = (((-(120745 / 296497152))) : ℚ) from by decide +kernel,
    show f_48_part_3_qExpList.getD 3 0 = ((1 / 7115931648) : ℚ) from by decide +kernel]
  push_cast; ring

lemma lmfdb_1_48_a_orbit_qExpansion_coeff_4 :
    (PowerSeries.coeff (R := ℂ) 4)
      (qExpansion 1 (lmfdb_1_48_a_orbit : ℍ → ℂ)) = (-140737488355328) + 1 * α_48 ^ 2 := by
  rw [lmfdb_1_48_a_orbit_coeff_decomp,
    f_48_part_0_qExpansion_coeff 10 4 (by decide),
    f_48_part_1_qExpansion_coeff 10 4 (by decide),
    f_48_part_2_qExpansion_coeff 10 4 (by decide),
    f_48_part_3_qExpansion_coeff 10 4 (by decide),
    f_48_part_0_evalEisList_eq,
    f_48_part_1_evalEisList_eq,
    f_48_part_2_evalEisList_eq,
    f_48_part_3_evalEisList_eq,
    show f_48_part_0_qExpList.getD 4 0 = ((-140737488355328) : ℚ) from by decide +kernel,
    show f_48_part_1_qExpList.getD 4 0 = (0 : ℚ) from by decide +kernel,
    show f_48_part_2_qExpList.getD 4 0 = (1 : ℚ) from by decide +kernel,
    show f_48_part_3_qExpList.getD 4 0 = (0 : ℚ) from by decide +kernel]
  push_cast; ring

lemma lmfdb_1_48_a_orbit_qExpansion_coeff_5 :
    (PowerSeries.coeff (R := ℂ) 5)
      (qExpansion 1 (lmfdb_1_48_a_orbit : ℍ → ℂ)) = (65616225923827326366 / 2681) + ((-(36521357960821 / 3064))) * α_48 + ((-(478358379 / 2745344))) * α_48 ^ 2 + (593 / 21962752) * α_48 ^ 3 := by
  rw [lmfdb_1_48_a_orbit_coeff_decomp,
    f_48_part_0_qExpansion_coeff 10 5 (by decide),
    f_48_part_1_qExpansion_coeff 10 5 (by decide),
    f_48_part_2_qExpansion_coeff 10 5 (by decide),
    f_48_part_3_qExpansion_coeff 10 5 (by decide),
    f_48_part_0_evalEisList_eq,
    f_48_part_1_evalEisList_eq,
    f_48_part_2_evalEisList_eq,
    f_48_part_3_evalEisList_eq,
    show f_48_part_0_qExpList.getD 5 0 = ((65616225923827326366 / 2681) : ℚ) from by decide +kernel,
    show f_48_part_1_qExpList.getD 5 0 = (((-(36521357960821 / 3064))) : ℚ) from by decide +kernel,
    show f_48_part_2_qExpList.getD 5 0 = (((-(478358379 / 2745344))) : ℚ) from by decide +kernel,
    show f_48_part_3_qExpList.getD 5 0 = ((593 / 21962752) : ℚ) from by decide +kernel]
  push_cast; ring

lemma lmfdb_1_48_a_orbit_qExpansion_coeff_6 :
    (PowerSeries.coeff (R := ℂ) 6)
      (qExpansion 1 (lmfdb_1_48_a_orbit : ℍ → ℂ)) = ((-(1242522752112952082432 / 2681))) + ((-(164822448828740 / 1149))) * α_48 + (79336781 / 24129) * α_48 ^ 2 + (235 / 579096) * α_48 ^ 3 := by
  rw [lmfdb_1_48_a_orbit_coeff_decomp,
    f_48_part_0_qExpansion_coeff 10 6 (by decide),
    f_48_part_1_qExpansion_coeff 10 6 (by decide),
    f_48_part_2_qExpansion_coeff 10 6 (by decide),
    f_48_part_3_qExpansion_coeff 10 6 (by decide),
    f_48_part_0_evalEisList_eq,
    f_48_part_1_evalEisList_eq,
    f_48_part_2_evalEisList_eq,
    f_48_part_3_evalEisList_eq,
    show f_48_part_0_qExpList.getD 6 0 = (((-(1242522752112952082432 / 2681))) : ℚ) from by decide +kernel,
    show f_48_part_1_qExpList.getD 6 0 = (((-(164822448828740 / 1149))) : ℚ) from by decide +kernel,
    show f_48_part_2_qExpList.getD 6 0 = ((79336781 / 24129) : ℚ) from by decide +kernel,
    show f_48_part_3_qExpList.getD 6 0 = ((235 / 579096) : ℚ) from by decide +kernel]
  push_cast; ring

lemma lmfdb_1_48_a_orbit_qExpansion_coeff_7 :
    (PowerSeries.coeff (R := ℂ) 7)
      (qExpansion 1 (lmfdb_1_48_a_orbit : ℍ → ℂ)) = ((-(2267109270676272440 / 383))) + (155441389884909327 / 6128) * α_48 + (542256295 / 784384) * α_48 ^ 2 + ((-(291141 / 6275072))) * α_48 ^ 3 := by
  rw [lmfdb_1_48_a_orbit_coeff_decomp,
    f_48_part_0_qExpansion_coeff 10 7 (by decide),
    f_48_part_1_qExpansion_coeff 10 7 (by decide),
    f_48_part_2_qExpansion_coeff 10 7 (by decide),
    f_48_part_3_qExpansion_coeff 10 7 (by decide),
    f_48_part_0_evalEisList_eq,
    f_48_part_1_evalEisList_eq,
    f_48_part_2_evalEisList_eq,
    f_48_part_3_evalEisList_eq,
    show f_48_part_0_qExpList.getD 7 0 = (((-(2267109270676272440 / 383))) : ℚ) from by decide +kernel,
    show f_48_part_1_qExpList.getD 7 0 = ((155441389884909327 / 6128) : ℚ) from by decide +kernel,
    show f_48_part_2_qExpList.getD 7 0 = ((542256295 / 784384) : ℚ) from by decide +kernel,
    show f_48_part_3_qExpList.getD 7 0 = (((-(291141 / 6275072))) : ℚ) from by decide +kernel]
  push_cast; ring

lemma lmfdb_1_48_a_orbit_qExpansion_coeff_8 :
    (PowerSeries.coeff (R := ℂ) 8)
      (qExpansion 1 (lmfdb_1_48_a_orbit : ℍ → ℂ)) = (-281474976710656) * α_48 + 1 * α_48 ^ 3 := by
  rw [lmfdb_1_48_a_orbit_coeff_decomp,
    f_48_part_0_qExpansion_coeff 10 8 (by decide),
    f_48_part_1_qExpansion_coeff 10 8 (by decide),
    f_48_part_2_qExpansion_coeff 10 8 (by decide),
    f_48_part_3_qExpansion_coeff 10 8 (by decide),
    f_48_part_0_evalEisList_eq,
    f_48_part_1_evalEisList_eq,
    f_48_part_2_evalEisList_eq,
    f_48_part_3_evalEisList_eq,
    show f_48_part_0_qExpList.getD 8 0 = (0 : ℚ) from by decide +kernel,
    show f_48_part_1_qExpList.getD 8 0 = ((-281474976710656) : ℚ) from by decide +kernel,
    show f_48_part_2_qExpList.getD 8 0 = (0 : ℚ) from by decide +kernel,
    show f_48_part_3_qExpList.getD 8 0 = (1 : ℚ) from by decide +kernel]
  push_cast; ring

lemma lmfdb_1_48_a_orbit_qExpansion_coeff_9 :
    (PowerSeries.coeff (R := ℂ) 9)
      (qExpansion 1 (lmfdb_1_48_a_orbit : ℍ → ℂ)) = (1340976751354492282550235 / 383) + (6883778239715903065 / 1532) * α_48 + ((-(13871641248509 / 588288))) * α_48 ^ 2 + ((-(120269515 / 14118912))) * α_48 ^ 3 := by
  rw [lmfdb_1_48_a_orbit_coeff_decomp,
    f_48_part_0_qExpansion_coeff 10 9 (by decide),
    f_48_part_1_qExpansion_coeff 10 9 (by decide),
    f_48_part_2_qExpansion_coeff 10 9 (by decide),
    f_48_part_3_qExpansion_coeff 10 9 (by decide),
    f_48_part_0_evalEisList_eq,
    f_48_part_1_evalEisList_eq,
    f_48_part_2_evalEisList_eq,
    f_48_part_3_evalEisList_eq,
    show f_48_part_0_qExpList.getD 9 0 = ((1340976751354492282550235 / 383) : ℚ) from by decide +kernel,
    show f_48_part_1_qExpList.getD 9 0 = ((6883778239715903065 / 1532) : ℚ) from by decide +kernel,
    show f_48_part_2_qExpList.getD 9 0 = (((-(13871641248509 / 588288))) : ℚ) from by decide +kernel,
    show f_48_part_3_qExpList.getD 9 0 = (((-(120269515 / 14118912))) : ℚ) from by decide +kernel]
  push_cast; ring


/-! ## Uniqueness theorem -/


/-- **Uniqueness theorem.** Any level-1 weight-48 modular form `f` whose first 5
q-coefficients match the LMFDB-published values for `1.48.a.{a..}` is equal to our
explicit construction `lmfdb_1_48_a_orbit`. Proven via `ModularForm.eq_of_sturm_bound`. -/
theorem identifies_lmfdb_1_48_a_orbit (f : ModularForm 𝒮ℒ 48)
    (h_0 : (PowerSeries.coeff (R := ℂ) 0) (qExpansion 1 (f : ℍ → ℂ)) = 0)
    (h_1 : (PowerSeries.coeff (R := ℂ) 1) (qExpansion 1 (f : ℍ → ℂ)) = 1)
    (h_2 : (PowerSeries.coeff (R := ℂ) 2) (qExpansion 1 (f : ℍ → ℂ)) = 1 * α_48)
    (h_3 : (PowerSeries.coeff (R := ℂ) 3) (qExpansion 1 (f : ℍ → ℂ)) = (458961863849380 / 8043) + ((-(6878487805 / 110304))) * α_48 + ((-(120745 / 296497152))) * α_48 ^ 2 + (1 / 7115931648) * α_48 ^ 3)
    (h_4 : (PowerSeries.coeff (R := ℂ) 4) (qExpansion 1 (f : ℍ → ℂ)) = (-140737488355328) + 1 * α_48 ^ 2) :
    f = lmfdb_1_48_a_orbit := by
  apply ModularForm.eq_of_sturm_bound
  intro i hi
  have : i ≤ 4 := by omega
  interval_cases i
  · rw [h_0, lmfdb_1_48_a_orbit_qExpansion_coeff_0]
  · rw [h_1, lmfdb_1_48_a_orbit_qExpansion_coeff_1]
  · rw [h_2, lmfdb_1_48_a_orbit_qExpansion_coeff_2]
  · rw [h_3, lmfdb_1_48_a_orbit_qExpansion_coeff_3]
  · rw [h_4, lmfdb_1_48_a_orbit_qExpansion_coeff_4]


end LeanBridge.QExpansion.LMFDB.W48