import LeanBridge.ForMathlib.QExpansion.IntEval

set_option maxHeartbeats 0
set_option maxRecDepth 4000

/-!
# LMFDB level-1 weight-20 form `1.20.a`, piece 0: integer q-coefficient certificate

Heavy `decide +kernel` over `ℤ` (denominators cleared by the scale `D = 1728`), isolated in its own
module so `lake` schedules it in parallel with the other pieces. Generated by
`scripts/lmfdb_qexp_to_e4e6_v3.sage`.
-/

namespace LeanBridge.QExpansion.LMFDB.W20

open LeanBridge.QExpansion

def f_20_part_0_polyDataZ : List (ℕ × ℕ × ℤ) :=
  [(2, 2, (-1)), (5, 0, 1)]

def f_20_part_0_scale : ℤ := 1728

def f_20_part_0_qExpListZ : List ℤ :=
  [0, 1728, 787968, 87526656, (-546656256), (-4108164480), 39912155136, (-29233516032), (-662397419520), 2425012364736]

/-- Integer-arithmetic certificate (the heavy kernel computation). -/
lemma f_20_part_0_evalEisListZ_eq :
    evalEisListZ f_20_part_0_polyDataZ 10 = f_20_part_0_qExpListZ := by
  decide +kernel

end LeanBridge.QExpansion.LMFDB.W20
