import LeanBridge.ForMathlib.QExpansion.Generic
import LeanBridge.ForMathlib.QExpansion.Sturm
import Mathlib.Analysis.Complex.Polynomial.Basic

/-!
# LMFDB level-1 modular form orbit `1.70.a.{a..}` (Hecke field degree 5)

The Hecke field `K = ℚ(α)` is degree 5 over ℚ. The LMFDB lists q-coefficients as
elements of `K`, which we decompose as `c_0 + c_1 · α + … + c_{4} · α^4`.
The combined form is `f = f_0 + α · f_1 + … + α^4 · f_{4}`, with each
`f_j` a level-1 weight-70 form with rational coefficients in `(E₄, E₆)`.

The Sturm bound for weight 70 is `⌊70/12⌋ + 1 = 6`. After certifying agreement
on the first 6 q-coefficients, `ModularForm.eq_of_sturm_bound` lets us conclude that any
form with the same coefficients equals our explicit `lmfdb_1_70_a_orbit`.

Generated by `scripts/lmfdb_qexp_to_e4e6_v3.sage`.
-/

namespace LeanBridge.QExpansion.LMFDB.W70

open LeanBridge.QExpansion ModularForm EisensteinSeries PowerSeries UpperHalfPlane
open scoped MatrixGroups


/-- Minimal polynomial of α (degree 5) as `Polynomial ℂ`. -/
noncomputable def α_70_minpoly : Polynomial ℂ :=
  Polynomial.X ^ 5 +
    Polynomial.C 4169744246282611427836654706819235757668276180615168 +
    Polynomial.C 613518461067953168654246762332094963122176 * Polynomial.X +
    Polynomial.C (-14539211744046993293953166475264) * Polynomial.X ^ 2 +
    Polynomial.C (-1942747456996431618048) * Polynomial.X ^ 3 +
    Polynomial.C 18005734368 * Polynomial.X ^ 4

lemma α_70_minpoly_natDegree : α_70_minpoly.natDegree = 5 := by
  unfold α_70_minpoly
  compute_degree!

lemma α_70_minpoly_degree_ne_zero : α_70_minpoly.degree ≠ 0 := by
  rw [Polynomial.degree_eq_natDegree (fun h => by
    have := α_70_minpoly_natDegree
    rw [h, Polynomial.natDegree_zero] at this
    exact absurd this (by decide))]
  rw [α_70_minpoly_natDegree]
  decide

/-- α is some root of the degree-5 minimal polynomial in ℂ. -/
noncomputable def α_70 : ℂ :=
  (IsAlgClosed.exists_root α_70_minpoly α_70_minpoly_degree_ne_zero).choose

lemma α_70_isRoot : Polynomial.IsRoot α_70_minpoly α_70 :=
  (IsAlgClosed.exists_root α_70_minpoly α_70_minpoly_degree_ne_zero).choose_spec

/-- Explicit polynomial relation: minpoly evaluated at α is zero. -/
lemma α_70_is_root :
    α_70 ^ 5 +
      4169744246282611427836654706819235757668276180615168 +
      613518461067953168654246762332094963122176 * α_70 +
      (-14539211744046993293953166475264) * α_70 ^ 2 +
      (-1942747456996431618048) * α_70 ^ 3 +
      18005734368 * α_70 ^ 4 = 0 := by
  have h := α_70_isRoot
  unfold Polynomial.IsRoot α_70_minpoly at h
  simp only [Polynomial.eval_add, Polynomial.eval_mul, Polynomial.eval_pow,
    Polynomial.eval_C, Polynomial.eval_X] at h
  linear_combination h


/-! ## Piece 0: coefficient of α^0 -/


def f_70_part_0_polyData : List (ℕ × ℕ × ℚ) :=
  [(1, 11, (1162295630045105008246473679043 / 12476581296690567684096)), (4, 9, ((-(6564833013876910963321779151517 / 12476581296690567684096)))), (7, 7, (2458351975633215418196053000997 / 2079430216115094614016)), (10, 5, ((-(8242146889299146097885974341861 / 6238290648345283842048)))), (13, 3, (187063385736196029229872170831 / 254624108095725871104)), (16, 1, ((-(1533927885444293114582615435 / 9430522522063921152))))]

noncomputable def f_70_part_0 : ModularForm 𝒮ℒ 70 :=
  ((1162295630045105008246473679043 / 12476581296690567684096) : ℂ) • mkMonomForm 1 11 70 (by decide) +
  (((-(6564833013876910963321779151517 / 12476581296690567684096))) : ℂ) • mkMonomForm 4 9 70 (by decide) +
  ((2458351975633215418196053000997 / 2079430216115094614016) : ℂ) • mkMonomForm 7 7 70 (by decide) +
  (((-(8242146889299146097885974341861 / 6238290648345283842048))) : ℂ) • mkMonomForm 10 5 70 (by decide) +
  ((187063385736196029229872170831 / 254624108095725871104) : ℂ) • mkMonomForm 13 3 70 (by decide) +
  (((-(1533927885444293114582615435 / 9430522522063921152))) : ℂ) • mkMonomForm 16 1 70 (by decide)

lemma f_70_part_0_qExpansion_eq_evalEisPS :
    qExpansion 1 (f_70_part_0 : ℍ → ℂ) = evalEisPS f_70_part_0_polyData := by
  unfold f_70_part_0
  rw [ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm]
  unfold evalEisPS f_70_part_0_polyData monomialEisPS
  simp only [List.foldr_cons, List.foldr_nil, add_zero]
  push_cast
  module

theorem f_70_part_0_qExpansion_coeff (N n : ℕ) (hn : n < N) :
    (PowerSeries.coeff (R := ℂ) n) (qExpansion 1 (f_70_part_0 : ℍ → ℂ))
      = ((evalEisList f_70_part_0_polyData N).getD n 0 : ℚ) :=
  qexp_coeff_via_E4E6 _ _ f_70_part_0_qExpansion_eq_evalEisPS N n hn

/-- Precomputed first 10 q-coefficients of `f_70_part_0` (rational). -/
def f_70_part_0_qExpList : List ℚ :=
  [0, 1, 0, ((-(3639555159914984669095597377588 / 77377441336111))), (-590295810358705651712), ((-(127071871750810341450610388676526998294 / 77377441336111))), (50968563098578220223155054395929063849984 / 77377441336111), (2302124489293101987177094862486780102026088 / 11053920190873), 0, (284764359222254648839830518090331615163262949 / 225590207977)]

/-- One-shot bridge: the symbolic `evalEisList` equals the precomputed list (verified by
`decide +kernel` once instead of N times). -/
lemma f_70_part_0_evalEisList_eq :
    evalEisList f_70_part_0_polyData 10 = f_70_part_0_qExpList := by
  decide +kernel


/-! ## Piece 1: coefficient of α^1 -/


def f_70_part_1_polyData : List (ℕ × ℕ × ℚ) :=
  [(1, 11, (7067106765281342141041498765 / 838924527888270782882283257856)), (4, 9, ((-(35442006769449679134695110633 / 838924527888270782882283257856)))), (7, 7, (11821749533413222904527279051 / 139820754648045130480380542976)), (10, 5, ((-(35405118841713190777698193193 / 419462263944135391441141628928)))), (13, 3, (719621979934831768630095889 / 17120908732413689446577209344)), (16, 1, ((-(15888518207916951340109693 / 1902323192490409938508578816))))]

noncomputable def f_70_part_1 : ModularForm 𝒮ℒ 70 :=
  ((7067106765281342141041498765 / 838924527888270782882283257856) : ℂ) • mkMonomForm 1 11 70 (by decide) +
  (((-(35442006769449679134695110633 / 838924527888270782882283257856))) : ℂ) • mkMonomForm 4 9 70 (by decide) +
  ((11821749533413222904527279051 / 139820754648045130480380542976) : ℂ) • mkMonomForm 7 7 70 (by decide) +
  (((-(35405118841713190777698193193 / 419462263944135391441141628928))) : ℂ) • mkMonomForm 10 5 70 (by decide) +
  ((719621979934831768630095889 / 17120908732413689446577209344) : ℂ) • mkMonomForm 13 3 70 (by decide) +
  (((-(15888518207916951340109693 / 1902323192490409938508578816))) : ℂ) • mkMonomForm 16 1 70 (by decide)

lemma f_70_part_1_qExpansion_eq_evalEisPS :
    qExpansion 1 (f_70_part_1 : ℍ → ℂ) = evalEisPS f_70_part_1_polyData := by
  unfold f_70_part_1
  rw [ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm]
  unfold evalEisPS f_70_part_1_polyData monomialEisPS
  simp only [List.foldr_cons, List.foldr_nil, add_zero]
  push_cast
  module

theorem f_70_part_1_qExpansion_coeff (N n : ℕ) (hn : n < N) :
    (PowerSeries.coeff (R := ℂ) n) (qExpansion 1 (f_70_part_1 : ℍ → ℂ))
      = ((evalEisList f_70_part_1_polyData N).getD n 0 : ℚ) :=
  qexp_coeff_via_E4E6 _ _ f_70_part_1_qExpansion_eq_evalEisPS N n hn

/-- Precomputed first 10 q-coefficients of `f_70_part_1` (rational). -/
def f_70_part_1_qExpList : List ℚ :=
  [0, 0, 1, (579037115750685222252515 / 564545811988265856), 0, ((-(6111684999315353694412410597245 / 47045484332355488))), (73335112633018635560993507825700 / 1470171385386109), (168674445024379139079867819029245047 / 13441566952101568), (-1180591620717411303424), (126064654223659907148150889207113225 / 3609443327632)]

/-- One-shot bridge: the symbolic `evalEisList` equals the precomputed list (verified by
`decide +kernel` once instead of N times). -/
lemma f_70_part_1_evalEisList_eq :
    evalEisList f_70_part_1_polyData 10 = f_70_part_1_qExpList := by
  decide +kernel


/-! ## Piece 2: coefficient of α^2 -/


def f_70_part_2_polyData : List (ℕ × ℕ × ℚ) :=
  [(1, 11, ((-(11466068567437700807177 / 61852227592146428280344980035207168)))), (4, 9, (62228902538461555674005 / 61852227592146428280344980035207168)), (7, 7, ((-(7635874675216394366117 / 3436234866230357126685832224178176)))), (10, 5, (76812251452646484899029 / 30926113796073214140172490017603584)), (13, 3, ((-(1765245727868538009917 / 1262290359023396495517244490514432)))), (16, 1, (133030258116575757899 / 420763453007798831839081496838144))]

noncomputable def f_70_part_2 : ModularForm 𝒮ℒ 70 :=
  (((-(11466068567437700807177 / 61852227592146428280344980035207168))) : ℂ) • mkMonomForm 1 11 70 (by decide) +
  ((62228902538461555674005 / 61852227592146428280344980035207168) : ℂ) • mkMonomForm 4 9 70 (by decide) +
  (((-(7635874675216394366117 / 3436234866230357126685832224178176))) : ℂ) • mkMonomForm 7 7 70 (by decide) +
  ((76812251452646484899029 / 30926113796073214140172490017603584) : ℂ) • mkMonomForm 10 5 70 (by decide) +
  (((-(1765245727868538009917 / 1262290359023396495517244490514432))) : ℂ) • mkMonomForm 13 3 70 (by decide) +
  ((133030258116575757899 / 420763453007798831839081496838144) : ℂ) • mkMonomForm 16 1 70 (by decide)

lemma f_70_part_2_qExpansion_eq_evalEisPS :
    qExpansion 1 (f_70_part_2 : ℍ → ℂ) = evalEisPS f_70_part_2_polyData := by
  unfold f_70_part_2
  rw [ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm]
  unfold evalEisPS f_70_part_2_polyData monomialEisPS
  simp only [List.foldr_cons, List.foldr_nil, add_zero]
  push_cast
  module

theorem f_70_part_2_qExpansion_coeff (N n : ℕ) (hn : n < N) :
    (PowerSeries.coeff (R := ℂ) n) (qExpansion 1 (f_70_part_2 : ℍ → ℂ))
      = ((evalEisList f_70_part_2_polyData N).getD n 0 : ℚ) :=
  qexp_coeff_via_E4E6 _ _ f_70_part_2_qExpansion_eq_evalEisPS N n hn

/-- Precomputed first 10 q-coefficients of `f_70_part_2` (rational). -/
def f_70_part_2_qExpList : List ℚ :=
  [0, 0, 0, (11079234980645430437 / 41622833626270865031168), 1, (1227353598924448747931037 / 385396607650656157696), ((-(59800052236851562352011 / 47045484332355488))), ((-(43492822534244592573343369303 / 110113316471616045056))), 0, ((-(101841160702768210481556748201 / 29568559739961344)))]

/-- One-shot bridge: the symbolic `evalEisList` equals the precomputed list (verified by
`decide +kernel` once instead of N times). -/
lemma f_70_part_2_evalEisList_eq :
    evalEisList f_70_part_2_polyData 10 = f_70_part_2_qExpList := by
  decide +kernel


/-! ## Piece 3: coefficient of α^3 -/


def f_70_part_3_polyData : List (ℕ × ℕ × ℚ) :=
  [(1, 11, ((-(978015292455695 / 142507532372305370757914834001117315072)))), (4, 9, (4937946840468899 / 142507532372305370757914834001117315072)), (7, 7, ((-(183272349793457 / 2639028377264914273294719148168839168)))), (10, 5, (4921296274141795 / 71253766186152685378957417000558657536)), (13, 3, ((-(99117863869883 / 2908316987189905525671731306145251328)))), (16, 1, (6469102871933 / 969438995729968508557243768715083776))]

noncomputable def f_70_part_3 : ModularForm 𝒮ℒ 70 :=
  (((-(978015292455695 / 142507532372305370757914834001117315072))) : ℂ) • mkMonomForm 1 11 70 (by decide) +
  ((4937946840468899 / 142507532372305370757914834001117315072) : ℂ) • mkMonomForm 4 9 70 (by decide) +
  (((-(183272349793457 / 2639028377264914273294719148168839168))) : ℂ) • mkMonomForm 7 7 70 (by decide) +
  ((4921296274141795 / 71253766186152685378957417000558657536) : ℂ) • mkMonomForm 10 5 70 (by decide) +
  (((-(99117863869883 / 2908316987189905525671731306145251328))) : ℂ) • mkMonomForm 13 3 70 (by decide) +
  ((6469102871933 / 969438995729968508557243768715083776) : ℂ) • mkMonomForm 16 1 70 (by decide)

lemma f_70_part_3_qExpansion_eq_evalEisPS :
    qExpansion 1 (f_70_part_3 : ℍ → ℂ) = evalEisPS f_70_part_3_polyData := by
  unfold f_70_part_3
  rw [ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm]
  unfold evalEisPS f_70_part_3_polyData monomialEisPS
  simp only [List.foldr_cons, List.foldr_nil, add_zero]
  push_cast
  module

theorem f_70_part_3_qExpansion_coeff (N n : ℕ) (hn : n < N) :
    (PowerSeries.coeff (R := ℂ) n) (qExpansion 1 (f_70_part_3 : ℍ → ℂ))
      = ((evalEisList f_70_part_3_polyData N).getD n 0 : ℚ) :=
  qexp_coeff_via_E4E6 _ _ f_70_part_3_qExpansion_eq_evalEisPS N n hn

/-- Precomputed first 10 q-coefficients of `f_70_part_3` (rational). -/
def f_70_part_3_qExpList : List ℚ :=
  [0, 0, 0, ((-(260165098861 / 95899008674928073031811072))), 0, (10463816539888835 / 98661531558567976370176), ((-(4413426658246525 / 108392795901747044352))), ((-(287872835320558173897 / 28189009016733707534336))), 1, ((-(1136063728673554766575 / 68125961640870936576)))]

/-- One-shot bridge: the symbolic `evalEisList` equals the precomputed list (verified by
`decide +kernel` once instead of N times). -/
lemma f_70_part_3_evalEisList_eq :
    evalEisList f_70_part_3_polyData 10 = f_70_part_3_qExpList := by
  decide +kernel


/-! ## Piece 4: coefficient of α^4 -/


def f_70_part_4_polyData : List (ℕ × ℕ × ℚ) :=
  [(1, 11, (958183 / 41042169323223946778279472192321786740736)), (4, 9, ((-(3988123 / 41042169323223946778279472192321786740736)))), (7, 7, (1271201 / 6840361553870657796379912032053631123456)), (10, 5, ((-(4267355 / 20521084661611973389139736096160893370368)))), (13, 3, (109171 / 837595292310692791393458616169832382464)), (16, 1, ((-(9605 / 279198430770230930464486205389944127488))))]

noncomputable def f_70_part_4 : ModularForm 𝒮ℒ 70 :=
  ((958183 / 41042169323223946778279472192321786740736) : ℂ) • mkMonomForm 1 11 70 (by decide) +
  (((-(3988123 / 41042169323223946778279472192321786740736))) : ℂ) • mkMonomForm 4 9 70 (by decide) +
  ((1271201 / 6840361553870657796379912032053631123456) : ℂ) • mkMonomForm 7 7 70 (by decide) +
  (((-(4267355 / 20521084661611973389139736096160893370368))) : ℂ) • mkMonomForm 10 5 70 (by decide) +
  ((109171 / 837595292310692791393458616169832382464) : ℂ) • mkMonomForm 13 3 70 (by decide) +
  (((-(9605 / 279198430770230930464486205389944127488))) : ℂ) • mkMonomForm 16 1 70 (by decide)

lemma f_70_part_4_qExpansion_eq_evalEisPS :
    qExpansion 1 (f_70_part_4 : ℍ → ℂ) = evalEisPS f_70_part_4_polyData := by
  unfold f_70_part_4
  rw [ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm]
  unfold evalEisPS f_70_part_4_polyData monomialEisPS
  simp only [List.foldr_cons, List.foldr_nil, add_zero]
  push_cast
  module

theorem f_70_part_4_qExpansion_coeff (N n : ℕ) (hn : n < N) :
    (PowerSeries.coeff (R := ℂ) n) (qExpansion 1 (f_70_part_4 : ℍ → ℂ))
      = ((evalEisList f_70_part_4_polyData N).getD n 0 : ℚ) :=
  qexp_coeff_via_E4E6 _ _ f_70_part_4_qExpansion_eq_evalEisPS N n hn

/-- Precomputed first 10 q-coefficients of `f_70_part_4` (rational). -/
def f_70_part_4_qExpList : List ℚ :=
  [0, 0, 0, ((-(4363 / 27618914498379285033161588736))), 0, ((-(1076643 / 3157169009874175243845632))), (4104581 / 31217125219703148773376), (32221413737 / 902048288535478641098752), 0, (21701298134471 / 19620276952570829733888)]

/-- One-shot bridge: the symbolic `evalEisList` equals the precomputed list (verified by
`decide +kernel` once instead of N times). -/
lemma f_70_part_4_evalEisList_eq :
    evalEisList f_70_part_4_polyData 10 = f_70_part_4_qExpList := by
  decide +kernel


/-! ## Combined LMFDB form -/


noncomputable def lmfdb_1_70_a_orbit : ModularForm 𝒮ℒ 70 :=
  f_70_part_0 +
  α_70 • f_70_part_1 +
  α_70 ^ 2 • f_70_part_2 +
  α_70 ^ 3 • f_70_part_3 +
  α_70 ^ 4 • f_70_part_4

lemma lmfdb_1_70_a_orbit_coeff_decomp (n : ℕ) :
    (PowerSeries.coeff (R := ℂ) n) (qExpansion 1 (lmfdb_1_70_a_orbit : ℍ → ℂ))
      = (PowerSeries.coeff (R := ℂ) n) (qExpansion 1 (f_70_part_0 : ℍ → ℂ))
        + α_70 * (PowerSeries.coeff (R := ℂ) n) (qExpansion 1 (f_70_part_1 : ℍ → ℂ))
        + α_70 ^ 2 * (PowerSeries.coeff (R := ℂ) n) (qExpansion 1 (f_70_part_2 : ℍ → ℂ))
        + α_70 ^ 3 * (PowerSeries.coeff (R := ℂ) n) (qExpansion 1 (f_70_part_3 : ℍ → ℂ))
        + α_70 ^ 4 * (PowerSeries.coeff (R := ℂ) n) (qExpansion 1 (f_70_part_4 : ℍ → ℂ)) := by
  unfold lmfdb_1_70_a_orbit
  rw [ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL]
  simp [smul_eq_mul]


/-! ## Coefficient lemmas (n = 0, …, 9)

Sturm bound is 6; we certify 10 coefficients for added
redundancy beyond the minimum mathematically required for uniqueness. -/


lemma lmfdb_1_70_a_orbit_qExpansion_coeff_0 :
    (PowerSeries.coeff (R := ℂ) 0)
      (qExpansion 1 (lmfdb_1_70_a_orbit : ℍ → ℂ)) = 0 := by
  rw [lmfdb_1_70_a_orbit_coeff_decomp,
    f_70_part_0_qExpansion_coeff 10 0 (by decide),
    f_70_part_1_qExpansion_coeff 10 0 (by decide),
    f_70_part_2_qExpansion_coeff 10 0 (by decide),
    f_70_part_3_qExpansion_coeff 10 0 (by decide),
    f_70_part_4_qExpansion_coeff 10 0 (by decide),
    f_70_part_0_evalEisList_eq,
    f_70_part_1_evalEisList_eq,
    f_70_part_2_evalEisList_eq,
    f_70_part_3_evalEisList_eq,
    f_70_part_4_evalEisList_eq,
    show f_70_part_0_qExpList.getD 0 0 = (0 : ℚ) from by decide +kernel,
    show f_70_part_1_qExpList.getD 0 0 = (0 : ℚ) from by decide +kernel,
    show f_70_part_2_qExpList.getD 0 0 = (0 : ℚ) from by decide +kernel,
    show f_70_part_3_qExpList.getD 0 0 = (0 : ℚ) from by decide +kernel,
    show f_70_part_4_qExpList.getD 0 0 = (0 : ℚ) from by decide +kernel]
  push_cast; ring

lemma lmfdb_1_70_a_orbit_qExpansion_coeff_1 :
    (PowerSeries.coeff (R := ℂ) 1)
      (qExpansion 1 (lmfdb_1_70_a_orbit : ℍ → ℂ)) = 1 := by
  rw [lmfdb_1_70_a_orbit_coeff_decomp,
    f_70_part_0_qExpansion_coeff 10 1 (by decide),
    f_70_part_1_qExpansion_coeff 10 1 (by decide),
    f_70_part_2_qExpansion_coeff 10 1 (by decide),
    f_70_part_3_qExpansion_coeff 10 1 (by decide),
    f_70_part_4_qExpansion_coeff 10 1 (by decide),
    f_70_part_0_evalEisList_eq,
    f_70_part_1_evalEisList_eq,
    f_70_part_2_evalEisList_eq,
    f_70_part_3_evalEisList_eq,
    f_70_part_4_evalEisList_eq,
    show f_70_part_0_qExpList.getD 1 0 = (1 : ℚ) from by decide +kernel,
    show f_70_part_1_qExpList.getD 1 0 = (0 : ℚ) from by decide +kernel,
    show f_70_part_2_qExpList.getD 1 0 = (0 : ℚ) from by decide +kernel,
    show f_70_part_3_qExpList.getD 1 0 = (0 : ℚ) from by decide +kernel,
    show f_70_part_4_qExpList.getD 1 0 = (0 : ℚ) from by decide +kernel]
  push_cast; ring

lemma lmfdb_1_70_a_orbit_qExpansion_coeff_2 :
    (PowerSeries.coeff (R := ℂ) 2)
      (qExpansion 1 (lmfdb_1_70_a_orbit : ℍ → ℂ)) = 1 * α_70 := by
  rw [lmfdb_1_70_a_orbit_coeff_decomp,
    f_70_part_0_qExpansion_coeff 10 2 (by decide),
    f_70_part_1_qExpansion_coeff 10 2 (by decide),
    f_70_part_2_qExpansion_coeff 10 2 (by decide),
    f_70_part_3_qExpansion_coeff 10 2 (by decide),
    f_70_part_4_qExpansion_coeff 10 2 (by decide),
    f_70_part_0_evalEisList_eq,
    f_70_part_1_evalEisList_eq,
    f_70_part_2_evalEisList_eq,
    f_70_part_3_evalEisList_eq,
    f_70_part_4_evalEisList_eq,
    show f_70_part_0_qExpList.getD 2 0 = (0 : ℚ) from by decide +kernel,
    show f_70_part_1_qExpList.getD 2 0 = (1 : ℚ) from by decide +kernel,
    show f_70_part_2_qExpList.getD 2 0 = (0 : ℚ) from by decide +kernel,
    show f_70_part_3_qExpList.getD 2 0 = (0 : ℚ) from by decide +kernel,
    show f_70_part_4_qExpList.getD 2 0 = (0 : ℚ) from by decide +kernel]
  push_cast; ring

lemma lmfdb_1_70_a_orbit_qExpansion_coeff_3 :
    (PowerSeries.coeff (R := ℂ) 3)
      (qExpansion 1 (lmfdb_1_70_a_orbit : ℍ → ℂ)) = ((-(3639555159914984669095597377588 / 77377441336111))) + (579037115750685222252515 / 564545811988265856) * α_70 + (11079234980645430437 / 41622833626270865031168) * α_70 ^ 2 + ((-(260165098861 / 95899008674928073031811072))) * α_70 ^ 3 + ((-(4363 / 27618914498379285033161588736))) * α_70 ^ 4 := by
  rw [lmfdb_1_70_a_orbit_coeff_decomp,
    f_70_part_0_qExpansion_coeff 10 3 (by decide),
    f_70_part_1_qExpansion_coeff 10 3 (by decide),
    f_70_part_2_qExpansion_coeff 10 3 (by decide),
    f_70_part_3_qExpansion_coeff 10 3 (by decide),
    f_70_part_4_qExpansion_coeff 10 3 (by decide),
    f_70_part_0_evalEisList_eq,
    f_70_part_1_evalEisList_eq,
    f_70_part_2_evalEisList_eq,
    f_70_part_3_evalEisList_eq,
    f_70_part_4_evalEisList_eq,
    show f_70_part_0_qExpList.getD 3 0 = (((-(3639555159914984669095597377588 / 77377441336111))) : ℚ) from by decide +kernel,
    show f_70_part_1_qExpList.getD 3 0 = ((579037115750685222252515 / 564545811988265856) : ℚ) from by decide +kernel,
    show f_70_part_2_qExpList.getD 3 0 = ((11079234980645430437 / 41622833626270865031168) : ℚ) from by decide +kernel,
    show f_70_part_3_qExpList.getD 3 0 = (((-(260165098861 / 95899008674928073031811072))) : ℚ) from by decide +kernel,
    show f_70_part_4_qExpList.getD 3 0 = (((-(4363 / 27618914498379285033161588736))) : ℚ) from by decide +kernel]
  push_cast; ring

lemma lmfdb_1_70_a_orbit_qExpansion_coeff_4 :
    (PowerSeries.coeff (R := ℂ) 4)
      (qExpansion 1 (lmfdb_1_70_a_orbit : ℍ → ℂ)) = (-590295810358705651712) + 1 * α_70 ^ 2 := by
  rw [lmfdb_1_70_a_orbit_coeff_decomp,
    f_70_part_0_qExpansion_coeff 10 4 (by decide),
    f_70_part_1_qExpansion_coeff 10 4 (by decide),
    f_70_part_2_qExpansion_coeff 10 4 (by decide),
    f_70_part_3_qExpansion_coeff 10 4 (by decide),
    f_70_part_4_qExpansion_coeff 10 4 (by decide),
    f_70_part_0_evalEisList_eq,
    f_70_part_1_evalEisList_eq,
    f_70_part_2_evalEisList_eq,
    f_70_part_3_evalEisList_eq,
    f_70_part_4_evalEisList_eq,
    show f_70_part_0_qExpList.getD 4 0 = ((-590295810358705651712) : ℚ) from by decide +kernel,
    show f_70_part_1_qExpList.getD 4 0 = (0 : ℚ) from by decide +kernel,
    show f_70_part_2_qExpList.getD 4 0 = (1 : ℚ) from by decide +kernel,
    show f_70_part_3_qExpList.getD 4 0 = (0 : ℚ) from by decide +kernel,
    show f_70_part_4_qExpList.getD 4 0 = (0 : ℚ) from by decide +kernel]
  push_cast; ring

lemma lmfdb_1_70_a_orbit_qExpansion_coeff_5 :
    (PowerSeries.coeff (R := ℂ) 5)
      (qExpansion 1 (lmfdb_1_70_a_orbit : ℍ → ℂ)) = ((-(127071871750810341450610388676526998294 / 77377441336111))) + ((-(6111684999315353694412410597245 / 47045484332355488))) * α_70 + (1227353598924448747931037 / 385396607650656157696) * α_70 ^ 2 + (10463816539888835 / 98661531558567976370176) * α_70 ^ 3 + ((-(1076643 / 3157169009874175243845632))) * α_70 ^ 4 := by
  rw [lmfdb_1_70_a_orbit_coeff_decomp,
    f_70_part_0_qExpansion_coeff 10 5 (by decide),
    f_70_part_1_qExpansion_coeff 10 5 (by decide),
    f_70_part_2_qExpansion_coeff 10 5 (by decide),
    f_70_part_3_qExpansion_coeff 10 5 (by decide),
    f_70_part_4_qExpansion_coeff 10 5 (by decide),
    f_70_part_0_evalEisList_eq,
    f_70_part_1_evalEisList_eq,
    f_70_part_2_evalEisList_eq,
    f_70_part_3_evalEisList_eq,
    f_70_part_4_evalEisList_eq,
    show f_70_part_0_qExpList.getD 5 0 = (((-(127071871750810341450610388676526998294 / 77377441336111))) : ℚ) from by decide +kernel,
    show f_70_part_1_qExpList.getD 5 0 = (((-(6111684999315353694412410597245 / 47045484332355488))) : ℚ) from by decide +kernel,
    show f_70_part_2_qExpList.getD 5 0 = ((1227353598924448747931037 / 385396607650656157696) : ℚ) from by decide +kernel,
    show f_70_part_3_qExpList.getD 5 0 = ((10463816539888835 / 98661531558567976370176) : ℚ) from by decide +kernel,
    show f_70_part_4_qExpList.getD 5 0 = (((-(1076643 / 3157169009874175243845632))) : ℚ) from by decide +kernel]
  push_cast; ring

lemma lmfdb_1_70_a_orbit_qExpansion_coeff_6 :
    (PowerSeries.coeff (R := ℂ) 6)
      (qExpansion 1 (lmfdb_1_70_a_orbit : ℍ → ℂ)) = (50968563098578220223155054395929063849984 / 77377441336111) + (73335112633018635560993507825700 / 1470171385386109) * α_70 + ((-(59800052236851562352011 / 47045484332355488))) * α_70 ^ 2 + ((-(4413426658246525 / 108392795901747044352))) * α_70 ^ 3 + (4104581 / 31217125219703148773376) * α_70 ^ 4 := by
  rw [lmfdb_1_70_a_orbit_coeff_decomp,
    f_70_part_0_qExpansion_coeff 10 6 (by decide),
    f_70_part_1_qExpansion_coeff 10 6 (by decide),
    f_70_part_2_qExpansion_coeff 10 6 (by decide),
    f_70_part_3_qExpansion_coeff 10 6 (by decide),
    f_70_part_4_qExpansion_coeff 10 6 (by decide),
    f_70_part_0_evalEisList_eq,
    f_70_part_1_evalEisList_eq,
    f_70_part_2_evalEisList_eq,
    f_70_part_3_evalEisList_eq,
    f_70_part_4_evalEisList_eq,
    show f_70_part_0_qExpList.getD 6 0 = ((50968563098578220223155054395929063849984 / 77377441336111) : ℚ) from by decide +kernel,
    show f_70_part_1_qExpList.getD 6 0 = ((73335112633018635560993507825700 / 1470171385386109) : ℚ) from by decide +kernel,
    show f_70_part_2_qExpList.getD 6 0 = (((-(59800052236851562352011 / 47045484332355488))) : ℚ) from by decide +kernel,
    show f_70_part_3_qExpList.getD 6 0 = (((-(4413426658246525 / 108392795901747044352))) : ℚ) from by decide +kernel,
    show f_70_part_4_qExpList.getD 6 0 = ((4104581 / 31217125219703148773376) : ℚ) from by decide +kernel]
  push_cast; ring

lemma lmfdb_1_70_a_orbit_qExpansion_coeff_7 :
    (PowerSeries.coeff (R := ℂ) 7)
      (qExpansion 1 (lmfdb_1_70_a_orbit : ℍ → ℂ)) = (2302124489293101987177094862486780102026088 / 11053920190873) + (168674445024379139079867819029245047 / 13441566952101568) * α_70 + ((-(43492822534244592573343369303 / 110113316471616045056))) * α_70 ^ 2 + ((-(287872835320558173897 / 28189009016733707534336))) * α_70 ^ 3 + (32221413737 / 902048288535478641098752) * α_70 ^ 4 := by
  rw [lmfdb_1_70_a_orbit_coeff_decomp,
    f_70_part_0_qExpansion_coeff 10 7 (by decide),
    f_70_part_1_qExpansion_coeff 10 7 (by decide),
    f_70_part_2_qExpansion_coeff 10 7 (by decide),
    f_70_part_3_qExpansion_coeff 10 7 (by decide),
    f_70_part_4_qExpansion_coeff 10 7 (by decide),
    f_70_part_0_evalEisList_eq,
    f_70_part_1_evalEisList_eq,
    f_70_part_2_evalEisList_eq,
    f_70_part_3_evalEisList_eq,
    f_70_part_4_evalEisList_eq,
    show f_70_part_0_qExpList.getD 7 0 = ((2302124489293101987177094862486780102026088 / 11053920190873) : ℚ) from by decide +kernel,
    show f_70_part_1_qExpList.getD 7 0 = ((168674445024379139079867819029245047 / 13441566952101568) : ℚ) from by decide +kernel,
    show f_70_part_2_qExpList.getD 7 0 = (((-(43492822534244592573343369303 / 110113316471616045056))) : ℚ) from by decide +kernel,
    show f_70_part_3_qExpList.getD 7 0 = (((-(287872835320558173897 / 28189009016733707534336))) : ℚ) from by decide +kernel,
    show f_70_part_4_qExpList.getD 7 0 = ((32221413737 / 902048288535478641098752) : ℚ) from by decide +kernel]
  push_cast; ring

lemma lmfdb_1_70_a_orbit_qExpansion_coeff_8 :
    (PowerSeries.coeff (R := ℂ) 8)
      (qExpansion 1 (lmfdb_1_70_a_orbit : ℍ → ℂ)) = (-1180591620717411303424) * α_70 + 1 * α_70 ^ 3 := by
  rw [lmfdb_1_70_a_orbit_coeff_decomp,
    f_70_part_0_qExpansion_coeff 10 8 (by decide),
    f_70_part_1_qExpansion_coeff 10 8 (by decide),
    f_70_part_2_qExpansion_coeff 10 8 (by decide),
    f_70_part_3_qExpansion_coeff 10 8 (by decide),
    f_70_part_4_qExpansion_coeff 10 8 (by decide),
    f_70_part_0_evalEisList_eq,
    f_70_part_1_evalEisList_eq,
    f_70_part_2_evalEisList_eq,
    f_70_part_3_evalEisList_eq,
    f_70_part_4_evalEisList_eq,
    show f_70_part_0_qExpList.getD 8 0 = (0 : ℚ) from by decide +kernel,
    show f_70_part_1_qExpList.getD 8 0 = ((-1180591620717411303424) : ℚ) from by decide +kernel,
    show f_70_part_2_qExpList.getD 8 0 = (0 : ℚ) from by decide +kernel,
    show f_70_part_3_qExpList.getD 8 0 = (1 : ℚ) from by decide +kernel,
    show f_70_part_4_qExpList.getD 8 0 = (0 : ℚ) from by decide +kernel]
  push_cast; ring

lemma lmfdb_1_70_a_orbit_qExpansion_coeff_9 :
    (PowerSeries.coeff (R := ℂ) 9)
      (qExpansion 1 (lmfdb_1_70_a_orbit : ℍ → ℂ)) = (284764359222254648839830518090331615163262949 / 225590207977) + (126064654223659907148150889207113225 / 3609443327632) * α_70 + ((-(101841160702768210481556748201 / 29568559739961344))) * α_70 ^ 2 + ((-(1136063728673554766575 / 68125961640870936576))) * α_70 ^ 3 + (21701298134471 / 19620276952570829733888) * α_70 ^ 4 := by
  rw [lmfdb_1_70_a_orbit_coeff_decomp,
    f_70_part_0_qExpansion_coeff 10 9 (by decide),
    f_70_part_1_qExpansion_coeff 10 9 (by decide),
    f_70_part_2_qExpansion_coeff 10 9 (by decide),
    f_70_part_3_qExpansion_coeff 10 9 (by decide),
    f_70_part_4_qExpansion_coeff 10 9 (by decide),
    f_70_part_0_evalEisList_eq,
    f_70_part_1_evalEisList_eq,
    f_70_part_2_evalEisList_eq,
    f_70_part_3_evalEisList_eq,
    f_70_part_4_evalEisList_eq,
    show f_70_part_0_qExpList.getD 9 0 = ((284764359222254648839830518090331615163262949 / 225590207977) : ℚ) from by decide +kernel,
    show f_70_part_1_qExpList.getD 9 0 = ((126064654223659907148150889207113225 / 3609443327632) : ℚ) from by decide +kernel,
    show f_70_part_2_qExpList.getD 9 0 = (((-(101841160702768210481556748201 / 29568559739961344))) : ℚ) from by decide +kernel,
    show f_70_part_3_qExpList.getD 9 0 = (((-(1136063728673554766575 / 68125961640870936576))) : ℚ) from by decide +kernel,
    show f_70_part_4_qExpList.getD 9 0 = ((21701298134471 / 19620276952570829733888) : ℚ) from by decide +kernel]
  push_cast; ring


/-! ## Uniqueness theorem -/


/-- **Uniqueness theorem.** Any level-1 weight-70 modular form `f` whose first 6
q-coefficients match the LMFDB-published values for `1.70.a.{a..}` is equal to our
explicit construction `lmfdb_1_70_a_orbit`. Proven via `ModularForm.eq_of_sturm_bound`. -/
theorem identifies_lmfdb_1_70_a_orbit (f : ModularForm 𝒮ℒ 70)
    (h_0 : (PowerSeries.coeff (R := ℂ) 0) (qExpansion 1 (f : ℍ → ℂ)) = 0)
    (h_1 : (PowerSeries.coeff (R := ℂ) 1) (qExpansion 1 (f : ℍ → ℂ)) = 1)
    (h_2 : (PowerSeries.coeff (R := ℂ) 2) (qExpansion 1 (f : ℍ → ℂ)) = 1 * α_70)
    (h_3 : (PowerSeries.coeff (R := ℂ) 3) (qExpansion 1 (f : ℍ → ℂ)) = ((-(3639555159914984669095597377588 / 77377441336111))) + (579037115750685222252515 / 564545811988265856) * α_70 + (11079234980645430437 / 41622833626270865031168) * α_70 ^ 2 + ((-(260165098861 / 95899008674928073031811072))) * α_70 ^ 3 + ((-(4363 / 27618914498379285033161588736))) * α_70 ^ 4)
    (h_4 : (PowerSeries.coeff (R := ℂ) 4) (qExpansion 1 (f : ℍ → ℂ)) = (-590295810358705651712) + 1 * α_70 ^ 2)
    (h_5 : (PowerSeries.coeff (R := ℂ) 5) (qExpansion 1 (f : ℍ → ℂ)) = ((-(127071871750810341450610388676526998294 / 77377441336111))) + ((-(6111684999315353694412410597245 / 47045484332355488))) * α_70 + (1227353598924448747931037 / 385396607650656157696) * α_70 ^ 2 + (10463816539888835 / 98661531558567976370176) * α_70 ^ 3 + ((-(1076643 / 3157169009874175243845632))) * α_70 ^ 4) :
    f = lmfdb_1_70_a_orbit := by
  apply ModularForm.eq_of_sturm_bound
  intro i hi
  have : i ≤ 5 := by omega
  interval_cases i
  · rw [h_0, lmfdb_1_70_a_orbit_qExpansion_coeff_0]
  · rw [h_1, lmfdb_1_70_a_orbit_qExpansion_coeff_1]
  · rw [h_2, lmfdb_1_70_a_orbit_qExpansion_coeff_2]
  · rw [h_3, lmfdb_1_70_a_orbit_qExpansion_coeff_3]
  · rw [h_4, lmfdb_1_70_a_orbit_qExpansion_coeff_4]
  · rw [h_5, lmfdb_1_70_a_orbit_qExpansion_coeff_5]


end LeanBridge.QExpansion.LMFDB.W70