import LeanBridge.ForMathlib.QExpansion.IntEval

set_option maxHeartbeats 0
set_option maxRecDepth 4000

/-!
# LMFDB level-1 weight-76 form `1.76.a`, piece 5: integer q-coefficient certificate

Heavy `decide +kernel` over `ℤ` (denominators cleared by the scale `D = 110520676584407682938277142177949777786329440526497460038496419840`), isolated in its own
module so `lake` schedules it in parallel with the other pieces. Generated by
`scripts/lmfdb_qexp_to_e4e6_v3.sage`.
-/

namespace LeanBridge.QExpansion.LMFDB.W76

open LeanBridge.QExpansion

def f_76_part_5_polyDataZ : List (ℕ × ℕ × ℤ) :=
  [(1, 12, (-2397797082653691755)), (4, 10, 17992708766989211874), (7, 8, (-54031705682750465925)), (10, 6, 84129609680081473180), (13, 4, (-72158726373828366405)), (16, 2, 32478685099390268130), (19, 0, (-6012774407228429099))]

def f_76_part_5_scale : ℤ := 110520676584407682938277142177949777786329440526497460038496419840

def f_76_part_5_qExpListZ : List ℤ :=
  [0, 0, 0, 134500170394965041228021760, 0, (-55723938112714988265421194261430272), (-110634371273097542997405214339969843200), (-19838340466839218139441465607629916078080), 0, (-88919288821026886499880788929136955280588800)]

/-- Integer-arithmetic certificate (the heavy kernel computation). -/
lemma f_76_part_5_evalEisListZ_eq :
    evalEisListZ f_76_part_5_polyDataZ 10 = f_76_part_5_qExpListZ := by
  decide +kernel

end LeanBridge.QExpansion.LMFDB.W76
