import LeanBridge.ForMathlib.QExpansion.IntEval

set_option maxHeartbeats 0
set_option maxRecDepth 4000

/-!
# LMFDB level-1 weight-82 form `1.82.a`, piece 4: integer q-coefficient certificate

Heavy `decide +kernel` over `ℤ` (denominators cleared by the scale `D = 6795155502980033019213819306868201657894790215658337460753778343936`), isolated in its own
module so `lake` schedules it in parallel with the other pieces. Generated by
`scripts/lmfdb_qexp_to_e4e6_v3.sage`.
-/

namespace LeanBridge.QExpansion.LMFDB.W82

open LeanBridge.QExpansion

def f_82_part_4_polyDataZ : List (ℕ × ℕ × ℤ) :=
  [(1, 13, (-1259164064446236694330503868963)), (4, 11, 5869896512495159765730580568262), (7, 9, (-10456579992356863264704765432945)), (10, 7, 8315791336645691008219671782660), (13, 5, (-2019398214053940678778670398485)), (16, 3, (-876755788200117270952492446762)), (19, 1, 426210209916307134816179796233)]

def f_82_part_4_scale : ℤ := 6795155502980033019213819306868201657894790215658337460753778343936

def f_82_part_4_qExpListZ : List ℤ :=
  [0, 0, 0, (-26599716414642495594490187351567892480), 0, 25981246057388369720876862330490257171743244288, (-24794310073418249157038027558237978037879973085184), 8639207710926925250288169328230489765509377535508480, 0, (-824471154075236989403626563728302177515646949235860963328)]

/-- Integer-arithmetic certificate (the heavy kernel computation). -/
lemma f_82_part_4_evalEisListZ_eq :
    evalEisListZ f_82_part_4_polyDataZ 10 = f_82_part_4_qExpListZ := by
  decide +kernel

end LeanBridge.QExpansion.LMFDB.W82
