import LeanBridge.ForMathlib.QExpansion.IntEval

set_option maxHeartbeats 0
set_option maxRecDepth 4000

/-!
# LMFDB level-1 weight-46 form `1.46.a`, piece 2: integer q-coefficient certificate

Heavy `decide +kernel` over `ℤ` (denominators cleared by the scale `D = 1733686198272`), isolated in its own
module so `lake` schedules it in parallel with the other pieces. Generated by
`scripts/lmfdb_qexp_to_e4e6_v3.sage`.
-/

namespace LeanBridge.QExpansion.LMFDB.W46

open LeanBridge.QExpansion

def f_46_part_2_polyDataZ : List (ℕ × ℕ × ℤ) :=
  [(1, 7, 1), (4, 5, (-3)), (7, 3, 3), (10, 1, (-1))]

def f_46_part_2_scale : ℤ := 1733686198272

def f_46_part_2_qExpListZ : List ℤ :=
  [0, 0, 0, (-5159780352), 1733686198272, 587905373306880, (-19835351463886848), 84379157402222592, 6612750722855337984, (-169628435437339017216)]

/-- Integer-arithmetic certificate (the heavy kernel computation). -/
lemma f_46_part_2_evalEisListZ_eq :
    evalEisListZ f_46_part_2_polyDataZ 10 = f_46_part_2_qExpListZ := by
  decide +kernel

end LeanBridge.QExpansion.LMFDB.W46
