import LeanBridge.ForMathlib.QExpansion.IntEval

set_option maxHeartbeats 0
set_option maxRecDepth 4000

/-!
# LMFDB level-1 weight-74 form `1.74.a`, piece 0: integer q-coefficient certificate

Heavy `decide +kernel` over `ℤ` (denominators cleared by the scale `D = 373329098161221752900517888`), isolated in its own
module so `lake` schedules it in parallel with the other pieces. Generated by
`scripts/lmfdb_qexp_to_e4e6_v3.sage`.
-/

namespace LeanBridge.QExpansion.LMFDB.W74

open LeanBridge.QExpansion

def f_74_part_0_polyDataZ : List (ℕ × ℕ × ℤ) :=
  [(2, 11, (-733953962390113312269988643212656431)), (5, 9, 3264645112664831727038948401295707819), (8, 7, (-5731462173902062283459029992670416614)), (11, 5, 4946055469617975533927270183121329414), (14, 3, (-2086535056238740611215107039939442203)), (17, 1, 341250610248108945977907091405478015)]

def f_74_part_0_scale : ℤ := 373329098161221752900517888

def f_74_part_0_qExpListZ : List ℤ :=
  [0, 373329098161221752900517888, 0, 64091422937400633916279724563566075783806976, (-3525993640473010602832085213388489205077661188096), 9175778169907791113931150224175798284459593069559808, (-1284026841575032543859814345400754333890065450965925888), (-1541550633853267871408884985712772187186287979860871872512), 0, 38584015202018015403043517130657453138116776463938865576902656]

/-- Integer-arithmetic certificate (the heavy kernel computation). -/
lemma f_74_part_0_evalEisListZ_eq :
    evalEisListZ f_74_part_0_polyDataZ 10 = f_74_part_0_qExpListZ := by
  decide +kernel

end LeanBridge.QExpansion.LMFDB.W74
