import LeanBridge.ForMathlib.QExpansion.IntEval

set_option maxHeartbeats 0
set_option maxRecDepth 4000

/-!
# LMFDB level-1 weight-66 form `1.66.a`, piece 3: integer q-coefficient certificate

Heavy `decide +kernel` over `ℤ` (denominators cleared by the scale `D = 7788658095995872611866055303757824`), isolated in its own
module so `lake` schedules it in parallel with the other pieces. Generated by
`scripts/lmfdb_qexp_to_e4e6_v3.sage`.
-/

namespace LeanBridge.QExpansion.LMFDB.W66

open LeanBridge.QExpansion

def f_66_part_3_polyDataZ : List (ℕ × ℕ × ℤ) :=
  [(0, 11, 668197717355), (3, 9, (-3411106771717)), (6, 7, 6822213543434), (9, 5, (-6681977173550)), (12, 3, 3200752216891), (15, 1, (-598079532413))]

def f_66_part_3_scale : ℤ := 7788658095995872611866055303757824

def f_66_part_3_qExpListZ : List ℤ :=
  [0, 0, 0, 723588865963267719168, 0, (-10319553140597919343706112000), 6428130539556857812478853120000, (-549196320797071456758368481312768), 7788658095995872611866055303757824, (-2135806371330723185853089662894080000)]

/-- Integer-arithmetic certificate (the heavy kernel computation). -/
lemma f_66_part_3_evalEisListZ_eq :
    evalEisListZ f_66_part_3_polyDataZ 10 = f_66_part_3_qExpListZ := by
  decide +kernel

end LeanBridge.QExpansion.LMFDB.W66
