import LeanBridge.ForMathlib.QExpansion.IntEval

set_option maxHeartbeats 0
set_option maxRecDepth 4000

/-!
# LMFDB level-1 weight-70 form `1.70.a`, piece 3: integer q-coefficient certificate

Heavy `decide +kernel` over `ℤ` (denominators cleared by the scale `D = 142507532372305370757914834001117315072`), isolated in its own
module so `lake` schedules it in parallel with the other pieces. Generated by
`scripts/lmfdb_qexp_to_e4e6_v3.sage`.
-/

namespace LeanBridge.QExpansion.LMFDB.W70

open LeanBridge.QExpansion

def f_70_part_3_polyDataZ : List (ℕ × ℕ × ℤ) :=
  [(1, 11, (-978015292455695)), (4, 9, 4937946840468899), (7, 7, (-9896706888846678)), (10, 5, 9842592548283590), (13, 3, (-4856775329624267)), (16, 1, 950958122174151)]

def f_70_part_3_scale : ℤ := 142507532372305370757914834001117315072

def f_70_part_3_qExpListZ : List ℤ :=
  [0, 0, 0, (-386609692429188109172736), 0, 15114023173366964960961358725120, (-5802475497937819976385966794342400), (-1455320666796014946917839404577849344), 142507532372305370757914834001117315072, (-2376445553082967355626949590970164838400)]

/-- Integer-arithmetic certificate (the heavy kernel computation). -/
lemma f_70_part_3_evalEisListZ_eq :
    evalEisListZ f_70_part_3_polyDataZ 10 = f_70_part_3_qExpListZ := by
  decide +kernel

end LeanBridge.QExpansion.LMFDB.W70
