import LeanBridge.ForMathlib.QExpansion.IntEval

set_option maxHeartbeats 0
set_option maxRecDepth 4000

/-!
# LMFDB level-1 weight-40 form `1.40.a`, piece 0: integer q-coefficient certificate

Heavy `decide +kernel` over `ℤ` (denominators cleared by the scale `D = 1161216`), isolated in its own
module so `lake` schedules it in parallel with the other pieces. Generated by
`scripts/lmfdb_qexp_to_e4e6_v3.sage`.
-/

namespace LeanBridge.QExpansion.LMFDB.W40

open LeanBridge.QExpansion

def f_40_part_0_polyDataZ : List (ℕ × ℕ × ℤ) :=
  [(1, 6, 736401), (4, 4, (-2209847)), (7, 2, 2209819), (10, 0, (-736373))]

def f_40_part_0_scale : ℤ := 1161216

def f_40_part_0_qExpListZ : List ℤ :=
  [0, 1161216, 0, (-3800045526147072), (-638385247179767808), 48061450811553288192, (-1476003413718447685632), 29896155131752726806528, (-247968573504699211186176), 5649114138998887551375360]

/-- Integer-arithmetic certificate (the heavy kernel computation). -/
lemma f_40_part_0_evalEisListZ_eq :
    evalEisListZ f_40_part_0_polyDataZ 10 = f_40_part_0_qExpListZ := by
  decide +kernel

end LeanBridge.QExpansion.LMFDB.W40
