import LeanBridge.ForMathlib.QExpansion.IntEval

set_option maxHeartbeats 0
set_option maxRecDepth 4000

/-!
# LMFDB level-1 weight-60 form `1.60.a`, piece 3: integer q-coefficient certificate

Heavy `decide +kernel` over `ℤ` (denominators cleared by the scale `D = 262236489829165109595639467999232`), isolated in its own
module so `lake` schedules it in parallel with the other pieces. Generated by
`scripts/lmfdb_qexp_to_e4e6_v3.sage`.
-/

namespace LeanBridge.QExpansion.LMFDB.W60

open LeanBridge.QExpansion

def f_60_part_3_polyDataZ : List (ℕ × ℕ × ℤ) :=
  [(0, 10, 6659047675), (3, 8, (-42473954987)), (6, 6, 91711174846), (9, 4, (-86880271366)), (12, 2, 35227599767), (15, 0, (-4243595935))]

def f_60_part_3_scale : ℤ := 262236489829165109595639467999232

def f_60_part_3_qExpListZ : List ℤ :=
  [0, 0, 0, 59823362060429819904, 0, (-107254416751845742133379072), 16837048636538298166149120000, 1347156858706096624282531528704, 262236489829165109595639467999232, 2625719062880615257176570593280000]

/-- Integer-arithmetic certificate (the heavy kernel computation). -/
lemma f_60_part_3_evalEisListZ_eq :
    evalEisListZ f_60_part_3_polyDataZ 10 = f_60_part_3_qExpListZ := by
  decide +kernel

end LeanBridge.QExpansion.LMFDB.W60
