import LeanBridge.ForMathlib.QExpansion.IntEval

set_option maxHeartbeats 0
set_option maxRecDepth 4000

/-!
# LMFDB level-1 weight-28 form `1.28.a`, piece 1: integer q-coefficient certificate

Heavy `decide +kernel` over `ℤ` (denominators cleared by the scale `D = 2985984`), isolated in its own
module so `lake` schedules it in parallel with the other pieces. Generated by
`scripts/lmfdb_qexp_to_e4e6_v3.sage`.
-/

namespace LeanBridge.QExpansion.LMFDB.W28

open LeanBridge.QExpansion

def f_28_part_1_polyDataZ : List (ℕ × ℕ × ℤ) :=
  [(1, 4, 1), (4, 2, (-2)), (7, 0, 1)]

def f_28_part_1_scale : ℤ := 2985984

def f_28_part_1_qExpListZ : List ℤ :=
  [0, 0, 2985984, 573308928, (-24723947520), 439536844800, (-4293904711680), 22369367752704, (-13815789649920), (-737435807907840)]

/-- Integer-arithmetic certificate (the heavy kernel computation). -/
lemma f_28_part_1_evalEisListZ_eq :
    evalEisListZ f_28_part_1_polyDataZ 10 = f_28_part_1_qExpListZ := by
  decide +kernel

end LeanBridge.QExpansion.LMFDB.W28
