import LeanBridge.ForMathlib.QExpansion.IntEval

set_option maxHeartbeats 0
set_option maxRecDepth 4000

/-!
# LMFDB level-1 weight-64 form `1.64.a`, piece 3: integer q-coefficient certificate

Heavy `decide +kernel` over `ℤ` (denominators cleared by the scale `D = 374907414662436082004581574548389888`), isolated in its own
module so `lake` schedules it in parallel with the other pieces. Generated by
`scripts/lmfdb_qexp_to_e4e6_v3.sage`.
-/

namespace LeanBridge.QExpansion.LMFDB.W64

open LeanBridge.QExpansion

def f_64_part_3_polyDataZ : List (ℕ × ℕ × ℤ) :=
  [(1, 10, 47747788211714), (4, 8, (-256831282240843)), (7, 6, 530404730948864), (10, 4, (-527704381518674)), (13, 2, 252780758095558), (16, 0, (-46397613496619))]

def f_64_part_3_scale : ℤ := 374907414662436082004581574548389888

def f_64_part_3_qExpListZ : List ℤ :=
  [0, 0, 0, 100319111520687054913536, 0, (-764048333376596095856227123200), (-88980795482147725754058670080000), 18941841620287804401417846276489216, 374907414662436082004581574548389888, 141178188964266048630910873113722880000]

/-- Integer-arithmetic certificate (the heavy kernel computation). -/
lemma f_64_part_3_evalEisListZ_eq :
    evalEisListZ f_64_part_3_polyDataZ 10 = f_64_part_3_qExpListZ := by
  decide +kernel

end LeanBridge.QExpansion.LMFDB.W64
