import LeanBridge.ForMathlib.QExpansion.IntEval

set_option maxHeartbeats 0
set_option maxRecDepth 4000

/-!
# LMFDB level-1 weight-54 form `1.54.a`, piece 3: integer q-coefficient certificate

Heavy `decide +kernel` over `ℤ` (denominators cleared by the scale `D = 6535754417851556954112`), isolated in its own
module so `lake` schedules it in parallel with the other pieces. Generated by
`scripts/lmfdb_qexp_to_e4e6_v3.sage`.
-/

namespace LeanBridge.QExpansion.LMFDB.W54

open LeanBridge.QExpansion

def f_54_part_3_polyDataZ : List (ℕ × ℕ × ℤ) :=
  [(0, 9, (-1)), (3, 7, (-8)), (6, 5, 30), (9, 3, (-32)), (12, 1, 11)]

def f_54_part_3_scale : ℤ := 6535754417851556954112

def f_54_part_3_qExpListZ : List ℤ :=
  [0, 0, 0, 61917364224, 0, (-7857313520025600), (-4694386326676439040), (-336843863144376827904), 6535754417851556954112, 92610883433060546641920]

/-- Integer-arithmetic certificate (the heavy kernel computation). -/
lemma f_54_part_3_evalEisListZ_eq :
    evalEisListZ f_54_part_3_polyDataZ 10 = f_54_part_3_qExpListZ := by
  decide +kernel

end LeanBridge.QExpansion.LMFDB.W54
