import LeanBridge.ForMathlib.QExpansion.Generic
import LeanBridge.ForMathlib.QExpansion.Sturm
import Mathlib.Analysis.Complex.Polynomial.Basic

/-!
# LMFDB level-1 modular form orbit `1.40.a.{a..}` (Hecke field degree 3)

The Hecke field `K = ℚ(α)` is degree 3 over ℚ. The LMFDB lists q-coefficients as
elements of `K`, which we decompose as `c_0 + c_1 · α + … + c_{2} · α^2`.
The combined form is `f = f_0 + α · f_1 + … + α^2 · f_{2}`, with each
`f_j` a level-1 weight-40 form with rational coefficients in `(E₄, E₆)`.

The Sturm bound for weight 40 is `⌊40/12⌋ + 1 = 4`. After certifying agreement
on the first 4 q-coefficients, `ModularForm.eq_of_sturm_bound` lets us conclude that any
form with the same coefficients equals our explicit `lmfdb_1_40_a_orbit`.

Generated by `scripts/lmfdb_qexp_to_e4e6_v3.sage`.
-/

namespace LeanBridge.QExpansion.LMFDB.W40

open LeanBridge.QExpansion ModularForm EisensteinSeries PowerSeries UpperHalfPlane
open scoped MatrixGroups


/-- Minimal polynomial of α (degree 3) as `Polynomial ℂ`. -/
noncomputable def α_40_minpoly : Polynomial ℂ :=
  Polynomial.X ^ 3 +
    Polynomial.C 213542160549543936 +
    Polynomial.C (-810051757056) * Polynomial.X +
    Polynomial.C (-548856) * Polynomial.X ^ 2

lemma α_40_minpoly_natDegree : α_40_minpoly.natDegree = 3 := by
  unfold α_40_minpoly
  compute_degree!

lemma α_40_minpoly_degree_ne_zero : α_40_minpoly.degree ≠ 0 := by
  rw [Polynomial.degree_eq_natDegree (fun h => by
    have := α_40_minpoly_natDegree
    rw [h, Polynomial.natDegree_zero] at this
    exact absurd this (by decide))]
  rw [α_40_minpoly_natDegree]
  decide

/-- α is some root of the degree-3 minimal polynomial in ℂ. -/
noncomputable def α_40 : ℂ :=
  (IsAlgClosed.exists_root α_40_minpoly α_40_minpoly_degree_ne_zero).choose

lemma α_40_isRoot : Polynomial.IsRoot α_40_minpoly α_40 :=
  (IsAlgClosed.exists_root α_40_minpoly α_40_minpoly_degree_ne_zero).choose_spec

/-- Explicit polynomial relation: minpoly evaluated at α is zero. -/
lemma α_40_is_root :
    α_40 ^ 3 +
      213542160549543936 +
      (-810051757056) * α_40 +
      (-548856) * α_40 ^ 2 = 0 := by
  have h := α_40_isRoot
  unfold Polynomial.IsRoot α_40_minpoly at h
  simp only [Polynomial.eval_add, Polynomial.eval_mul, Polynomial.eval_pow,
    Polynomial.eval_C, Polynomial.eval_X] at h
  linear_combination h


/-! ## Piece 0: coefficient of α^0 -/


def f_40_part_0_polyData : List (ℕ × ℕ × ℚ) :=
  [(1, 6, (245467 / 387072)), (4, 4, ((-(2209847 / 1161216)))), (7, 2, (2209819 / 1161216)), (10, 0, ((-(736373 / 1161216))))]

noncomputable def f_40_part_0 : ModularForm 𝒮ℒ 40 :=
  ((245467 / 387072) : ℂ) • mkMonomForm 1 6 40 (by decide) +
  (((-(2209847 / 1161216))) : ℂ) • mkMonomForm 4 4 40 (by decide) +
  ((2209819 / 1161216) : ℂ) • mkMonomForm 7 2 40 (by decide) +
  (((-(736373 / 1161216))) : ℂ) • mkMonomForm 10 0 40 (by decide)

lemma f_40_part_0_qExpansion_eq_evalEisPS :
    qExpansion 1 (f_40_part_0 : ℍ → ℂ) = evalEisPS f_40_part_0_polyData := by
  unfold f_40_part_0
  rw [ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm]
  unfold evalEisPS f_40_part_0_polyData monomialEisPS
  simp only [List.foldr_cons, List.foldr_nil, add_zero]
  push_cast
  module

theorem f_40_part_0_qExpansion_coeff (N n : ℕ) (hn : n < N) :
    (PowerSeries.coeff (R := ℂ) n) (qExpansion 1 (f_40_part_0 : ℍ → ℂ))
      = ((evalEisList f_40_part_0_polyData N).getD n 0 : ℚ) :=
  qexp_coeff_via_E4E6 _ _ f_40_part_0_qExpansion_eq_evalEisPS N n hn

/-- Precomputed first 10 q-coefficients of `f_40_part_0` (rational). -/
def f_40_part_0_qExpList : List ℚ :=
  [0, 1, 0, ((-(22907296044 / 7))), (-549755813888), (289722287396034 / 7), ((-(8897590022897664 / 7))), 25745559079234808, (-213542160549543936), 4864826301910142085]

/-- One-shot bridge: the symbolic `evalEisList` equals the precomputed list (verified by
`decide +kernel` once instead of N times). -/
lemma f_40_part_0_evalEisList_eq :
    evalEisList f_40_part_0_polyData 10 = f_40_part_0_qExpList := by
  decide +kernel


/-! ## Piece 1: coefficient of α^1 -/


def f_40_part_1_polyData : List (ℕ × ℕ × ℚ) :=
  [(1, 6, (4295 / 12039487488)), (4, 4, ((-(2951 / 4013162496)))), (7, 2, (1607 / 4013162496)), (10, 0, ((-(263 / 12039487488))))]

noncomputable def f_40_part_1 : ModularForm 𝒮ℒ 40 :=
  ((4295 / 12039487488) : ℂ) • mkMonomForm 1 6 40 (by decide) +
  (((-(2951 / 4013162496))) : ℂ) • mkMonomForm 4 4 40 (by decide) +
  ((1607 / 4013162496) : ℂ) • mkMonomForm 7 2 40 (by decide) +
  (((-(263 / 12039487488))) : ℂ) • mkMonomForm 10 0 40 (by decide)

lemma f_40_part_1_qExpansion_eq_evalEisPS :
    qExpansion 1 (f_40_part_1 : ℍ → ℂ) = evalEisPS f_40_part_1_polyData := by
  unfold f_40_part_1
  rw [ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm]
  unfold evalEisPS f_40_part_1_polyData monomialEisPS
  simp only [List.foldr_cons, List.foldr_nil, add_zero]
  push_cast
  module

theorem f_40_part_1_qExpansion_coeff (N n : ℕ) (hn : n < N) :
    (PowerSeries.coeff (R := ℂ) n) (qExpansion 1 (f_40_part_1 : ℍ → ℂ))
      = ((evalEisList f_40_part_1_polyData N).getD n 0 : ℚ) :=
  qexp_coeff_via_E4E6 _ _ f_40_part_1_qExpansion_eq_evalEisPS N n hn

/-- Precomputed first 10 q-coefficients of `f_40_part_1` (rational). -/
def f_40_part_1_qExpList : List ℚ :=
  [0, 0, 1, ((-(6501 / 7))), 0, (481748300 / 7), (10844860500 / 7), (-20667766734), (-289459870720), 5308985187000]

/-- One-shot bridge: the symbolic `evalEisList` equals the precomputed list (verified by
`decide +kernel` once instead of N times). -/
lemma f_40_part_1_evalEisList_eq :
    evalEisList f_40_part_1_polyData 10 = f_40_part_1_qExpList := by
  decide +kernel


/-! ## Piece 2: coefficient of α^2 -/


def f_40_part_2_polyData : List (ℕ × ℕ × ℚ) :=
  [(1, 6, ((-(1 / 866843099136)))), (4, 4, (1 / 288947699712)), (7, 2, ((-(1 / 288947699712)))), (10, 0, (1 / 866843099136))]

noncomputable def f_40_part_2 : ModularForm 𝒮ℒ 40 :=
  (((-(1 / 866843099136))) : ℂ) • mkMonomForm 1 6 40 (by decide) +
  ((1 / 288947699712) : ℂ) • mkMonomForm 4 4 40 (by decide) +
  (((-(1 / 288947699712))) : ℂ) • mkMonomForm 7 2 40 (by decide) +
  ((1 / 866843099136) : ℂ) • mkMonomForm 10 0 40 (by decide)

lemma f_40_part_2_qExpansion_eq_evalEisPS :
    qExpansion 1 (f_40_part_2 : ℍ → ℂ) = evalEisPS f_40_part_2_polyData := by
  unfold f_40_part_2
  rw [ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm]
  unfold evalEisPS f_40_part_2_polyData monomialEisPS
  simp only [List.foldr_cons, List.foldr_nil, add_zero]
  push_cast
  module

theorem f_40_part_2_qExpansion_coeff (N n : ℕ) (hn : n < N) :
    (PowerSeries.coeff (R := ℂ) n) (qExpansion 1 (f_40_part_2 : ℍ → ℂ))
      = ((evalEisList f_40_part_2_polyData N).getD n 0 : ℚ) :=
  qexp_coeff_via_E4E6 _ _ f_40_part_2_qExpansion_eq_evalEisPS N n hn

/-- Precomputed first 10 q-coefficients of `f_40_part_2` (rational). -/
def f_40_part_2_qExpList : List ℚ :=
  [0, 0, 0, (1 / 168), 1, ((-(1053 / 14))), (16368 / 7), ((-(174647 / 4))), 548856, (-4789593)]

/-- One-shot bridge: the symbolic `evalEisList` equals the precomputed list (verified by
`decide +kernel` once instead of N times). -/
lemma f_40_part_2_evalEisList_eq :
    evalEisList f_40_part_2_polyData 10 = f_40_part_2_qExpList := by
  decide +kernel


/-! ## Combined LMFDB form -/


noncomputable def lmfdb_1_40_a_orbit : ModularForm 𝒮ℒ 40 :=
  f_40_part_0 +
  α_40 • f_40_part_1 +
  α_40 ^ 2 • f_40_part_2

lemma lmfdb_1_40_a_orbit_coeff_decomp (n : ℕ) :
    (PowerSeries.coeff (R := ℂ) n) (qExpansion 1 (lmfdb_1_40_a_orbit : ℍ → ℂ))
      = (PowerSeries.coeff (R := ℂ) n) (qExpansion 1 (f_40_part_0 : ℍ → ℂ))
        + α_40 * (PowerSeries.coeff (R := ℂ) n) (qExpansion 1 (f_40_part_1 : ℍ → ℂ))
        + α_40 ^ 2 * (PowerSeries.coeff (R := ℂ) n) (qExpansion 1 (f_40_part_2 : ℍ → ℂ)) := by
  unfold lmfdb_1_40_a_orbit
  rw [ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL]
  simp [smul_eq_mul]


/-! ## Coefficient lemmas (n = 0, …, 9)

Sturm bound is 4; we certify 10 coefficients for added
redundancy beyond the minimum mathematically required for uniqueness. -/


lemma lmfdb_1_40_a_orbit_qExpansion_coeff_0 :
    (PowerSeries.coeff (R := ℂ) 0)
      (qExpansion 1 (lmfdb_1_40_a_orbit : ℍ → ℂ)) = 0 := by
  rw [lmfdb_1_40_a_orbit_coeff_decomp,
    f_40_part_0_qExpansion_coeff 10 0 (by decide),
    f_40_part_1_qExpansion_coeff 10 0 (by decide),
    f_40_part_2_qExpansion_coeff 10 0 (by decide),
    f_40_part_0_evalEisList_eq,
    f_40_part_1_evalEisList_eq,
    f_40_part_2_evalEisList_eq,
    show f_40_part_0_qExpList.getD 0 0 = (0 : ℚ) from by decide +kernel,
    show f_40_part_1_qExpList.getD 0 0 = (0 : ℚ) from by decide +kernel,
    show f_40_part_2_qExpList.getD 0 0 = (0 : ℚ) from by decide +kernel]
  push_cast; ring

lemma lmfdb_1_40_a_orbit_qExpansion_coeff_1 :
    (PowerSeries.coeff (R := ℂ) 1)
      (qExpansion 1 (lmfdb_1_40_a_orbit : ℍ → ℂ)) = 1 := by
  rw [lmfdb_1_40_a_orbit_coeff_decomp,
    f_40_part_0_qExpansion_coeff 10 1 (by decide),
    f_40_part_1_qExpansion_coeff 10 1 (by decide),
    f_40_part_2_qExpansion_coeff 10 1 (by decide),
    f_40_part_0_evalEisList_eq,
    f_40_part_1_evalEisList_eq,
    f_40_part_2_evalEisList_eq,
    show f_40_part_0_qExpList.getD 1 0 = (1 : ℚ) from by decide +kernel,
    show f_40_part_1_qExpList.getD 1 0 = (0 : ℚ) from by decide +kernel,
    show f_40_part_2_qExpList.getD 1 0 = (0 : ℚ) from by decide +kernel]
  push_cast; ring

lemma lmfdb_1_40_a_orbit_qExpansion_coeff_2 :
    (PowerSeries.coeff (R := ℂ) 2)
      (qExpansion 1 (lmfdb_1_40_a_orbit : ℍ → ℂ)) = 1 * α_40 := by
  rw [lmfdb_1_40_a_orbit_coeff_decomp,
    f_40_part_0_qExpansion_coeff 10 2 (by decide),
    f_40_part_1_qExpansion_coeff 10 2 (by decide),
    f_40_part_2_qExpansion_coeff 10 2 (by decide),
    f_40_part_0_evalEisList_eq,
    f_40_part_1_evalEisList_eq,
    f_40_part_2_evalEisList_eq,
    show f_40_part_0_qExpList.getD 2 0 = (0 : ℚ) from by decide +kernel,
    show f_40_part_1_qExpList.getD 2 0 = (1 : ℚ) from by decide +kernel,
    show f_40_part_2_qExpList.getD 2 0 = (0 : ℚ) from by decide +kernel]
  push_cast; ring

lemma lmfdb_1_40_a_orbit_qExpansion_coeff_3 :
    (PowerSeries.coeff (R := ℂ) 3)
      (qExpansion 1 (lmfdb_1_40_a_orbit : ℍ → ℂ)) = ((-(22907296044 / 7))) + ((-(6501 / 7))) * α_40 + (1 / 168) * α_40 ^ 2 := by
  rw [lmfdb_1_40_a_orbit_coeff_decomp,
    f_40_part_0_qExpansion_coeff 10 3 (by decide),
    f_40_part_1_qExpansion_coeff 10 3 (by decide),
    f_40_part_2_qExpansion_coeff 10 3 (by decide),
    f_40_part_0_evalEisList_eq,
    f_40_part_1_evalEisList_eq,
    f_40_part_2_evalEisList_eq,
    show f_40_part_0_qExpList.getD 3 0 = (((-(22907296044 / 7))) : ℚ) from by decide +kernel,
    show f_40_part_1_qExpList.getD 3 0 = (((-(6501 / 7))) : ℚ) from by decide +kernel,
    show f_40_part_2_qExpList.getD 3 0 = ((1 / 168) : ℚ) from by decide +kernel]
  push_cast; ring

lemma lmfdb_1_40_a_orbit_qExpansion_coeff_4 :
    (PowerSeries.coeff (R := ℂ) 4)
      (qExpansion 1 (lmfdb_1_40_a_orbit : ℍ → ℂ)) = (-549755813888) + 1 * α_40 ^ 2 := by
  rw [lmfdb_1_40_a_orbit_coeff_decomp,
    f_40_part_0_qExpansion_coeff 10 4 (by decide),
    f_40_part_1_qExpansion_coeff 10 4 (by decide),
    f_40_part_2_qExpansion_coeff 10 4 (by decide),
    f_40_part_0_evalEisList_eq,
    f_40_part_1_evalEisList_eq,
    f_40_part_2_evalEisList_eq,
    show f_40_part_0_qExpList.getD 4 0 = ((-549755813888) : ℚ) from by decide +kernel,
    show f_40_part_1_qExpList.getD 4 0 = (0 : ℚ) from by decide +kernel,
    show f_40_part_2_qExpList.getD 4 0 = (1 : ℚ) from by decide +kernel]
  push_cast; ring

lemma lmfdb_1_40_a_orbit_qExpansion_coeff_5 :
    (PowerSeries.coeff (R := ℂ) 5)
      (qExpansion 1 (lmfdb_1_40_a_orbit : ℍ → ℂ)) = (289722287396034 / 7) + (481748300 / 7) * α_40 + ((-(1053 / 14))) * α_40 ^ 2 := by
  rw [lmfdb_1_40_a_orbit_coeff_decomp,
    f_40_part_0_qExpansion_coeff 10 5 (by decide),
    f_40_part_1_qExpansion_coeff 10 5 (by decide),
    f_40_part_2_qExpansion_coeff 10 5 (by decide),
    f_40_part_0_evalEisList_eq,
    f_40_part_1_evalEisList_eq,
    f_40_part_2_evalEisList_eq,
    show f_40_part_0_qExpList.getD 5 0 = ((289722287396034 / 7) : ℚ) from by decide +kernel,
    show f_40_part_1_qExpList.getD 5 0 = ((481748300 / 7) : ℚ) from by decide +kernel,
    show f_40_part_2_qExpList.getD 5 0 = (((-(1053 / 14))) : ℚ) from by decide +kernel]
  push_cast; ring

lemma lmfdb_1_40_a_orbit_qExpansion_coeff_6 :
    (PowerSeries.coeff (R := ℂ) 6)
      (qExpansion 1 (lmfdb_1_40_a_orbit : ℍ → ℂ)) = ((-(8897590022897664 / 7))) + (10844860500 / 7) * α_40 + (16368 / 7) * α_40 ^ 2 := by
  rw [lmfdb_1_40_a_orbit_coeff_decomp,
    f_40_part_0_qExpansion_coeff 10 6 (by decide),
    f_40_part_1_qExpansion_coeff 10 6 (by decide),
    f_40_part_2_qExpansion_coeff 10 6 (by decide),
    f_40_part_0_evalEisList_eq,
    f_40_part_1_evalEisList_eq,
    f_40_part_2_evalEisList_eq,
    show f_40_part_0_qExpList.getD 6 0 = (((-(8897590022897664 / 7))) : ℚ) from by decide +kernel,
    show f_40_part_1_qExpList.getD 6 0 = ((10844860500 / 7) : ℚ) from by decide +kernel,
    show f_40_part_2_qExpList.getD 6 0 = ((16368 / 7) : ℚ) from by decide +kernel]
  push_cast; ring

lemma lmfdb_1_40_a_orbit_qExpansion_coeff_7 :
    (PowerSeries.coeff (R := ℂ) 7)
      (qExpansion 1 (lmfdb_1_40_a_orbit : ℍ → ℂ)) = 25745559079234808 + (-20667766734) * α_40 + ((-(174647 / 4))) * α_40 ^ 2 := by
  rw [lmfdb_1_40_a_orbit_coeff_decomp,
    f_40_part_0_qExpansion_coeff 10 7 (by decide),
    f_40_part_1_qExpansion_coeff 10 7 (by decide),
    f_40_part_2_qExpansion_coeff 10 7 (by decide),
    f_40_part_0_evalEisList_eq,
    f_40_part_1_evalEisList_eq,
    f_40_part_2_evalEisList_eq,
    show f_40_part_0_qExpList.getD 7 0 = (25745559079234808 : ℚ) from by decide +kernel,
    show f_40_part_1_qExpList.getD 7 0 = ((-20667766734) : ℚ) from by decide +kernel,
    show f_40_part_2_qExpList.getD 7 0 = (((-(174647 / 4))) : ℚ) from by decide +kernel]
  push_cast; ring

lemma lmfdb_1_40_a_orbit_qExpansion_coeff_8 :
    (PowerSeries.coeff (R := ℂ) 8)
      (qExpansion 1 (lmfdb_1_40_a_orbit : ℍ → ℂ)) = (-213542160549543936) + (-289459870720) * α_40 + 548856 * α_40 ^ 2 := by
  rw [lmfdb_1_40_a_orbit_coeff_decomp,
    f_40_part_0_qExpansion_coeff 10 8 (by decide),
    f_40_part_1_qExpansion_coeff 10 8 (by decide),
    f_40_part_2_qExpansion_coeff 10 8 (by decide),
    f_40_part_0_evalEisList_eq,
    f_40_part_1_evalEisList_eq,
    f_40_part_2_evalEisList_eq,
    show f_40_part_0_qExpList.getD 8 0 = ((-213542160549543936) : ℚ) from by decide +kernel,
    show f_40_part_1_qExpList.getD 8 0 = ((-289459870720) : ℚ) from by decide +kernel,
    show f_40_part_2_qExpList.getD 8 0 = (548856 : ℚ) from by decide +kernel]
  push_cast; ring

lemma lmfdb_1_40_a_orbit_qExpansion_coeff_9 :
    (PowerSeries.coeff (R := ℂ) 9)
      (qExpansion 1 (lmfdb_1_40_a_orbit : ℍ → ℂ)) = 4864826301910142085 + 5308985187000 * α_40 + (-4789593) * α_40 ^ 2 := by
  rw [lmfdb_1_40_a_orbit_coeff_decomp,
    f_40_part_0_qExpansion_coeff 10 9 (by decide),
    f_40_part_1_qExpansion_coeff 10 9 (by decide),
    f_40_part_2_qExpansion_coeff 10 9 (by decide),
    f_40_part_0_evalEisList_eq,
    f_40_part_1_evalEisList_eq,
    f_40_part_2_evalEisList_eq,
    show f_40_part_0_qExpList.getD 9 0 = (4864826301910142085 : ℚ) from by decide +kernel,
    show f_40_part_1_qExpList.getD 9 0 = (5308985187000 : ℚ) from by decide +kernel,
    show f_40_part_2_qExpList.getD 9 0 = ((-4789593) : ℚ) from by decide +kernel]
  push_cast; ring


/-! ## Uniqueness theorem -/


/-- **Uniqueness theorem.** Any level-1 weight-40 modular form `f` whose first 4
q-coefficients match the LMFDB-published values for `1.40.a.{a..}` is equal to our
explicit construction `lmfdb_1_40_a_orbit`. Proven via `ModularForm.eq_of_sturm_bound`. -/
theorem identifies_lmfdb_1_40_a_orbit (f : ModularForm 𝒮ℒ 40)
    (h_0 : (PowerSeries.coeff (R := ℂ) 0) (qExpansion 1 (f : ℍ → ℂ)) = 0)
    (h_1 : (PowerSeries.coeff (R := ℂ) 1) (qExpansion 1 (f : ℍ → ℂ)) = 1)
    (h_2 : (PowerSeries.coeff (R := ℂ) 2) (qExpansion 1 (f : ℍ → ℂ)) = 1 * α_40)
    (h_3 : (PowerSeries.coeff (R := ℂ) 3) (qExpansion 1 (f : ℍ → ℂ)) = ((-(22907296044 / 7))) + ((-(6501 / 7))) * α_40 + (1 / 168) * α_40 ^ 2) :
    f = lmfdb_1_40_a_orbit := by
  apply ModularForm.eq_of_sturm_bound
  intro i hi
  have : i ≤ 3 := by omega
  interval_cases i
  · rw [h_0, lmfdb_1_40_a_orbit_qExpansion_coeff_0]
  · rw [h_1, lmfdb_1_40_a_orbit_qExpansion_coeff_1]
  · rw [h_2, lmfdb_1_40_a_orbit_qExpansion_coeff_2]
  · rw [h_3, lmfdb_1_40_a_orbit_qExpansion_coeff_3]


end LeanBridge.QExpansion.LMFDB.W40