import LeanBridge.ForMathlib.QExpansion.IntEval

set_option maxHeartbeats 0
set_option maxRecDepth 4000

/-!
# LMFDB level-1 weight-64 form `1.64.a`, piece 0: integer q-coefficient certificate

Heavy `decide +kernel` over `ℤ` (denominators cleared by the scale `D = 12472841601860881489920`), isolated in its own
module so `lake` schedules it in parallel with the other pieces. Generated by
`scripts/lmfdb_qexp_to_e4e6_v3.sage`.
-/

namespace LeanBridge.QExpansion.LMFDB.W64

open LeanBridge.QExpansion

def f_64_part_0_polyDataZ : List (ℕ × ℕ × ℤ) :=
  [(1, 10, (-76955901528692931639325218707)), (4, 8, 391481333419608368445503379625), (7, 6, (-775298781664140383650005747170)), (10, 4, 746567359748767863998566620350), (13, 2, (-348384200547301472263209952795)), (16, 0, 62590190571758555108470918697)]

def f_64_part_0_scale : ℤ := 12472841601860881489920

def f_64_part_0_qExpListZ : List ℤ :=
  [0, 12472841601860881489920, 0, (-108703862106257221769545248494956216320), (-115041658450722583154724793156258611855360), 1117035827081264151470483684066061074549293056, 112377063650001864877357919065098443562449633280, (-31793328044206125108185428912888655091744365936640), 0, (-158043653983380814643852284991036850624669486609162240)]

/-- Integer-arithmetic certificate (the heavy kernel computation). -/
lemma f_64_part_0_evalEisListZ_eq :
    evalEisListZ f_64_part_0_polyDataZ 10 = f_64_part_0_qExpListZ := by
  decide +kernel

end LeanBridge.QExpansion.LMFDB.W64
