import LeanBridge.ForMathlib.QExpansion.IntEval

set_option maxHeartbeats 0
set_option maxRecDepth 4000

/-!
# LMFDB level-1 weight-36 form `1.36.a`, piece 2: integer q-coefficient certificate

Heavy `decide +kernel` over `ℤ` (denominators cleared by the scale `D = 371504185344`), isolated in its own
module so `lake` schedules it in parallel with the other pieces. Generated by
`scripts/lmfdb_qexp_to_e4e6_v3.sage`.
-/

namespace LeanBridge.QExpansion.LMFDB.W36

open LeanBridge.QExpansion

def f_36_part_2_polyDataZ : List (ℕ × ℕ × ℤ) :=
  [(0, 6, 1), (3, 4, (-3)), (6, 2, 3), (9, 0, (-1))]

def f_36_part_2_scale : ℤ := 371504185344

def f_36_part_2_qExpListZ : List ℤ :=
  [0, 0, 0, (-5159780352), 371504185344, (-12816894394368), 281352503033856, (-4398330926333952), 51882788508401664, (-476707855062269952)]

/-- Integer-arithmetic certificate (the heavy kernel computation). -/
lemma f_36_part_2_evalEisListZ_eq :
    evalEisListZ f_36_part_2_polyDataZ 10 = f_36_part_2_qExpListZ := by
  decide +kernel

end LeanBridge.QExpansion.LMFDB.W36
