import LeanBridge.ForMathlib.QExpansion.IntEval

set_option maxHeartbeats 0
set_option maxRecDepth 4000

/-!
# LMFDB level-1 weight-56 form `1.56.a`, piece 3: integer q-coefficient certificate

Heavy `decide +kernel` over `ℤ` (denominators cleared by the scale `D = 63382322927262731599872`), isolated in its own
module so `lake` schedules it in parallel with the other pieces. Generated by
`scripts/lmfdb_qexp_to_e4e6_v3.sage`.
-/

namespace LeanBridge.QExpansion.LMFDB.W56

open LeanBridge.QExpansion

def f_56_part_3_polyDataZ : List (ℕ × ℕ × ℤ) :=
  [(2, 8, (-47)), (5, 6, 116), (8, 4, (-66)), (11, 2, (-28)), (14, 0, 25)]

def f_56_part_3_scale : ℤ := 63382322927262731599872

def f_56_part_3_qExpListZ : List ℤ :=
  [0, 0, 0, 371504185344, 0, 25905729852407808, 32103667918008483840, 5329424356476016656384, 63382322927262731599872, (-4125328655205824074874880)]

/-- Integer-arithmetic certificate (the heavy kernel computation). -/
lemma f_56_part_3_evalEisListZ_eq :
    evalEisListZ f_56_part_3_polyDataZ 10 = f_56_part_3_qExpListZ := by
  decide +kernel

end LeanBridge.QExpansion.LMFDB.W56
