import LeanBridge.ForMathlib.QExpansion.IntEval

set_option maxHeartbeats 0
set_option maxRecDepth 4000

/-!
# LMFDB level-1 weight-56 form `1.56.a`, piece 0: integer q-coefficient certificate

Heavy `decide +kernel` over `ℤ` (denominators cleared by the scale `D = 1119372101664768`), isolated in its own
module so `lake` schedules it in parallel with the other pieces. Generated by
`scripts/lmfdb_qexp_to_e4e6_v3.sage`.
-/

namespace LeanBridge.QExpansion.LMFDB.W56

open LeanBridge.QExpansion

def f_56_part_0_polyDataZ : List (ℕ × ℕ × ℤ) :=
  [(2, 8, (-8177922968262940523)), (5, 6, 27113022773464560812), (8, 4, (-32271531491490221730)), (11, 2, 15915685887853742060), (14, 0, (-2579254201565140619))]

def f_56_part_0_scale : ℤ := 1119372101664768

def f_56_part_0_qExpListZ : List ℤ :=
  [0, 1119372101664768, 0, 28887900837790010681071042560, (-40329630239571025040159407079424), (-13472166910456395817100590414528512), 1677505541537004104675783783422623744, 530768072223743743629736762339568517120, 0, (-200806520045739994671961411096110752808960)]

/-- Integer-arithmetic certificate (the heavy kernel computation). -/
lemma f_56_part_0_evalEisListZ_eq :
    evalEisListZ f_56_part_0_polyDataZ 10 = f_56_part_0_qExpListZ := by
  decide +kernel

end LeanBridge.QExpansion.LMFDB.W56
