import LeanBridge.ForMathlib.QExpansion.IntEval

set_option maxHeartbeats 0
set_option maxRecDepth 4000

/-!
# LMFDB level-1 weight-52 form `1.52.a`, piece 2: integer q-coefficient certificate

Heavy `decide +kernel` over `ℤ` (denominators cleared by the scale `D = 308280806577184702464`), isolated in its own
module so `lake` schedules it in parallel with the other pieces. Generated by
`scripts/lmfdb_qexp_to_e4e6_v3.sage`.
-/

namespace LeanBridge.QExpansion.LMFDB.W52

open LeanBridge.QExpansion

def f_52_part_2_polyDataZ : List (ℕ × ℕ × ℤ) :=
  [(1, 8, 44951099), (4, 6, (-159614516)), (7, 4, 209136954), (10, 2, (-119234756)), (13, 0, 24761219)]

def f_52_part_2_scale : ℤ := 308280806577184702464

def f_52_part_2_qExpListZ : List ℤ :=
  [0, 0, 0, (-104175346133237760), 308280806577184702464, 27752299758560263274496, (-10576397263113779857588224), 164576912120115693071892480, 0, 29184396255300336195414786048]

/-- Integer-arithmetic certificate (the heavy kernel computation). -/
lemma f_52_part_2_evalEisListZ_eq :
    evalEisListZ f_52_part_2_polyDataZ 10 = f_52_part_2_qExpListZ := by
  decide +kernel

end LeanBridge.QExpansion.LMFDB.W52
