import LeanBridge.ForMathlib.QExpansion.IntEval

set_option maxHeartbeats 0
set_option maxRecDepth 4000

/-!
# LMFDB level-1 weight-48 form `1.48.a`, piece 0: integer q-coefficient certificate

Heavy `decide +kernel` over `ℤ` (denominators cleared by the scale `D = 2593757085696`), isolated in its own
module so `lake` schedules it in parallel with the other pieces. Generated by
`scripts/lmfdb_qexp_to_e4e6_v3.sage`.
-/

namespace LeanBridge.QExpansion.LMFDB.W48

open LeanBridge.QExpansion

def f_48_part_0_polyDataZ : List (ℕ × ℕ × ℤ) :=
  [(0, 8, (-51698463068351)), (3, 6, 178108267348444), (6, 4, (-224135879058810)), (9, 2, 120739307328860), (12, 0, (-23013232550143))]

def f_48_part_0_scale : ℤ := 2593757085696

def f_48_part_0_qExpListZ : List ℤ :=
  [0, 2593757085696, 0, 148008900462958125711360, (-365038857644690289394188288), 63480996242654491354495942656, (-1202089590612258119934397120512), (-15353343955257630378670817280), 0, 9081378461042604499700314695352320]

/-- Integer-arithmetic certificate (the heavy kernel computation). -/
lemma f_48_part_0_evalEisListZ_eq :
    evalEisListZ f_48_part_0_polyDataZ 10 = f_48_part_0_qExpListZ := by
  decide +kernel

end LeanBridge.QExpansion.LMFDB.W48
