import LeanBridge.ForMathlib.QExpansion.IntEval

set_option maxHeartbeats 0
set_option maxRecDepth 4000

/-!
# LMFDB level-1 weight-42 form `1.42.a`, piece 2: integer q-coefficient certificate

Heavy `decide +kernel` over `ℤ` (denominators cleared by the scale `D = 2972033482752`), isolated in its own
module so `lake` schedules it in parallel with the other pieces. Generated by
`scripts/lmfdb_qexp_to_e4e6_v3.sage`.
-/

namespace LeanBridge.QExpansion.LMFDB.W42

open LeanBridge.QExpansion

def f_42_part_2_polyDataZ : List (ℕ × ℕ × ℤ) :=
  [(0, 7, 1), (3, 5, (-3)), (6, 3, 3), (9, 1, (-1))]

def f_42_part_2_scale : ℤ := 2972033482752

def f_42_part_2_qExpListZ : List ℤ :=
  [0, 0, 0, (-5159780352), 2972033482752, (-114237536993280), 1196738815721472, 24033255882227712, (-1024424277102821376), 18191352939197497344]

/-- Integer-arithmetic certificate (the heavy kernel computation). -/
lemma f_42_part_2_evalEisListZ_eq :
    evalEisListZ f_42_part_2_polyDataZ 10 = f_42_part_2_qExpListZ := by
  decide +kernel

end LeanBridge.QExpansion.LMFDB.W42
