import LeanBridge.ForMathlib.QExpansion.IntEval

set_option maxHeartbeats 0
set_option maxRecDepth 4000

/-!
# LMFDB level-1 weight-30 form `1.30.a`, piece 0: integer q-coefficient certificate

Heavy `decide +kernel` over `ℤ` (denominators cleared by the scale `D = 15552`), isolated in its own
module so `lake` schedules it in parallel with the other pieces. Generated by
`scripts/lmfdb_qexp_to_e4e6_v3.sage`.
-/

namespace LeanBridge.QExpansion.LMFDB.W30

open LeanBridge.QExpansion

def f_30_part_0_polyDataZ : List (ℕ × ℕ × ℤ) :=
  [(0, 5, (-1)), (3, 3, (-7)), (6, 1, 8)]

def f_30_part_0_scale : ℤ := 15552

def f_30_part_0_qExpListZ : List ℤ :=
  [0, 15552, 0, (-1542447360), (-1279944032256), (-143700701616000), (-3902348759924736), (-28044801179619840), 61080241459691520, 1086909866628958656]

/-- Integer-arithmetic certificate (the heavy kernel computation). -/
lemma f_30_part_0_evalEisListZ_eq :
    evalEisListZ f_30_part_0_polyDataZ 10 = f_30_part_0_qExpListZ := by
  decide +kernel

end LeanBridge.QExpansion.LMFDB.W30
