import LeanBridge.ForMathlib.QExpansion.IntEval

set_option maxHeartbeats 0
set_option maxRecDepth 4000

/-!
# LMFDB level-1 weight-74 form `1.74.a`, piece 1: integer q-coefficient certificate

Heavy `decide +kernel` over `ℤ` (denominators cleared by the scale `D = 8155498592364609599362780102656`), isolated in its own
module so `lake` schedules it in parallel with the other pieces. Generated by
`scripts/lmfdb_qexp_to_e4e6_v3.sage`.
-/

namespace LeanBridge.QExpansion.LMFDB.W74

open LeanBridge.QExpansion

def f_74_part_1_polyDataZ : List (ℕ × ℕ × ℤ) :=
  [(2, 11, (-676556669837575461639704081365)), (5, 9, 3433705874698000620619295202137), (8, 7, (-6903782931934108514320932110914)), (11, 5, 6874682977250053838272345041154), (14, 3, (-3390057308301907307860554151289)), (17, 1, 662008058125536824929550100277)]

def f_74_part_1_scale : ℤ := 8155498592364609599362780102656

def f_74_part_1_qExpListZ : List ℤ :=
  [0, 0, 8155498592364609599362780102656, (-337813751482513832828334005379284336640), 0, 10511589351150936018653196686740935782034309120, (-1513490176768545657135494014957885266048162201600), (-1960827528483682129291228735249217949790846945591296), (-154053012814692815244802357696418685695979735748706304), 20118604908243254998624383718372745128527083753334374400]

/-- Integer-arithmetic certificate (the heavy kernel computation). -/
lemma f_74_part_1_evalEisListZ_eq :
    evalEisListZ f_74_part_1_polyDataZ 10 = f_74_part_1_qExpListZ := by
  decide +kernel

end LeanBridge.QExpansion.LMFDB.W74
