import LeanBridge.ForMathlib.QExpansion.IntEval

set_option maxHeartbeats 0
set_option maxRecDepth 4000

/-!
# LMFDB level-1 weight-78 form `1.78.a`, piece 4: integer q-coefficient certificate

Heavy `decide +kernel` over `ℤ` (denominators cleared by the scale `D = 4629246832771036908851794242425264423600139526231512676564992`), isolated in its own
module so `lake` schedules it in parallel with the other pieces. Generated by
`scripts/lmfdb_qexp_to_e4e6_v3.sage`.
-/

namespace LeanBridge.QExpansion.LMFDB.W78

open LeanBridge.QExpansion

def f_78_part_4_polyDataZ : List (ℕ × ℕ × ℤ) :=
  [(0, 13, (-7896532282874408546023661)), (3, 11, 62356469575784963226927654), (6, 9, (-193323759585314415200431275)), (9, 7, 307672556295980860628033140), (12, 5, (-268191822890789594760433395)), (15, 3, 122257861053215903579996166), (18, 1, (-22874772166003308928068629))]

def f_78_part_4_scale : ℤ := 4629246832771036908851794242425264423600139526231512676564992

def f_78_part_4_qExpListZ : List ℤ :=
  [0, 0, 0, (-59688623336688427916826739998720), 0, (-230727783279206710717793892881892202512384), (-232382285106501949686380158940354534449348608), 186790537563755538083401219896133988426207723520, 0, 1253823459272933709176959706672346531004030107254784]

/-- Integer-arithmetic certificate (the heavy kernel computation). -/
lemma f_78_part_4_evalEisListZ_eq :
    evalEisListZ f_78_part_4_polyDataZ 10 = f_78_part_4_qExpListZ := by
  decide +kernel

end LeanBridge.QExpansion.LMFDB.W78
