import LeanBridge.ForMathlib.QExpansion.IntEval

set_option maxHeartbeats 0
set_option maxRecDepth 4000

/-!
# LMFDB level-1 weight-68 form `1.68.a`, piece 4: integer q-coefficient certificate

Heavy `decide +kernel` over `ℤ` (denominators cleared by the scale `D = 83124265925813751595376452430009739509760`), isolated in its own
module so `lake` schedules it in parallel with the other pieces. Generated by
`scripts/lmfdb_qexp_to_e4e6_v3.sage`.
-/

namespace LeanBridge.QExpansion.LMFDB.W68

open LeanBridge.QExpansion

def f_68_part_4_polyDataZ : List (ℕ × ℕ × ℤ) :=
  [(2, 10, 40675013), (5, 8, (-183097885)), (8, 6, 344601890), (11, 4, (-341968490)), (14, 2, 179147785), (17, 0, (-39358313))]

def f_68_part_4_scale : ℤ := 83124265925813751595376452430009739509760

def f_68_part_4_qExpListZ : List ℤ :=
  [0, 0, 0, (-97831912168488960), 0, (-573277492605992256405504), (-207096355650455437616087040), (-8988865010131685299527352320), 0, (-526557257085626573509570037022720)]

/-- Integer-arithmetic certificate (the heavy kernel computation). -/
lemma f_68_part_4_evalEisListZ_eq :
    evalEisListZ f_68_part_4_polyDataZ 10 = f_68_part_4_qExpListZ := by
  decide +kernel

end LeanBridge.QExpansion.LMFDB.W68
