import LeanBridge.ForMathlib.QExpansion.IntEval

set_option maxHeartbeats 0
set_option maxRecDepth 4000

/-!
# LMFDB level-1 weight-74 form `1.74.a`, piece 3: integer q-coefficient certificate

Heavy `decide +kernel` over `ℤ` (denominators cleared by the scale `D = 153929881655771631754705677160607121408`), isolated in its own
module so `lake` schedules it in parallel with the other pieces. Generated by
`scripts/lmfdb_qexp_to_e4e6_v3.sage`.
-/

namespace LeanBridge.QExpansion.LMFDB.W74

open LeanBridge.QExpansion

def f_74_part_3_polyDataZ : List (ℕ × ℕ × ℤ) :=
  [(2, 11, 679973695484705), (5, 9, (-3464638747015189)), (8, 7, 6975541972310138), (11, 5, (-6938530389686330)), (14, 3, 3409121373079477), (17, 1, (-661467904172801))]

def f_74_part_3_scale : ℤ := 153929881655771631754705677160607121408

def f_74_part_3_qExpListZ : List ℤ :=
  [0, 0, 0, 429686182842185533095936, 0, (-10588130772641323595057898455040), 1524463544457074395228750951219200, 1974570193381382735071098052200628224, 153929881655771631754705677160607121408, (-21098916416704259270322102184520240332800)]

/-- Integer-arithmetic certificate (the heavy kernel computation). -/
lemma f_74_part_3_evalEisListZ_eq :
    evalEisListZ f_74_part_3_polyDataZ 10 = f_74_part_3_qExpListZ := by
  decide +kernel

end LeanBridge.QExpansion.LMFDB.W74
