import LeanBridge.ForMathlib.QExpansion.IntEval

set_option maxHeartbeats 0
set_option maxRecDepth 4000

/-!
# LMFDB level-1 weight-58 form `1.58.a`, piece 2: integer q-coefficient certificate

Heavy `decide +kernel` over `ℤ` (denominators cleared by the scale `D = 143170413717343961088`), isolated in its own
module so `lake` schedules it in parallel with the other pieces. Generated by
`scripts/lmfdb_qexp_to_e4e6_v3.sage`.
-/

namespace LeanBridge.QExpansion.LMFDB.W58

open LeanBridge.QExpansion

def f_58_part_2_polyDataZ : List (ℕ × ℕ × ℤ) :=
  [(1, 9, 16690978), (4, 7, (-63913327)), (7, 5, 91594113), (10, 3, (-58212157)), (13, 1, 13840393)]

def f_58_part_2_scale : ℤ := 143170413717343961088

def f_58_part_2_qExpListZ : List ℤ :=
  [0, 0, 0, (-14708392474705920), 143170413717343961088, (-50977429170763601018880), (-13932080432969046464397312), 1304156221369397569443594240, 0, (-178204326231252458116579590144)]

/-- Integer-arithmetic certificate (the heavy kernel computation). -/
lemma f_58_part_2_evalEisListZ_eq :
    evalEisListZ f_58_part_2_polyDataZ 10 = f_58_part_2_qExpListZ := by
  decide +kernel

end LeanBridge.QExpansion.LMFDB.W58
