import LeanBridge.ForMathlib.QExpansion.IntEval
import LeanBridge.ForMathlib.QExpansion.Sturm
import Mathlib.Analysis.Complex.Polynomial.Basic
import LeanBridge.ForMathlib.QExpansion.LMFDB.Weight_16_part_0

set_option maxHeartbeats 0
set_option maxRecDepth 2000

/-!
# LMFDB level-1 modular form orbit `1.16.a.{a..}` (Hecke field degree 1)

The Hecke field `K = ℚ(α)` is degree 1 over ℚ. The LMFDB lists q-coefficients as
elements of `K`, which we decompose as `c_0 + c_1 · α + … + c_{0} · α^0`.
The combined form is `f = f_0 + α · f_1 + … + α^0 · f_{0}`, with each
`f_j` a level-1 weight-16 form with rational coefficients in `(E₄, E₆)`.

The Sturm bound for weight 16 is `⌊16/12⌋ + 1 = 2`. After certifying agreement
on the first 2 q-coefficients, `ModularForm.eq_of_sturm_bound` lets us conclude that any
form with the same coefficients equals our explicit `lmfdb_1_16_a_orbit`.

Generated by `scripts/lmfdb_qexp_to_e4e6_v3.sage`.
-/

namespace LeanBridge.QExpansion.LMFDB.W16

open LeanBridge.QExpansion ModularForm EisensteinSeries PowerSeries UpperHalfPlane
open scoped MatrixGroups


/-- Minimal polynomial of α (degree 1) as `Polynomial ℂ`. -/
noncomputable def α_16_minpoly : Polynomial ℂ :=
  Polynomial.X +
    Polynomial.C (-1)

lemma α_16_minpoly_natDegree : α_16_minpoly.natDegree = 1 := by
  unfold α_16_minpoly
  compute_degree!

lemma α_16_minpoly_degree_ne_zero : α_16_minpoly.degree ≠ 0 := by
  rw [Polynomial.degree_eq_natDegree (fun h => by
    have := α_16_minpoly_natDegree
    rw [h, Polynomial.natDegree_zero] at this
    exact absurd this (by decide))]
  rw [α_16_minpoly_natDegree]
  decide

/-- α is some root of the degree-1 minimal polynomial in ℂ. -/
noncomputable def α_16 : ℂ :=
  (IsAlgClosed.exists_root α_16_minpoly α_16_minpoly_degree_ne_zero).choose

lemma α_16_isRoot : Polynomial.IsRoot α_16_minpoly α_16 :=
  (IsAlgClosed.exists_root α_16_minpoly α_16_minpoly_degree_ne_zero).choose_spec

/-- Explicit polynomial relation: minpoly evaluated at α is zero. -/
lemma α_16_is_root :
    α_16 +
      (-1) = 0 := by
  have h := α_16_isRoot
  unfold Polynomial.IsRoot α_16_minpoly at h
  simp only [Polynomial.eval_add, Polynomial.eval_mul, Polynomial.eval_pow,
    Polynomial.eval_C, Polynomial.eval_X] at h
  linear_combination h


/-! ## Piece 0: coefficient of α^0 -/


def f_16_part_0_polyData : List (ℕ × ℕ × ℚ) :=
  [(1, 2, ((-(1 / 1728)))), (4, 0, (1 / 1728))]

noncomputable def f_16_part_0 : ModularForm 𝒮ℒ 16 :=
  (((-(1 / 1728))) : ℂ) • mkMonomForm 1 2 16 (by decide) +
  ((1 / 1728) : ℂ) • mkMonomForm 4 0 16 (by decide)

lemma f_16_part_0_qExpansion_eq_evalEisPS :
    qExpansion 1 (f_16_part_0 : ℍ → ℂ) = evalEisPS f_16_part_0_polyData := by
  unfold f_16_part_0
  rw [ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm]
  unfold evalEisPS f_16_part_0_polyData monomialEisPS
  simp only [List.foldr_cons, List.foldr_nil, add_zero]
  push_cast
  module

theorem f_16_part_0_qExpansion_coeff (N n : ℕ) (hn : n < N) :
    (PowerSeries.coeff (R := ℂ) n) (qExpansion 1 (f_16_part_0 : ℍ → ℂ))
      = ((evalEisList f_16_part_0_polyData N).getD n 0 : ℚ) :=
  qexp_coeff_via_E4E6 _ _ f_16_part_0_qExpansion_eq_evalEisPS N n hn

/-- Precomputed first 10 q-coefficients of `f_16_part_0` (rational). -/
def f_16_part_0_qExpList : List ℚ :=
  [0, 1, 216, (-3348), 13888, 52110, (-723168), 2822456, (-4078080), (-3139803)]

/-- Bridge: the symbolic `evalEisList` (over ℚ) equals the precomputed list. The heavy kernel work
is the integer certificate `f_16_part_0_evalEisListZ_eq`; the steps here are cheap rational
list checks. -/
lemma f_16_part_0_evalEisList_eq :
    evalEisList f_16_part_0_polyData 10 = f_16_part_0_qExpList := by
  have h : f_16_part_0_polyData
      = f_16_part_0_polyDataZ.map
          (fun t => (t.1, t.2.1, (t.2.2 : ℚ) / f_16_part_0_scale)) := by
    decide +kernel
  rw [h, evalEisList_eq_intCast_div, f_16_part_0_evalEisListZ_eq]
  decide +kernel


/-! ## Combined LMFDB form -/


noncomputable def lmfdb_1_16_a_orbit : ModularForm 𝒮ℒ 16 :=
  f_16_part_0

lemma lmfdb_1_16_a_orbit_coeff_decomp (n : ℕ) :
    (PowerSeries.coeff (R := ℂ) n) (qExpansion 1 (lmfdb_1_16_a_orbit : ℍ → ℂ))
      = (PowerSeries.coeff (R := ℂ) n) (qExpansion 1 (f_16_part_0 : ℍ → ℂ)) := by
  rfl


/-! ## Coefficient lemmas (n = 0, …, 9)

Sturm bound is 2; we certify 10 coefficients for added
redundancy beyond the minimum mathematically required for uniqueness. -/


lemma lmfdb_1_16_a_orbit_qExpansion_coeff_0 :
    (PowerSeries.coeff (R := ℂ) 0)
      (qExpansion 1 (lmfdb_1_16_a_orbit : ℍ → ℂ)) = 0 := by
  rw [lmfdb_1_16_a_orbit_coeff_decomp,
    f_16_part_0_qExpansion_coeff 10 0 (by decide),
    f_16_part_0_evalEisList_eq,
    show f_16_part_0_qExpList.getD 0 0 = (0 : ℚ) from by decide +kernel]
  push_cast; ring

lemma lmfdb_1_16_a_orbit_qExpansion_coeff_1 :
    (PowerSeries.coeff (R := ℂ) 1)
      (qExpansion 1 (lmfdb_1_16_a_orbit : ℍ → ℂ)) = 1 := by
  rw [lmfdb_1_16_a_orbit_coeff_decomp,
    f_16_part_0_qExpansion_coeff 10 1 (by decide),
    f_16_part_0_evalEisList_eq,
    show f_16_part_0_qExpList.getD 1 0 = (1 : ℚ) from by decide +kernel]
  push_cast; ring

lemma lmfdb_1_16_a_orbit_qExpansion_coeff_2 :
    (PowerSeries.coeff (R := ℂ) 2)
      (qExpansion 1 (lmfdb_1_16_a_orbit : ℍ → ℂ)) = 216 := by
  rw [lmfdb_1_16_a_orbit_coeff_decomp,
    f_16_part_0_qExpansion_coeff 10 2 (by decide),
    f_16_part_0_evalEisList_eq,
    show f_16_part_0_qExpList.getD 2 0 = (216 : ℚ) from by decide +kernel]
  push_cast; ring

lemma lmfdb_1_16_a_orbit_qExpansion_coeff_3 :
    (PowerSeries.coeff (R := ℂ) 3)
      (qExpansion 1 (lmfdb_1_16_a_orbit : ℍ → ℂ)) = (-3348) := by
  rw [lmfdb_1_16_a_orbit_coeff_decomp,
    f_16_part_0_qExpansion_coeff 10 3 (by decide),
    f_16_part_0_evalEisList_eq,
    show f_16_part_0_qExpList.getD 3 0 = ((-3348) : ℚ) from by decide +kernel]
  push_cast; ring

lemma lmfdb_1_16_a_orbit_qExpansion_coeff_4 :
    (PowerSeries.coeff (R := ℂ) 4)
      (qExpansion 1 (lmfdb_1_16_a_orbit : ℍ → ℂ)) = 13888 := by
  rw [lmfdb_1_16_a_orbit_coeff_decomp,
    f_16_part_0_qExpansion_coeff 10 4 (by decide),
    f_16_part_0_evalEisList_eq,
    show f_16_part_0_qExpList.getD 4 0 = (13888 : ℚ) from by decide +kernel]
  push_cast; ring

lemma lmfdb_1_16_a_orbit_qExpansion_coeff_5 :
    (PowerSeries.coeff (R := ℂ) 5)
      (qExpansion 1 (lmfdb_1_16_a_orbit : ℍ → ℂ)) = 52110 := by
  rw [lmfdb_1_16_a_orbit_coeff_decomp,
    f_16_part_0_qExpansion_coeff 10 5 (by decide),
    f_16_part_0_evalEisList_eq,
    show f_16_part_0_qExpList.getD 5 0 = (52110 : ℚ) from by decide +kernel]
  push_cast; ring

lemma lmfdb_1_16_a_orbit_qExpansion_coeff_6 :
    (PowerSeries.coeff (R := ℂ) 6)
      (qExpansion 1 (lmfdb_1_16_a_orbit : ℍ → ℂ)) = (-723168) := by
  rw [lmfdb_1_16_a_orbit_coeff_decomp,
    f_16_part_0_qExpansion_coeff 10 6 (by decide),
    f_16_part_0_evalEisList_eq,
    show f_16_part_0_qExpList.getD 6 0 = ((-723168) : ℚ) from by decide +kernel]
  push_cast; ring

lemma lmfdb_1_16_a_orbit_qExpansion_coeff_7 :
    (PowerSeries.coeff (R := ℂ) 7)
      (qExpansion 1 (lmfdb_1_16_a_orbit : ℍ → ℂ)) = 2822456 := by
  rw [lmfdb_1_16_a_orbit_coeff_decomp,
    f_16_part_0_qExpansion_coeff 10 7 (by decide),
    f_16_part_0_evalEisList_eq,
    show f_16_part_0_qExpList.getD 7 0 = (2822456 : ℚ) from by decide +kernel]
  push_cast; ring

lemma lmfdb_1_16_a_orbit_qExpansion_coeff_8 :
    (PowerSeries.coeff (R := ℂ) 8)
      (qExpansion 1 (lmfdb_1_16_a_orbit : ℍ → ℂ)) = (-4078080) := by
  rw [lmfdb_1_16_a_orbit_coeff_decomp,
    f_16_part_0_qExpansion_coeff 10 8 (by decide),
    f_16_part_0_evalEisList_eq,
    show f_16_part_0_qExpList.getD 8 0 = ((-4078080) : ℚ) from by decide +kernel]
  push_cast; ring

lemma lmfdb_1_16_a_orbit_qExpansion_coeff_9 :
    (PowerSeries.coeff (R := ℂ) 9)
      (qExpansion 1 (lmfdb_1_16_a_orbit : ℍ → ℂ)) = (-3139803) := by
  rw [lmfdb_1_16_a_orbit_coeff_decomp,
    f_16_part_0_qExpansion_coeff 10 9 (by decide),
    f_16_part_0_evalEisList_eq,
    show f_16_part_0_qExpList.getD 9 0 = ((-3139803) : ℚ) from by decide +kernel]
  push_cast; ring


/-! ## Uniqueness theorem -/


/-- **Uniqueness theorem.** Any level-1 weight-16 modular form `f` whose first 2
q-coefficients match the LMFDB-published values for `1.16.a.{a..}` is equal to our
explicit construction `lmfdb_1_16_a_orbit`. Proven via `ModularForm.eq_of_sturm_bound`. -/
theorem identifies_lmfdb_1_16_a_orbit (f : ModularForm 𝒮ℒ 16)
    (h_0 : (PowerSeries.coeff (R := ℂ) 0) (qExpansion 1 (f : ℍ → ℂ)) = 0)
    (h_1 : (PowerSeries.coeff (R := ℂ) 1) (qExpansion 1 (f : ℍ → ℂ)) = 1) :
    f = lmfdb_1_16_a_orbit := by
  apply ModularForm.eq_of_sturm_bound
  intro i hi
  have : i ≤ 1 := by omega
  interval_cases i
  · rw [h_0, lmfdb_1_16_a_orbit_qExpansion_coeff_0]
  · rw [h_1, lmfdb_1_16_a_orbit_qExpansion_coeff_1]


end LeanBridge.QExpansion.LMFDB.W16