import LeanBridge.ForMathlib.QExpansion.IntEval

set_option maxHeartbeats 0
set_option maxRecDepth 4000

/-!
# LMFDB level-1 weight-60 form `1.60.a`, piece 2: integer q-coefficient certificate

Heavy `decide +kernel` over `ℤ` (denominators cleared by the scale `D = 46096257977782929421108500234240`), isolated in its own
module so `lake` schedules it in parallel with the other pieces. Generated by
`scripts/lmfdb_qexp_to_e4e6_v3.sage`.
-/

namespace LeanBridge.QExpansion.LMFDB.W60

open LeanBridge.QExpansion

def f_60_part_2_polyDataZ : List (ℕ × ℕ × ℤ) :=
  [(0, 10, (-14832138603393380713)), (3, 8, 76006900996212137465), (6, 6, (-159904694726028248170)), (9, 4, 171994064234745726850), (12, 2, (-94140955259288355485)), (15, 0, 20876823357752120053)]

def f_60_part_2_scale : ℤ := 46096257977782929421108500234240

def f_60_part_2_qExpListZ : List ℤ :=
  [0, 0, 0, 21663217972558987939157114880, 46096257977782929421108500234240, 255596272980786462388506490048610304, (-20499772947534923702723230497578680320), 2483019311268614670437311425507030466560, 0, 3845458961486839574397386958175233260912640]

/-- Integer-arithmetic certificate (the heavy kernel computation). -/
lemma f_60_part_2_evalEisListZ_eq :
    evalEisListZ f_60_part_2_polyDataZ 10 = f_60_part_2_qExpListZ := by
  decide +kernel

end LeanBridge.QExpansion.LMFDB.W60
