import LeanBridge.ForMathlib.QExpansion.IntEval

set_option maxHeartbeats 0
set_option maxRecDepth 4000

/-!
# LMFDB level-1 weight-46 form `1.46.a`, piece 0: integer q-coefficient certificate

Heavy `decide +kernel` over `ℤ` (denominators cleared by the scale `D = 5225472`), isolated in its own
module so `lake` schedules it in parallel with the other pieces. Generated by
`scripts/lmfdb_qexp_to_e4e6_v3.sage`.
-/

namespace LeanBridge.QExpansion.LMFDB.W46

open LeanBridge.QExpansion

def f_46_part_0_polyDataZ : List (ℕ × ℕ × ℤ) :=
  [(1, 7, (-106048709)), (4, 5, 318144111), (7, 3, (-318145119)), (10, 1, 106049717)]

def f_46_part_0_scale : ℤ := 5225472

def f_46_part_0_qExpListZ : List ℤ :=
  [0, 5225472, 0, 547187331149180928, (-183854951187773128704), (-62346595200266561771520), 2103412392149563490697216, (-8985735862171362254757888), (-706746563762253332874264576), 17608309839819648815026129920]

/-- Integer-arithmetic certificate (the heavy kernel computation). -/
lemma f_46_part_0_evalEisListZ_eq :
    evalEisListZ f_46_part_0_polyDataZ 10 = f_46_part_0_qExpListZ := by
  decide +kernel

end LeanBridge.QExpansion.LMFDB.W46
