import LeanBridge.ForMathlib.QExpansion.IntEval

set_option maxHeartbeats 0
set_option maxRecDepth 4000

/-!
# LMFDB level-1 weight-22 form `1.22.a`, piece 0: integer q-coefficient certificate

Heavy `decide +kernel` over `ℤ` (denominators cleared by the scale `D = 1728`), isolated in its own
module so `lake` schedules it in parallel with the other pieces. Generated by
`scripts/lmfdb_qexp_to_e4e6_v3.sage`.
-/

namespace LeanBridge.QExpansion.LMFDB.W22

open LeanBridge.QExpansion

def f_22_part_0_polyDataZ : List (ℕ × ℕ × ℤ) :=
  [(1, 3, (-1)), (4, 1, 1)]

def f_22_part_0_scale : ℤ := 1728

def f_22_part_0_qExpListZ : List ℤ :=
  [0, 1728, (-497664), (-222642432), (-3480551424), 37395561600, 64121020416, (-1327240180224), 2046075863040, 10610651173824]

/-- Integer-arithmetic certificate (the heavy kernel computation). -/
lemma f_22_part_0_evalEisListZ_eq :
    evalEisListZ f_22_part_0_polyDataZ 10 = f_22_part_0_qExpListZ := by
  decide +kernel

end LeanBridge.QExpansion.LMFDB.W22
