import LeanBridge.ForMathlib.QExpansion.Generic
import LeanBridge.ForMathlib.QExpansion.Sturm
import Mathlib.Analysis.Complex.Polynomial.Basic

/-!
# LMFDB level-1 modular form orbit `1.74.a.{a..}` (Hecke field degree 5)

The Hecke field `K = ℚ(α)` is degree 5 over ℚ. The LMFDB lists q-coefficients as
elements of `K`, which we decompose as `c_0 + c_1 · α + … + c_{4} · α^4`.
The combined form is `f = f_0 + α · f_1 + … + α^4 · f_{4}`, with each
`f_j` a level-1 weight-74 form with rational coefficients in `(E₄, E₆)`.

The Sturm bound for weight 74 is `⌊74/12⌋ + 1 = 7`. After certifying agreement
on the first 7 q-coefficients, `ModularForm.eq_of_sturm_bound` lets us conclude that any
form with the same coefficients equals our explicit `lmfdb_1_74_a_orbit`.

Generated by `scripts/lmfdb_qexp_to_e4e6_v3.sage`.
-/

namespace LeanBridge.QExpansion.LMFDB.W74

open LeanBridge.QExpansion ModularForm EisensteinSeries PowerSeries UpperHalfPlane
open scoped MatrixGroups


/-- Minimal polynomial of α (degree 5) as `Polynomial ℂ`. -/
noncomputable def α_74_minpoly : Polynomial ℂ :=
  Polynomial.X ^ 5 +
    Polynomial.C 113628227457643966226006850359168010340399423074336768 +
    Polynomial.C 11802708847432637761332792635527627366465536 * Polynomial.X +
    Polynomial.C (-1377989142595747748686715833810944) * Polynomial.X ^ 2 +
    Polynomial.C (-19817164982845968703488) * Polynomial.X ^ 3 +
    Polynomial.C 92089333488 * Polynomial.X ^ 4

lemma α_74_minpoly_natDegree : α_74_minpoly.natDegree = 5 := by
  unfold α_74_minpoly
  compute_degree!

lemma α_74_minpoly_degree_ne_zero : α_74_minpoly.degree ≠ 0 := by
  rw [Polynomial.degree_eq_natDegree (fun h => by
    have := α_74_minpoly_natDegree
    rw [h, Polynomial.natDegree_zero] at this
    exact absurd this (by decide))]
  rw [α_74_minpoly_natDegree]
  decide

/-- α is some root of the degree-5 minimal polynomial in ℂ. -/
noncomputable def α_74 : ℂ :=
  (IsAlgClosed.exists_root α_74_minpoly α_74_minpoly_degree_ne_zero).choose

lemma α_74_isRoot : Polynomial.IsRoot α_74_minpoly α_74 :=
  (IsAlgClosed.exists_root α_74_minpoly α_74_minpoly_degree_ne_zero).choose_spec

/-- Explicit polynomial relation: minpoly evaluated at α is zero. -/
lemma α_74_is_root :
    α_74 ^ 5 +
      113628227457643966226006850359168010340399423074336768 +
      11802708847432637761332792635527627366465536 * α_74 +
      (-1377989142595747748686715833810944) * α_74 ^ 2 +
      (-19817164982845968703488) * α_74 ^ 3 +
      92089333488 * α_74 ^ 4 = 0 := by
  have h := α_74_isRoot
  unfold Polynomial.IsRoot α_74_minpoly at h
  simp only [Polynomial.eval_add, Polynomial.eval_mul, Polynomial.eval_pow,
    Polynomial.eval_C, Polynomial.eval_X] at h
  linear_combination h


/-! ## Piece 0: coefficient of α^0 -/


def f_74_part_0_polyData : List (ℕ × ℕ × ℚ) :=
  [(2, 11, ((-(733953962390113312269988643212656431 / 373329098161221752900517888)))), (5, 9, (3264645112664831727038948401295707819 / 373329098161221752900517888)), (8, 7, ((-(2865731086951031141729514996335208307 / 186664549080610876450258944)))), (11, 5, (2473027734808987766963635091560664707 / 186664549080610876450258944)), (14, 3, ((-(298076436605534373030729577134206029 / 53332728308745964700073984)))), (17, 1, (341250610248108945977907091405478015 / 373329098161221752900517888))]

noncomputable def f_74_part_0 : ModularForm 𝒮ℒ 74 :=
  (((-(733953962390113312269988643212656431 / 373329098161221752900517888))) : ℂ) • mkMonomForm 2 11 74 (by decide) +
  ((3264645112664831727038948401295707819 / 373329098161221752900517888) : ℂ) • mkMonomForm 5 9 74 (by decide) +
  (((-(2865731086951031141729514996335208307 / 186664549080610876450258944))) : ℂ) • mkMonomForm 8 7 74 (by decide) +
  ((2473027734808987766963635091560664707 / 186664549080610876450258944) : ℂ) • mkMonomForm 11 5 74 (by decide) +
  (((-(298076436605534373030729577134206029 / 53332728308745964700073984))) : ℂ) • mkMonomForm 14 3 74 (by decide) +
  ((341250610248108945977907091405478015 / 373329098161221752900517888) : ℂ) • mkMonomForm 17 1 74 (by decide)

lemma f_74_part_0_qExpansion_eq_evalEisPS :
    qExpansion 1 (f_74_part_0 : ℍ → ℂ) = evalEisPS f_74_part_0_polyData := by
  unfold f_74_part_0
  rw [ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm]
  unfold evalEisPS f_74_part_0_polyData monomialEisPS
  simp only [List.foldr_cons, List.foldr_nil, add_zero]
  push_cast
  module

theorem f_74_part_0_qExpansion_coeff (N n : ℕ) (hn : n < N) :
    (PowerSeries.coeff (R := ℂ) n) (qExpansion 1 (f_74_part_0 : ℍ → ℂ))
      = ((evalEisList f_74_part_0_polyData N).getD n 0 : ℚ) :=
  qexp_coeff_via_E4E6 _ _ f_74_part_0_qExpansion_eq_evalEisPS N n hn

/-- Precomputed first 10 q-coefficients of `f_74_part_0` (rational). -/
def f_74_part_0_qExpList : List ℚ :=
  [0, 1, 0, (1226799717895646509499387014878484 / 7146042501720717), (-9444732965739290427392), (6505083793904547093507416112771892378986 / 264668240804471), ((-(1170384499441457319163036698806095867543552 / 340287738177177))), ((-(156124026603759774847802166828485974021391672 / 37809748686353))), 0, (558240485131555151730364581391960694243859772123 / 5401392669479)]

/-- One-shot bridge: the symbolic `evalEisList` equals the precomputed list (verified by
`decide +kernel` once instead of N times). -/
lemma f_74_part_0_evalEisList_eq :
    evalEisList f_74_part_0_polyData 10 = f_74_part_0_qExpList := by
  decide +kernel


/-! ## Piece 1: coefficient of α^1 -/


def f_74_part_1_polyData : List (ℕ × ℕ × ℚ) :=
  [(2, 11, ((-(676556669837575461639704081365 / 8155498592364609599362780102656)))), (5, 9, (3433705874698000620619295202137 / 8155498592364609599362780102656)), (8, 7, ((-(3451891465967054257160466055457 / 4077749296182304799681390051328)))), (11, 5, (3437341488625026919136172520577 / 4077749296182304799681390051328)), (14, 3, ((-(3390057308301907307860554151289 / 8155498592364609599362780102656)))), (17, 1, (662008058125536824929550100277 / 8155498592364609599362780102656))]

noncomputable def f_74_part_1 : ModularForm 𝒮ℒ 74 :=
  (((-(676556669837575461639704081365 / 8155498592364609599362780102656))) : ℂ) • mkMonomForm 2 11 74 (by decide) +
  ((3433705874698000620619295202137 / 8155498592364609599362780102656) : ℂ) • mkMonomForm 5 9 74 (by decide) +
  (((-(3451891465967054257160466055457 / 4077749296182304799681390051328))) : ℂ) • mkMonomForm 8 7 74 (by decide) +
  ((3437341488625026919136172520577 / 4077749296182304799681390051328) : ℂ) • mkMonomForm 11 5 74 (by decide) +
  (((-(3390057308301907307860554151289 / 8155498592364609599362780102656))) : ℂ) • mkMonomForm 14 3 74 (by decide) +
  ((662008058125536824929550100277 / 8155498592364609599362780102656) : ℂ) • mkMonomForm 17 1 74 (by decide)

lemma f_74_part_1_qExpansion_eq_evalEisPS :
    qExpansion 1 (f_74_part_1 : ℍ → ℂ) = evalEisPS f_74_part_1_polyData := by
  unfold f_74_part_1
  rw [ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm]
  unfold evalEisPS f_74_part_1_polyData monomialEisPS
  simp only [List.foldr_cons, List.foldr_nil, add_zero]
  push_cast
  module

theorem f_74_part_1_qExpansion_coeff (N n : ℕ) (hn : n < N) :
    (PowerSeries.coeff (R := ℂ) n) (qExpansion 1 (f_74_part_1 : ℍ → ℂ))
      = ((evalEisList f_74_part_1_polyData N).getD n 0 : ℚ) :=
  qexp_coeff_via_E4E6 _ _ f_74_part_1_qExpansion_eq_evalEisPS N n hn

/-- Precomputed first 10 q-coefficients of `f_74_part_1` (rational). -/
def f_74_part_1_qExpList : List ℚ :=
  [0, 0, 1, ((-(7216773391718105921153435 / 174227321946714624))), 0, (43664618447950799903495778236885 / 33877534822972288), ((-(147350690343520690919225390444300 / 794004722413413))), ((-(2327194245548299870082354398532765163 / 9679295663706368))), (-18889465931478580854784), (852772269630348217765789512514102396275 / 345689130846656)]

/-- One-shot bridge: the symbolic `evalEisList` equals the precomputed list (verified by
`decide +kernel` once instead of N times). -/
lemma f_74_part_1_evalEisList_eq :
    evalEisList f_74_part_1_polyData 10 = f_74_part_1_qExpList := by
  decide +kernel


/-! ## Piece 2: coefficient of α^2 -/


def f_74_part_2_polyData : List (ℕ × ℕ × ℚ) :=
  [(2, 11, (165592367373808864318177 / 901932900326786904812728577112932352)), (5, 9, ((-(646598238886215518515925 / 901932900326786904812728577112932352)))), (8, 7, (516795525858952177438973 / 450966450163393452406364288556466176)), (11, 5, ((-(438553697787254298360029 / 450966450163393452406364288556466176)))), (14, 3, (58838964953017411611299 / 128847557189540986401818368158990336)), (17, 1, ((-(87350539302110985239233 / 901932900326786904812728577112932352))))]

noncomputable def f_74_part_2 : ModularForm 𝒮ℒ 74 :=
  ((165592367373808864318177 / 901932900326786904812728577112932352) : ℂ) • mkMonomForm 2 11 74 (by decide) +
  (((-(646598238886215518515925 / 901932900326786904812728577112932352))) : ℂ) • mkMonomForm 5 9 74 (by decide) +
  ((516795525858952177438973 / 450966450163393452406364288556466176) : ℂ) • mkMonomForm 8 7 74 (by decide) +
  (((-(438553697787254298360029 / 450966450163393452406364288556466176))) : ℂ) • mkMonomForm 11 5 74 (by decide) +
  ((58838964953017411611299 / 128847557189540986401818368158990336) : ℂ) • mkMonomForm 14 3 74 (by decide) +
  (((-(87350539302110985239233 / 901932900326786904812728577112932352))) : ℂ) • mkMonomForm 17 1 74 (by decide)

lemma f_74_part_2_qExpansion_eq_evalEisPS :
    qExpansion 1 (f_74_part_2 : ℍ → ℂ) = evalEisPS f_74_part_2_polyData := by
  unfold f_74_part_2
  rw [ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm]
  unfold evalEisPS f_74_part_2_polyData monomialEisPS
  simp only [List.foldr_cons, List.foldr_nil, add_zero]
  push_cast
  module

theorem f_74_part_2_qExpansion_coeff (N n : ℕ) (hn : n < N) :
    (PowerSeries.coeff (R := ℂ) n) (qExpansion 1 (f_74_part_2 : ℍ → ℂ))
      = ((evalEisList f_74_part_2_polyData N).getD n 0 : ℚ) :=
  qexp_coeff_via_E4E6 _ _ f_74_part_2_qExpansion_eq_evalEisPS N n hn

/-- Precomputed first 10 q-coefficients of `f_74_part_2` (rational). -/
def f_74_part_2_qExpList : List ℚ :=
  [0, 0, 0, ((-(79569266906736824071 / 134877035921117445881856))), 1, ((-(287965665179159370287139 / 138762382634894491648))), (28280006506805753583343 / 98002868595026976), (13566856725639677107918812701 / 39646395038541283328), 0, ((-(60660593756223174909783916573181 / 12743484119531126784)))]

/-- One-shot bridge: the symbolic `evalEisList` equals the precomputed list (verified by
`decide +kernel` once instead of N times). -/
lemma f_74_part_2_evalEisList_eq :
    evalEisList f_74_part_2_polyData 10 = f_74_part_2_qExpList := by
  decide +kernel


/-! ## Piece 3: coefficient of α^3 -/


def f_74_part_3_polyData : List (ℕ × ℕ × ℚ) :=
  [(2, 11, (679973695484705 / 153929881655771631754705677160607121408)), (5, 9, ((-(3464638747015189 / 153929881655771631754705677160607121408)))), (8, 7, (3487770986155069 / 76964940827885815877352838580303560704)), (11, 5, ((-(3469265194843165 / 76964940827885815877352838580303560704)))), (14, 3, (3409121373079477 / 153929881655771631754705677160607121408)), (17, 1, ((-(661467904172801 / 153929881655771631754705677160607121408))))]

noncomputable def f_74_part_3 : ModularForm 𝒮ℒ 74 :=
  ((679973695484705 / 153929881655771631754705677160607121408) : ℂ) • mkMonomForm 2 11 74 (by decide) +
  (((-(3464638747015189 / 153929881655771631754705677160607121408))) : ℂ) • mkMonomForm 5 9 74 (by decide) +
  ((3487770986155069 / 76964940827885815877352838580303560704) : ℂ) • mkMonomForm 8 7 74 (by decide) +
  (((-(3469265194843165 / 76964940827885815877352838580303560704))) : ℂ) • mkMonomForm 11 5 74 (by decide) +
  ((3409121373079477 / 153929881655771631754705677160607121408) : ℂ) • mkMonomForm 14 3 74 (by decide) +
  (((-(661467904172801 / 153929881655771631754705677160607121408))) : ℂ) • mkMonomForm 17 1 74 (by decide)

lemma f_74_part_3_qExpansion_eq_evalEisPS :
    qExpansion 1 (f_74_part_3 : ℍ → ℂ) = evalEisPS f_74_part_3_polyData := by
  unfold f_74_part_3
  rw [ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm]
  unfold evalEisPS f_74_part_3_polyData monomialEisPS
  simp only [List.foldr_cons, List.foldr_nil, add_zero]
  push_cast
  module

theorem f_74_part_3_qExpansion_coeff (N n : ℕ) (hn : n < N) :
    (PowerSeries.coeff (R := ℂ) n) (qExpansion 1 (f_74_part_3 : ℍ → ℂ))
      = ((evalEisList f_74_part_3_polyData N).getD n 0 : ℚ) :=
  qexp_coeff_via_E4E6 _ _ f_74_part_3_qExpansion_eq_evalEisPS N n hn

/-- Precomputed first 10 q-coefficients of `f_74_part_3` (rational). -/
def f_74_part_3_qExpList : List ℚ :=
  [0, 0, 0, (64256219833 / 23019014130537377430503424), 0, ((-(698135995227215 / 10149477129866568531968))), (1159523732417825 / 117080760348192227328), (260389403324005164183 / 20298954259733137063936), 1, ((-(298108325129471845505725 / 2174887956399978971136)))]

/-- One-shot bridge: the symbolic `evalEisList` equals the precomputed list (verified by
`decide +kernel` once instead of N times). -/
lemma f_74_part_3_evalEisList_eq :
    evalEisList f_74_part_3_polyData 10 = f_74_part_3_qExpList := by
  decide +kernel


/-! ## Piece 4: coefficient of α^4 -/


def f_74_part_4_polyData : List (ℕ × ℕ × ℚ) :=
  [(2, 11, (86453 / 66497708875293344918032852533382276448256)), (5, 9, ((-(735673 / 66497708875293344918032852533382276448256)))), (8, 7, (844033 / 33248854437646672459016426266691138224128)), (11, 5, ((-(757345 / 33248854437646672459016426266691138224128)))), (14, 3, (475609 / 66497708875293344918032852533382276448256)), (17, 1, (235 / 66497708875293344918032852533382276448256))]

noncomputable def f_74_part_4 : ModularForm 𝒮ℒ 74 :=
  ((86453 / 66497708875293344918032852533382276448256) : ℂ) • mkMonomForm 2 11 74 (by decide) +
  (((-(735673 / 66497708875293344918032852533382276448256))) : ℂ) • mkMonomForm 5 9 74 (by decide) +
  ((844033 / 33248854437646672459016426266691138224128) : ℂ) • mkMonomForm 8 7 74 (by decide) +
  (((-(757345 / 33248854437646672459016426266691138224128))) : ℂ) • mkMonomForm 11 5 74 (by decide) +
  ((475609 / 66497708875293344918032852533382276448256) : ℂ) • mkMonomForm 14 3 74 (by decide) +
  ((235 / 66497708875293344918032852533382276448256) : ℂ) • mkMonomForm 17 1 74 (by decide)

lemma f_74_part_4_qExpansion_eq_evalEisPS :
    qExpansion 1 (f_74_part_4 : ℍ → ℂ) = evalEisPS f_74_part_4_polyData := by
  unfold f_74_part_4
  rw [ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm]
  unfold evalEisPS f_74_part_4_polyData monomialEisPS
  simp only [List.foldr_cons, List.foldr_nil, add_zero]
  push_cast
  module

theorem f_74_part_4_qExpansion_coeff (N n : ℕ) (hn : n < N) :
    (PowerSeries.coeff (R := ℂ) n) (qExpansion 1 (f_74_part_4 : ℍ → ℂ))
      = ((evalEisList f_74_part_4_polyData N).getD n 0 : ℚ) :=
  qexp_coeff_via_E4E6 _ _ f_74_part_4_qExpansion_eq_evalEisPS N n hn

/-- Precomputed first 10 q-coefficients of `f_74_part_4` (rational). -/
def f_74_part_4_qExpList : List ℚ :=
  [0, 0, 0, (43 / 1420602014913163864282497024), 0, ((-(31719 / 1136741438545055675580416))), (202421 / 50578888470419042205696), (1633412441 / 324783268155730193022976), 0, ((-(307519596773761 / 939551597164790915530752)))]

/-- One-shot bridge: the symbolic `evalEisList` equals the precomputed list (verified by
`decide +kernel` once instead of N times). -/
lemma f_74_part_4_evalEisList_eq :
    evalEisList f_74_part_4_polyData 10 = f_74_part_4_qExpList := by
  decide +kernel


/-! ## Combined LMFDB form -/


noncomputable def lmfdb_1_74_a_orbit : ModularForm 𝒮ℒ 74 :=
  f_74_part_0 +
  α_74 • f_74_part_1 +
  α_74 ^ 2 • f_74_part_2 +
  α_74 ^ 3 • f_74_part_3 +
  α_74 ^ 4 • f_74_part_4

lemma lmfdb_1_74_a_orbit_coeff_decomp (n : ℕ) :
    (PowerSeries.coeff (R := ℂ) n) (qExpansion 1 (lmfdb_1_74_a_orbit : ℍ → ℂ))
      = (PowerSeries.coeff (R := ℂ) n) (qExpansion 1 (f_74_part_0 : ℍ → ℂ))
        + α_74 * (PowerSeries.coeff (R := ℂ) n) (qExpansion 1 (f_74_part_1 : ℍ → ℂ))
        + α_74 ^ 2 * (PowerSeries.coeff (R := ℂ) n) (qExpansion 1 (f_74_part_2 : ℍ → ℂ))
        + α_74 ^ 3 * (PowerSeries.coeff (R := ℂ) n) (qExpansion 1 (f_74_part_3 : ℍ → ℂ))
        + α_74 ^ 4 * (PowerSeries.coeff (R := ℂ) n) (qExpansion 1 (f_74_part_4 : ℍ → ℂ)) := by
  unfold lmfdb_1_74_a_orbit
  rw [ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL]
  simp [smul_eq_mul]


/-! ## Coefficient lemmas (n = 0, …, 9)

Sturm bound is 7; we certify 10 coefficients for added
redundancy beyond the minimum mathematically required for uniqueness. -/


lemma lmfdb_1_74_a_orbit_qExpansion_coeff_0 :
    (PowerSeries.coeff (R := ℂ) 0)
      (qExpansion 1 (lmfdb_1_74_a_orbit : ℍ → ℂ)) = 0 := by
  rw [lmfdb_1_74_a_orbit_coeff_decomp,
    f_74_part_0_qExpansion_coeff 10 0 (by decide),
    f_74_part_1_qExpansion_coeff 10 0 (by decide),
    f_74_part_2_qExpansion_coeff 10 0 (by decide),
    f_74_part_3_qExpansion_coeff 10 0 (by decide),
    f_74_part_4_qExpansion_coeff 10 0 (by decide),
    f_74_part_0_evalEisList_eq,
    f_74_part_1_evalEisList_eq,
    f_74_part_2_evalEisList_eq,
    f_74_part_3_evalEisList_eq,
    f_74_part_4_evalEisList_eq,
    show f_74_part_0_qExpList.getD 0 0 = (0 : ℚ) from by decide +kernel,
    show f_74_part_1_qExpList.getD 0 0 = (0 : ℚ) from by decide +kernel,
    show f_74_part_2_qExpList.getD 0 0 = (0 : ℚ) from by decide +kernel,
    show f_74_part_3_qExpList.getD 0 0 = (0 : ℚ) from by decide +kernel,
    show f_74_part_4_qExpList.getD 0 0 = (0 : ℚ) from by decide +kernel]
  push_cast; ring

lemma lmfdb_1_74_a_orbit_qExpansion_coeff_1 :
    (PowerSeries.coeff (R := ℂ) 1)
      (qExpansion 1 (lmfdb_1_74_a_orbit : ℍ → ℂ)) = 1 := by
  rw [lmfdb_1_74_a_orbit_coeff_decomp,
    f_74_part_0_qExpansion_coeff 10 1 (by decide),
    f_74_part_1_qExpansion_coeff 10 1 (by decide),
    f_74_part_2_qExpansion_coeff 10 1 (by decide),
    f_74_part_3_qExpansion_coeff 10 1 (by decide),
    f_74_part_4_qExpansion_coeff 10 1 (by decide),
    f_74_part_0_evalEisList_eq,
    f_74_part_1_evalEisList_eq,
    f_74_part_2_evalEisList_eq,
    f_74_part_3_evalEisList_eq,
    f_74_part_4_evalEisList_eq,
    show f_74_part_0_qExpList.getD 1 0 = (1 : ℚ) from by decide +kernel,
    show f_74_part_1_qExpList.getD 1 0 = (0 : ℚ) from by decide +kernel,
    show f_74_part_2_qExpList.getD 1 0 = (0 : ℚ) from by decide +kernel,
    show f_74_part_3_qExpList.getD 1 0 = (0 : ℚ) from by decide +kernel,
    show f_74_part_4_qExpList.getD 1 0 = (0 : ℚ) from by decide +kernel]
  push_cast; ring

lemma lmfdb_1_74_a_orbit_qExpansion_coeff_2 :
    (PowerSeries.coeff (R := ℂ) 2)
      (qExpansion 1 (lmfdb_1_74_a_orbit : ℍ → ℂ)) = 1 * α_74 := by
  rw [lmfdb_1_74_a_orbit_coeff_decomp,
    f_74_part_0_qExpansion_coeff 10 2 (by decide),
    f_74_part_1_qExpansion_coeff 10 2 (by decide),
    f_74_part_2_qExpansion_coeff 10 2 (by decide),
    f_74_part_3_qExpansion_coeff 10 2 (by decide),
    f_74_part_4_qExpansion_coeff 10 2 (by decide),
    f_74_part_0_evalEisList_eq,
    f_74_part_1_evalEisList_eq,
    f_74_part_2_evalEisList_eq,
    f_74_part_3_evalEisList_eq,
    f_74_part_4_evalEisList_eq,
    show f_74_part_0_qExpList.getD 2 0 = (0 : ℚ) from by decide +kernel,
    show f_74_part_1_qExpList.getD 2 0 = (1 : ℚ) from by decide +kernel,
    show f_74_part_2_qExpList.getD 2 0 = (0 : ℚ) from by decide +kernel,
    show f_74_part_3_qExpList.getD 2 0 = (0 : ℚ) from by decide +kernel,
    show f_74_part_4_qExpList.getD 2 0 = (0 : ℚ) from by decide +kernel]
  push_cast; ring

lemma lmfdb_1_74_a_orbit_qExpansion_coeff_3 :
    (PowerSeries.coeff (R := ℂ) 3)
      (qExpansion 1 (lmfdb_1_74_a_orbit : ℍ → ℂ)) = (1226799717895646509499387014878484 / 7146042501720717) + ((-(7216773391718105921153435 / 174227321946714624))) * α_74 + ((-(79569266906736824071 / 134877035921117445881856))) * α_74 ^ 2 + (64256219833 / 23019014130537377430503424) * α_74 ^ 3 + (43 / 1420602014913163864282497024) * α_74 ^ 4 := by
  rw [lmfdb_1_74_a_orbit_coeff_decomp,
    f_74_part_0_qExpansion_coeff 10 3 (by decide),
    f_74_part_1_qExpansion_coeff 10 3 (by decide),
    f_74_part_2_qExpansion_coeff 10 3 (by decide),
    f_74_part_3_qExpansion_coeff 10 3 (by decide),
    f_74_part_4_qExpansion_coeff 10 3 (by decide),
    f_74_part_0_evalEisList_eq,
    f_74_part_1_evalEisList_eq,
    f_74_part_2_evalEisList_eq,
    f_74_part_3_evalEisList_eq,
    f_74_part_4_evalEisList_eq,
    show f_74_part_0_qExpList.getD 3 0 = ((1226799717895646509499387014878484 / 7146042501720717) : ℚ) from by decide +kernel,
    show f_74_part_1_qExpList.getD 3 0 = (((-(7216773391718105921153435 / 174227321946714624))) : ℚ) from by decide +kernel,
    show f_74_part_2_qExpList.getD 3 0 = (((-(79569266906736824071 / 134877035921117445881856))) : ℚ) from by decide +kernel,
    show f_74_part_3_qExpList.getD 3 0 = ((64256219833 / 23019014130537377430503424) : ℚ) from by decide +kernel,
    show f_74_part_4_qExpList.getD 3 0 = ((43 / 1420602014913163864282497024) : ℚ) from by decide +kernel]
  push_cast; ring

lemma lmfdb_1_74_a_orbit_qExpansion_coeff_4 :
    (PowerSeries.coeff (R := ℂ) 4)
      (qExpansion 1 (lmfdb_1_74_a_orbit : ℍ → ℂ)) = (-9444732965739290427392) + 1 * α_74 ^ 2 := by
  rw [lmfdb_1_74_a_orbit_coeff_decomp,
    f_74_part_0_qExpansion_coeff 10 4 (by decide),
    f_74_part_1_qExpansion_coeff 10 4 (by decide),
    f_74_part_2_qExpansion_coeff 10 4 (by decide),
    f_74_part_3_qExpansion_coeff 10 4 (by decide),
    f_74_part_4_qExpansion_coeff 10 4 (by decide),
    f_74_part_0_evalEisList_eq,
    f_74_part_1_evalEisList_eq,
    f_74_part_2_evalEisList_eq,
    f_74_part_3_evalEisList_eq,
    f_74_part_4_evalEisList_eq,
    show f_74_part_0_qExpList.getD 4 0 = ((-9444732965739290427392) : ℚ) from by decide +kernel,
    show f_74_part_1_qExpList.getD 4 0 = (0 : ℚ) from by decide +kernel,
    show f_74_part_2_qExpList.getD 4 0 = (1 : ℚ) from by decide +kernel,
    show f_74_part_3_qExpList.getD 4 0 = (0 : ℚ) from by decide +kernel,
    show f_74_part_4_qExpList.getD 4 0 = (0 : ℚ) from by decide +kernel]
  push_cast; ring

lemma lmfdb_1_74_a_orbit_qExpansion_coeff_5 :
    (PowerSeries.coeff (R := ℂ) 5)
      (qExpansion 1 (lmfdb_1_74_a_orbit : ℍ → ℂ)) = (6505083793904547093507416112771892378986 / 264668240804471) + (43664618447950799903495778236885 / 33877534822972288) * α_74 + ((-(287965665179159370287139 / 138762382634894491648))) * α_74 ^ 2 + ((-(698135995227215 / 10149477129866568531968))) * α_74 ^ 3 + ((-(31719 / 1136741438545055675580416))) * α_74 ^ 4 := by
  rw [lmfdb_1_74_a_orbit_coeff_decomp,
    f_74_part_0_qExpansion_coeff 10 5 (by decide),
    f_74_part_1_qExpansion_coeff 10 5 (by decide),
    f_74_part_2_qExpansion_coeff 10 5 (by decide),
    f_74_part_3_qExpansion_coeff 10 5 (by decide),
    f_74_part_4_qExpansion_coeff 10 5 (by decide),
    f_74_part_0_evalEisList_eq,
    f_74_part_1_evalEisList_eq,
    f_74_part_2_evalEisList_eq,
    f_74_part_3_evalEisList_eq,
    f_74_part_4_evalEisList_eq,
    show f_74_part_0_qExpList.getD 5 0 = ((6505083793904547093507416112771892378986 / 264668240804471) : ℚ) from by decide +kernel,
    show f_74_part_1_qExpList.getD 5 0 = ((43664618447950799903495778236885 / 33877534822972288) : ℚ) from by decide +kernel,
    show f_74_part_2_qExpList.getD 5 0 = (((-(287965665179159370287139 / 138762382634894491648))) : ℚ) from by decide +kernel,
    show f_74_part_3_qExpList.getD 5 0 = (((-(698135995227215 / 10149477129866568531968))) : ℚ) from by decide +kernel,
    show f_74_part_4_qExpList.getD 5 0 = (((-(31719 / 1136741438545055675580416))) : ℚ) from by decide +kernel]
  push_cast; ring

lemma lmfdb_1_74_a_orbit_qExpansion_coeff_6 :
    (PowerSeries.coeff (R := ℂ) 6)
      (qExpansion 1 (lmfdb_1_74_a_orbit : ℍ → ℂ)) = ((-(1170384499441457319163036698806095867543552 / 340287738177177))) + ((-(147350690343520690919225390444300 / 794004722413413))) * α_74 + (28280006506805753583343 / 98002868595026976) * α_74 ^ 2 + (1159523732417825 / 117080760348192227328) * α_74 ^ 3 + (202421 / 50578888470419042205696) * α_74 ^ 4 := by
  rw [lmfdb_1_74_a_orbit_coeff_decomp,
    f_74_part_0_qExpansion_coeff 10 6 (by decide),
    f_74_part_1_qExpansion_coeff 10 6 (by decide),
    f_74_part_2_qExpansion_coeff 10 6 (by decide),
    f_74_part_3_qExpansion_coeff 10 6 (by decide),
    f_74_part_4_qExpansion_coeff 10 6 (by decide),
    f_74_part_0_evalEisList_eq,
    f_74_part_1_evalEisList_eq,
    f_74_part_2_evalEisList_eq,
    f_74_part_3_evalEisList_eq,
    f_74_part_4_evalEisList_eq,
    show f_74_part_0_qExpList.getD 6 0 = (((-(1170384499441457319163036698806095867543552 / 340287738177177))) : ℚ) from by decide +kernel,
    show f_74_part_1_qExpList.getD 6 0 = (((-(147350690343520690919225390444300 / 794004722413413))) : ℚ) from by decide +kernel,
    show f_74_part_2_qExpList.getD 6 0 = ((28280006506805753583343 / 98002868595026976) : ℚ) from by decide +kernel,
    show f_74_part_3_qExpList.getD 6 0 = ((1159523732417825 / 117080760348192227328) : ℚ) from by decide +kernel,
    show f_74_part_4_qExpList.getD 6 0 = ((202421 / 50578888470419042205696) : ℚ) from by decide +kernel]
  push_cast; ring

lemma lmfdb_1_74_a_orbit_qExpansion_coeff_7 :
    (PowerSeries.coeff (R := ℂ) 7)
      (qExpansion 1 (lmfdb_1_74_a_orbit : ℍ → ℂ)) = ((-(156124026603759774847802166828485974021391672 / 37809748686353))) + ((-(2327194245548299870082354398532765163 / 9679295663706368))) * α_74 + (13566856725639677107918812701 / 39646395038541283328) * α_74 ^ 2 + (260389403324005164183 / 20298954259733137063936) * α_74 ^ 3 + (1633412441 / 324783268155730193022976) * α_74 ^ 4 := by
  rw [lmfdb_1_74_a_orbit_coeff_decomp,
    f_74_part_0_qExpansion_coeff 10 7 (by decide),
    f_74_part_1_qExpansion_coeff 10 7 (by decide),
    f_74_part_2_qExpansion_coeff 10 7 (by decide),
    f_74_part_3_qExpansion_coeff 10 7 (by decide),
    f_74_part_4_qExpansion_coeff 10 7 (by decide),
    f_74_part_0_evalEisList_eq,
    f_74_part_1_evalEisList_eq,
    f_74_part_2_evalEisList_eq,
    f_74_part_3_evalEisList_eq,
    f_74_part_4_evalEisList_eq,
    show f_74_part_0_qExpList.getD 7 0 = (((-(156124026603759774847802166828485974021391672 / 37809748686353))) : ℚ) from by decide +kernel,
    show f_74_part_1_qExpList.getD 7 0 = (((-(2327194245548299870082354398532765163 / 9679295663706368))) : ℚ) from by decide +kernel,
    show f_74_part_2_qExpList.getD 7 0 = ((13566856725639677107918812701 / 39646395038541283328) : ℚ) from by decide +kernel,
    show f_74_part_3_qExpList.getD 7 0 = ((260389403324005164183 / 20298954259733137063936) : ℚ) from by decide +kernel,
    show f_74_part_4_qExpList.getD 7 0 = ((1633412441 / 324783268155730193022976) : ℚ) from by decide +kernel]
  push_cast; ring

lemma lmfdb_1_74_a_orbit_qExpansion_coeff_8 :
    (PowerSeries.coeff (R := ℂ) 8)
      (qExpansion 1 (lmfdb_1_74_a_orbit : ℍ → ℂ)) = (-18889465931478580854784) * α_74 + 1 * α_74 ^ 3 := by
  rw [lmfdb_1_74_a_orbit_coeff_decomp,
    f_74_part_0_qExpansion_coeff 10 8 (by decide),
    f_74_part_1_qExpansion_coeff 10 8 (by decide),
    f_74_part_2_qExpansion_coeff 10 8 (by decide),
    f_74_part_3_qExpansion_coeff 10 8 (by decide),
    f_74_part_4_qExpansion_coeff 10 8 (by decide),
    f_74_part_0_evalEisList_eq,
    f_74_part_1_evalEisList_eq,
    f_74_part_2_evalEisList_eq,
    f_74_part_3_evalEisList_eq,
    f_74_part_4_evalEisList_eq,
    show f_74_part_0_qExpList.getD 8 0 = (0 : ℚ) from by decide +kernel,
    show f_74_part_1_qExpList.getD 8 0 = ((-18889465931478580854784) : ℚ) from by decide +kernel,
    show f_74_part_2_qExpList.getD 8 0 = (0 : ℚ) from by decide +kernel,
    show f_74_part_3_qExpList.getD 8 0 = (1 : ℚ) from by decide +kernel,
    show f_74_part_4_qExpList.getD 8 0 = (0 : ℚ) from by decide +kernel]
  push_cast; ring

lemma lmfdb_1_74_a_orbit_qExpansion_coeff_9 :
    (PowerSeries.coeff (R := ℂ) 9)
      (qExpansion 1 (lmfdb_1_74_a_orbit : ℍ → ℂ)) = (558240485131555151730364581391960694243859772123 / 5401392669479) + (852772269630348217765789512514102396275 / 345689130846656) * α_74 + ((-(60660593756223174909783916573181 / 12743484119531126784))) * α_74 ^ 2 + ((-(298108325129471845505725 / 2174887956399978971136))) * α_74 ^ 3 + ((-(307519596773761 / 939551597164790915530752))) * α_74 ^ 4 := by
  rw [lmfdb_1_74_a_orbit_coeff_decomp,
    f_74_part_0_qExpansion_coeff 10 9 (by decide),
    f_74_part_1_qExpansion_coeff 10 9 (by decide),
    f_74_part_2_qExpansion_coeff 10 9 (by decide),
    f_74_part_3_qExpansion_coeff 10 9 (by decide),
    f_74_part_4_qExpansion_coeff 10 9 (by decide),
    f_74_part_0_evalEisList_eq,
    f_74_part_1_evalEisList_eq,
    f_74_part_2_evalEisList_eq,
    f_74_part_3_evalEisList_eq,
    f_74_part_4_evalEisList_eq,
    show f_74_part_0_qExpList.getD 9 0 = ((558240485131555151730364581391960694243859772123 / 5401392669479) : ℚ) from by decide +kernel,
    show f_74_part_1_qExpList.getD 9 0 = ((852772269630348217765789512514102396275 / 345689130846656) : ℚ) from by decide +kernel,
    show f_74_part_2_qExpList.getD 9 0 = (((-(60660593756223174909783916573181 / 12743484119531126784))) : ℚ) from by decide +kernel,
    show f_74_part_3_qExpList.getD 9 0 = (((-(298108325129471845505725 / 2174887956399978971136))) : ℚ) from by decide +kernel,
    show f_74_part_4_qExpList.getD 9 0 = (((-(307519596773761 / 939551597164790915530752))) : ℚ) from by decide +kernel]
  push_cast; ring


/-! ## Uniqueness theorem -/


/-- **Uniqueness theorem.** Any level-1 weight-74 modular form `f` whose first 7
q-coefficients match the LMFDB-published values for `1.74.a.{a..}` is equal to our
explicit construction `lmfdb_1_74_a_orbit`. Proven via `ModularForm.eq_of_sturm_bound`. -/
theorem identifies_lmfdb_1_74_a_orbit (f : ModularForm 𝒮ℒ 74)
    (h_0 : (PowerSeries.coeff (R := ℂ) 0) (qExpansion 1 (f : ℍ → ℂ)) = 0)
    (h_1 : (PowerSeries.coeff (R := ℂ) 1) (qExpansion 1 (f : ℍ → ℂ)) = 1)
    (h_2 : (PowerSeries.coeff (R := ℂ) 2) (qExpansion 1 (f : ℍ → ℂ)) = 1 * α_74)
    (h_3 : (PowerSeries.coeff (R := ℂ) 3) (qExpansion 1 (f : ℍ → ℂ)) = (1226799717895646509499387014878484 / 7146042501720717) + ((-(7216773391718105921153435 / 174227321946714624))) * α_74 + ((-(79569266906736824071 / 134877035921117445881856))) * α_74 ^ 2 + (64256219833 / 23019014130537377430503424) * α_74 ^ 3 + (43 / 1420602014913163864282497024) * α_74 ^ 4)
    (h_4 : (PowerSeries.coeff (R := ℂ) 4) (qExpansion 1 (f : ℍ → ℂ)) = (-9444732965739290427392) + 1 * α_74 ^ 2)
    (h_5 : (PowerSeries.coeff (R := ℂ) 5) (qExpansion 1 (f : ℍ → ℂ)) = (6505083793904547093507416112771892378986 / 264668240804471) + (43664618447950799903495778236885 / 33877534822972288) * α_74 + ((-(287965665179159370287139 / 138762382634894491648))) * α_74 ^ 2 + ((-(698135995227215 / 10149477129866568531968))) * α_74 ^ 3 + ((-(31719 / 1136741438545055675580416))) * α_74 ^ 4)
    (h_6 : (PowerSeries.coeff (R := ℂ) 6) (qExpansion 1 (f : ℍ → ℂ)) = ((-(1170384499441457319163036698806095867543552 / 340287738177177))) + ((-(147350690343520690919225390444300 / 794004722413413))) * α_74 + (28280006506805753583343 / 98002868595026976) * α_74 ^ 2 + (1159523732417825 / 117080760348192227328) * α_74 ^ 3 + (202421 / 50578888470419042205696) * α_74 ^ 4) :
    f = lmfdb_1_74_a_orbit := by
  apply ModularForm.eq_of_sturm_bound
  intro i hi
  have : i ≤ 6 := by omega
  interval_cases i
  · rw [h_0, lmfdb_1_74_a_orbit_qExpansion_coeff_0]
  · rw [h_1, lmfdb_1_74_a_orbit_qExpansion_coeff_1]
  · rw [h_2, lmfdb_1_74_a_orbit_qExpansion_coeff_2]
  · rw [h_3, lmfdb_1_74_a_orbit_qExpansion_coeff_3]
  · rw [h_4, lmfdb_1_74_a_orbit_qExpansion_coeff_4]
  · rw [h_5, lmfdb_1_74_a_orbit_qExpansion_coeff_5]
  · rw [h_6, lmfdb_1_74_a_orbit_qExpansion_coeff_6]


end LeanBridge.QExpansion.LMFDB.W74