import LeanBridge.ForMathlib.QExpansion.IntEval

set_option maxHeartbeats 0
set_option maxRecDepth 4000

/-!
# LMFDB level-1 weight-78 form `1.78.a`, piece 5: integer q-coefficient certificate

Heavy `decide +kernel` over `ℤ` (denominators cleared by the scale `D = 3555261567568156345998177978182603077324907156145801735601913856`), isolated in its own
module so `lake` schedules it in parallel with the other pieces. Generated by
`scripts/lmfdb_qexp_to_e4e6_v3.sage`.
-/

namespace LeanBridge.QExpansion.LMFDB.W78

open LeanBridge.QExpansion

def f_78_part_5_polyDataZ : List (ℕ × ℕ × ℤ) :=
  [(0, 13, (-54208142860864831)), (3, 11, 428189797532557698), (6, 9, (-1326787035202668489)), (9, 7, 2110547360390190908), (12, 5, (-1839695702367166305)), (15, 3, 839197333876834338), (18, 1, (-157243611368883319))]

def f_78_part_5_scale : ℤ := 3555261567568156345998177978182603077324907156145801735601913856

def f_78_part_5_qExpListZ : List ℤ :=
  [0, 0, 0, (-5852933314029680616013824), 0, (-1583323632173129305287642952237056), (-1595240449917629221180270213689507840), 1282186129250563392521815484736510885888, 0, 8654034832195046132093790952982160825384960]

/-- Integer-arithmetic certificate (the heavy kernel computation). -/
lemma f_78_part_5_evalEisListZ_eq :
    evalEisListZ f_78_part_5_polyDataZ 10 = f_78_part_5_qExpListZ := by
  decide +kernel

end LeanBridge.QExpansion.LMFDB.W78
