import LeanBridge.ForMathlib.QExpansion.IntEval

set_option maxHeartbeats 0
set_option maxRecDepth 4000

/-!
# LMFDB level-1 weight-38 form `1.38.a`, piece 1: integer q-coefficient certificate

Heavy `decide +kernel` over `ℤ` (denominators cleared by the scale `D = 2985984`), isolated in its own
module so `lake` schedules it in parallel with the other pieces. Generated by
`scripts/lmfdb_qexp_to_e4e6_v3.sage`.
-/

namespace LeanBridge.QExpansion.LMFDB.W38

open LeanBridge.QExpansion

def f_38_part_1_polyDataZ : List (ℕ × ℕ × ℤ) :=
  [(2, 5, 1), (5, 3, (-2)), (8, 1, 1)]

def f_38_part_1_scale : ℤ := 2985984

def f_38_part_1_qExpListZ : List ℤ :=
  [0, 0, 2985984, (-214990848), (-580475289600), (-86194608537600), 41786158694400, 28814758547226624, (-297652256809943040), (-3008022950707200)]

/-- Integer-arithmetic certificate (the heavy kernel computation). -/
lemma f_38_part_1_evalEisListZ_eq :
    evalEisListZ f_38_part_1_polyDataZ 10 = f_38_part_1_qExpListZ := by
  decide +kernel

end LeanBridge.QExpansion.LMFDB.W38
