import LeanBridge.ForMathlib.QExpansion.IntEval

set_option maxHeartbeats 0
set_option maxRecDepth 4000

/-!
# LMFDB level-1 weight-66 form `1.66.a`, piece 4: integer q-coefficient certificate

Heavy `decide +kernel` over `ℤ` (denominators cleared by the scale `D = 3364700297470216968326135891223379968`), isolated in its own
module so `lake` schedules it in parallel with the other pieces. Generated by
`scripts/lmfdb_qexp_to_e4e6_v3.sage`.
-/

namespace LeanBridge.QExpansion.LMFDB.W66

open LeanBridge.QExpansion

def f_66_part_4_polyDataZ : List (ℕ × ℕ × ℤ) :=
  [(0, 11, 18749), (3, 9, (-96979)), (6, 7, 193958), (9, 5, (-187490)), (12, 3, 87277), (15, 1, (-15515))]

def f_66_part_4_scale : ℤ := 3364700297470216968326135891223379968

def f_66_part_4_qExpListZ : List ℤ :=
  [0, 0, 0, 33373459316736, 0, (-290001612587875172352), 180441181252516627611648, (-15870784461884607506153472), 0, (-91219646128245731777329496064)]

/-- Integer-arithmetic certificate (the heavy kernel computation). -/
lemma f_66_part_4_evalEisListZ_eq :
    evalEisListZ f_66_part_4_polyDataZ 10 = f_66_part_4_qExpListZ := by
  decide +kernel

end LeanBridge.QExpansion.LMFDB.W66
