import LeanBridge.ForMathlib.QExpansion.Generic
import LeanBridge.ForMathlib.QExpansion.Sturm
import Mathlib.Analysis.Complex.Polynomial.Basic

/-!
# LMFDB level-1 modular form orbit `1.38.a.{a..}` (Hecke field degree 2)

The Hecke field `K = ℚ(α)` is degree 2 over ℚ. The LMFDB lists q-coefficients as
elements of `K`, which we decompose as `c_0 + c_1 · α + … + c_{1} · α^1`.
The combined form is `f = f_0 + α · f_1 + … + α^1 · f_{1}`, with each
`f_j` a level-1 weight-38 form with rational coefficients in `(E₄, E₆)`.

The Sturm bound for weight 38 is `⌊38/12⌋ + 1 = 4`. After certifying agreement
on the first 4 q-coefficients, `ModularForm.eq_of_sturm_bound` lets us conclude that any
form with the same coefficients equals our explicit `lmfdb_1_38_a_orbit`.

Generated by `scripts/lmfdb_qexp_to_e4e6_v3.sage`.
-/

namespace LeanBridge.QExpansion.LMFDB.W38

open LeanBridge.QExpansion ModularForm EisensteinSeries PowerSeries UpperHalfPlane
open scoped MatrixGroups


/-- Minimal polynomial of α (degree 2) as `Polynomial ℂ`. -/
noncomputable def α_38_minpoly : Polynomial ℂ :=
  Polynomial.X ^ 2 +
    Polynomial.C (-137403408384) +
    Polynomial.C 194400 * Polynomial.X

lemma α_38_minpoly_natDegree : α_38_minpoly.natDegree = 2 := by
  unfold α_38_minpoly
  compute_degree!

lemma α_38_minpoly_degree_ne_zero : α_38_minpoly.degree ≠ 0 := by
  rw [Polynomial.degree_eq_natDegree (fun h => by
    have := α_38_minpoly_natDegree
    rw [h, Polynomial.natDegree_zero] at this
    exact absurd this (by decide))]
  rw [α_38_minpoly_natDegree]
  decide

/-- α is some root of the degree-2 minimal polynomial in ℂ. -/
noncomputable def α_38 : ℂ :=
  (IsAlgClosed.exists_root α_38_minpoly α_38_minpoly_degree_ne_zero).choose

lemma α_38_isRoot : Polynomial.IsRoot α_38_minpoly α_38 :=
  (IsAlgClosed.exists_root α_38_minpoly α_38_minpoly_degree_ne_zero).choose_spec

/-- Explicit polynomial relation: minpoly evaluated at α is zero. -/
lemma α_38_is_root :
    α_38 ^ 2 +
      (-137403408384) +
      194400 * α_38 = 0 := by
  have h := α_38_isRoot
  unfold Polynomial.IsRoot α_38_minpoly at h
  simp only [Polynomial.eval_add, Polynomial.eval_mul, Polynomial.eval_pow,
    Polynomial.eval_C, Polynomial.eval_X] at h
  linear_combination h


/-! ## Piece 0: coefficient of α^0 -/


def f_38_part_0_polyData : List (ℕ × ℕ × ℚ) :=
  [(2, 5, ((-(7 / 31104)))), (5, 3, ((-(1 / 7776)))), (8, 1, (11 / 31104))]

noncomputable def f_38_part_0 : ModularForm 𝒮ℒ 38 :=
  (((-(7 / 31104))) : ℂ) • mkMonomForm 2 5 38 (by decide) +
  (((-(1 / 7776))) : ℂ) • mkMonomForm 5 3 38 (by decide) +
  ((11 / 31104) : ℂ) • mkMonomForm 8 1 38 (by decide)

lemma f_38_part_0_qExpansion_eq_evalEisPS :
    qExpansion 1 (f_38_part_0 : ℍ → ℂ) = evalEisPS f_38_part_0_polyData := by
  unfold f_38_part_0
  rw [ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm]
  unfold evalEisPS f_38_part_0_polyData monomialEisPS
  simp only [List.foldr_cons, List.foldr_nil, add_zero]
  push_cast
  module

theorem f_38_part_0_qExpansion_coeff (N n : ℕ) (hn : n < N) :
    (PowerSeries.coeff (R := ℂ) n) (qExpansion 1 (f_38_part_0 : ℍ → ℂ))
      = ((evalEisList f_38_part_0_polyData N).getD n 0 : ℚ) :=
  qexp_coeff_via_E4E6 _ _ f_38_part_0_qExpansion_eq_evalEisPS N n hn

/-- Precomputed first 10 q-coefficients of `f_38_part_0` (rational). -/
def f_38_part_0_qExpList : List ℚ :=
  [0, 1, 0, (-2700), (-35545088), (-41021887050), (-9893045403648), (-786241555283800), (-26711222589849600), (-449571606614644707)]

/-- One-shot bridge: the symbolic `evalEisList` equals the precomputed list (verified by
`decide +kernel` once instead of N times). -/
lemma f_38_part_0_evalEisList_eq :
    evalEisList f_38_part_0_polyData 10 = f_38_part_0_qExpList := by
  decide +kernel


/-! ## Piece 1: coefficient of α^1 -/


def f_38_part_1_polyData : List (ℕ × ℕ × ℚ) :=
  [(2, 5, (1 / 2985984)), (5, 3, ((-(1 / 1492992)))), (8, 1, (1 / 2985984))]

noncomputable def f_38_part_1 : ModularForm 𝒮ℒ 38 :=
  ((1 / 2985984) : ℂ) • mkMonomForm 2 5 38 (by decide) +
  (((-(1 / 1492992))) : ℂ) • mkMonomForm 5 3 38 (by decide) +
  ((1 / 2985984) : ℂ) • mkMonomForm 8 1 38 (by decide)

lemma f_38_part_1_qExpansion_eq_evalEisPS :
    qExpansion 1 (f_38_part_1 : ℍ → ℂ) = evalEisPS f_38_part_1_polyData := by
  unfold f_38_part_1
  rw [ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm]
  unfold evalEisPS f_38_part_1_polyData monomialEisPS
  simp only [List.foldr_cons, List.foldr_nil, add_zero]
  push_cast
  module

theorem f_38_part_1_qExpansion_coeff (N n : ℕ) (hn : n < N) :
    (PowerSeries.coeff (R := ℂ) n) (qExpansion 1 (f_38_part_1 : ℍ → ℂ))
      = ((evalEisList f_38_part_1_polyData N).getD n 0 : ℚ) :=
  qexp_coeff_via_E4E6 _ _ f_38_part_1_qExpansion_eq_evalEisPS N n hn

/-- Precomputed first 10 q-coefficients of `f_38_part_1` (rational). -/
def f_38_part_1_qExpList : List ℚ :=
  [0, 0, 1, (-72), (-194400), (-28866400), 13994100, 9650004336, (-99683138560), (-1007380800)]

/-- One-shot bridge: the symbolic `evalEisList` equals the precomputed list (verified by
`decide +kernel` once instead of N times). -/
lemma f_38_part_1_evalEisList_eq :
    evalEisList f_38_part_1_polyData 10 = f_38_part_1_qExpList := by
  decide +kernel


/-! ## Combined LMFDB form -/


noncomputable def lmfdb_1_38_a_orbit : ModularForm 𝒮ℒ 38 :=
  f_38_part_0 +
  α_38 • f_38_part_1

lemma lmfdb_1_38_a_orbit_coeff_decomp (n : ℕ) :
    (PowerSeries.coeff (R := ℂ) n) (qExpansion 1 (lmfdb_1_38_a_orbit : ℍ → ℂ))
      = (PowerSeries.coeff (R := ℂ) n) (qExpansion 1 (f_38_part_0 : ℍ → ℂ))
        + α_38 * (PowerSeries.coeff (R := ℂ) n) (qExpansion 1 (f_38_part_1 : ℍ → ℂ)) := by
  unfold lmfdb_1_38_a_orbit
  rw [ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL]
  simp [smul_eq_mul]


/-! ## Coefficient lemmas (n = 0, …, 9)

Sturm bound is 4; we certify 10 coefficients for added
redundancy beyond the minimum mathematically required for uniqueness. -/


lemma lmfdb_1_38_a_orbit_qExpansion_coeff_0 :
    (PowerSeries.coeff (R := ℂ) 0)
      (qExpansion 1 (lmfdb_1_38_a_orbit : ℍ → ℂ)) = 0 := by
  rw [lmfdb_1_38_a_orbit_coeff_decomp,
    f_38_part_0_qExpansion_coeff 10 0 (by decide),
    f_38_part_1_qExpansion_coeff 10 0 (by decide),
    f_38_part_0_evalEisList_eq,
    f_38_part_1_evalEisList_eq,
    show f_38_part_0_qExpList.getD 0 0 = (0 : ℚ) from by decide +kernel,
    show f_38_part_1_qExpList.getD 0 0 = (0 : ℚ) from by decide +kernel]
  push_cast; ring

lemma lmfdb_1_38_a_orbit_qExpansion_coeff_1 :
    (PowerSeries.coeff (R := ℂ) 1)
      (qExpansion 1 (lmfdb_1_38_a_orbit : ℍ → ℂ)) = 1 := by
  rw [lmfdb_1_38_a_orbit_coeff_decomp,
    f_38_part_0_qExpansion_coeff 10 1 (by decide),
    f_38_part_1_qExpansion_coeff 10 1 (by decide),
    f_38_part_0_evalEisList_eq,
    f_38_part_1_evalEisList_eq,
    show f_38_part_0_qExpList.getD 1 0 = (1 : ℚ) from by decide +kernel,
    show f_38_part_1_qExpList.getD 1 0 = (0 : ℚ) from by decide +kernel]
  push_cast; ring

lemma lmfdb_1_38_a_orbit_qExpansion_coeff_2 :
    (PowerSeries.coeff (R := ℂ) 2)
      (qExpansion 1 (lmfdb_1_38_a_orbit : ℍ → ℂ)) = 1 * α_38 := by
  rw [lmfdb_1_38_a_orbit_coeff_decomp,
    f_38_part_0_qExpansion_coeff 10 2 (by decide),
    f_38_part_1_qExpansion_coeff 10 2 (by decide),
    f_38_part_0_evalEisList_eq,
    f_38_part_1_evalEisList_eq,
    show f_38_part_0_qExpList.getD 2 0 = (0 : ℚ) from by decide +kernel,
    show f_38_part_1_qExpList.getD 2 0 = (1 : ℚ) from by decide +kernel]
  push_cast; ring

lemma lmfdb_1_38_a_orbit_qExpansion_coeff_3 :
    (PowerSeries.coeff (R := ℂ) 3)
      (qExpansion 1 (lmfdb_1_38_a_orbit : ℍ → ℂ)) = (-2700) + (-72) * α_38 := by
  rw [lmfdb_1_38_a_orbit_coeff_decomp,
    f_38_part_0_qExpansion_coeff 10 3 (by decide),
    f_38_part_1_qExpansion_coeff 10 3 (by decide),
    f_38_part_0_evalEisList_eq,
    f_38_part_1_evalEisList_eq,
    show f_38_part_0_qExpList.getD 3 0 = ((-2700) : ℚ) from by decide +kernel,
    show f_38_part_1_qExpList.getD 3 0 = ((-72) : ℚ) from by decide +kernel]
  push_cast; ring

lemma lmfdb_1_38_a_orbit_qExpansion_coeff_4 :
    (PowerSeries.coeff (R := ℂ) 4)
      (qExpansion 1 (lmfdb_1_38_a_orbit : ℍ → ℂ)) = (-35545088) + (-194400) * α_38 := by
  rw [lmfdb_1_38_a_orbit_coeff_decomp,
    f_38_part_0_qExpansion_coeff 10 4 (by decide),
    f_38_part_1_qExpansion_coeff 10 4 (by decide),
    f_38_part_0_evalEisList_eq,
    f_38_part_1_evalEisList_eq,
    show f_38_part_0_qExpList.getD 4 0 = ((-35545088) : ℚ) from by decide +kernel,
    show f_38_part_1_qExpList.getD 4 0 = ((-194400) : ℚ) from by decide +kernel]
  push_cast; ring

lemma lmfdb_1_38_a_orbit_qExpansion_coeff_5 :
    (PowerSeries.coeff (R := ℂ) 5)
      (qExpansion 1 (lmfdb_1_38_a_orbit : ℍ → ℂ)) = (-41021887050) + (-28866400) * α_38 := by
  rw [lmfdb_1_38_a_orbit_coeff_decomp,
    f_38_part_0_qExpansion_coeff 10 5 (by decide),
    f_38_part_1_qExpansion_coeff 10 5 (by decide),
    f_38_part_0_evalEisList_eq,
    f_38_part_1_evalEisList_eq,
    show f_38_part_0_qExpList.getD 5 0 = ((-41021887050) : ℚ) from by decide +kernel,
    show f_38_part_1_qExpList.getD 5 0 = ((-28866400) : ℚ) from by decide +kernel]
  push_cast; ring

lemma lmfdb_1_38_a_orbit_qExpansion_coeff_6 :
    (PowerSeries.coeff (R := ℂ) 6)
      (qExpansion 1 (lmfdb_1_38_a_orbit : ℍ → ℂ)) = (-9893045403648) + 13994100 * α_38 := by
  rw [lmfdb_1_38_a_orbit_coeff_decomp,
    f_38_part_0_qExpansion_coeff 10 6 (by decide),
    f_38_part_1_qExpansion_coeff 10 6 (by decide),
    f_38_part_0_evalEisList_eq,
    f_38_part_1_evalEisList_eq,
    show f_38_part_0_qExpList.getD 6 0 = ((-9893045403648) : ℚ) from by decide +kernel,
    show f_38_part_1_qExpList.getD 6 0 = (13994100 : ℚ) from by decide +kernel]
  push_cast; ring

lemma lmfdb_1_38_a_orbit_qExpansion_coeff_7 :
    (PowerSeries.coeff (R := ℂ) 7)
      (qExpansion 1 (lmfdb_1_38_a_orbit : ℍ → ℂ)) = (-786241555283800) + 9650004336 * α_38 := by
  rw [lmfdb_1_38_a_orbit_coeff_decomp,
    f_38_part_0_qExpansion_coeff 10 7 (by decide),
    f_38_part_1_qExpansion_coeff 10 7 (by decide),
    f_38_part_0_evalEisList_eq,
    f_38_part_1_evalEisList_eq,
    show f_38_part_0_qExpList.getD 7 0 = ((-786241555283800) : ℚ) from by decide +kernel,
    show f_38_part_1_qExpList.getD 7 0 = (9650004336 : ℚ) from by decide +kernel]
  push_cast; ring

lemma lmfdb_1_38_a_orbit_qExpansion_coeff_8 :
    (PowerSeries.coeff (R := ℂ) 8)
      (qExpansion 1 (lmfdb_1_38_a_orbit : ℍ → ℂ)) = (-26711222589849600) + (-99683138560) * α_38 := by
  rw [lmfdb_1_38_a_orbit_coeff_decomp,
    f_38_part_0_qExpansion_coeff 10 8 (by decide),
    f_38_part_1_qExpansion_coeff 10 8 (by decide),
    f_38_part_0_evalEisList_eq,
    f_38_part_1_evalEisList_eq,
    show f_38_part_0_qExpList.getD 8 0 = ((-26711222589849600) : ℚ) from by decide +kernel,
    show f_38_part_1_qExpList.getD 8 0 = ((-99683138560) : ℚ) from by decide +kernel]
  push_cast; ring

lemma lmfdb_1_38_a_orbit_qExpansion_coeff_9 :
    (PowerSeries.coeff (R := ℂ) 9)
      (qExpansion 1 (lmfdb_1_38_a_orbit : ℍ → ℂ)) = (-449571606614644707) + (-1007380800) * α_38 := by
  rw [lmfdb_1_38_a_orbit_coeff_decomp,
    f_38_part_0_qExpansion_coeff 10 9 (by decide),
    f_38_part_1_qExpansion_coeff 10 9 (by decide),
    f_38_part_0_evalEisList_eq,
    f_38_part_1_evalEisList_eq,
    show f_38_part_0_qExpList.getD 9 0 = ((-449571606614644707) : ℚ) from by decide +kernel,
    show f_38_part_1_qExpList.getD 9 0 = ((-1007380800) : ℚ) from by decide +kernel]
  push_cast; ring


/-! ## Uniqueness theorem -/


/-- **Uniqueness theorem.** Any level-1 weight-38 modular form `f` whose first 4
q-coefficients match the LMFDB-published values for `1.38.a.{a..}` is equal to our
explicit construction `lmfdb_1_38_a_orbit`. Proven via `ModularForm.eq_of_sturm_bound`. -/
theorem identifies_lmfdb_1_38_a_orbit (f : ModularForm 𝒮ℒ 38)
    (h_0 : (PowerSeries.coeff (R := ℂ) 0) (qExpansion 1 (f : ℍ → ℂ)) = 0)
    (h_1 : (PowerSeries.coeff (R := ℂ) 1) (qExpansion 1 (f : ℍ → ℂ)) = 1)
    (h_2 : (PowerSeries.coeff (R := ℂ) 2) (qExpansion 1 (f : ℍ → ℂ)) = 1 * α_38)
    (h_3 : (PowerSeries.coeff (R := ℂ) 3) (qExpansion 1 (f : ℍ → ℂ)) = (-2700) + (-72) * α_38) :
    f = lmfdb_1_38_a_orbit := by
  apply ModularForm.eq_of_sturm_bound
  intro i hi
  have : i ≤ 3 := by omega
  interval_cases i
  · rw [h_0, lmfdb_1_38_a_orbit_qExpansion_coeff_0]
  · rw [h_1, lmfdb_1_38_a_orbit_qExpansion_coeff_1]
  · rw [h_2, lmfdb_1_38_a_orbit_qExpansion_coeff_2]
  · rw [h_3, lmfdb_1_38_a_orbit_qExpansion_coeff_3]


end LeanBridge.QExpansion.LMFDB.W38