import LeanBridge.ForMathlib.QExpansion.IntEval

set_option maxHeartbeats 0
set_option maxRecDepth 4000

/-!
# LMFDB level-1 weight-44 form `1.44.a`, piece 2: integer q-coefficient certificate

Heavy `decide +kernel` over `ℤ` (denominators cleared by the scale `D = 2105190383616`), isolated in its own
module so `lake` schedules it in parallel with the other pieces. Generated by
`scripts/lmfdb_qexp_to_e4e6_v3.sage`.
-/

namespace LeanBridge.QExpansion.LMFDB.W44

open LeanBridge.QExpansion

def f_44_part_2_polyDataZ : List (ℕ × ℕ × ℤ) :=
  [(2, 6, (-1)), (5, 4, 3), (8, 2, (-3)), (11, 0, 1)]

def f_44_part_2_scale : ℤ := 2105190383616

def f_44_part_2_qExpListZ : List ℤ :=
  [0, 0, 0, 5159780352, 2105190383616, 153988484825088, (-11713774633353216), 313700332170903552, (-4652352857129877504), 40787215290835402752]

/-- Integer-arithmetic certificate (the heavy kernel computation). -/
lemma f_44_part_2_evalEisListZ_eq :
    evalEisListZ f_44_part_2_polyDataZ 10 = f_44_part_2_qExpListZ := by
  decide +kernel

end LeanBridge.QExpansion.LMFDB.W44
