import LeanBridge.ForMathlib.QExpansion.Generic
import LeanBridge.ForMathlib.QExpansion.Sturm
import Mathlib.Analysis.Complex.Polynomial.Basic

/-!
# LMFDB level-1 modular form orbit `1.36.a.{a..}` (Hecke field degree 3)

The Hecke field `K = ℚ(α)` is degree 3 over ℚ. The LMFDB lists q-coefficients as
elements of `K`, which we decompose as `c_0 + c_1 · α + … + c_{2} · α^2`.
The combined form is `f = f_0 + α · f_1 + … + α^2 · f_{2}`, with each
`f_j` a level-1 weight-36 form with rational coefficients in `(E₄, E₆)`.

The Sturm bound for weight 36 is `⌊36/12⌋ + 1 = 4`. After certifying agreement
on the first 4 q-coefficients, `ModularForm.eq_of_sturm_bound` lets us conclude that any
form with the same coefficients equals our explicit `lmfdb_1_36_a_orbit`.

Generated by `scripts/lmfdb_qexp_to_e4e6_v3.sage`.
-/

namespace LeanBridge.QExpansion.LMFDB.W36

open LeanBridge.QExpansion ModularForm EisensteinSeries PowerSeries UpperHalfPlane
open scoped MatrixGroups


/-- Minimal polynomial of α (degree 3) as `Polynomial ℂ`. -/
noncomputable def α_36_minpoly : Polynomial ℂ :=
  Polynomial.X ^ 3 +
    Polynomial.C (-1467625047588864) +
    Polynomial.C (-59208339456) * Polynomial.X +
    Polynomial.C (-139656) * Polynomial.X ^ 2

lemma α_36_minpoly_natDegree : α_36_minpoly.natDegree = 3 := by
  unfold α_36_minpoly
  compute_degree!

lemma α_36_minpoly_degree_ne_zero : α_36_minpoly.degree ≠ 0 := by
  rw [Polynomial.degree_eq_natDegree (fun h => by
    have := α_36_minpoly_natDegree
    rw [h, Polynomial.natDegree_zero] at this
    exact absurd this (by decide))]
  rw [α_36_minpoly_natDegree]
  decide

/-- α is some root of the degree-3 minimal polynomial in ℂ. -/
noncomputable def α_36 : ℂ :=
  (IsAlgClosed.exists_root α_36_minpoly α_36_minpoly_degree_ne_zero).choose

lemma α_36_isRoot : Polynomial.IsRoot α_36_minpoly α_36 :=
  (IsAlgClosed.exists_root α_36_minpoly α_36_minpoly_degree_ne_zero).choose_spec

/-- Explicit polynomial relation: minpoly evaluated at α is zero. -/
lemma α_36_is_root :
    α_36 ^ 3 +
      (-1467625047588864) +
      (-59208339456) * α_36 +
      (-139656) * α_36 ^ 2 = 0 := by
  have h := α_36_isRoot
  unfold Polynomial.IsRoot α_36_minpoly at h
  simp only [Polynomial.eval_add, Polynomial.eval_mul, Polynomial.eval_pow,
    Polynomial.eval_C, Polynomial.eval_X] at h
  linear_combination h


/-! ## Piece 0: coefficient of α^0 -/


def f_36_part_0_polyData : List (ℕ × ℕ × ℚ) :=
  [(0, 6, ((-(933829 / 10077696)))), (3, 4, (233059 / 839808)), (6, 2, ((-(932587 / 3359232)))), (9, 0, (467441 / 5038848))]

noncomputable def f_36_part_0 : ModularForm 𝒮ℒ 36 :=
  (((-(933829 / 10077696))) : ℂ) • mkMonomForm 0 6 36 (by decide) +
  ((233059 / 839808) : ℂ) • mkMonomForm 3 4 36 (by decide) +
  (((-(932587 / 3359232))) : ℂ) • mkMonomForm 6 2 36 (by decide) +
  ((467441 / 5038848) : ℂ) • mkMonomForm 9 0 36 (by decide)

lemma f_36_part_0_qExpansion_eq_evalEisPS :
    qExpansion 1 (f_36_part_0 : ℍ → ℂ) = evalEisPS f_36_part_0_polyData := by
  unfold f_36_part_0
  rw [ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm]
  unfold evalEisPS f_36_part_0_polyData monomialEisPS
  simp only [List.foldr_cons, List.foldr_nil, add_zero]
  push_cast
  module

theorem f_36_part_0_qExpansion_coeff (N n : ℕ) (hn : n < N) :
    (PowerSeries.coeff (R := ℂ) n) (qExpansion 1 (f_36_part_0 : ℍ → ℂ))
      = ((evalEisList f_36_part_0_polyData N).getD n 0 : ℚ) :=
  qexp_coeff_via_E4E6 _ _ f_36_part_0_qExpansion_eq_evalEisPS N n hn

/-- Precomputed first 10 q-coefficients of `f_36_part_0` (rational). -/
def f_36_part_0_qExpList : List ℚ :=
  [0, 1, 0, 478011548, (-34359738368), 1225308030462, (-20383681216512), 696447777679448, 1467625047588864, 108051465440118645]

/-- One-shot bridge: the symbolic `evalEisList` equals the precomputed list (verified by
`decide +kernel` once instead of N times). -/
lemma f_36_part_0_evalEisList_eq :
    evalEisList f_36_part_0_polyData 10 = f_36_part_0_qExpList := by
  decide +kernel


/-! ## Piece 1: coefficient of α^1 -/


def f_36_part_1_polyData : List (ℕ × ℕ × ℚ) :=
  [(0, 6, ((-(25 / 63700992)))), (3, 4, (289 / 191102976)), (6, 2, ((-(353 / 191102976)))), (9, 0, (139 / 191102976))]

noncomputable def f_36_part_1 : ModularForm 𝒮ℒ 36 :=
  (((-(25 / 63700992))) : ℂ) • mkMonomForm 0 6 36 (by decide) +
  ((289 / 191102976) : ℂ) • mkMonomForm 3 4 36 (by decide) +
  (((-(353 / 191102976))) : ℂ) • mkMonomForm 6 2 36 (by decide) +
  ((139 / 191102976) : ℂ) • mkMonomForm 9 0 36 (by decide)

lemma f_36_part_1_qExpansion_eq_evalEisPS :
    qExpansion 1 (f_36_part_1 : ℍ → ℂ) = evalEisPS f_36_part_1_polyData := by
  unfold f_36_part_1
  rw [ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm]
  unfold evalEisPS f_36_part_1_polyData monomialEisPS
  simp only [List.foldr_cons, List.foldr_nil, add_zero]
  push_cast
  module

theorem f_36_part_1_qExpansion_coeff (N n : ℕ) (hn : n < N) :
    (PowerSeries.coeff (R := ℂ) n) (qExpansion 1 (f_36_part_1 : ℍ → ℂ))
      = ((evalEisList f_36_part_1_polyData N).getD n 0 : ℚ) :=
  qexp_coeff_via_E4E6 _ _ f_36_part_1_qExpansion_eq_evalEisPS N n hn

/-- Precomputed first 10 q-coefficients of `f_36_part_1` (rational). -/
def f_36_part_1_qExpList : List ℚ :=
  [0, 0, 1, 2697, 0, 14141780, (-344326500), 3021379866, (-9511137280), 20871243000]

/-- One-shot bridge: the symbolic `evalEisList` equals the precomputed list (verified by
`decide +kernel` once instead of N times). -/
lemma f_36_part_1_evalEisList_eq :
    evalEisList f_36_part_1_polyData 10 = f_36_part_1_qExpList := by
  decide +kernel


/-! ## Piece 2: coefficient of α^2 -/


def f_36_part_2_polyData : List (ℕ × ℕ × ℚ) :=
  [(0, 6, (1 / 371504185344)), (3, 4, ((-(1 / 123834728448)))), (6, 2, (1 / 123834728448)), (9, 0, ((-(1 / 371504185344))))]

noncomputable def f_36_part_2 : ModularForm 𝒮ℒ 36 :=
  ((1 / 371504185344) : ℂ) • mkMonomForm 0 6 36 (by decide) +
  (((-(1 / 123834728448))) : ℂ) • mkMonomForm 3 4 36 (by decide) +
  ((1 / 123834728448) : ℂ) • mkMonomForm 6 2 36 (by decide) +
  (((-(1 / 371504185344))) : ℂ) • mkMonomForm 9 0 36 (by decide)

lemma f_36_part_2_qExpansion_eq_evalEisPS :
    qExpansion 1 (f_36_part_2 : ℍ → ℂ) = evalEisPS f_36_part_2_polyData := by
  unfold f_36_part_2
  rw [ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm]
  unfold evalEisPS f_36_part_2_polyData monomialEisPS
  simp only [List.foldr_cons, List.foldr_nil, add_zero]
  push_cast
  module

theorem f_36_part_2_qExpansion_coeff (N n : ℕ) (hn : n < N) :
    (PowerSeries.coeff (R := ℂ) n) (qExpansion 1 (f_36_part_2 : ℍ → ℂ))
      = ((evalEisList f_36_part_2_polyData N).getD n 0 : ℚ) :=
  qexp_coeff_via_E4E6 _ _ f_36_part_2_qExpansion_eq_evalEisPS N n hn

/-- Precomputed first 10 q-coefficients of `f_36_part_2` (rational). -/
def f_36_part_2_qExpList : List ℚ :=
  [0, 0, 0, ((-(1 / 72))), 1, ((-(69 / 2))), (2272 / 3), ((-(47357 / 4))), 139656, (-1283183)]

/-- One-shot bridge: the symbolic `evalEisList` equals the precomputed list (verified by
`decide +kernel` once instead of N times). -/
lemma f_36_part_2_evalEisList_eq :
    evalEisList f_36_part_2_polyData 10 = f_36_part_2_qExpList := by
  decide +kernel


/-! ## Combined LMFDB form -/


noncomputable def lmfdb_1_36_a_orbit : ModularForm 𝒮ℒ 36 :=
  f_36_part_0 +
  α_36 • f_36_part_1 +
  α_36 ^ 2 • f_36_part_2

lemma lmfdb_1_36_a_orbit_coeff_decomp (n : ℕ) :
    (PowerSeries.coeff (R := ℂ) n) (qExpansion 1 (lmfdb_1_36_a_orbit : ℍ → ℂ))
      = (PowerSeries.coeff (R := ℂ) n) (qExpansion 1 (f_36_part_0 : ℍ → ℂ))
        + α_36 * (PowerSeries.coeff (R := ℂ) n) (qExpansion 1 (f_36_part_1 : ℍ → ℂ))
        + α_36 ^ 2 * (PowerSeries.coeff (R := ℂ) n) (qExpansion 1 (f_36_part_2 : ℍ → ℂ)) := by
  unfold lmfdb_1_36_a_orbit
  rw [ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL]
  simp [smul_eq_mul]


/-! ## Coefficient lemmas (n = 0, …, 9)

Sturm bound is 4; we certify 10 coefficients for added
redundancy beyond the minimum mathematically required for uniqueness. -/


lemma lmfdb_1_36_a_orbit_qExpansion_coeff_0 :
    (PowerSeries.coeff (R := ℂ) 0)
      (qExpansion 1 (lmfdb_1_36_a_orbit : ℍ → ℂ)) = 0 := by
  rw [lmfdb_1_36_a_orbit_coeff_decomp,
    f_36_part_0_qExpansion_coeff 10 0 (by decide),
    f_36_part_1_qExpansion_coeff 10 0 (by decide),
    f_36_part_2_qExpansion_coeff 10 0 (by decide),
    f_36_part_0_evalEisList_eq,
    f_36_part_1_evalEisList_eq,
    f_36_part_2_evalEisList_eq,
    show f_36_part_0_qExpList.getD 0 0 = (0 : ℚ) from by decide +kernel,
    show f_36_part_1_qExpList.getD 0 0 = (0 : ℚ) from by decide +kernel,
    show f_36_part_2_qExpList.getD 0 0 = (0 : ℚ) from by decide +kernel]
  push_cast; ring

lemma lmfdb_1_36_a_orbit_qExpansion_coeff_1 :
    (PowerSeries.coeff (R := ℂ) 1)
      (qExpansion 1 (lmfdb_1_36_a_orbit : ℍ → ℂ)) = 1 := by
  rw [lmfdb_1_36_a_orbit_coeff_decomp,
    f_36_part_0_qExpansion_coeff 10 1 (by decide),
    f_36_part_1_qExpansion_coeff 10 1 (by decide),
    f_36_part_2_qExpansion_coeff 10 1 (by decide),
    f_36_part_0_evalEisList_eq,
    f_36_part_1_evalEisList_eq,
    f_36_part_2_evalEisList_eq,
    show f_36_part_0_qExpList.getD 1 0 = (1 : ℚ) from by decide +kernel,
    show f_36_part_1_qExpList.getD 1 0 = (0 : ℚ) from by decide +kernel,
    show f_36_part_2_qExpList.getD 1 0 = (0 : ℚ) from by decide +kernel]
  push_cast; ring

lemma lmfdb_1_36_a_orbit_qExpansion_coeff_2 :
    (PowerSeries.coeff (R := ℂ) 2)
      (qExpansion 1 (lmfdb_1_36_a_orbit : ℍ → ℂ)) = 1 * α_36 := by
  rw [lmfdb_1_36_a_orbit_coeff_decomp,
    f_36_part_0_qExpansion_coeff 10 2 (by decide),
    f_36_part_1_qExpansion_coeff 10 2 (by decide),
    f_36_part_2_qExpansion_coeff 10 2 (by decide),
    f_36_part_0_evalEisList_eq,
    f_36_part_1_evalEisList_eq,
    f_36_part_2_evalEisList_eq,
    show f_36_part_0_qExpList.getD 2 0 = (0 : ℚ) from by decide +kernel,
    show f_36_part_1_qExpList.getD 2 0 = (1 : ℚ) from by decide +kernel,
    show f_36_part_2_qExpList.getD 2 0 = (0 : ℚ) from by decide +kernel]
  push_cast; ring

lemma lmfdb_1_36_a_orbit_qExpansion_coeff_3 :
    (PowerSeries.coeff (R := ℂ) 3)
      (qExpansion 1 (lmfdb_1_36_a_orbit : ℍ → ℂ)) = 478011548 + 2697 * α_36 + ((-(1 / 72))) * α_36 ^ 2 := by
  rw [lmfdb_1_36_a_orbit_coeff_decomp,
    f_36_part_0_qExpansion_coeff 10 3 (by decide),
    f_36_part_1_qExpansion_coeff 10 3 (by decide),
    f_36_part_2_qExpansion_coeff 10 3 (by decide),
    f_36_part_0_evalEisList_eq,
    f_36_part_1_evalEisList_eq,
    f_36_part_2_evalEisList_eq,
    show f_36_part_0_qExpList.getD 3 0 = (478011548 : ℚ) from by decide +kernel,
    show f_36_part_1_qExpList.getD 3 0 = (2697 : ℚ) from by decide +kernel,
    show f_36_part_2_qExpList.getD 3 0 = (((-(1 / 72))) : ℚ) from by decide +kernel]
  push_cast; ring

lemma lmfdb_1_36_a_orbit_qExpansion_coeff_4 :
    (PowerSeries.coeff (R := ℂ) 4)
      (qExpansion 1 (lmfdb_1_36_a_orbit : ℍ → ℂ)) = (-34359738368) + 1 * α_36 ^ 2 := by
  rw [lmfdb_1_36_a_orbit_coeff_decomp,
    f_36_part_0_qExpansion_coeff 10 4 (by decide),
    f_36_part_1_qExpansion_coeff 10 4 (by decide),
    f_36_part_2_qExpansion_coeff 10 4 (by decide),
    f_36_part_0_evalEisList_eq,
    f_36_part_1_evalEisList_eq,
    f_36_part_2_evalEisList_eq,
    show f_36_part_0_qExpList.getD 4 0 = ((-34359738368) : ℚ) from by decide +kernel,
    show f_36_part_1_qExpList.getD 4 0 = (0 : ℚ) from by decide +kernel,
    show f_36_part_2_qExpList.getD 4 0 = (1 : ℚ) from by decide +kernel]
  push_cast; ring

lemma lmfdb_1_36_a_orbit_qExpansion_coeff_5 :
    (PowerSeries.coeff (R := ℂ) 5)
      (qExpansion 1 (lmfdb_1_36_a_orbit : ℍ → ℂ)) = 1225308030462 + 14141780 * α_36 + ((-(69 / 2))) * α_36 ^ 2 := by
  rw [lmfdb_1_36_a_orbit_coeff_decomp,
    f_36_part_0_qExpansion_coeff 10 5 (by decide),
    f_36_part_1_qExpansion_coeff 10 5 (by decide),
    f_36_part_2_qExpansion_coeff 10 5 (by decide),
    f_36_part_0_evalEisList_eq,
    f_36_part_1_evalEisList_eq,
    f_36_part_2_evalEisList_eq,
    show f_36_part_0_qExpList.getD 5 0 = (1225308030462 : ℚ) from by decide +kernel,
    show f_36_part_1_qExpList.getD 5 0 = (14141780 : ℚ) from by decide +kernel,
    show f_36_part_2_qExpList.getD 5 0 = (((-(69 / 2))) : ℚ) from by decide +kernel]
  push_cast; ring

lemma lmfdb_1_36_a_orbit_qExpansion_coeff_6 :
    (PowerSeries.coeff (R := ℂ) 6)
      (qExpansion 1 (lmfdb_1_36_a_orbit : ℍ → ℂ)) = (-20383681216512) + (-344326500) * α_36 + (2272 / 3) * α_36 ^ 2 := by
  rw [lmfdb_1_36_a_orbit_coeff_decomp,
    f_36_part_0_qExpansion_coeff 10 6 (by decide),
    f_36_part_1_qExpansion_coeff 10 6 (by decide),
    f_36_part_2_qExpansion_coeff 10 6 (by decide),
    f_36_part_0_evalEisList_eq,
    f_36_part_1_evalEisList_eq,
    f_36_part_2_evalEisList_eq,
    show f_36_part_0_qExpList.getD 6 0 = ((-20383681216512) : ℚ) from by decide +kernel,
    show f_36_part_1_qExpList.getD 6 0 = ((-344326500) : ℚ) from by decide +kernel,
    show f_36_part_2_qExpList.getD 6 0 = ((2272 / 3) : ℚ) from by decide +kernel]
  push_cast; ring

lemma lmfdb_1_36_a_orbit_qExpansion_coeff_7 :
    (PowerSeries.coeff (R := ℂ) 7)
      (qExpansion 1 (lmfdb_1_36_a_orbit : ℍ → ℂ)) = 696447777679448 + 3021379866 * α_36 + ((-(47357 / 4))) * α_36 ^ 2 := by
  rw [lmfdb_1_36_a_orbit_coeff_decomp,
    f_36_part_0_qExpansion_coeff 10 7 (by decide),
    f_36_part_1_qExpansion_coeff 10 7 (by decide),
    f_36_part_2_qExpansion_coeff 10 7 (by decide),
    f_36_part_0_evalEisList_eq,
    f_36_part_1_evalEisList_eq,
    f_36_part_2_evalEisList_eq,
    show f_36_part_0_qExpList.getD 7 0 = (696447777679448 : ℚ) from by decide +kernel,
    show f_36_part_1_qExpList.getD 7 0 = (3021379866 : ℚ) from by decide +kernel,
    show f_36_part_2_qExpList.getD 7 0 = (((-(47357 / 4))) : ℚ) from by decide +kernel]
  push_cast; ring

lemma lmfdb_1_36_a_orbit_qExpansion_coeff_8 :
    (PowerSeries.coeff (R := ℂ) 8)
      (qExpansion 1 (lmfdb_1_36_a_orbit : ℍ → ℂ)) = 1467625047588864 + (-9511137280) * α_36 + 139656 * α_36 ^ 2 := by
  rw [lmfdb_1_36_a_orbit_coeff_decomp,
    f_36_part_0_qExpansion_coeff 10 8 (by decide),
    f_36_part_1_qExpansion_coeff 10 8 (by decide),
    f_36_part_2_qExpansion_coeff 10 8 (by decide),
    f_36_part_0_evalEisList_eq,
    f_36_part_1_evalEisList_eq,
    f_36_part_2_evalEisList_eq,
    show f_36_part_0_qExpList.getD 8 0 = (1467625047588864 : ℚ) from by decide +kernel,
    show f_36_part_1_qExpList.getD 8 0 = ((-9511137280) : ℚ) from by decide +kernel,
    show f_36_part_2_qExpList.getD 8 0 = (139656 : ℚ) from by decide +kernel]
  push_cast; ring

lemma lmfdb_1_36_a_orbit_qExpansion_coeff_9 :
    (PowerSeries.coeff (R := ℂ) 9)
      (qExpansion 1 (lmfdb_1_36_a_orbit : ℍ → ℂ)) = 108051465440118645 + 20871243000 * α_36 + (-1283183) * α_36 ^ 2 := by
  rw [lmfdb_1_36_a_orbit_coeff_decomp,
    f_36_part_0_qExpansion_coeff 10 9 (by decide),
    f_36_part_1_qExpansion_coeff 10 9 (by decide),
    f_36_part_2_qExpansion_coeff 10 9 (by decide),
    f_36_part_0_evalEisList_eq,
    f_36_part_1_evalEisList_eq,
    f_36_part_2_evalEisList_eq,
    show f_36_part_0_qExpList.getD 9 0 = (108051465440118645 : ℚ) from by decide +kernel,
    show f_36_part_1_qExpList.getD 9 0 = (20871243000 : ℚ) from by decide +kernel,
    show f_36_part_2_qExpList.getD 9 0 = ((-1283183) : ℚ) from by decide +kernel]
  push_cast; ring


/-! ## Uniqueness theorem -/


/-- **Uniqueness theorem.** Any level-1 weight-36 modular form `f` whose first 4
q-coefficients match the LMFDB-published values for `1.36.a.{a..}` is equal to our
explicit construction `lmfdb_1_36_a_orbit`. Proven via `ModularForm.eq_of_sturm_bound`. -/
theorem identifies_lmfdb_1_36_a_orbit (f : ModularForm 𝒮ℒ 36)
    (h_0 : (PowerSeries.coeff (R := ℂ) 0) (qExpansion 1 (f : ℍ → ℂ)) = 0)
    (h_1 : (PowerSeries.coeff (R := ℂ) 1) (qExpansion 1 (f : ℍ → ℂ)) = 1)
    (h_2 : (PowerSeries.coeff (R := ℂ) 2) (qExpansion 1 (f : ℍ → ℂ)) = 1 * α_36)
    (h_3 : (PowerSeries.coeff (R := ℂ) 3) (qExpansion 1 (f : ℍ → ℂ)) = 478011548 + 2697 * α_36 + ((-(1 / 72))) * α_36 ^ 2) :
    f = lmfdb_1_36_a_orbit := by
  apply ModularForm.eq_of_sturm_bound
  intro i hi
  have : i ≤ 3 := by omega
  interval_cases i
  · rw [h_0, lmfdb_1_36_a_orbit_qExpansion_coeff_0]
  · rw [h_1, lmfdb_1_36_a_orbit_qExpansion_coeff_1]
  · rw [h_2, lmfdb_1_36_a_orbit_qExpansion_coeff_2]
  · rw [h_3, lmfdb_1_36_a_orbit_qExpansion_coeff_3]


end LeanBridge.QExpansion.LMFDB.W36