import LeanBridge.ForMathlib.QExpansion.IntEval

set_option maxHeartbeats 0
set_option maxRecDepth 4000

/-!
# LMFDB level-1 weight-64 form `1.64.a`, piece 1: integer q-coefficient certificate

Heavy `decide +kernel` over `ℤ` (denominators cleared by the scale `D = 4414068794985595538346344448`), isolated in its own
module so `lake` schedules it in parallel with the other pieces. Generated by
`scripts/lmfdb_qexp_to_e4e6_v3.sage`.
-/

namespace LeanBridge.QExpansion.LMFDB.W64

open LeanBridge.QExpansion

def f_64_part_1_polyDataZ : List (ℕ × ℕ × ℤ) :=
  [(1, 10, (-12622774232578187326891994)), (4, 8, 67638453406570612739772643), (7, 6, (-139462503910891214434621424)), (10, 4, 138786011881740208831213826), (13, 2, (-66624454494198288683193982)), (16, 0, 12285267349356868873720931)]

def f_64_part_1_scale : ℤ := 4414068794985595538346344448

def f_64_part_1_qExpListZ : List ℤ :=
  [0, 0, 4414068794985595538346344448, (-25084557567728515360507367805419520), 0, 201580383116836747239120878076436886323200, 23513276427312049459470515555907435233280000, (-4942957566305211207716087542203178024276328448), (-81425197384846796263982875678316495374771027968), (-35730985937789901814322610718349209153390510080000)]

/-- Integer-arithmetic certificate (the heavy kernel computation). -/
lemma f_64_part_1_evalEisListZ_eq :
    evalEisListZ f_64_part_1_polyDataZ 10 = f_64_part_1_qExpListZ := by
  decide +kernel

end LeanBridge.QExpansion.LMFDB.W64
