import LeanBridge.ForMathlib.QExpansion.IntEval

set_option maxHeartbeats 0
set_option maxRecDepth 4000

/-!
# LMFDB level-1 weight-50 form `1.50.a`, piece 2: integer q-coefficient certificate

Heavy `decide +kernel` over `ℤ` (denominators cleared by the scale `D = 495338913792`), isolated in its own
module so `lake` schedules it in parallel with the other pieces. Generated by
`scripts/lmfdb_qexp_to_e4e6_v3.sage`.
-/

namespace LeanBridge.QExpansion.LMFDB.W50

open LeanBridge.QExpansion

def f_50_part_2_polyDataZ : List (ℕ × ℕ × ℤ) :=
  [(2, 7, 1), (5, 5, (-3)), (8, 3, 3), (11, 1, (-1))]

def f_50_part_2_scale : ℤ := 495338913792

def f_50_part_2_qExpListZ : List ℤ :=
  [0, 0, 0, (-5159780352), 495338913792, 992844935331840, 124972026594066432, (-3394669615687139328), (-11999668403548717056), 1476749372946879873024]

/-- Integer-arithmetic certificate (the heavy kernel computation). -/
lemma f_50_part_2_evalEisListZ_eq :
    evalEisListZ f_50_part_2_polyDataZ 10 = f_50_part_2_qExpListZ := by
  decide +kernel

end LeanBridge.QExpansion.LMFDB.W50
