import LeanBridge.ForMathlib.QExpansion.IntEval

set_option maxHeartbeats 0
set_option maxRecDepth 4000

/-!
# LMFDB level-1 weight-54 form `1.54.a`, piece 2: integer q-coefficient certificate

Heavy `decide +kernel` over `ℤ` (denominators cleared by the scale `D = 68080775185953718272`), isolated in its own
module so `lake` schedules it in parallel with the other pieces. Generated by
`scripts/lmfdb_qexp_to_e4e6_v3.sage`.
-/

namespace LeanBridge.QExpansion.LMFDB.W54

open LeanBridge.QExpansion

def f_54_part_2_polyDataZ : List (ℕ × ℕ × ℤ) :=
  [(0, 9, 7712177), (3, 7, (-29931128)), (6, 5, 43520322), (9, 3, (-28095968)), (12, 1, 6794597)]

def f_54_part_2_scale : ℤ := 68080775185953718272

def f_54_part_2_qExpListZ : List ℤ :=
  [0, 0, 0, (-4734511255388160), 68080775185953718272, (-40247655633263473459200), 2824569604603813772132352, (-36191292961868233184378880), 0, 7658102287413093907084345344]

/-- Integer-arithmetic certificate (the heavy kernel computation). -/
lemma f_54_part_2_evalEisListZ_eq :
    evalEisListZ f_54_part_2_polyDataZ 10 = f_54_part_2_qExpListZ := by
  decide +kernel

end LeanBridge.QExpansion.LMFDB.W54
