import LeanBridge.ForMathlib.QExpansion.IntEval

set_option maxHeartbeats 0
set_option maxRecDepth 4000

/-!
# LMFDB level-1 weight-82 form `1.82.a`, piece 5: integer q-coefficient certificate

Heavy `decide +kernel` over `ℤ` (denominators cleared by the scale `D = 2935507177287374264300369940567063116210549373164401783045632244580352`), isolated in its own
module so `lake` schedules it in parallel with the other pieces. Generated by
`scripts/lmfdb_qexp_to_e4e6_v3.sage`.
-/

namespace LeanBridge.QExpansion.LMFDB.W82

open LeanBridge.QExpansion

def f_82_part_5_polyDataZ : List (ℕ × ℕ × ℤ) :=
  [(1, 13, (-708536727026530062097)), (4, 11, 3302131552378070579106), (7, 9, (-5883699006370923319563)), (10, 7, 4683180373927621129196), (13, 5, (-1140611701940078329815)), (16, 3, (-492959092150185972654)), (19, 1, 240494601182025975827)]

def f_82_part_5_scale : ℤ := 2935507177287374264300369940567063116210549373164401783045632244580352

def f_82_part_5_qExpListZ : List ℤ :=
  [0, 0, 0, 5338661195968746498369257472, 0, 14618806190656248828595344796085649408, (-13951517096056000493623604082069932605440), 4861226120684811426036581105894136527978496, 0, (-464026761904362163594123852306763964520794685440)]

/-- Integer-arithmetic certificate (the heavy kernel computation). -/
lemma f_82_part_5_evalEisListZ_eq :
    evalEisListZ f_82_part_5_polyDataZ 10 = f_82_part_5_qExpListZ := by
  decide +kernel

end LeanBridge.QExpansion.LMFDB.W82
