import LeanBridge.ForMathlib.QExpansion.IntEval

set_option maxHeartbeats 0
set_option maxRecDepth 4000

/-!
# LMFDB level-1 weight-80 form `1.80.a`, piece 4: integer q-coefficient certificate

Heavy `decide +kernel` over `ℤ` (denominators cleared by the scale `D = 352646945279333913058226861281553449677937006590032028435500205342720`), isolated in its own
module so `lake` schedules it in parallel with the other pieces. Generated by
`scripts/lmfdb_qexp_to_e4e6_v3.sage`.
-/

namespace LeanBridge.QExpansion.LMFDB.W80

open LeanBridge.QExpansion

def f_80_part_4_polyDataZ : List (ℕ × ℕ × ℤ) :=
  [(2, 12, 550619261271881367587037458769265), (5, 10, (-3271019761935003680332449391615374)), (8, 8, 8096304095004712316975037927921495), (11, 6, (-10687071437345974032236767669051940)), (14, 4, 7934298442281464484379007474241615), (17, 2, (-3141215710500125943807841447552110)), (20, 0, 518085111223045487435975647287049)]

def f_80_part_4_scale : ℤ := 352646945279333913058226861281553449677937006590032028435500205342720

def f_80_part_4_qExpListZ : List ℤ :=
  [0, 0, 0, (-1715878560333307062397273013119824691200), 0, (-500862534275749553567439213388440755874601893888), 14118037091899370456606219861717322658282638692843520, 4700114370795879382062087570312399019837289088732364800, 0, (-53923846965785613929614903124109534743868226361869404733440)]

/-- Integer-arithmetic certificate (the heavy kernel computation). -/
lemma f_80_part_4_evalEisListZ_eq :
    evalEisListZ f_80_part_4_polyDataZ 10 = f_80_part_4_qExpListZ := by
  decide +kernel

end LeanBridge.QExpansion.LMFDB.W80
