import LeanBridge.ForMathlib.QExpansion.IntEval

set_option maxHeartbeats 0
set_option maxRecDepth 4000

/-!
# LMFDB level-1 weight-52 form `1.52.a`, piece 1: integer q-coefficient certificate

Heavy `decide +kernel` over `ℤ` (denominators cleared by the scale `D = 4778658336079872`), isolated in its own
module so `lake` schedules it in parallel with the other pieces. Generated by
`scripts/lmfdb_qexp_to_e4e6_v3.sage`.
-/

namespace LeanBridge.QExpansion.LMFDB.W52

open LeanBridge.QExpansion

def f_52_part_1_polyDataZ : List (ℕ × ℕ × ℤ) :=
  [(1, 8, (-46886131723)), (4, 6, 97500988924), (7, 4, (-9585813426)), (10, 2, (-85786813028)), (13, 0, 44757769253)]

def f_52_part_1_scale : ℤ := 4778658336079872

def f_52_part_1_qExpListZ : List ℤ :=
  [0, 0, 4778658336079872, 472403648436334755840, 0, 75568304342349899158781952, 25197105878720563004540190720, 348709568637267682019191554048, (-21521163901700225980291992256512), 647193435716322646410957013647360]

/-- Integer-arithmetic certificate (the heavy kernel computation). -/
lemma f_52_part_1_evalEisListZ_eq :
    evalEisListZ f_52_part_1_polyDataZ 10 = f_52_part_1_qExpListZ := by
  decide +kernel

end LeanBridge.QExpansion.LMFDB.W52
