import LeanBridge.ForMathlib.QExpansion.IntEval

set_option maxHeartbeats 0
set_option maxRecDepth 4000

/-!
# LMFDB level-1 weight-16 form `1.16.a`, piece 0: integer q-coefficient certificate

Heavy `decide +kernel` over `ℤ` (denominators cleared by the scale `D = 1728`), isolated in its own
module so `lake` schedules it in parallel with the other pieces. Generated by
`scripts/lmfdb_qexp_to_e4e6_v3.sage`.
-/

namespace LeanBridge.QExpansion.LMFDB.W16

open LeanBridge.QExpansion

def f_16_part_0_polyDataZ : List (ℕ × ℕ × ℤ) :=
  [(1, 2, (-1)), (4, 0, 1)]

def f_16_part_0_scale : ℤ := 1728

def f_16_part_0_qExpListZ : List ℤ :=
  [0, 1728, 373248, (-5785344), 23998464, 90046080, (-1249634304), 4877203968, (-7046922240), (-5425579584)]

/-- Integer-arithmetic certificate (the heavy kernel computation). -/
lemma f_16_part_0_evalEisListZ_eq :
    evalEisListZ f_16_part_0_polyDataZ 10 = f_16_part_0_qExpListZ := by
  decide +kernel

end LeanBridge.QExpansion.LMFDB.W16
