import LeanBridge.ForMathlib.QExpansion.IntEval

set_option maxHeartbeats 0
set_option maxRecDepth 4000

/-!
# LMFDB level-1 weight-80 form `1.80.a`, piece 5: integer q-coefficient certificate

Heavy `decide +kernel` over `ℤ` (denominators cleared by the scale `D = 8463526686704013913397444670757282792270488158160768682452004928225280`), isolated in its own
module so `lake` schedules it in parallel with the other pieces. Generated by
`scripts/lmfdb_qexp_to_e4e6_v3.sage`.
-/

namespace LeanBridge.QExpansion.LMFDB.W80

open LeanBridge.QExpansion

def f_80_part_5_polyDataZ : List (ℕ × ℕ × ℤ) :=
  [(2, 12, (-1909451990047714947385)), (5, 10, 11293440837281739810174), (8, 8, (-27963456123815913800655)), (11, 6, 37015574720177643850820), (14, 4, (-27558615939739122639495)), (17, 2, 10913839968086559562590), (20, 0, (-1791331471943191836049))]

def f_80_part_5_scale : ℤ := 8463526686704013913397444670757282792270488158160768682452004928225280

def f_80_part_5_qExpListZ : List ℤ :=
  [0, 0, 0, 479246607459701434223186411520, 0, 1710450366517499352193272799914098688, (-48890523054247545403280734660565611315200), (-16278201023934110725602666508575935362498560), 0, 190021539155141497820698629765853319322088243200]

/-- Integer-arithmetic certificate (the heavy kernel computation). -/
lemma f_80_part_5_evalEisListZ_eq :
    evalEisListZ f_80_part_5_polyDataZ 10 = f_80_part_5_qExpListZ := by
  decide +kernel

end LeanBridge.QExpansion.LMFDB.W80
