import LeanBridge.ForMathlib.QExpansion.Generic
import LeanBridge.ForMathlib.QExpansion.Sturm
import Mathlib.Analysis.Complex.Polynomial.Basic

/-!
# LMFDB level-1 modular form orbit `1.50.a.{a..}` (Hecke field degree 3)

The Hecke field `K = ℚ(α)` is degree 3 over ℚ. The LMFDB lists q-coefficients as
elements of `K`, which we decompose as `c_0 + c_1 · α + … + c_{2} · α^2`.
The combined form is `f = f_0 + α · f_1 + … + α^2 · f_{2}`, with each
`f_j` a level-1 weight-50 form with rational coefficients in `(E₄, E₆)`.

The Sturm bound for weight 50 is `⌊50/12⌋ + 1 = 5`. After certifying agreement
on the first 5 q-coefficients, `ModularForm.eq_of_sturm_bound` lets us conclude that any
form with the same coefficients equals our explicit `lmfdb_1_50_a_orbit`.

Generated by `scripts/lmfdb_qexp_to_e4e6_v3.sage`.
-/

namespace LeanBridge.QExpansion.LMFDB.W50

open LeanBridge.QExpansion ModularForm EisensteinSeries PowerSeries UpperHalfPlane
open scoped MatrixGroups


/-- Minimal polynomial of α (degree 3) as `Polynomial ℂ`. -/
noncomputable def α_50_minpoly : Polynomial ℂ :=
  Polynomial.X ^ 3 +
    Polynomial.C (-13634883228742736412672) +
    Polynomial.C (-566746931810304) * Polynomial.X +
    Polynomial.C 24225168 * Polynomial.X ^ 2

lemma α_50_minpoly_natDegree : α_50_minpoly.natDegree = 3 := by
  unfold α_50_minpoly
  compute_degree!

lemma α_50_minpoly_degree_ne_zero : α_50_minpoly.degree ≠ 0 := by
  rw [Polynomial.degree_eq_natDegree (fun h => by
    have := α_50_minpoly_natDegree
    rw [h, Polynomial.natDegree_zero] at this
    exact absurd this (by decide))]
  rw [α_50_minpoly_natDegree]
  decide

/-- α is some root of the degree-3 minimal polynomial in ℂ. -/
noncomputable def α_50 : ℂ :=
  (IsAlgClosed.exists_root α_50_minpoly α_50_minpoly_degree_ne_zero).choose

lemma α_50_isRoot : Polynomial.IsRoot α_50_minpoly α_50 :=
  (IsAlgClosed.exists_root α_50_minpoly α_50_minpoly_degree_ne_zero).choose_spec

/-- Explicit polynomial relation: minpoly evaluated at α is zero. -/
lemma α_50_is_root :
    α_50 ^ 3 +
      (-13634883228742736412672) +
      (-566746931810304) * α_50 +
      24225168 * α_50 ^ 2 = 0 := by
  have h := α_50_isRoot
  unfold Polynomial.IsRoot α_50_minpoly at h
  simp only [Polynomial.eval_add, Polynomial.eval_mul, Polynomial.eval_pow,
    Polynomial.eval_C, Polynomial.eval_X] at h
  linear_combination h


/-! ## Piece 0: coefficient of α^0 -/


def f_50_part_0_polyData : List (ℕ × ℕ × ℚ) :=
  [(2, 7, ((-(15270995581 / 13436928)))), (5, 5, (15270993493 / 4478976)), (8, 3, ((-(15270993997 / 4478976)))), (11, 1, (15270997093 / 13436928))]

noncomputable def f_50_part_0 : ModularForm 𝒮ℒ 50 :=
  (((-(15270995581 / 13436928))) : ℂ) • mkMonomForm 2 7 50 (by decide) +
  ((15270993493 / 4478976) : ℂ) • mkMonomForm 5 5 50 (by decide) +
  (((-(15270993997 / 4478976))) : ℂ) • mkMonomForm 8 3 50 (by decide) +
  ((15270997093 / 13436928) : ℂ) • mkMonomForm 11 1 50 (by decide)

lemma f_50_part_0_qExpansion_eq_evalEisPS :
    qExpansion 1 (f_50_part_0 : ℍ → ℂ) = evalEisPS f_50_part_0_polyData := by
  unfold f_50_part_0
  rw [ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm]
  unfold evalEisPS f_50_part_0_polyData monomialEisPS
  simp only [List.foldr_cons, List.foldr_nil, add_zero]
  push_cast
  module

theorem f_50_part_0_qExpansion_coeff (N n : ℕ) (hn : n < N) :
    (PowerSeries.coeff (R := ℂ) n) (qExpansion 1 (f_50_part_0 : ℍ → ℂ))
      = ((evalEisList f_50_part_0_polyData N).getD n 0 : ℚ) :=
  qexp_coeff_via_E4E6 _ _ f_50_part_0_qExpansion_eq_evalEisPS N n hn

/-- Precomputed first 10 q-coefficients of `f_50_part_0` (rational). -/
def f_50_part_0_qExpList : List ℚ :=
  [0, 1, 0, 5864062013124, (-562949953421312), (-1128362816417343930), (-142030033632736837632), 3858013787644323520136, 13634883228742736412672, (-1678654914206870695090995)]

/-- One-shot bridge: the symbolic `evalEisList` equals the precomputed list (verified by
`decide +kernel` once instead of N times). -/
lemma f_50_part_0_evalEisList_eq :
    evalEisList f_50_part_0_polyData 10 = f_50_part_0_qExpList := by
  decide +kernel


/-! ## Piece 1: coefficient of α^1 -/


def f_50_part_1_polyData : List (ℕ × ℕ × ℚ) :=
  [(2, 7, (155 / 1146617856)), (5, 5, ((-(1 / 14155776)))), (8, 3, ((-(101 / 382205952)))), (11, 1, (229 / 1146617856))]

noncomputable def f_50_part_1 : ModularForm 𝒮ℒ 50 :=
  ((155 / 1146617856) : ℂ) • mkMonomForm 2 7 50 (by decide) +
  (((-(1 / 14155776))) : ℂ) • mkMonomForm 5 5 50 (by decide) +
  (((-(101 / 382205952))) : ℂ) • mkMonomForm 8 3 50 (by decide) +
  ((229 / 1146617856) : ℂ) • mkMonomForm 11 1 50 (by decide)

lemma f_50_part_1_qExpansion_eq_evalEisPS :
    qExpansion 1 (f_50_part_1 : ℍ → ℂ) = evalEisPS f_50_part_1_polyData := by
  unfold f_50_part_1
  rw [ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm]
  unfold evalEisPS f_50_part_1_polyData monomialEisPS
  simp only [List.foldr_cons, List.foldr_nil, add_zero]
  push_cast
  module

theorem f_50_part_1_qExpansion_coeff (N n : ℕ) (hn : n < N) :
    (PowerSeries.coeff (R := ℂ) n) (qExpansion 1 (f_50_part_1 : ℍ → ℂ))
      = ((evalEisList f_50_part_1_polyData N).getD n 0 : ℚ) :=
  qexp_coeff_via_E4E6 _ _ f_50_part_1_qExpansion_eq_evalEisPS N n hn

/-- Precomputed first 10 q-coefficients of `f_50_part_1` (rational). -/
def f_50_part_1_qExpList : List ℚ :=
  [0, 0, 1, ((-(99 / 2))), 0, (-30575050), (-39551859900), (-8934250205979), (-559152975032320), (-10266961953372300)]

/-- One-shot bridge: the symbolic `evalEisList` equals the precomputed list (verified by
`decide +kernel` once instead of N times). -/
lemma f_50_part_1_evalEisList_eq :
    evalEisList f_50_part_1_polyData 10 = f_50_part_1_qExpList := by
  decide +kernel


/-! ## Piece 2: coefficient of α^2 -/


def f_50_part_2_polyData : List (ℕ × ℕ × ℚ) :=
  [(2, 7, (1 / 495338913792)), (5, 5, ((-(1 / 165112971264)))), (8, 3, (1 / 165112971264)), (11, 1, ((-(1 / 495338913792))))]

noncomputable def f_50_part_2 : ModularForm 𝒮ℒ 50 :=
  ((1 / 495338913792) : ℂ) • mkMonomForm 2 7 50 (by decide) +
  (((-(1 / 165112971264))) : ℂ) • mkMonomForm 5 5 50 (by decide) +
  ((1 / 165112971264) : ℂ) • mkMonomForm 8 3 50 (by decide) +
  (((-(1 / 495338913792))) : ℂ) • mkMonomForm 11 1 50 (by decide)

lemma f_50_part_2_qExpansion_eq_evalEisPS :
    qExpansion 1 (f_50_part_2 : ℍ → ℂ) = evalEisPS f_50_part_2_polyData := by
  unfold f_50_part_2
  rw [ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm]
  unfold evalEisPS f_50_part_2_polyData monomialEisPS
  simp only [List.foldr_cons, List.foldr_nil, add_zero]
  push_cast
  module

theorem f_50_part_2_qExpansion_coeff (N n : ℕ) (hn : n < N) :
    (PowerSeries.coeff (R := ℂ) n) (qExpansion 1 (f_50_part_2 : ℍ → ℂ))
      = ((evalEisList f_50_part_2_polyData N).getD n 0 : ℚ) :=
  qexp_coeff_via_E4E6 _ _ f_50_part_2_qExpansion_eq_evalEisPS N n hn

/-- Precomputed first 10 q-coefficients of `f_50_part_2` (rational). -/
def f_50_part_2_qExpList : List ℚ :=
  [0, 0, 0, ((-(1 / 96))), 1, (16035 / 8), 252296, ((-(109651619 / 16))), (-24225168), (11925163413 / 4)]

/-- One-shot bridge: the symbolic `evalEisList` equals the precomputed list (verified by
`decide +kernel` once instead of N times). -/
lemma f_50_part_2_evalEisList_eq :
    evalEisList f_50_part_2_polyData 10 = f_50_part_2_qExpList := by
  decide +kernel


/-! ## Combined LMFDB form -/


noncomputable def lmfdb_1_50_a_orbit : ModularForm 𝒮ℒ 50 :=
  f_50_part_0 +
  α_50 • f_50_part_1 +
  α_50 ^ 2 • f_50_part_2

lemma lmfdb_1_50_a_orbit_coeff_decomp (n : ℕ) :
    (PowerSeries.coeff (R := ℂ) n) (qExpansion 1 (lmfdb_1_50_a_orbit : ℍ → ℂ))
      = (PowerSeries.coeff (R := ℂ) n) (qExpansion 1 (f_50_part_0 : ℍ → ℂ))
        + α_50 * (PowerSeries.coeff (R := ℂ) n) (qExpansion 1 (f_50_part_1 : ℍ → ℂ))
        + α_50 ^ 2 * (PowerSeries.coeff (R := ℂ) n) (qExpansion 1 (f_50_part_2 : ℍ → ℂ)) := by
  unfold lmfdb_1_50_a_orbit
  rw [ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL]
  simp [smul_eq_mul]


/-! ## Coefficient lemmas (n = 0, …, 9)

Sturm bound is 5; we certify 10 coefficients for added
redundancy beyond the minimum mathematically required for uniqueness. -/


lemma lmfdb_1_50_a_orbit_qExpansion_coeff_0 :
    (PowerSeries.coeff (R := ℂ) 0)
      (qExpansion 1 (lmfdb_1_50_a_orbit : ℍ → ℂ)) = 0 := by
  rw [lmfdb_1_50_a_orbit_coeff_decomp,
    f_50_part_0_qExpansion_coeff 10 0 (by decide),
    f_50_part_1_qExpansion_coeff 10 0 (by decide),
    f_50_part_2_qExpansion_coeff 10 0 (by decide),
    f_50_part_0_evalEisList_eq,
    f_50_part_1_evalEisList_eq,
    f_50_part_2_evalEisList_eq,
    show f_50_part_0_qExpList.getD 0 0 = (0 : ℚ) from by decide +kernel,
    show f_50_part_1_qExpList.getD 0 0 = (0 : ℚ) from by decide +kernel,
    show f_50_part_2_qExpList.getD 0 0 = (0 : ℚ) from by decide +kernel]
  push_cast; ring

lemma lmfdb_1_50_a_orbit_qExpansion_coeff_1 :
    (PowerSeries.coeff (R := ℂ) 1)
      (qExpansion 1 (lmfdb_1_50_a_orbit : ℍ → ℂ)) = 1 := by
  rw [lmfdb_1_50_a_orbit_coeff_decomp,
    f_50_part_0_qExpansion_coeff 10 1 (by decide),
    f_50_part_1_qExpansion_coeff 10 1 (by decide),
    f_50_part_2_qExpansion_coeff 10 1 (by decide),
    f_50_part_0_evalEisList_eq,
    f_50_part_1_evalEisList_eq,
    f_50_part_2_evalEisList_eq,
    show f_50_part_0_qExpList.getD 1 0 = (1 : ℚ) from by decide +kernel,
    show f_50_part_1_qExpList.getD 1 0 = (0 : ℚ) from by decide +kernel,
    show f_50_part_2_qExpList.getD 1 0 = (0 : ℚ) from by decide +kernel]
  push_cast; ring

lemma lmfdb_1_50_a_orbit_qExpansion_coeff_2 :
    (PowerSeries.coeff (R := ℂ) 2)
      (qExpansion 1 (lmfdb_1_50_a_orbit : ℍ → ℂ)) = 1 * α_50 := by
  rw [lmfdb_1_50_a_orbit_coeff_decomp,
    f_50_part_0_qExpansion_coeff 10 2 (by decide),
    f_50_part_1_qExpansion_coeff 10 2 (by decide),
    f_50_part_2_qExpansion_coeff 10 2 (by decide),
    f_50_part_0_evalEisList_eq,
    f_50_part_1_evalEisList_eq,
    f_50_part_2_evalEisList_eq,
    show f_50_part_0_qExpList.getD 2 0 = (0 : ℚ) from by decide +kernel,
    show f_50_part_1_qExpList.getD 2 0 = (1 : ℚ) from by decide +kernel,
    show f_50_part_2_qExpList.getD 2 0 = (0 : ℚ) from by decide +kernel]
  push_cast; ring

lemma lmfdb_1_50_a_orbit_qExpansion_coeff_3 :
    (PowerSeries.coeff (R := ℂ) 3)
      (qExpansion 1 (lmfdb_1_50_a_orbit : ℍ → ℂ)) = 5864062013124 + ((-(99 / 2))) * α_50 + ((-(1 / 96))) * α_50 ^ 2 := by
  rw [lmfdb_1_50_a_orbit_coeff_decomp,
    f_50_part_0_qExpansion_coeff 10 3 (by decide),
    f_50_part_1_qExpansion_coeff 10 3 (by decide),
    f_50_part_2_qExpansion_coeff 10 3 (by decide),
    f_50_part_0_evalEisList_eq,
    f_50_part_1_evalEisList_eq,
    f_50_part_2_evalEisList_eq,
    show f_50_part_0_qExpList.getD 3 0 = (5864062013124 : ℚ) from by decide +kernel,
    show f_50_part_1_qExpList.getD 3 0 = (((-(99 / 2))) : ℚ) from by decide +kernel,
    show f_50_part_2_qExpList.getD 3 0 = (((-(1 / 96))) : ℚ) from by decide +kernel]
  push_cast; ring

lemma lmfdb_1_50_a_orbit_qExpansion_coeff_4 :
    (PowerSeries.coeff (R := ℂ) 4)
      (qExpansion 1 (lmfdb_1_50_a_orbit : ℍ → ℂ)) = (-562949953421312) + 1 * α_50 ^ 2 := by
  rw [lmfdb_1_50_a_orbit_coeff_decomp,
    f_50_part_0_qExpansion_coeff 10 4 (by decide),
    f_50_part_1_qExpansion_coeff 10 4 (by decide),
    f_50_part_2_qExpansion_coeff 10 4 (by decide),
    f_50_part_0_evalEisList_eq,
    f_50_part_1_evalEisList_eq,
    f_50_part_2_evalEisList_eq,
    show f_50_part_0_qExpList.getD 4 0 = ((-562949953421312) : ℚ) from by decide +kernel,
    show f_50_part_1_qExpList.getD 4 0 = (0 : ℚ) from by decide +kernel,
    show f_50_part_2_qExpList.getD 4 0 = (1 : ℚ) from by decide +kernel]
  push_cast; ring

lemma lmfdb_1_50_a_orbit_qExpansion_coeff_5 :
    (PowerSeries.coeff (R := ℂ) 5)
      (qExpansion 1 (lmfdb_1_50_a_orbit : ℍ → ℂ)) = (-1128362816417343930) + (-30575050) * α_50 + (16035 / 8) * α_50 ^ 2 := by
  rw [lmfdb_1_50_a_orbit_coeff_decomp,
    f_50_part_0_qExpansion_coeff 10 5 (by decide),
    f_50_part_1_qExpansion_coeff 10 5 (by decide),
    f_50_part_2_qExpansion_coeff 10 5 (by decide),
    f_50_part_0_evalEisList_eq,
    f_50_part_1_evalEisList_eq,
    f_50_part_2_evalEisList_eq,
    show f_50_part_0_qExpList.getD 5 0 = ((-1128362816417343930) : ℚ) from by decide +kernel,
    show f_50_part_1_qExpList.getD 5 0 = ((-30575050) : ℚ) from by decide +kernel,
    show f_50_part_2_qExpList.getD 5 0 = ((16035 / 8) : ℚ) from by decide +kernel]
  push_cast; ring

lemma lmfdb_1_50_a_orbit_qExpansion_coeff_6 :
    (PowerSeries.coeff (R := ℂ) 6)
      (qExpansion 1 (lmfdb_1_50_a_orbit : ℍ → ℂ)) = (-142030033632736837632) + (-39551859900) * α_50 + 252296 * α_50 ^ 2 := by
  rw [lmfdb_1_50_a_orbit_coeff_decomp,
    f_50_part_0_qExpansion_coeff 10 6 (by decide),
    f_50_part_1_qExpansion_coeff 10 6 (by decide),
    f_50_part_2_qExpansion_coeff 10 6 (by decide),
    f_50_part_0_evalEisList_eq,
    f_50_part_1_evalEisList_eq,
    f_50_part_2_evalEisList_eq,
    show f_50_part_0_qExpList.getD 6 0 = ((-142030033632736837632) : ℚ) from by decide +kernel,
    show f_50_part_1_qExpList.getD 6 0 = ((-39551859900) : ℚ) from by decide +kernel,
    show f_50_part_2_qExpList.getD 6 0 = (252296 : ℚ) from by decide +kernel]
  push_cast; ring

lemma lmfdb_1_50_a_orbit_qExpansion_coeff_7 :
    (PowerSeries.coeff (R := ℂ) 7)
      (qExpansion 1 (lmfdb_1_50_a_orbit : ℍ → ℂ)) = 3858013787644323520136 + (-8934250205979) * α_50 + ((-(109651619 / 16))) * α_50 ^ 2 := by
  rw [lmfdb_1_50_a_orbit_coeff_decomp,
    f_50_part_0_qExpansion_coeff 10 7 (by decide),
    f_50_part_1_qExpansion_coeff 10 7 (by decide),
    f_50_part_2_qExpansion_coeff 10 7 (by decide),
    f_50_part_0_evalEisList_eq,
    f_50_part_1_evalEisList_eq,
    f_50_part_2_evalEisList_eq,
    show f_50_part_0_qExpList.getD 7 0 = (3858013787644323520136 : ℚ) from by decide +kernel,
    show f_50_part_1_qExpList.getD 7 0 = ((-8934250205979) : ℚ) from by decide +kernel,
    show f_50_part_2_qExpList.getD 7 0 = (((-(109651619 / 16))) : ℚ) from by decide +kernel]
  push_cast; ring

lemma lmfdb_1_50_a_orbit_qExpansion_coeff_8 :
    (PowerSeries.coeff (R := ℂ) 8)
      (qExpansion 1 (lmfdb_1_50_a_orbit : ℍ → ℂ)) = 13634883228742736412672 + (-559152975032320) * α_50 + (-24225168) * α_50 ^ 2 := by
  rw [lmfdb_1_50_a_orbit_coeff_decomp,
    f_50_part_0_qExpansion_coeff 10 8 (by decide),
    f_50_part_1_qExpansion_coeff 10 8 (by decide),
    f_50_part_2_qExpansion_coeff 10 8 (by decide),
    f_50_part_0_evalEisList_eq,
    f_50_part_1_evalEisList_eq,
    f_50_part_2_evalEisList_eq,
    show f_50_part_0_qExpList.getD 8 0 = (13634883228742736412672 : ℚ) from by decide +kernel,
    show f_50_part_1_qExpList.getD 8 0 = ((-559152975032320) : ℚ) from by decide +kernel,
    show f_50_part_2_qExpList.getD 8 0 = ((-24225168) : ℚ) from by decide +kernel]
  push_cast; ring

lemma lmfdb_1_50_a_orbit_qExpansion_coeff_9 :
    (PowerSeries.coeff (R := ℂ) 9)
      (qExpansion 1 (lmfdb_1_50_a_orbit : ℍ → ℂ)) = (-1678654914206870695090995) + (-10266961953372300) * α_50 + (11925163413 / 4) * α_50 ^ 2 := by
  rw [lmfdb_1_50_a_orbit_coeff_decomp,
    f_50_part_0_qExpansion_coeff 10 9 (by decide),
    f_50_part_1_qExpansion_coeff 10 9 (by decide),
    f_50_part_2_qExpansion_coeff 10 9 (by decide),
    f_50_part_0_evalEisList_eq,
    f_50_part_1_evalEisList_eq,
    f_50_part_2_evalEisList_eq,
    show f_50_part_0_qExpList.getD 9 0 = ((-1678654914206870695090995) : ℚ) from by decide +kernel,
    show f_50_part_1_qExpList.getD 9 0 = ((-10266961953372300) : ℚ) from by decide +kernel,
    show f_50_part_2_qExpList.getD 9 0 = ((11925163413 / 4) : ℚ) from by decide +kernel]
  push_cast; ring


/-! ## Uniqueness theorem -/


/-- **Uniqueness theorem.** Any level-1 weight-50 modular form `f` whose first 5
q-coefficients match the LMFDB-published values for `1.50.a.{a..}` is equal to our
explicit construction `lmfdb_1_50_a_orbit`. Proven via `ModularForm.eq_of_sturm_bound`. -/
theorem identifies_lmfdb_1_50_a_orbit (f : ModularForm 𝒮ℒ 50)
    (h_0 : (PowerSeries.coeff (R := ℂ) 0) (qExpansion 1 (f : ℍ → ℂ)) = 0)
    (h_1 : (PowerSeries.coeff (R := ℂ) 1) (qExpansion 1 (f : ℍ → ℂ)) = 1)
    (h_2 : (PowerSeries.coeff (R := ℂ) 2) (qExpansion 1 (f : ℍ → ℂ)) = 1 * α_50)
    (h_3 : (PowerSeries.coeff (R := ℂ) 3) (qExpansion 1 (f : ℍ → ℂ)) = 5864062013124 + ((-(99 / 2))) * α_50 + ((-(1 / 96))) * α_50 ^ 2)
    (h_4 : (PowerSeries.coeff (R := ℂ) 4) (qExpansion 1 (f : ℍ → ℂ)) = (-562949953421312) + 1 * α_50 ^ 2) :
    f = lmfdb_1_50_a_orbit := by
  apply ModularForm.eq_of_sturm_bound
  intro i hi
  have : i ≤ 4 := by omega
  interval_cases i
  · rw [h_0, lmfdb_1_50_a_orbit_qExpansion_coeff_0]
  · rw [h_1, lmfdb_1_50_a_orbit_qExpansion_coeff_1]
  · rw [h_2, lmfdb_1_50_a_orbit_qExpansion_coeff_2]
  · rw [h_3, lmfdb_1_50_a_orbit_qExpansion_coeff_3]
  · rw [h_4, lmfdb_1_50_a_orbit_qExpansion_coeff_4]


end LeanBridge.QExpansion.LMFDB.W50