import LeanBridge.ForMathlib.QExpansion.IntEval

set_option maxHeartbeats 0
set_option maxRecDepth 4000

/-!
# LMFDB level-1 weight-46 form `1.46.a`, piece 1: integer q-coefficient certificate

Heavy `decide +kernel` over `ℤ` (denominators cleared by the scale `D = 1504935936`), isolated in its own
module so `lake` schedules it in parallel with the other pieces. Generated by
`scripts/lmfdb_qexp_to_e4e6_v3.sage`.
-/

namespace LeanBridge.QExpansion.LMFDB.W46

open LeanBridge.QExpansion

def f_46_part_1_polyDataZ : List (ℕ × ℕ × ℤ) :=
  [(1, 7, 145), (4, 5, 69), (7, 3, (-573)), (10, 1, 359)]

def f_46_part_1_scale : ℤ := 1504935936

def f_46_part_1_qExpListZ : List ℤ :=
  [0, 0, 1504935936, (-134154289152), 0, (-103753207303372800), (-41924423200083148800), (-2961127389857357758464), (-38863622028285444096000), 469436798310003140198400]

/-- Integer-arithmetic certificate (the heavy kernel computation). -/
lemma f_46_part_1_evalEisListZ_eq :
    evalEisListZ f_46_part_1_polyDataZ 10 = f_46_part_1_qExpListZ := by
  decide +kernel

end LeanBridge.QExpansion.LMFDB.W46
