import LeanBridge.ForMathlib.QExpansion.IntEval

set_option maxHeartbeats 0
set_option maxRecDepth 4000

/-!
# LMFDB level-1 weight-42 form `1.42.a`, piece 1: integer q-coefficient certificate

Heavy `decide +kernel` over `ℤ` (denominators cleared by the scale `D = 6879707136`), isolated in its own
module so `lake` schedules it in parallel with the other pieces. Generated by
`scripts/lmfdb_qexp_to_e4e6_v3.sage`.
-/

namespace LeanBridge.QExpansion.LMFDB.W42

open LeanBridge.QExpansion

def f_42_part_1_polyDataZ : List (ℕ × ℕ × ℤ) :=
  [(0, 7, 485), (3, 5, 849), (6, 3, (-3153)), (9, 1, 1819)]

def f_42_part_1_scale : ℤ := 6879707136

def f_42_part_1_qExpListZ : List ℤ :=
  [0, 0, 6879707136, (-1346702671872), 0, (-576000900071424000), (-49877501791961088000), (-336804029072483549184), 13600740125417637150720, (-15246077463337107456000)]

/-- Integer-arithmetic certificate (the heavy kernel computation). -/
lemma f_42_part_1_evalEisListZ_eq :
    evalEisListZ f_42_part_1_polyDataZ 10 = f_42_part_1_qExpListZ := by
  decide +kernel

end LeanBridge.QExpansion.LMFDB.W42
