import LeanBridge.ForMathlib.QExpansion.IntEval

set_option maxHeartbeats 0
set_option maxRecDepth 4000

/-!
# LMFDB level-1 weight-30 form `1.30.a`, piece 1: integer q-coefficient certificate

Heavy `decide +kernel` over `ℤ` (denominators cleared by the scale `D = 2985984`), isolated in its own
module so `lake` schedules it in parallel with the other pieces. Generated by
`scripts/lmfdb_qexp_to_e4e6_v3.sage`.
-/

namespace LeanBridge.QExpansion.LMFDB.W30

open LeanBridge.QExpansion

def f_30_part_1_polyDataZ : List (ℕ × ℕ × ℤ) :=
  [(0, 5, 1), (3, 3, (-2)), (6, 1, 1)]

def f_30_part_1_scale : ℤ := 2985984

def f_30_part_1_qExpListZ : List ℤ :=
  [0, 0, 2985984, (-1648263168), 25798901760, 346374144000, (-14537143664640), 202615544807424, (-1625934696284160), 8187978043883520]

/-- Integer-arithmetic certificate (the heavy kernel computation). -/
lemma f_30_part_1_evalEisListZ_eq :
    evalEisListZ f_30_part_1_polyDataZ 10 = f_30_part_1_qExpListZ := by
  decide +kernel

end LeanBridge.QExpansion.LMFDB.W30
