import LeanBridge.ForMathlib.QExpansion.IntEval

set_option maxHeartbeats 0
set_option maxRecDepth 4000

/-!
# LMFDB level-1 weight-60 form `1.60.a`, piece 1: integer q-coefficient certificate

Heavy `decide +kernel` over `ℤ` (denominators cleared by the scale `D = 27787578352733729637531648`), isolated in its own
module so `lake` schedules it in parallel with the other pieces. Generated by
`scripts/lmfdb_qexp_to_e4e6_v3.sage`.
-/

namespace LeanBridge.QExpansion.LMFDB.W60

open LeanBridge.QExpansion

def f_60_part_1_polyDataZ : List (ℕ × ℕ × ℤ) :=
  [(0, 10, 365482671337002988925), (3, 8, (-504844818195162827917)), (6, 6, 43001234556661486706), (9, 4, (-745455504101859215594)), (12, 2, 1553873220629370338113), (15, 0, (-712056804226012770233))]

def f_60_part_1_scale : ℤ := 27787578352733729637531648

def f_60_part_1_qExpListZ : List ℤ :=
  [0, 0, 27787578352733729637531648, (-8601739130377994617323572428800), 0, (-4960563517404410547247909163501617152), 25194778138619908617286766108344320000, (-336321647489910862708115477727466506682368), (-32036896643814421978951887623496248693096448), (-484178664305021728800468161449507600465920000)]

/-- Integer-arithmetic certificate (the heavy kernel computation). -/
lemma f_60_part_1_evalEisListZ_eq :
    evalEisListZ f_60_part_1_polyDataZ 10 = f_60_part_1_qExpListZ := by
  decide +kernel

end LeanBridge.QExpansion.LMFDB.W60
