import LeanBridge.ForMathlib.QExpansion.IntEval

set_option maxHeartbeats 0
set_option maxRecDepth 4000

/-!
# LMFDB level-1 weight-36 form `1.36.a`, piece 1: integer q-coefficient certificate

Heavy `decide +kernel` over `ℤ` (denominators cleared by the scale `D = 191102976`), isolated in its own
module so `lake` schedules it in parallel with the other pieces. Generated by
`scripts/lmfdb_qexp_to_e4e6_v3.sage`.
-/

namespace LeanBridge.QExpansion.LMFDB.W36

open LeanBridge.QExpansion

def f_36_part_1_polyDataZ : List (ℕ × ℕ × ℤ) :=
  [(0, 6, (-75)), (3, 4, 289), (6, 2, (-353)), (9, 0, 139)]

def f_36_part_1_scale : ℤ := 191102976

def f_36_part_1_qExpListZ : List ℤ :=
  [0, 0, 191102976, 515404726272, 0, 2702536243937280, (-65801818865664000), 577394684019081216, (-1817606639352545280), 3988556650119168000]

/-- Integer-arithmetic certificate (the heavy kernel computation). -/
lemma f_36_part_1_evalEisListZ_eq :
    evalEisListZ f_36_part_1_polyDataZ 10 = f_36_part_1_qExpListZ := by
  decide +kernel

end LeanBridge.QExpansion.LMFDB.W36
