import LeanBridge.ForMathlib.QExpansion.IntEval

set_option maxHeartbeats 0
set_option maxRecDepth 4000

/-!
# LMFDB level-1 weight-62 form `1.62.a`, piece 1: integer q-coefficient certificate

Heavy `decide +kernel` over `ℤ` (denominators cleared by the scale `D = 334731215061909504`), isolated in its own
module so `lake` schedules it in parallel with the other pieces. Generated by
`scripts/lmfdb_qexp_to_e4e6_v3.sage`.
-/

namespace LeanBridge.QExpansion.LMFDB.W62

open LeanBridge.QExpansion

def f_62_part_1_polyDataZ : List (ℕ × ℕ × ℤ) :=
  [(2, 9, (-13628001382757)), (5, 7, 16833107102864), (8, 5, 31380787794606), (11, 3, (-58748891366776)), (14, 1, 24162997852063)]

def f_62_part_1_scale : ℤ := 334731215061909504

def f_62_part_1_qExpListZ : List ℤ :=
  [0, 0, 334731215061909504, 194872752096848982835200, 0, (-1438264596815923070411735040), (-8682041794685124483294953472000), (-7850084487204121855832521728589824), (-1543675264432219136386797805152239616), (-70210466224788709300288531159056384000)]

/-- Integer-arithmetic certificate (the heavy kernel computation). -/
lemma f_62_part_1_evalEisListZ_eq :
    evalEisListZ f_62_part_1_polyDataZ 10 = f_62_part_1_qExpListZ := by
  decide +kernel

end LeanBridge.QExpansion.LMFDB.W62
