import LeanBridge.ForMathlib.QExpansion.IntEval

set_option maxHeartbeats 0
set_option maxRecDepth 4000

/-!
# LMFDB level-1 weight-36 form `1.36.a`, piece 0: integer q-coefficient certificate

Heavy `decide +kernel` over `ℤ` (denominators cleared by the scale `D = 10077696`), isolated in its own
module so `lake` schedules it in parallel with the other pieces. Generated by
`scripts/lmfdb_qexp_to_e4e6_v3.sage`.
-/

namespace LeanBridge.QExpansion.LMFDB.W36

open LeanBridge.QExpansion

def f_36_part_0_polyDataZ : List (ℕ × ℕ × ℤ) :=
  [(0, 6, (-933829)), (3, 4, 2796708), (6, 2, (-2797761)), (9, 0, 934882)]

def f_36_part_0_scale : ℤ := 10077696

def f_36_part_0_qExpListZ : List ℤ :=
  [0, 10077696, 0, 4817255065233408, (-346266997912240128), 12348281837354775552, (-205420542660918116352), 7018588983329062391808, 14790279071586104377344, 1088909821060021908241920]

/-- Integer-arithmetic certificate (the heavy kernel computation). -/
lemma f_36_part_0_evalEisListZ_eq :
    evalEisListZ f_36_part_0_polyDataZ 10 = f_36_part_0_qExpListZ := by
  decide +kernel

end LeanBridge.QExpansion.LMFDB.W36
