import LeanBridge.ForMathlib.QExpansion.IntEval

set_option maxHeartbeats 0
set_option maxRecDepth 4000

/-!
# LMFDB level-1 weight-48 form `1.48.a`, piece 2: integer q-coefficient certificate

Heavy `decide +kernel` over `ℤ` (denominators cleared by the scale `D = 12238881434508460032`), isolated in its own
module so `lake` schedules it in parallel with the other pieces. Generated by
`scripts/lmfdb_qexp_to_e4e6_v3.sage`.
-/

namespace LeanBridge.QExpansion.LMFDB.W48

open LeanBridge.QExpansion

def f_48_part_2_polyDataZ : List (ℕ × ℕ × ℤ) :=
  [(0, 8, 1734907), (3, 6, (-5973668)), (6, 4, 7511562), (9, 2, (-4041748)), (12, 0, 768947)]

def f_48_part_2_scale : ℤ := 12238881434508460032

def f_48_part_2_qExpListZ : List ℤ :=
  [0, 0, 0, (-4984141428817920), 12238881434508460032, (-2132545678714456768512), 40241761202476834357248, 8460920291108491100160, 0, (-288588875759047533580517376)]

/-- Integer-arithmetic certificate (the heavy kernel computation). -/
lemma f_48_part_2_evalEisListZ_eq :
    evalEisListZ f_48_part_2_polyDataZ 10 = f_48_part_2_qExpListZ := by
  decide +kernel

end LeanBridge.QExpansion.LMFDB.W48
