import LeanBridge.ForMathlib.QExpansion.IntEval

set_option maxHeartbeats 0
set_option maxRecDepth 4000

/-!
# LMFDB level-1 weight-44 form `1.44.a`, piece 0: integer q-coefficient certificate

Heavy `decide +kernel` over `ℤ` (denominators cleared by the scale `D = 114213888`), isolated in its own
module so `lake` schedules it in parallel with the other pieces. Generated by
`scripts/lmfdb_qexp_to_e4e6_v3.sage`.
-/

namespace LeanBridge.QExpansion.LMFDB.W44

open LeanBridge.QExpansion

def f_44_part_0_polyDataZ : List (ℕ × ℕ × ℤ) :=
  [(2, 6, 477205523), (5, 4, (-1431689091)), (8, 2, 1431695517), (11, 0, (-477211949))]

def f_44_part_0_scale : ℤ := 114213888

def f_44_part_0_qExpListZ : List ℤ :=
  [0, 114213888, 0, (-2462344202921250816), (-1004635983276046024704), (-73483738900561948575744), 5592277114636794020757504, (-149114276043655965813743616), 2281649062771811960469061632, (-16348433028960998842939468800)]

/-- Integer-arithmetic certificate (the heavy kernel computation). -/
lemma f_44_part_0_evalEisListZ_eq :
    evalEisListZ f_44_part_0_polyDataZ 10 = f_44_part_0_qExpListZ := by
  decide +kernel

end LeanBridge.QExpansion.LMFDB.W44
