import LeanBridge.ForMathlib.QExpansion.IntEval

set_option maxHeartbeats 0
set_option maxRecDepth 4000

/-!
# LMFDB level-1 weight-44 form `1.44.a`, piece 1: integer q-coefficient certificate

Heavy `decide +kernel` over `ℤ` (denominators cleared by the scale `D = 9746251776`), isolated in its own
module so `lake` schedules it in parallel with the other pieces. Generated by
`scripts/lmfdb_qexp_to_e4e6_v3.sage`.
-/

namespace LeanBridge.QExpansion.LMFDB.W44

open LeanBridge.QExpansion

def f_44_part_1_polyDataZ : List (ℕ × ℕ × ℤ) :=
  [(2, 6, 2455), (5, 4, (-4101)), (8, 2, 837), (11, 0, 809)]

def f_44_part_1_scale : ℤ := 9746251776

def f_44_part_1_qExpListZ : List ℤ :=
  [0, 0, 9746251776, (-1439578718208), 0, 808624460393349120, 164048181963286118400, 5191685561030335266816, (-18797240469184850165760), (-905528348758369684684800)]

/-- Integer-arithmetic certificate (the heavy kernel computation). -/
lemma f_44_part_1_evalEisListZ_eq :
    evalEisListZ f_44_part_1_polyDataZ 10 = f_44_part_1_qExpListZ := by
  decide +kernel

end LeanBridge.QExpansion.LMFDB.W44
