import LeanBridge.ForMathlib.QExpansion.IntEval

set_option maxHeartbeats 0
set_option maxRecDepth 4000

/-!
# LMFDB level-1 weight-54 form `1.54.a`, piece 1: integer q-coefficient certificate

Heavy `decide +kernel` over `ℤ` (denominators cleared by the scale `D = 6331917335003136`), isolated in its own
module so `lake` schedules it in parallel with the other pieces. Generated by
`scripts/lmfdb_qexp_to_e4e6_v3.sage`.
-/

namespace LeanBridge.QExpansion.LMFDB.W54

open LeanBridge.QExpansion

def f_54_part_1_polyDataZ : List (ℕ × ℕ × ℤ) :=
  [(0, 9, 14757510607), (3, 7, 118833200696), (6, 5, (-442924119426)), (9, 3, 470318594336), (12, 1, (-160985186213))]

def f_54_part_1_scale : ℤ := 6331917335003136

def f_54_part_1_qExpListZ : List ℤ :=
  [0, 0, 6331917335003136, (-912112524620731514880), 0, 115668989104261702562611200, 68950375675927277976661524480, 4851501210566518469390871035904, (-114065682201843629513518375501824), (-2404665107147927358722627642327040)]

/-- Integer-arithmetic certificate (the heavy kernel computation). -/
lemma f_54_part_1_evalEisListZ_eq :
    evalEisListZ f_54_part_1_polyDataZ 10 = f_54_part_1_qExpListZ := by
  decide +kernel

end LeanBridge.QExpansion.LMFDB.W54
