import LeanBridge.ForMathlib.QExpansion.Generic
import LeanBridge.ForMathlib.QExpansion.Sturm
import Mathlib.Analysis.Complex.Polynomial.Basic

/-!
# LMFDB level-1 modular form orbit `1.24.a.{a..}` (Hecke field degree 2)

The Hecke field `K = ℚ(α)` is degree 2 over ℚ. The LMFDB lists q-coefficients as
elements of `K`, which we decompose as `c_0 + c_1 · α + … + c_{1} · α^1`.
The combined form is `f = f_0 + α · f_1 + … + α^1 · f_{1}`, with each
`f_j` a level-1 weight-24 form with rational coefficients in `(E₄, E₆)`.

The Sturm bound for weight 24 is `⌊24/12⌋ + 1 = 3`. After certifying agreement
on the first 3 q-coefficients, `ModularForm.eq_of_sturm_bound` lets us conclude that any
form with the same coefficients equals our explicit `lmfdb_1_24_a_orbit`.

Generated by `scripts/lmfdb_qexp_to_e4e6_v3.sage`.
-/

namespace LeanBridge.QExpansion.LMFDB.W24

open LeanBridge.QExpansion ModularForm EisensteinSeries PowerSeries UpperHalfPlane
open scoped MatrixGroups


/-- Minimal polynomial of α (degree 2) as `Polynomial ℂ`. -/
noncomputable def α_24_minpoly : Polynomial ℂ :=
  Polynomial.X ^ 2 +
    Polynomial.C (-20468736) +
    Polynomial.C (-1080) * Polynomial.X

lemma α_24_minpoly_natDegree : α_24_minpoly.natDegree = 2 := by
  unfold α_24_minpoly
  compute_degree!

lemma α_24_minpoly_degree_ne_zero : α_24_minpoly.degree ≠ 0 := by
  rw [Polynomial.degree_eq_natDegree (fun h => by
    have := α_24_minpoly_natDegree
    rw [h, Polynomial.natDegree_zero] at this
    exact absurd this (by decide))]
  rw [α_24_minpoly_natDegree]
  decide

/-- α is some root of the degree-2 minimal polynomial in ℂ. -/
noncomputable def α_24 : ℂ :=
  (IsAlgClosed.exists_root α_24_minpoly α_24_minpoly_degree_ne_zero).choose

lemma α_24_isRoot : Polynomial.IsRoot α_24_minpoly α_24 :=
  (IsAlgClosed.exists_root α_24_minpoly α_24_minpoly_degree_ne_zero).choose_spec

/-- Explicit polynomial relation: minpoly evaluated at α is zero. -/
lemma α_24_is_root :
    α_24 ^ 2 +
      (-20468736) +
      (-1080) * α_24 = 0 := by
  have h := α_24_isRoot
  unfold Polynomial.IsRoot α_24_minpoly at h
  simp only [Polynomial.eval_add, Polynomial.eval_mul, Polynomial.eval_pow,
    Polynomial.eval_C, Polynomial.eval_X] at h
  linear_combination h


/-! ## Piece 0: coefficient of α^0 -/


def f_24_part_0_polyData : List (ℕ × ℕ × ℚ) :=
  [(0, 4, ((-(29 / 124416)))), (3, 2, ((-(7 / 62208)))), (6, 0, (43 / 124416))]

noncomputable def f_24_part_0 : ModularForm 𝒮ℒ 24 :=
  (((-(29 / 124416))) : ℂ) • mkMonomForm 0 4 24 (by decide) +
  (((-(7 / 62208))) : ℂ) • mkMonomForm 3 2 24 (by decide) +
  ((43 / 124416) : ℂ) • mkMonomForm 6 0 24 (by decide)

lemma f_24_part_0_qExpansion_eq_evalEisPS :
    qExpansion 1 (f_24_part_0 : ℍ → ℂ) = evalEisPS f_24_part_0_polyData := by
  unfold f_24_part_0
  rw [ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm]
  unfold evalEisPS f_24_part_0_polyData monomialEisPS
  simp only [List.foldr_cons, List.foldr_nil, add_zero]
  push_cast
  module

theorem f_24_part_0_qExpansion_coeff (N n : ℕ) (hn : n < N) :
    (PowerSeries.coeff (R := ℂ) n) (qExpansion 1 (f_24_part_0 : ℍ → ℂ))
      = ((evalEisList f_24_part_0_polyData N).getD n 0 : ℚ) :=
  qexp_coeff_via_E4E6 _ _ f_24_part_0_qExpansion_eq_evalEisPS N n hn

/-- Precomputed first 10 q-coefficients of `f_24_part_0` (rational). -/
def f_24_part_0_qExpList : List ℚ :=
  [0, 1, 0, 195660, 12080128, 44656110, (-982499328), (-147247240), 22106234880, (-8700375483)]

/-- One-shot bridge: the symbolic `evalEisList` equals the precomputed list (verified by
`decide +kernel` once instead of N times). -/
lemma f_24_part_0_evalEisList_eq :
    evalEisList f_24_part_0_polyData 10 = f_24_part_0_qExpList := by
  decide +kernel


/-! ## Piece 1: coefficient of α^1 -/


def f_24_part_1_polyData : List (ℕ × ℕ × ℚ) :=
  [(0, 4, (1 / 2985984)), (3, 2, ((-(1 / 1492992)))), (6, 0, (1 / 2985984))]

noncomputable def f_24_part_1 : ModularForm 𝒮ℒ 24 :=
  ((1 / 2985984) : ℂ) • mkMonomForm 0 4 24 (by decide) +
  (((-(1 / 1492992))) : ℂ) • mkMonomForm 3 2 24 (by decide) +
  ((1 / 2985984) : ℂ) • mkMonomForm 6 0 24 (by decide)

lemma f_24_part_1_qExpansion_eq_evalEisPS :
    qExpansion 1 (f_24_part_1 : ℍ → ℂ) = evalEisPS f_24_part_1_polyData := by
  unfold f_24_part_1
  rw [ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm]
  unfold evalEisPS f_24_part_1_polyData monomialEisPS
  simp only [List.foldr_cons, List.foldr_nil, add_zero]
  push_cast
  module

theorem f_24_part_1_qExpansion_coeff (N n : ℕ) (hn : n < N) :
    (PowerSeries.coeff (R := ℂ) n) (qExpansion 1 (f_24_part_1 : ℍ → ℂ))
      = ((evalEisList f_24_part_1_polyData N).getD n 0 : ℚ) :=
  qexp_coeff_via_E4E6 _ _ f_24_part_1_qExpansion_eq_evalEisPS N n hn

/-- Precomputed first 10 q-coefficients of `f_24_part_1` (rational). -/
def f_24_part_1_qExpList : List ℚ :=
  [0, 0, 1, (-48), 1080, (-15040), 143820, (-985824), 4857920, (-16295040)]

/-- One-shot bridge: the symbolic `evalEisList` equals the precomputed list (verified by
`decide +kernel` once instead of N times). -/
lemma f_24_part_1_evalEisList_eq :
    evalEisList f_24_part_1_polyData 10 = f_24_part_1_qExpList := by
  decide +kernel


/-! ## Combined LMFDB form -/


noncomputable def lmfdb_1_24_a_orbit : ModularForm 𝒮ℒ 24 :=
  f_24_part_0 +
  α_24 • f_24_part_1

lemma lmfdb_1_24_a_orbit_coeff_decomp (n : ℕ) :
    (PowerSeries.coeff (R := ℂ) n) (qExpansion 1 (lmfdb_1_24_a_orbit : ℍ → ℂ))
      = (PowerSeries.coeff (R := ℂ) n) (qExpansion 1 (f_24_part_0 : ℍ → ℂ))
        + α_24 * (PowerSeries.coeff (R := ℂ) n) (qExpansion 1 (f_24_part_1 : ℍ → ℂ)) := by
  unfold lmfdb_1_24_a_orbit
  rw [ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL]
  simp [smul_eq_mul]


/-! ## Coefficient lemmas (n = 0, …, 9)

Sturm bound is 3; we certify 10 coefficients for added
redundancy beyond the minimum mathematically required for uniqueness. -/


lemma lmfdb_1_24_a_orbit_qExpansion_coeff_0 :
    (PowerSeries.coeff (R := ℂ) 0)
      (qExpansion 1 (lmfdb_1_24_a_orbit : ℍ → ℂ)) = 0 := by
  rw [lmfdb_1_24_a_orbit_coeff_decomp,
    f_24_part_0_qExpansion_coeff 10 0 (by decide),
    f_24_part_1_qExpansion_coeff 10 0 (by decide),
    f_24_part_0_evalEisList_eq,
    f_24_part_1_evalEisList_eq,
    show f_24_part_0_qExpList.getD 0 0 = (0 : ℚ) from by decide +kernel,
    show f_24_part_1_qExpList.getD 0 0 = (0 : ℚ) from by decide +kernel]
  push_cast; ring

lemma lmfdb_1_24_a_orbit_qExpansion_coeff_1 :
    (PowerSeries.coeff (R := ℂ) 1)
      (qExpansion 1 (lmfdb_1_24_a_orbit : ℍ → ℂ)) = 1 := by
  rw [lmfdb_1_24_a_orbit_coeff_decomp,
    f_24_part_0_qExpansion_coeff 10 1 (by decide),
    f_24_part_1_qExpansion_coeff 10 1 (by decide),
    f_24_part_0_evalEisList_eq,
    f_24_part_1_evalEisList_eq,
    show f_24_part_0_qExpList.getD 1 0 = (1 : ℚ) from by decide +kernel,
    show f_24_part_1_qExpList.getD 1 0 = (0 : ℚ) from by decide +kernel]
  push_cast; ring

lemma lmfdb_1_24_a_orbit_qExpansion_coeff_2 :
    (PowerSeries.coeff (R := ℂ) 2)
      (qExpansion 1 (lmfdb_1_24_a_orbit : ℍ → ℂ)) = 1 * α_24 := by
  rw [lmfdb_1_24_a_orbit_coeff_decomp,
    f_24_part_0_qExpansion_coeff 10 2 (by decide),
    f_24_part_1_qExpansion_coeff 10 2 (by decide),
    f_24_part_0_evalEisList_eq,
    f_24_part_1_evalEisList_eq,
    show f_24_part_0_qExpList.getD 2 0 = (0 : ℚ) from by decide +kernel,
    show f_24_part_1_qExpList.getD 2 0 = (1 : ℚ) from by decide +kernel]
  push_cast; ring

lemma lmfdb_1_24_a_orbit_qExpansion_coeff_3 :
    (PowerSeries.coeff (R := ℂ) 3)
      (qExpansion 1 (lmfdb_1_24_a_orbit : ℍ → ℂ)) = 195660 + (-48) * α_24 := by
  rw [lmfdb_1_24_a_orbit_coeff_decomp,
    f_24_part_0_qExpansion_coeff 10 3 (by decide),
    f_24_part_1_qExpansion_coeff 10 3 (by decide),
    f_24_part_0_evalEisList_eq,
    f_24_part_1_evalEisList_eq,
    show f_24_part_0_qExpList.getD 3 0 = (195660 : ℚ) from by decide +kernel,
    show f_24_part_1_qExpList.getD 3 0 = ((-48) : ℚ) from by decide +kernel]
  push_cast; ring

lemma lmfdb_1_24_a_orbit_qExpansion_coeff_4 :
    (PowerSeries.coeff (R := ℂ) 4)
      (qExpansion 1 (lmfdb_1_24_a_orbit : ℍ → ℂ)) = 12080128 + 1080 * α_24 := by
  rw [lmfdb_1_24_a_orbit_coeff_decomp,
    f_24_part_0_qExpansion_coeff 10 4 (by decide),
    f_24_part_1_qExpansion_coeff 10 4 (by decide),
    f_24_part_0_evalEisList_eq,
    f_24_part_1_evalEisList_eq,
    show f_24_part_0_qExpList.getD 4 0 = (12080128 : ℚ) from by decide +kernel,
    show f_24_part_1_qExpList.getD 4 0 = (1080 : ℚ) from by decide +kernel]
  push_cast; ring

lemma lmfdb_1_24_a_orbit_qExpansion_coeff_5 :
    (PowerSeries.coeff (R := ℂ) 5)
      (qExpansion 1 (lmfdb_1_24_a_orbit : ℍ → ℂ)) = 44656110 + (-15040) * α_24 := by
  rw [lmfdb_1_24_a_orbit_coeff_decomp,
    f_24_part_0_qExpansion_coeff 10 5 (by decide),
    f_24_part_1_qExpansion_coeff 10 5 (by decide),
    f_24_part_0_evalEisList_eq,
    f_24_part_1_evalEisList_eq,
    show f_24_part_0_qExpList.getD 5 0 = (44656110 : ℚ) from by decide +kernel,
    show f_24_part_1_qExpList.getD 5 0 = ((-15040) : ℚ) from by decide +kernel]
  push_cast; ring

lemma lmfdb_1_24_a_orbit_qExpansion_coeff_6 :
    (PowerSeries.coeff (R := ℂ) 6)
      (qExpansion 1 (lmfdb_1_24_a_orbit : ℍ → ℂ)) = (-982499328) + 143820 * α_24 := by
  rw [lmfdb_1_24_a_orbit_coeff_decomp,
    f_24_part_0_qExpansion_coeff 10 6 (by decide),
    f_24_part_1_qExpansion_coeff 10 6 (by decide),
    f_24_part_0_evalEisList_eq,
    f_24_part_1_evalEisList_eq,
    show f_24_part_0_qExpList.getD 6 0 = ((-982499328) : ℚ) from by decide +kernel,
    show f_24_part_1_qExpList.getD 6 0 = (143820 : ℚ) from by decide +kernel]
  push_cast; ring

lemma lmfdb_1_24_a_orbit_qExpansion_coeff_7 :
    (PowerSeries.coeff (R := ℂ) 7)
      (qExpansion 1 (lmfdb_1_24_a_orbit : ℍ → ℂ)) = (-147247240) + (-985824) * α_24 := by
  rw [lmfdb_1_24_a_orbit_coeff_decomp,
    f_24_part_0_qExpansion_coeff 10 7 (by decide),
    f_24_part_1_qExpansion_coeff 10 7 (by decide),
    f_24_part_0_evalEisList_eq,
    f_24_part_1_evalEisList_eq,
    show f_24_part_0_qExpList.getD 7 0 = ((-147247240) : ℚ) from by decide +kernel,
    show f_24_part_1_qExpList.getD 7 0 = ((-985824) : ℚ) from by decide +kernel]
  push_cast; ring

lemma lmfdb_1_24_a_orbit_qExpansion_coeff_8 :
    (PowerSeries.coeff (R := ℂ) 8)
      (qExpansion 1 (lmfdb_1_24_a_orbit : ℍ → ℂ)) = 22106234880 + 4857920 * α_24 := by
  rw [lmfdb_1_24_a_orbit_coeff_decomp,
    f_24_part_0_qExpansion_coeff 10 8 (by decide),
    f_24_part_1_qExpansion_coeff 10 8 (by decide),
    f_24_part_0_evalEisList_eq,
    f_24_part_1_evalEisList_eq,
    show f_24_part_0_qExpList.getD 8 0 = (22106234880 : ℚ) from by decide +kernel,
    show f_24_part_1_qExpList.getD 8 0 = (4857920 : ℚ) from by decide +kernel]
  push_cast; ring

lemma lmfdb_1_24_a_orbit_qExpansion_coeff_9 :
    (PowerSeries.coeff (R := ℂ) 9)
      (qExpansion 1 (lmfdb_1_24_a_orbit : ℍ → ℂ)) = (-8700375483) + (-16295040) * α_24 := by
  rw [lmfdb_1_24_a_orbit_coeff_decomp,
    f_24_part_0_qExpansion_coeff 10 9 (by decide),
    f_24_part_1_qExpansion_coeff 10 9 (by decide),
    f_24_part_0_evalEisList_eq,
    f_24_part_1_evalEisList_eq,
    show f_24_part_0_qExpList.getD 9 0 = ((-8700375483) : ℚ) from by decide +kernel,
    show f_24_part_1_qExpList.getD 9 0 = ((-16295040) : ℚ) from by decide +kernel]
  push_cast; ring


/-! ## Uniqueness theorem -/


/-- **Uniqueness theorem.** Any level-1 weight-24 modular form `f` whose first 3
q-coefficients match the LMFDB-published values for `1.24.a.{a..}` is equal to our
explicit construction `lmfdb_1_24_a_orbit`. Proven via `ModularForm.eq_of_sturm_bound`. -/
theorem identifies_lmfdb_1_24_a_orbit (f : ModularForm 𝒮ℒ 24)
    (h_0 : (PowerSeries.coeff (R := ℂ) 0) (qExpansion 1 (f : ℍ → ℂ)) = 0)
    (h_1 : (PowerSeries.coeff (R := ℂ) 1) (qExpansion 1 (f : ℍ → ℂ)) = 1)
    (h_2 : (PowerSeries.coeff (R := ℂ) 2) (qExpansion 1 (f : ℍ → ℂ)) = 1 * α_24) :
    f = lmfdb_1_24_a_orbit := by
  apply ModularForm.eq_of_sturm_bound
  intro i hi
  have : i ≤ 2 := by omega
  interval_cases i
  · rw [h_0, lmfdb_1_24_a_orbit_qExpansion_coeff_0]
  · rw [h_1, lmfdb_1_24_a_orbit_qExpansion_coeff_1]
  · rw [h_2, lmfdb_1_24_a_orbit_qExpansion_coeff_2]


end LeanBridge.QExpansion.LMFDB.W24