import LeanBridge.ForMathlib.QExpansion.IntEval

set_option maxHeartbeats 0
set_option maxRecDepth 4000

/-!
# LMFDB level-1 weight-72 form `1.72.a`, piece 4: integer q-coefficient certificate

Heavy `decide +kernel` over `ℤ` (denominators cleared by the scale `D = 233952082567397500176943524815323919864776858961082895564800`), isolated in its own
module so `lake` schedules it in parallel with the other pieces. Generated by
`scripts/lmfdb_qexp_to_e4e6_v3.sage`.
-/

namespace LeanBridge.QExpansion.LMFDB.W72

open LeanBridge.QExpansion

def f_72_part_4_polyDataZ : List (ℕ × ℕ × ℤ) :=
  [(0, 12, (-118092828877572761944275)), (3, 10, 22410864148528097592930932), (6, 8, (-111753228014427201757271035)), (9, 6, 224049327394158344086152320), (12, 4, (-223965863148029206214975945)), (15, 2, 111450892401917135807590060), (18, 0, (-22073899953269596752482057))]

def f_72_part_4_scale : ℤ := 233952082567397500176943524815323919864776858961082895564800

def f_72_part_4_qExpListZ : List ℤ :=
  [0, 0, 0, 6278419472403295464617401122816000, 0, (-339806708747092213880570675404770719563776), (-206894910328487270752545886366843698098995200), (-33445022516660477378971112324519013377900544000), 0, 244167512644331856648624366756754813036658058854400]

/-- Integer-arithmetic certificate (the heavy kernel computation). -/
lemma f_72_part_4_evalEisListZ_eq :
    evalEisListZ f_72_part_4_polyDataZ 10 = f_72_part_4_qExpListZ := by
  decide +kernel

end LeanBridge.QExpansion.LMFDB.W72
