import LeanBridge.ForMathlib.QExpansion.IntEval

set_option maxHeartbeats 0
set_option maxRecDepth 4000

/-!
# LMFDB level-1 weight-26 form `1.26.a`, piece 0: integer q-coefficient certificate

Heavy `decide +kernel` over `ℤ` (denominators cleared by the scale `D = 1728`), isolated in its own
module so `lake` schedules it in parallel with the other pieces. Generated by
`scripts/lmfdb_qexp_to_e4e6_v3.sage`.
-/

namespace LeanBridge.QExpansion.LMFDB.W26

open LeanBridge.QExpansion

def f_26_part_0_polyDataZ : List (ℕ × ℕ × ℤ) :=
  [(2, 3, (-1)), (5, 1, 1)]

def f_26_part_0_scale : ℤ := 1728

def f_26_part_0_qExpListZ : List ℤ :=
  [0, 1728, (-82944), (-338349312), (-57978077184), (-1282158460800), 16240766976, 67531271947776, 5566086512640, (-1397864568430656)]

/-- Integer-arithmetic certificate (the heavy kernel computation). -/
lemma f_26_part_0_evalEisListZ_eq :
    evalEisListZ f_26_part_0_polyDataZ 10 = f_26_part_0_qExpListZ := by
  decide +kernel

end LeanBridge.QExpansion.LMFDB.W26
