import LeanBridge.ForMathlib.QExpansion.IntEval

set_option maxHeartbeats 0
set_option maxRecDepth 4000

/-!
# LMFDB level-1 weight-64 form `1.64.a`, piece 4: integer q-coefficient certificate

Heavy `decide +kernel` over `ℤ` (denominators cleared by the scale `D = 134966669278476989521649366837420359680`), isolated in its own
module so `lake` schedules it in parallel with the other pieces. Generated by
`scripts/lmfdb_qexp_to_e4e6_v3.sage`.
-/

namespace LeanBridge.QExpansion.LMFDB.W64

open LeanBridge.QExpansion

def f_64_part_4_polyDataZ : List (ℕ × ℕ × ℤ) :=
  [(1, 10, (-13886398)), (4, 8, 73093205), (7, 6, (-149574400)), (10, 4, 149027950), (13, 2, (-72273530)), (16, 0, 13613173)]

def f_64_part_4_scale : ℤ := 134966669278476989521649366837420359680

def f_64_part_4_qExpListZ : List ℤ :=
  [0, 0, 0, (-20300846208122880), 0, 219694553513733918818304, 25815954404492244921876480, (-5109985333142224243009781760), 0, (-31316921015501240464235361730560)]

/-- Integer-arithmetic certificate (the heavy kernel computation). -/
lemma f_64_part_4_evalEisListZ_eq :
    evalEisListZ f_64_part_4_polyDataZ 10 = f_64_part_4_qExpListZ := by
  decide +kernel

end LeanBridge.QExpansion.LMFDB.W64
