import LeanBridge.ForMathlib.QExpansion.IntEval
import LeanBridge.ForMathlib.QExpansion.Sturm
import Mathlib.Analysis.Complex.Polynomial.Basic
import LeanBridge.ForMathlib.QExpansion.LMFDB.Weight_86_part_0
import LeanBridge.ForMathlib.QExpansion.LMFDB.Weight_86_part_1
import LeanBridge.ForMathlib.QExpansion.LMFDB.Weight_86_part_2
import LeanBridge.ForMathlib.QExpansion.LMFDB.Weight_86_part_3
import LeanBridge.ForMathlib.QExpansion.LMFDB.Weight_86_part_4
import LeanBridge.ForMathlib.QExpansion.LMFDB.Weight_86_part_5

set_option maxHeartbeats 0
set_option maxRecDepth 2000

/-!
# LMFDB level-1 modular form orbit `1.86.a.{a..}` (Hecke field degree 6)

The Hecke field `K = ℚ(α)` is degree 6 over ℚ. The LMFDB lists q-coefficients as
elements of `K`, which we decompose as `c_0 + c_1 · α + … + c_{5} · α^5`.
The combined form is `f = f_0 + α · f_1 + … + α^5 · f_{5}`, with each
`f_j` a level-1 weight-86 form with rational coefficients in `(E₄, E₆)`.

The Sturm bound for weight 86 is `⌊86/12⌋ + 1 = 8`. After certifying agreement
on the first 8 q-coefficients, `ModularForm.eq_of_sturm_bound` lets us conclude that any
form with the same coefficients equals our explicit `lmfdb_1_86_a_orbit`.

Generated by `scripts/lmfdb_qexp_to_e4e6_v3.sage`.
-/

namespace LeanBridge.QExpansion.LMFDB.W86

open LeanBridge.QExpansion ModularForm EisensteinSeries PowerSeries UpperHalfPlane
open scoped MatrixGroups


/-- Minimal polynomial of α (degree 6) as `Polynomial ℂ`. -/
noncomputable def α_86_minpoly : Polynomial ℂ :=
  Polynomial.X ^ 6 +
    Polynomial.C (-651453564182627074233502499539063680566772829640480606321381488113393598464) +
    Polynomial.C 25777042732431769711558332265361302177218232143229983587617996800 * Polynomial.X +
    Polynomial.C 6762034528787600549896548602635210390056501245902848 * Polynomial.X ^ 2 +
    Polynomial.C (-718682363872979487719506400535537254400) * Polynomial.X ^ 3 +
    Polynomial.C (-180083699101345331242893312) * Polynomial.X ^ 4 +
    Polynomial.C 3596910688800 * Polynomial.X ^ 5

lemma α_86_minpoly_natDegree : α_86_minpoly.natDegree = 6 := by
  unfold α_86_minpoly
  compute_degree!

lemma α_86_minpoly_degree_ne_zero : α_86_minpoly.degree ≠ 0 := by
  rw [Polynomial.degree_eq_natDegree (fun h => by
    have := α_86_minpoly_natDegree
    rw [h, Polynomial.natDegree_zero] at this
    exact absurd this (by decide))]
  rw [α_86_minpoly_natDegree]
  decide

/-- α is some root of the degree-6 minimal polynomial in ℂ. -/
noncomputable def α_86 : ℂ :=
  (IsAlgClosed.exists_root α_86_minpoly α_86_minpoly_degree_ne_zero).choose

lemma α_86_isRoot : Polynomial.IsRoot α_86_minpoly α_86 :=
  (IsAlgClosed.exists_root α_86_minpoly α_86_minpoly_degree_ne_zero).choose_spec

/-- Explicit polynomial relation: minpoly evaluated at α is zero. -/
lemma α_86_is_root :
    α_86 ^ 6 +
      (-651453564182627074233502499539063680566772829640480606321381488113393598464) +
      25777042732431769711558332265361302177218232143229983587617996800 * α_86 +
      6762034528787600549896548602635210390056501245902848 * α_86 ^ 2 +
      (-718682363872979487719506400535537254400) * α_86 ^ 3 +
      (-180083699101345331242893312) * α_86 ^ 4 +
      3596910688800 * α_86 ^ 5 = 0 := by
  have h := α_86_isRoot
  unfold Polynomial.IsRoot α_86_minpoly at h
  simp only [Polynomial.eval_add, Polynomial.eval_mul, Polynomial.eval_pow,
    Polynomial.eval_C, Polynomial.eval_X] at h
  linear_combination h


/-! ## Piece 0: coefficient of α^0 -/


def f_86_part_0_polyData : List (ℕ × ℕ × ℚ) :=
  [(2, 13, ((-(80774211887917947961119552222898578033152625009041219562809826107 / 44992631072776744083279445760531147085509517563756544)))), (5, 11, (525327296759270488887753873406861066523801858981557900879777147 / 117168310085356104383540223334716528868514368655616)), (8, 9, (1073770138212001481002940202029951347727277783456393917658558781 / 4999181230308527120364382862281238565056613062639616)), (11, 7, ((-(7836453762511818036925863485240749259560890655864720768909245841 / 803439840585299001487132960009484769384098527924224)))), (14, 5, (150965667800569279598625958319559476201128941580323445973723851669 / 14997543690925581361093148586843715695169839187918848)), (17, 3, ((-(100468676010154747116064084962973828181219519228103491854147349 / 29757031132788851906930850370721658125336982515712)))), (20, 1, (1033949159251145115807854242173474928642025167051706455323625201 / 6427518724682392011897063680075878155072788223393792))]

noncomputable def f_86_part_0 : ModularForm 𝒮ℒ 86 :=
  (((-(80774211887917947961119552222898578033152625009041219562809826107 / 44992631072776744083279445760531147085509517563756544))) : ℂ) • mkMonomForm 2 13 86 (by decide) +
  ((525327296759270488887753873406861066523801858981557900879777147 / 117168310085356104383540223334716528868514368655616) : ℂ) • mkMonomForm 5 11 86 (by decide) +
  ((1073770138212001481002940202029951347727277783456393917658558781 / 4999181230308527120364382862281238565056613062639616) : ℂ) • mkMonomForm 8 9 86 (by decide) +
  (((-(7836453762511818036925863485240749259560890655864720768909245841 / 803439840585299001487132960009484769384098527924224))) : ℂ) • mkMonomForm 11 7 86 (by decide) +
  ((150965667800569279598625958319559476201128941580323445973723851669 / 14997543690925581361093148586843715695169839187918848) : ℂ) • mkMonomForm 14 5 86 (by decide) +
  (((-(100468676010154747116064084962973828181219519228103491854147349 / 29757031132788851906930850370721658125336982515712))) : ℂ) • mkMonomForm 17 3 86 (by decide) +
  ((1033949159251145115807854242173474928642025167051706455323625201 / 6427518724682392011897063680075878155072788223393792) : ℂ) • mkMonomForm 20 1 86 (by decide)

lemma f_86_part_0_qExpansion_eq_evalEisPS :
    qExpansion 1 (f_86_part_0 : ℍ → ℂ) = evalEisPS f_86_part_0_polyData := by
  unfold f_86_part_0
  rw [ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm]
  unfold evalEisPS f_86_part_0_polyData monomialEisPS
  simp only [List.foldr_cons, List.foldr_nil, add_zero]
  push_cast
  module

theorem f_86_part_0_qExpansion_coeff (N n : ℕ) (hn : n < N) :
    (PowerSeries.coeff (R := ℂ) n) (qExpansion 1 (f_86_part_0 : ℍ → ℂ))
      = ((evalEisList f_86_part_0_polyData N).getD n 0 : ℚ) :=
  qexp_coeff_via_E4E6 _ _ f_86_part_0_qExpansion_eq_evalEisPS N n hn

/-- Precomputed first 10 q-coefficients of `f_86_part_0` (rational). -/
def f_86_part_0_qExpList : List ℚ :=
  [0, 1, 0, ((-(52243492089218058299911772771623830827582222696196728269381700 / 287074019048161685397628960631714176420107))), (-38685626227668133590597632), (4402186474259201322184129483763474807216407419038327384433717709593222 / 95691339682720561799209653543904725473369), ((-(1128848500838925031669697647619166801181993859977042841113513792670531584 / 95691339682720561799209653543904725473369))), (2642800538867883270136724690590682243710211496019955050629239271071914600 / 1952884483320827791820605174365402560681), 0, ((-(2114222518674518467140803002491723427521257421395954220337037217942939840139803 / 1952884483320827791820605174365402560681)))]

/-- Bridge: the symbolic `evalEisList` (over ℚ) equals the precomputed list. The heavy kernel work
is the integer certificate `f_86_part_0_evalEisListZ_eq`; the steps here are cheap rational
list checks. -/
lemma f_86_part_0_evalEisList_eq :
    evalEisList f_86_part_0_polyData 10 = f_86_part_0_qExpList := by
  have h : f_86_part_0_polyData
      = f_86_part_0_polyDataZ.map
          (fun t => (t.1, t.2.1, (t.2.2 : ℚ) / f_86_part_0_scale)) := by
    decide +kernel
  rw [h, evalEisList_eq_intCast_div, f_86_part_0_evalEisListZ_eq]
  decide +kernel


/-! ## Piece 1: coefficient of α^1 -/


def f_86_part_1_polyData : List (ℕ × ℕ × ℚ) :=
  [(2, 13, (110255730642826835515742020528822467050011697471692208003771 / 283069158718607683223212968706768248518011367333601491288064)), (5, 11, ((-(522934850301880608564893072004123017269825005920187879776101 / 15726064373255982401289609372598236028778409296311193960448)))), (8, 9, (15139562250057163456293459700811275295835471329487735398097479 / 94356386239535894407737656235589416172670455777867163762688)), (11, 7, ((-(3205163124215246199986442353708818503596386227700637039042053 / 10109612811378845829400463168098866018500405976200053260288)))), (14, 5, (9910668791394126012222635970657404784545900555140201813225549 / 31452128746511964802579218745196472057556818592622387920896)), (17, 3, ((-(1057868587342553693783854328876897586137410535036575957235017 / 6739741874252563886266975445399244012333603984133368840192)))), (20, 1, (1266130549783792625472928307695934230551053753074384915955981 / 40438451245515383317601852672395464074001623904800213041152))]

noncomputable def f_86_part_1 : ModularForm 𝒮ℒ 86 :=
  ((110255730642826835515742020528822467050011697471692208003771 / 283069158718607683223212968706768248518011367333601491288064) : ℂ) • mkMonomForm 2 13 86 (by decide) +
  (((-(522934850301880608564893072004123017269825005920187879776101 / 15726064373255982401289609372598236028778409296311193960448))) : ℂ) • mkMonomForm 5 11 86 (by decide) +
  ((15139562250057163456293459700811275295835471329487735398097479 / 94356386239535894407737656235589416172670455777867163762688) : ℂ) • mkMonomForm 8 9 86 (by decide) +
  (((-(3205163124215246199986442353708818503596386227700637039042053 / 10109612811378845829400463168098866018500405976200053260288))) : ℂ) • mkMonomForm 11 7 86 (by decide) +
  ((9910668791394126012222635970657404784545900555140201813225549 / 31452128746511964802579218745196472057556818592622387920896) : ℂ) • mkMonomForm 14 5 86 (by decide) +
  (((-(1057868587342553693783854328876897586137410535036575957235017 / 6739741874252563886266975445399244012333603984133368840192))) : ℂ) • mkMonomForm 17 3 86 (by decide) +
  ((1266130549783792625472928307695934230551053753074384915955981 / 40438451245515383317601852672395464074001623904800213041152) : ℂ) • mkMonomForm 20 1 86 (by decide)

lemma f_86_part_1_qExpansion_eq_evalEisPS :
    qExpansion 1 (f_86_part_1 : ℍ → ℂ) = evalEisPS f_86_part_1_polyData := by
  unfold f_86_part_1
  rw [ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm]
  unfold evalEisPS f_86_part_1_polyData monomialEisPS
  simp only [List.foldr_cons, List.foldr_nil, add_zero]
  push_cast
  module

theorem f_86_part_1_qExpansion_coeff (N n : ℕ) (hn : n < N) :
    (PowerSeries.coeff (R := ℂ) n) (qExpansion 1 (f_86_part_1 : ℍ → ℂ))
      = ((evalEisList f_86_part_1_polyData N).getD n 0 : ℚ) :=
  qexp_coeff_via_E4E6 _ _ f_86_part_1_qExpansion_eq_evalEisPS N n hn

/-- Precomputed first 10 q-coefficients of `f_86_part_1` (rational). -/
def f_86_part_1_qExpList : List ℚ :=
  [0, 0, 1, ((-(902897007233951502040088502829856298063482833425239873 / 7055131092127621580332129336485007599700549632))), 0, (93372988102927335694231622865378452477633946598112811124470053 / 195975863670211710564781370457916877769459712), (81757045989390729126527448727328007542610533464540575085440700 / 287074019048161685397628960631714176420107), ((-(437459623189633552114263376468701812075405427868989841854326668233 / 7999014843682110635297198794200688888549376))), (-77371252455336267181195264), ((-(42887426087551617366731918233822781770306162964610590821429520875060725 / 1999753710920527658824299698550172222137344)))]

/-- Bridge: the symbolic `evalEisList` (over ℚ) equals the precomputed list. The heavy kernel work
is the integer certificate `f_86_part_1_evalEisListZ_eq`; the steps here are cheap rational
list checks. -/
lemma f_86_part_1_evalEisList_eq :
    evalEisList f_86_part_1_polyData 10 = f_86_part_1_qExpList := by
  have h : f_86_part_1_polyData
      = f_86_part_1_polyDataZ.map
          (fun t => (t.1, t.2.1, (t.2.2 : ℚ) / f_86_part_1_scale)) := by
    decide +kernel
  rw [h, evalEisList_eq_intCast_div, f_86_part_1_evalEisListZ_eq]
  decide +kernel


/-! ## Piece 2: coefficient of α^2 -/


def f_86_part_2_polyData : List (ℕ × ℕ × ℚ) :=
  [(2, 13, ((-(33869004446262109379990089427811909551221404858571507 / 55653661157348019383149455351500291804629178908724721999163686912)))), (5, 11, (23243617262816654655685597353101094869913718487833703 / 9275610192891336563858242558583381967438196484787453666527281152)), (8, 9, ((-(20353663070155929793818171547388050258911027617715637 / 6183740128594224375905495039055587978292130989858302444351520768)))), (11, 7, (548861878588425783279063452780684285559084443375789 / 1987630755619572120826766262553581850165327818168740071398703104)), (14, 5, (55470479637308268143151811252163395022576787240542849 / 18551220385782673127716485117166763934876392969574907333054562304)), (17, 3, ((-(371137291816378003882342343562829178814047481303287 / 147231907823672008950130834263228285197431690234721486770274304)))), (20, 1, (5157227613565101242356606381156839598609080612500267 / 7950523022478288483307065050214327400661311272674960285594812416))]

noncomputable def f_86_part_2 : ModularForm 𝒮ℒ 86 :=
  (((-(33869004446262109379990089427811909551221404858571507 / 55653661157348019383149455351500291804629178908724721999163686912))) : ℂ) • mkMonomForm 2 13 86 (by decide) +
  ((23243617262816654655685597353101094869913718487833703 / 9275610192891336563858242558583381967438196484787453666527281152) : ℂ) • mkMonomForm 5 11 86 (by decide) +
  (((-(20353663070155929793818171547388050258911027617715637 / 6183740128594224375905495039055587978292130989858302444351520768))) : ℂ) • mkMonomForm 8 9 86 (by decide) +
  ((548861878588425783279063452780684285559084443375789 / 1987630755619572120826766262553581850165327818168740071398703104) : ℂ) • mkMonomForm 11 7 86 (by decide) +
  ((55470479637308268143151811252163395022576787240542849 / 18551220385782673127716485117166763934876392969574907333054562304) : ℂ) • mkMonomForm 14 5 86 (by decide) +
  (((-(371137291816378003882342343562829178814047481303287 / 147231907823672008950130834263228285197431690234721486770274304))) : ℂ) • mkMonomForm 17 3 86 (by decide) +
  ((5157227613565101242356606381156839598609080612500267 / 7950523022478288483307065050214327400661311272674960285594812416) : ℂ) • mkMonomForm 20 1 86 (by decide)

lemma f_86_part_2_qExpansion_eq_evalEisPS :
    qExpansion 1 (f_86_part_2 : ℍ → ℂ) = evalEisPS f_86_part_2_polyData := by
  unfold f_86_part_2
  rw [ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm]
  unfold evalEisPS f_86_part_2_polyData monomialEisPS
  simp only [List.foldr_cons, List.foldr_nil, add_zero]
  push_cast
  module

theorem f_86_part_2_qExpansion_coeff (N n : ℕ) (hn : n < N) :
    (PowerSeries.coeff (R := ℂ) n) (qExpansion 1 (f_86_part_2 : ℍ → ℂ))
      = ((evalEisList f_86_part_2_polyData N).getD n 0 : ℚ) :=
  qexp_coeff_via_E4E6 _ _ f_86_part_2_qExpansion_eq_evalEisPS N n hn

/-- Precomputed first 10 q-coefficients of `f_86_part_2` (rational). -/
def f_86_part_2_qExpList : List ℚ :=
  [0, 0, 0, (16305437420326505183429320766865760641411744425 / 1387095213761027423665939284587644374161925662048256), 1, (243472622774502729494086422329890743425351987527756017 / 12843474201490994663573511894330040501499311685632), ((-(609373020472064554149992742444842443571765331787631 / 110236423314494087192689520882578243745321088))), (343655938183232008241677693836479936399239110879772766075 / 524223436795550802594837220176736346999971905536), 0, ((-(90211841902874627136792938281808243782399868699734668383680641 / 131055859198887700648709305044184086749992976384)))]

/-- Bridge: the symbolic `evalEisList` (over ℚ) equals the precomputed list. The heavy kernel work
is the integer certificate `f_86_part_2_evalEisListZ_eq`; the steps here are cheap rational
list checks. -/
lemma f_86_part_2_evalEisList_eq :
    evalEisList f_86_part_2_polyData 10 = f_86_part_2_qExpList := by
  have h : f_86_part_2_polyData
      = f_86_part_2_polyDataZ.map
          (fun t => (t.1, t.2.1, (t.2.2 : ℚ) / f_86_part_2_scale)) := by
    decide +kernel
  rw [h, evalEisList_eq_intCast_div, f_86_part_2_evalEisListZ_eq]
  decide +kernel


/-! ## Piece 3: coefficient of α^3 -/


def f_86_part_3_polyData : List (ℕ × ℕ × ℚ) :=
  [(2, 13, (45631186573954076584456912267823523938285627 / 170968047075373115545035126839808896423820837607602345981430846193664)), (5, 11, ((-(6259420293090336489641837952722597068241797 / 9498224837520728641390840379989383134656713200422352554523935899648)))), (8, 9, ((-(40417338578498650959133215199223945286796153 / 56989349025124371848345042279936298807940279202534115327143615397888)))), (11, 7, (24963194148894235288777749719959741548047771 / 6106001681263325555179825958564603443707887057414369499336815935488)), (14, 5, ((-(103018706660798958624917328379763629073826995 / 18996449675041457282781680759978766269313426400844705109047871799296)))), (17, 3, (12666599553896550644328653783045404029677975 / 4070667787508883703453217305709735629138591371609579666224543956992)), (20, 1, ((-(16501123292619307773832668450007430253844915 / 24424006725053302220719303834258413774831548229657477997347263741952))))]

noncomputable def f_86_part_3 : ModularForm 𝒮ℒ 86 :=
  ((45631186573954076584456912267823523938285627 / 170968047075373115545035126839808896423820837607602345981430846193664) : ℂ) • mkMonomForm 2 13 86 (by decide) +
  (((-(6259420293090336489641837952722597068241797 / 9498224837520728641390840379989383134656713200422352554523935899648))) : ℂ) • mkMonomForm 5 11 86 (by decide) +
  (((-(40417338578498650959133215199223945286796153 / 56989349025124371848345042279936298807940279202534115327143615397888))) : ℂ) • mkMonomForm 8 9 86 (by decide) +
  ((24963194148894235288777749719959741548047771 / 6106001681263325555179825958564603443707887057414369499336815935488) : ℂ) • mkMonomForm 11 7 86 (by decide) +
  (((-(103018706660798958624917328379763629073826995 / 18996449675041457282781680759978766269313426400844705109047871799296))) : ℂ) • mkMonomForm 14 5 86 (by decide) +
  ((12666599553896550644328653783045404029677975 / 4070667787508883703453217305709735629138591371609579666224543956992) : ℂ) • mkMonomForm 17 3 86 (by decide) +
  (((-(16501123292619307773832668450007430253844915 / 24424006725053302220719303834258413774831548229657477997347263741952))) : ℂ) • mkMonomForm 20 1 86 (by decide)

lemma f_86_part_3_qExpansion_eq_evalEisPS :
    qExpansion 1 (f_86_part_3 : ℍ → ℂ) = evalEisPS f_86_part_3_polyData := by
  unfold f_86_part_3
  rw [ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm]
  unfold evalEisPS f_86_part_3_polyData monomialEisPS
  simp only [List.foldr_cons, List.foldr_nil, add_zero]
  push_cast
  module

theorem f_86_part_3_qExpansion_coeff (N n : ℕ) (hn : n < N) :
    (PowerSeries.coeff (R := ℂ) n) (qExpansion 1 (f_86_part_3 : ℍ → ℂ))
      = ((evalEisList f_86_part_3_polyData N).getD n 0 : ℚ) :=
  qexp_coeff_via_E4E6 _ _ f_86_part_3_qExpansion_eq_evalEisPS N n hn

/-- Precomputed first 10 q-coefficients of `f_86_part_3` (rational). -/
def f_86_part_3_qExpList : List ℚ :=
  [0, 0, 0, (14216570232029304297090581971652985343 / 4261156496673876245501765482253243517425435633812242432), 0, ((-(190999386457112530535066628659838321634778371 / 13151717582326778535499276179793961473535295166087168))), ((-(426381481685607416113140145249381736744425 / 338646292422125835855942208151280364785626382336))), (225527673027354758253658868843411060519754900351 / 536804799278644021857113313460978019327971231268864), 1, (77112061954562070317764735189868940298025528969873075 / 134201199819661005464278328365244504831992807817216)]

/-- Bridge: the symbolic `evalEisList` (over ℚ) equals the precomputed list. The heavy kernel work
is the integer certificate `f_86_part_3_evalEisListZ_eq`; the steps here are cheap rational
list checks. -/
lemma f_86_part_3_evalEisList_eq :
    evalEisList f_86_part_3_polyData 10 = f_86_part_3_qExpList := by
  have h : f_86_part_3_polyData
      = f_86_part_3_polyDataZ.map
          (fun t => (t.1, t.2.1, (t.2.2 : ℚ) / f_86_part_3_scale)) := by
    decide +kernel
  rw [h, evalEisList_eq_intCast_div, f_86_part_3_evalEisListZ_eq]
  decide +kernel


/-! ## Piece 4: coefficient of α^4 -/


def f_86_part_4_polyData : List (ℕ × ℕ × ℚ) :=
  [(2, 13, (66277381263315180808019655059933 / 7839012546500689715736535964953625818119068852694841893357545664282624)), (5, 11, ((-(44216699362822009949709364234537 / 1306502091083448285956089327492270969686511475449140315559590944047104)))), (8, 9, (36945083444268017362563237456635 / 871001394055632190637392884994847313124340983632760210373060629364736)), (11, 7, ((-(86789946687621416760503251075 / 279964733803596061276304855891200922075681030453387210477055202295808)))), (14, 5, ((-(109634302549706617902755173798255 / 2613004182166896571912178654984541939373022950898280631119181888094208)))), (17, 3, (25858304931522682247236896347 / 768078830736889056999464625215914738204886228953051331898642530304)), (20, 1, ((-(9437110008506074144367536922149 / 1119858935214384245105219423564803688302724121813548841908220809183232))))]

noncomputable def f_86_part_4 : ModularForm 𝒮ℒ 86 :=
  ((66277381263315180808019655059933 / 7839012546500689715736535964953625818119068852694841893357545664282624) : ℂ) • mkMonomForm 2 13 86 (by decide) +
  (((-(44216699362822009949709364234537 / 1306502091083448285956089327492270969686511475449140315559590944047104))) : ℂ) • mkMonomForm 5 11 86 (by decide) +
  ((36945083444268017362563237456635 / 871001394055632190637392884994847313124340983632760210373060629364736) : ℂ) • mkMonomForm 8 9 86 (by decide) +
  (((-(86789946687621416760503251075 / 279964733803596061276304855891200922075681030453387210477055202295808))) : ℂ) • mkMonomForm 11 7 86 (by decide) +
  (((-(109634302549706617902755173798255 / 2613004182166896571912178654984541939373022950898280631119181888094208))) : ℂ) • mkMonomForm 14 5 86 (by decide) +
  ((25858304931522682247236896347 / 768078830736889056999464625215914738204886228953051331898642530304) : ℂ) • mkMonomForm 17 3 86 (by decide) +
  (((-(9437110008506074144367536922149 / 1119858935214384245105219423564803688302724121813548841908220809183232))) : ℂ) • mkMonomForm 20 1 86 (by decide)

lemma f_86_part_4_qExpansion_eq_evalEisPS :
    qExpansion 1 (f_86_part_4 : ℍ → ℂ) = evalEisPS f_86_part_4_polyData := by
  unfold f_86_part_4
  rw [ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm]
  unfold evalEisPS f_86_part_4_polyData monomialEisPS
  simp only [List.foldr_cons, List.foldr_nil, add_zero]
  push_cast
  module

theorem f_86_part_4_qExpansion_coeff (N n : ℕ) (hn : n < N) :
    (PowerSeries.coeff (R := ℂ) n) (qExpansion 1 (f_86_part_4 : ℍ → ℂ))
      = ((evalEisList f_86_part_4_polyData N).getD n 0 : ℚ) :=
  qexp_coeff_via_E4E6 _ _ f_86_part_4_qExpansion_eq_evalEisPS N n hn

/-- Precomputed first 10 q-coefficients of `f_86_part_4` (rational). -/
def f_86_part_4_qExpList : List ℚ :=
  [0, 0, 0, ((-(17817513294527335495589575 / 195377205340032057107185426290775583366133406971212070912))), 0, ((-(52273083665305229607651387016647 / 201005355288098824184347146389686814162688690299600896))), (1169096955894238267985853692161 / 15527185228668217429096335275234825083902152933376), ((-(73131804724337378417555334912553325 / 8204300215840768334054985566925992414803620012228608))), 0, (56897946166381005609660943117022277024037 / 6153225161880576250541239175194494311102715009171456)]

/-- Bridge: the symbolic `evalEisList` (over ℚ) equals the precomputed list. The heavy kernel work
is the integer certificate `f_86_part_4_evalEisListZ_eq`; the steps here are cheap rational
list checks. -/
lemma f_86_part_4_evalEisList_eq :
    evalEisList f_86_part_4_polyData 10 = f_86_part_4_qExpList := by
  have h : f_86_part_4_polyData
      = f_86_part_4_polyDataZ.map
          (fun t => (t.1, t.2.1, (t.2.2 : ℚ) / f_86_part_4_scale)) := by
    decide +kernel
  rw [h, evalEisList_eq_intCast_div, f_86_part_4_evalEisListZ_eq]
  decide +kernel


/-! ## Piece 5: coefficient of α^5 -/


def f_86_part_5_polyData : List (ℕ × ℕ × ℚ) :=
  [(2, 13, ((-(147545337951926346475403 / 50420528699092436251617399326581721262141850860533223058075733712665837568)))), (5, 11, (32819768959551262853173 / 2801140483282913125089855518143428959007880603362956836559762984036990976)), (8, 9, ((-(246795925872557326492439 / 16806842899697478750539133108860573754047283620177741019358577904221945856)))), (11, 7, (25900045400941770499 / 257247595403532838018456119013172047255825769696598076826917008738091008)), (14, 5, (81413232841105111041155 / 5602280966565826250179711036286857918015761206725913673119525968073981952)), (17, 3, ((-(13991035381262224281383 / 1200488778549819910752795222061469553860520258584124358525612707444424704)))), (20, 1, (21000750834594061146499 / 7202932671298919464516771332368817323163121551504746151153676244666548224))]

noncomputable def f_86_part_5 : ModularForm 𝒮ℒ 86 :=
  (((-(147545337951926346475403 / 50420528699092436251617399326581721262141850860533223058075733712665837568))) : ℂ) • mkMonomForm 2 13 86 (by decide) +
  ((32819768959551262853173 / 2801140483282913125089855518143428959007880603362956836559762984036990976) : ℂ) • mkMonomForm 5 11 86 (by decide) +
  (((-(246795925872557326492439 / 16806842899697478750539133108860573754047283620177741019358577904221945856))) : ℂ) • mkMonomForm 8 9 86 (by decide) +
  ((25900045400941770499 / 257247595403532838018456119013172047255825769696598076826917008738091008) : ℂ) • mkMonomForm 11 7 86 (by decide) +
  ((81413232841105111041155 / 5602280966565826250179711036286857918015761206725913673119525968073981952) : ℂ) • mkMonomForm 14 5 86 (by decide) +
  (((-(13991035381262224281383 / 1200488778549819910752795222061469553860520258584124358525612707444424704))) : ℂ) • mkMonomForm 17 3 86 (by decide) +
  ((21000750834594061146499 / 7202932671298919464516771332368817323163121551504746151153676244666548224) : ℂ) • mkMonomForm 20 1 86 (by decide)

lemma f_86_part_5_qExpansion_eq_evalEisPS :
    qExpansion 1 (f_86_part_5 : ℍ → ℂ) = evalEisPS f_86_part_5_polyData := by
  unfold f_86_part_5
  rw [ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm,
    qExpansion_mkMonomForm]
  unfold evalEisPS f_86_part_5_polyData monomialEisPS
  simp only [List.foldr_cons, List.foldr_nil, add_zero]
  push_cast
  module

theorem f_86_part_5_qExpansion_coeff (N n : ℕ) (hn : n < N) :
    (PowerSeries.coeff (R := ℂ) n) (qExpansion 1 (f_86_part_5 : ℍ → ℂ))
      = ((evalEisList f_86_part_5_polyData N).getD n 0 : ℚ) :=
  qexp_coeff_via_E4E6 _ _ f_86_part_5_qExpansion_eq_evalEisPS N n hn

/-- Precomputed first 10 q-coefficients of `f_86_part_5` (rational). -/
def f_86_part_5_qExpList : List ℚ :=
  [0, 0, 0, ((-(22756186805176591 / 1256666184747086191313416661902268552210970073638836040105984))), 0, (38792072094573802346491 / 430955481737683879051240281859488529564804552002344321024), ((-(2602757927142033463175 / 99870855390793974503947628490310394939658647667474432))), (54270939708620982502804521 / 17590019662762607308213889055489327737338961306218135552), 0, ((-(126667286597681919490732636460675 / 39577544241215866443481250374850987409012662938990804992)))]

/-- Bridge: the symbolic `evalEisList` (over ℚ) equals the precomputed list. The heavy kernel work
is the integer certificate `f_86_part_5_evalEisListZ_eq`; the steps here are cheap rational
list checks. -/
lemma f_86_part_5_evalEisList_eq :
    evalEisList f_86_part_5_polyData 10 = f_86_part_5_qExpList := by
  have h : f_86_part_5_polyData
      = f_86_part_5_polyDataZ.map
          (fun t => (t.1, t.2.1, (t.2.2 : ℚ) / f_86_part_5_scale)) := by
    decide +kernel
  rw [h, evalEisList_eq_intCast_div, f_86_part_5_evalEisListZ_eq]
  decide +kernel


/-! ## Combined LMFDB form -/


noncomputable def lmfdb_1_86_a_orbit : ModularForm 𝒮ℒ 86 :=
  f_86_part_0 +
  α_86 • f_86_part_1 +
  α_86 ^ 2 • f_86_part_2 +
  α_86 ^ 3 • f_86_part_3 +
  α_86 ^ 4 • f_86_part_4 +
  α_86 ^ 5 • f_86_part_5

lemma lmfdb_1_86_a_orbit_coeff_decomp (n : ℕ) :
    (PowerSeries.coeff (R := ℂ) n) (qExpansion 1 (lmfdb_1_86_a_orbit : ℍ → ℂ))
      = (PowerSeries.coeff (R := ℂ) n) (qExpansion 1 (f_86_part_0 : ℍ → ℂ))
        + α_86 * (PowerSeries.coeff (R := ℂ) n) (qExpansion 1 (f_86_part_1 : ℍ → ℂ))
        + α_86 ^ 2 * (PowerSeries.coeff (R := ℂ) n) (qExpansion 1 (f_86_part_2 : ℍ → ℂ))
        + α_86 ^ 3 * (PowerSeries.coeff (R := ℂ) n) (qExpansion 1 (f_86_part_3 : ℍ → ℂ))
        + α_86 ^ 4 * (PowerSeries.coeff (R := ℂ) n) (qExpansion 1 (f_86_part_4 : ℍ → ℂ))
        + α_86 ^ 5 * (PowerSeries.coeff (R := ℂ) n) (qExpansion 1 (f_86_part_5 : ℍ → ℂ)) := by
  unfold lmfdb_1_86_a_orbit
  rw [ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.coe_add,
    ModularForm.qExpansion_add one_pos one_mem_strictPeriods_SL,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.IsGLPos.coe_smul,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
    ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL]
  simp [smul_eq_mul]


/-! ## Coefficient lemmas (n = 0, …, 9)

Sturm bound is 8; we certify 10 coefficients for added
redundancy beyond the minimum mathematically required for uniqueness. -/


lemma lmfdb_1_86_a_orbit_qExpansion_coeff_0 :
    (PowerSeries.coeff (R := ℂ) 0)
      (qExpansion 1 (lmfdb_1_86_a_orbit : ℍ → ℂ)) = 0 := by
  rw [lmfdb_1_86_a_orbit_coeff_decomp,
    f_86_part_0_qExpansion_coeff 10 0 (by decide),
    f_86_part_1_qExpansion_coeff 10 0 (by decide),
    f_86_part_2_qExpansion_coeff 10 0 (by decide),
    f_86_part_3_qExpansion_coeff 10 0 (by decide),
    f_86_part_4_qExpansion_coeff 10 0 (by decide),
    f_86_part_5_qExpansion_coeff 10 0 (by decide),
    f_86_part_0_evalEisList_eq,
    f_86_part_1_evalEisList_eq,
    f_86_part_2_evalEisList_eq,
    f_86_part_3_evalEisList_eq,
    f_86_part_4_evalEisList_eq,
    f_86_part_5_evalEisList_eq,
    show f_86_part_0_qExpList.getD 0 0 = (0 : ℚ) from by decide +kernel,
    show f_86_part_1_qExpList.getD 0 0 = (0 : ℚ) from by decide +kernel,
    show f_86_part_2_qExpList.getD 0 0 = (0 : ℚ) from by decide +kernel,
    show f_86_part_3_qExpList.getD 0 0 = (0 : ℚ) from by decide +kernel,
    show f_86_part_4_qExpList.getD 0 0 = (0 : ℚ) from by decide +kernel,
    show f_86_part_5_qExpList.getD 0 0 = (0 : ℚ) from by decide +kernel]
  push_cast; ring

lemma lmfdb_1_86_a_orbit_qExpansion_coeff_1 :
    (PowerSeries.coeff (R := ℂ) 1)
      (qExpansion 1 (lmfdb_1_86_a_orbit : ℍ → ℂ)) = 1 := by
  rw [lmfdb_1_86_a_orbit_coeff_decomp,
    f_86_part_0_qExpansion_coeff 10 1 (by decide),
    f_86_part_1_qExpansion_coeff 10 1 (by decide),
    f_86_part_2_qExpansion_coeff 10 1 (by decide),
    f_86_part_3_qExpansion_coeff 10 1 (by decide),
    f_86_part_4_qExpansion_coeff 10 1 (by decide),
    f_86_part_5_qExpansion_coeff 10 1 (by decide),
    f_86_part_0_evalEisList_eq,
    f_86_part_1_evalEisList_eq,
    f_86_part_2_evalEisList_eq,
    f_86_part_3_evalEisList_eq,
    f_86_part_4_evalEisList_eq,
    f_86_part_5_evalEisList_eq,
    show f_86_part_0_qExpList.getD 1 0 = (1 : ℚ) from by decide +kernel,
    show f_86_part_1_qExpList.getD 1 0 = (0 : ℚ) from by decide +kernel,
    show f_86_part_2_qExpList.getD 1 0 = (0 : ℚ) from by decide +kernel,
    show f_86_part_3_qExpList.getD 1 0 = (0 : ℚ) from by decide +kernel,
    show f_86_part_4_qExpList.getD 1 0 = (0 : ℚ) from by decide +kernel,
    show f_86_part_5_qExpList.getD 1 0 = (0 : ℚ) from by decide +kernel]
  push_cast; ring

lemma lmfdb_1_86_a_orbit_qExpansion_coeff_2 :
    (PowerSeries.coeff (R := ℂ) 2)
      (qExpansion 1 (lmfdb_1_86_a_orbit : ℍ → ℂ)) = 1 * α_86 := by
  rw [lmfdb_1_86_a_orbit_coeff_decomp,
    f_86_part_0_qExpansion_coeff 10 2 (by decide),
    f_86_part_1_qExpansion_coeff 10 2 (by decide),
    f_86_part_2_qExpansion_coeff 10 2 (by decide),
    f_86_part_3_qExpansion_coeff 10 2 (by decide),
    f_86_part_4_qExpansion_coeff 10 2 (by decide),
    f_86_part_5_qExpansion_coeff 10 2 (by decide),
    f_86_part_0_evalEisList_eq,
    f_86_part_1_evalEisList_eq,
    f_86_part_2_evalEisList_eq,
    f_86_part_3_evalEisList_eq,
    f_86_part_4_evalEisList_eq,
    f_86_part_5_evalEisList_eq,
    show f_86_part_0_qExpList.getD 2 0 = (0 : ℚ) from by decide +kernel,
    show f_86_part_1_qExpList.getD 2 0 = (1 : ℚ) from by decide +kernel,
    show f_86_part_2_qExpList.getD 2 0 = (0 : ℚ) from by decide +kernel,
    show f_86_part_3_qExpList.getD 2 0 = (0 : ℚ) from by decide +kernel,
    show f_86_part_4_qExpList.getD 2 0 = (0 : ℚ) from by decide +kernel,
    show f_86_part_5_qExpList.getD 2 0 = (0 : ℚ) from by decide +kernel]
  push_cast; ring

lemma lmfdb_1_86_a_orbit_qExpansion_coeff_3 :
    (PowerSeries.coeff (R := ℂ) 3)
      (qExpansion 1 (lmfdb_1_86_a_orbit : ℍ → ℂ)) = ((-(52243492089218058299911772771623830827582222696196728269381700 / 287074019048161685397628960631714176420107))) + ((-(902897007233951502040088502829856298063482833425239873 / 7055131092127621580332129336485007599700549632))) * α_86 + (16305437420326505183429320766865760641411744425 / 1387095213761027423665939284587644374161925662048256) * α_86 ^ 2 + (14216570232029304297090581971652985343 / 4261156496673876245501765482253243517425435633812242432) * α_86 ^ 3 + ((-(17817513294527335495589575 / 195377205340032057107185426290775583366133406971212070912))) * α_86 ^ 4 + ((-(22756186805176591 / 1256666184747086191313416661902268552210970073638836040105984))) * α_86 ^ 5 := by
  rw [lmfdb_1_86_a_orbit_coeff_decomp,
    f_86_part_0_qExpansion_coeff 10 3 (by decide),
    f_86_part_1_qExpansion_coeff 10 3 (by decide),
    f_86_part_2_qExpansion_coeff 10 3 (by decide),
    f_86_part_3_qExpansion_coeff 10 3 (by decide),
    f_86_part_4_qExpansion_coeff 10 3 (by decide),
    f_86_part_5_qExpansion_coeff 10 3 (by decide),
    f_86_part_0_evalEisList_eq,
    f_86_part_1_evalEisList_eq,
    f_86_part_2_evalEisList_eq,
    f_86_part_3_evalEisList_eq,
    f_86_part_4_evalEisList_eq,
    f_86_part_5_evalEisList_eq,
    show f_86_part_0_qExpList.getD 3 0 = (((-(52243492089218058299911772771623830827582222696196728269381700 / 287074019048161685397628960631714176420107))) : ℚ) from by decide +kernel,
    show f_86_part_1_qExpList.getD 3 0 = (((-(902897007233951502040088502829856298063482833425239873 / 7055131092127621580332129336485007599700549632))) : ℚ) from by decide +kernel,
    show f_86_part_2_qExpList.getD 3 0 = ((16305437420326505183429320766865760641411744425 / 1387095213761027423665939284587644374161925662048256) : ℚ) from by decide +kernel,
    show f_86_part_3_qExpList.getD 3 0 = ((14216570232029304297090581971652985343 / 4261156496673876245501765482253243517425435633812242432) : ℚ) from by decide +kernel,
    show f_86_part_4_qExpList.getD 3 0 = (((-(17817513294527335495589575 / 195377205340032057107185426290775583366133406971212070912))) : ℚ) from by decide +kernel,
    show f_86_part_5_qExpList.getD 3 0 = (((-(22756186805176591 / 1256666184747086191313416661902268552210970073638836040105984))) : ℚ) from by decide +kernel]
  push_cast; ring

lemma lmfdb_1_86_a_orbit_qExpansion_coeff_4 :
    (PowerSeries.coeff (R := ℂ) 4)
      (qExpansion 1 (lmfdb_1_86_a_orbit : ℍ → ℂ)) = (-38685626227668133590597632) + 1 * α_86 ^ 2 := by
  rw [lmfdb_1_86_a_orbit_coeff_decomp,
    f_86_part_0_qExpansion_coeff 10 4 (by decide),
    f_86_part_1_qExpansion_coeff 10 4 (by decide),
    f_86_part_2_qExpansion_coeff 10 4 (by decide),
    f_86_part_3_qExpansion_coeff 10 4 (by decide),
    f_86_part_4_qExpansion_coeff 10 4 (by decide),
    f_86_part_5_qExpansion_coeff 10 4 (by decide),
    f_86_part_0_evalEisList_eq,
    f_86_part_1_evalEisList_eq,
    f_86_part_2_evalEisList_eq,
    f_86_part_3_evalEisList_eq,
    f_86_part_4_evalEisList_eq,
    f_86_part_5_evalEisList_eq,
    show f_86_part_0_qExpList.getD 4 0 = ((-38685626227668133590597632) : ℚ) from by decide +kernel,
    show f_86_part_1_qExpList.getD 4 0 = (0 : ℚ) from by decide +kernel,
    show f_86_part_2_qExpList.getD 4 0 = (1 : ℚ) from by decide +kernel,
    show f_86_part_3_qExpList.getD 4 0 = (0 : ℚ) from by decide +kernel,
    show f_86_part_4_qExpList.getD 4 0 = (0 : ℚ) from by decide +kernel,
    show f_86_part_5_qExpList.getD 4 0 = (0 : ℚ) from by decide +kernel]
  push_cast; ring

lemma lmfdb_1_86_a_orbit_qExpansion_coeff_5 :
    (PowerSeries.coeff (R := ℂ) 5)
      (qExpansion 1 (lmfdb_1_86_a_orbit : ℍ → ℂ)) = (4402186474259201322184129483763474807216407419038327384433717709593222 / 95691339682720561799209653543904725473369) + (93372988102927335694231622865378452477633946598112811124470053 / 195975863670211710564781370457916877769459712) * α_86 + (243472622774502729494086422329890743425351987527756017 / 12843474201490994663573511894330040501499311685632) * α_86 ^ 2 + ((-(190999386457112530535066628659838321634778371 / 13151717582326778535499276179793961473535295166087168))) * α_86 ^ 3 + ((-(52273083665305229607651387016647 / 201005355288098824184347146389686814162688690299600896))) * α_86 ^ 4 + (38792072094573802346491 / 430955481737683879051240281859488529564804552002344321024) * α_86 ^ 5 := by
  rw [lmfdb_1_86_a_orbit_coeff_decomp,
    f_86_part_0_qExpansion_coeff 10 5 (by decide),
    f_86_part_1_qExpansion_coeff 10 5 (by decide),
    f_86_part_2_qExpansion_coeff 10 5 (by decide),
    f_86_part_3_qExpansion_coeff 10 5 (by decide),
    f_86_part_4_qExpansion_coeff 10 5 (by decide),
    f_86_part_5_qExpansion_coeff 10 5 (by decide),
    f_86_part_0_evalEisList_eq,
    f_86_part_1_evalEisList_eq,
    f_86_part_2_evalEisList_eq,
    f_86_part_3_evalEisList_eq,
    f_86_part_4_evalEisList_eq,
    f_86_part_5_evalEisList_eq,
    show f_86_part_0_qExpList.getD 5 0 = ((4402186474259201322184129483763474807216407419038327384433717709593222 / 95691339682720561799209653543904725473369) : ℚ) from by decide +kernel,
    show f_86_part_1_qExpList.getD 5 0 = ((93372988102927335694231622865378452477633946598112811124470053 / 195975863670211710564781370457916877769459712) : ℚ) from by decide +kernel,
    show f_86_part_2_qExpList.getD 5 0 = ((243472622774502729494086422329890743425351987527756017 / 12843474201490994663573511894330040501499311685632) : ℚ) from by decide +kernel,
    show f_86_part_3_qExpList.getD 5 0 = (((-(190999386457112530535066628659838321634778371 / 13151717582326778535499276179793961473535295166087168))) : ℚ) from by decide +kernel,
    show f_86_part_4_qExpList.getD 5 0 = (((-(52273083665305229607651387016647 / 201005355288098824184347146389686814162688690299600896))) : ℚ) from by decide +kernel,
    show f_86_part_5_qExpList.getD 5 0 = ((38792072094573802346491 / 430955481737683879051240281859488529564804552002344321024) : ℚ) from by decide +kernel]
  push_cast; ring

lemma lmfdb_1_86_a_orbit_qExpansion_coeff_6 :
    (PowerSeries.coeff (R := ℂ) 6)
      (qExpansion 1 (lmfdb_1_86_a_orbit : ℍ → ℂ)) = ((-(1128848500838925031669697647619166801181993859977042841113513792670531584 / 95691339682720561799209653543904725473369))) + (81757045989390729126527448727328007542610533464540575085440700 / 287074019048161685397628960631714176420107) * α_86 + ((-(609373020472064554149992742444842443571765331787631 / 110236423314494087192689520882578243745321088))) * α_86 ^ 2 + ((-(426381481685607416113140145249381736744425 / 338646292422125835855942208151280364785626382336))) * α_86 ^ 3 + (1169096955894238267985853692161 / 15527185228668217429096335275234825083902152933376) * α_86 ^ 4 + ((-(2602757927142033463175 / 99870855390793974503947628490310394939658647667474432))) * α_86 ^ 5 := by
  rw [lmfdb_1_86_a_orbit_coeff_decomp,
    f_86_part_0_qExpansion_coeff 10 6 (by decide),
    f_86_part_1_qExpansion_coeff 10 6 (by decide),
    f_86_part_2_qExpansion_coeff 10 6 (by decide),
    f_86_part_3_qExpansion_coeff 10 6 (by decide),
    f_86_part_4_qExpansion_coeff 10 6 (by decide),
    f_86_part_5_qExpansion_coeff 10 6 (by decide),
    f_86_part_0_evalEisList_eq,
    f_86_part_1_evalEisList_eq,
    f_86_part_2_evalEisList_eq,
    f_86_part_3_evalEisList_eq,
    f_86_part_4_evalEisList_eq,
    f_86_part_5_evalEisList_eq,
    show f_86_part_0_qExpList.getD 6 0 = (((-(1128848500838925031669697647619166801181993859977042841113513792670531584 / 95691339682720561799209653543904725473369))) : ℚ) from by decide +kernel,
    show f_86_part_1_qExpList.getD 6 0 = ((81757045989390729126527448727328007542610533464540575085440700 / 287074019048161685397628960631714176420107) : ℚ) from by decide +kernel,
    show f_86_part_2_qExpList.getD 6 0 = (((-(609373020472064554149992742444842443571765331787631 / 110236423314494087192689520882578243745321088))) : ℚ) from by decide +kernel,
    show f_86_part_3_qExpList.getD 6 0 = (((-(426381481685607416113140145249381736744425 / 338646292422125835855942208151280364785626382336))) : ℚ) from by decide +kernel,
    show f_86_part_4_qExpList.getD 6 0 = ((1169096955894238267985853692161 / 15527185228668217429096335275234825083902152933376) : ℚ) from by decide +kernel,
    show f_86_part_5_qExpList.getD 6 0 = (((-(2602757927142033463175 / 99870855390793974503947628490310394939658647667474432))) : ℚ) from by decide +kernel]
  push_cast; ring

lemma lmfdb_1_86_a_orbit_qExpansion_coeff_7 :
    (PowerSeries.coeff (R := ℂ) 7)
      (qExpansion 1 (lmfdb_1_86_a_orbit : ℍ → ℂ)) = (2642800538867883270136724690590682243710211496019955050629239271071914600 / 1952884483320827791820605174365402560681) + ((-(437459623189633552114263376468701812075405427868989841854326668233 / 7999014843682110635297198794200688888549376))) * α_86 + (343655938183232008241677693836479936399239110879772766075 / 524223436795550802594837220176736346999971905536) * α_86 ^ 2 + (225527673027354758253658868843411060519754900351 / 536804799278644021857113313460978019327971231268864) * α_86 ^ 3 + ((-(73131804724337378417555334912553325 / 8204300215840768334054985566925992414803620012228608))) * α_86 ^ 4 + (54270939708620982502804521 / 17590019662762607308213889055489327737338961306218135552) * α_86 ^ 5 := by
  rw [lmfdb_1_86_a_orbit_coeff_decomp,
    f_86_part_0_qExpansion_coeff 10 7 (by decide),
    f_86_part_1_qExpansion_coeff 10 7 (by decide),
    f_86_part_2_qExpansion_coeff 10 7 (by decide),
    f_86_part_3_qExpansion_coeff 10 7 (by decide),
    f_86_part_4_qExpansion_coeff 10 7 (by decide),
    f_86_part_5_qExpansion_coeff 10 7 (by decide),
    f_86_part_0_evalEisList_eq,
    f_86_part_1_evalEisList_eq,
    f_86_part_2_evalEisList_eq,
    f_86_part_3_evalEisList_eq,
    f_86_part_4_evalEisList_eq,
    f_86_part_5_evalEisList_eq,
    show f_86_part_0_qExpList.getD 7 0 = ((2642800538867883270136724690590682243710211496019955050629239271071914600 / 1952884483320827791820605174365402560681) : ℚ) from by decide +kernel,
    show f_86_part_1_qExpList.getD 7 0 = (((-(437459623189633552114263376468701812075405427868989841854326668233 / 7999014843682110635297198794200688888549376))) : ℚ) from by decide +kernel,
    show f_86_part_2_qExpList.getD 7 0 = ((343655938183232008241677693836479936399239110879772766075 / 524223436795550802594837220176736346999971905536) : ℚ) from by decide +kernel,
    show f_86_part_3_qExpList.getD 7 0 = ((225527673027354758253658868843411060519754900351 / 536804799278644021857113313460978019327971231268864) : ℚ) from by decide +kernel,
    show f_86_part_4_qExpList.getD 7 0 = (((-(73131804724337378417555334912553325 / 8204300215840768334054985566925992414803620012228608))) : ℚ) from by decide +kernel,
    show f_86_part_5_qExpList.getD 7 0 = ((54270939708620982502804521 / 17590019662762607308213889055489327737338961306218135552) : ℚ) from by decide +kernel]
  push_cast; ring

lemma lmfdb_1_86_a_orbit_qExpansion_coeff_8 :
    (PowerSeries.coeff (R := ℂ) 8)
      (qExpansion 1 (lmfdb_1_86_a_orbit : ℍ → ℂ)) = (-77371252455336267181195264) * α_86 + 1 * α_86 ^ 3 := by
  rw [lmfdb_1_86_a_orbit_coeff_decomp,
    f_86_part_0_qExpansion_coeff 10 8 (by decide),
    f_86_part_1_qExpansion_coeff 10 8 (by decide),
    f_86_part_2_qExpansion_coeff 10 8 (by decide),
    f_86_part_3_qExpansion_coeff 10 8 (by decide),
    f_86_part_4_qExpansion_coeff 10 8 (by decide),
    f_86_part_5_qExpansion_coeff 10 8 (by decide),
    f_86_part_0_evalEisList_eq,
    f_86_part_1_evalEisList_eq,
    f_86_part_2_evalEisList_eq,
    f_86_part_3_evalEisList_eq,
    f_86_part_4_evalEisList_eq,
    f_86_part_5_evalEisList_eq,
    show f_86_part_0_qExpList.getD 8 0 = (0 : ℚ) from by decide +kernel,
    show f_86_part_1_qExpList.getD 8 0 = ((-77371252455336267181195264) : ℚ) from by decide +kernel,
    show f_86_part_2_qExpList.getD 8 0 = (0 : ℚ) from by decide +kernel,
    show f_86_part_3_qExpList.getD 8 0 = (1 : ℚ) from by decide +kernel,
    show f_86_part_4_qExpList.getD 8 0 = (0 : ℚ) from by decide +kernel,
    show f_86_part_5_qExpList.getD 8 0 = (0 : ℚ) from by decide +kernel]
  push_cast; ring

lemma lmfdb_1_86_a_orbit_qExpansion_coeff_9 :
    (PowerSeries.coeff (R := ℂ) 9)
      (qExpansion 1 (lmfdb_1_86_a_orbit : ℍ → ℂ)) = ((-(2114222518674518467140803002491723427521257421395954220337037217942939840139803 / 1952884483320827791820605174365402560681))) + ((-(42887426087551617366731918233822781770306162964610590821429520875060725 / 1999753710920527658824299698550172222137344))) * α_86 + ((-(90211841902874627136792938281808243782399868699734668383680641 / 131055859198887700648709305044184086749992976384))) * α_86 ^ 2 + (77112061954562070317764735189868940298025528969873075 / 134201199819661005464278328365244504831992807817216) * α_86 ^ 3 + (56897946166381005609660943117022277024037 / 6153225161880576250541239175194494311102715009171456) * α_86 ^ 4 + ((-(126667286597681919490732636460675 / 39577544241215866443481250374850987409012662938990804992))) * α_86 ^ 5 := by
  rw [lmfdb_1_86_a_orbit_coeff_decomp,
    f_86_part_0_qExpansion_coeff 10 9 (by decide),
    f_86_part_1_qExpansion_coeff 10 9 (by decide),
    f_86_part_2_qExpansion_coeff 10 9 (by decide),
    f_86_part_3_qExpansion_coeff 10 9 (by decide),
    f_86_part_4_qExpansion_coeff 10 9 (by decide),
    f_86_part_5_qExpansion_coeff 10 9 (by decide),
    f_86_part_0_evalEisList_eq,
    f_86_part_1_evalEisList_eq,
    f_86_part_2_evalEisList_eq,
    f_86_part_3_evalEisList_eq,
    f_86_part_4_evalEisList_eq,
    f_86_part_5_evalEisList_eq,
    show f_86_part_0_qExpList.getD 9 0 = (((-(2114222518674518467140803002491723427521257421395954220337037217942939840139803 / 1952884483320827791820605174365402560681))) : ℚ) from by decide +kernel,
    show f_86_part_1_qExpList.getD 9 0 = (((-(42887426087551617366731918233822781770306162964610590821429520875060725 / 1999753710920527658824299698550172222137344))) : ℚ) from by decide +kernel,
    show f_86_part_2_qExpList.getD 9 0 = (((-(90211841902874627136792938281808243782399868699734668383680641 / 131055859198887700648709305044184086749992976384))) : ℚ) from by decide +kernel,
    show f_86_part_3_qExpList.getD 9 0 = ((77112061954562070317764735189868940298025528969873075 / 134201199819661005464278328365244504831992807817216) : ℚ) from by decide +kernel,
    show f_86_part_4_qExpList.getD 9 0 = ((56897946166381005609660943117022277024037 / 6153225161880576250541239175194494311102715009171456) : ℚ) from by decide +kernel,
    show f_86_part_5_qExpList.getD 9 0 = (((-(126667286597681919490732636460675 / 39577544241215866443481250374850987409012662938990804992))) : ℚ) from by decide +kernel]
  push_cast; ring


/-! ## Uniqueness theorem -/


/-- **Uniqueness theorem.** Any level-1 weight-86 modular form `f` whose first 8
q-coefficients match the LMFDB-published values for `1.86.a.{a..}` is equal to our
explicit construction `lmfdb_1_86_a_orbit`. Proven via `ModularForm.eq_of_sturm_bound`. -/
theorem identifies_lmfdb_1_86_a_orbit (f : ModularForm 𝒮ℒ 86)
    (h_0 : (PowerSeries.coeff (R := ℂ) 0) (qExpansion 1 (f : ℍ → ℂ)) = 0)
    (h_1 : (PowerSeries.coeff (R := ℂ) 1) (qExpansion 1 (f : ℍ → ℂ)) = 1)
    (h_2 : (PowerSeries.coeff (R := ℂ) 2) (qExpansion 1 (f : ℍ → ℂ)) = 1 * α_86)
    (h_3 : (PowerSeries.coeff (R := ℂ) 3) (qExpansion 1 (f : ℍ → ℂ)) = ((-(52243492089218058299911772771623830827582222696196728269381700 / 287074019048161685397628960631714176420107))) + ((-(902897007233951502040088502829856298063482833425239873 / 7055131092127621580332129336485007599700549632))) * α_86 + (16305437420326505183429320766865760641411744425 / 1387095213761027423665939284587644374161925662048256) * α_86 ^ 2 + (14216570232029304297090581971652985343 / 4261156496673876245501765482253243517425435633812242432) * α_86 ^ 3 + ((-(17817513294527335495589575 / 195377205340032057107185426290775583366133406971212070912))) * α_86 ^ 4 + ((-(22756186805176591 / 1256666184747086191313416661902268552210970073638836040105984))) * α_86 ^ 5)
    (h_4 : (PowerSeries.coeff (R := ℂ) 4) (qExpansion 1 (f : ℍ → ℂ)) = (-38685626227668133590597632) + 1 * α_86 ^ 2)
    (h_5 : (PowerSeries.coeff (R := ℂ) 5) (qExpansion 1 (f : ℍ → ℂ)) = (4402186474259201322184129483763474807216407419038327384433717709593222 / 95691339682720561799209653543904725473369) + (93372988102927335694231622865378452477633946598112811124470053 / 195975863670211710564781370457916877769459712) * α_86 + (243472622774502729494086422329890743425351987527756017 / 12843474201490994663573511894330040501499311685632) * α_86 ^ 2 + ((-(190999386457112530535066628659838321634778371 / 13151717582326778535499276179793961473535295166087168))) * α_86 ^ 3 + ((-(52273083665305229607651387016647 / 201005355288098824184347146389686814162688690299600896))) * α_86 ^ 4 + (38792072094573802346491 / 430955481737683879051240281859488529564804552002344321024) * α_86 ^ 5)
    (h_6 : (PowerSeries.coeff (R := ℂ) 6) (qExpansion 1 (f : ℍ → ℂ)) = ((-(1128848500838925031669697647619166801181993859977042841113513792670531584 / 95691339682720561799209653543904725473369))) + (81757045989390729126527448727328007542610533464540575085440700 / 287074019048161685397628960631714176420107) * α_86 + ((-(609373020472064554149992742444842443571765331787631 / 110236423314494087192689520882578243745321088))) * α_86 ^ 2 + ((-(426381481685607416113140145249381736744425 / 338646292422125835855942208151280364785626382336))) * α_86 ^ 3 + (1169096955894238267985853692161 / 15527185228668217429096335275234825083902152933376) * α_86 ^ 4 + ((-(2602757927142033463175 / 99870855390793974503947628490310394939658647667474432))) * α_86 ^ 5)
    (h_7 : (PowerSeries.coeff (R := ℂ) 7) (qExpansion 1 (f : ℍ → ℂ)) = (2642800538867883270136724690590682243710211496019955050629239271071914600 / 1952884483320827791820605174365402560681) + ((-(437459623189633552114263376468701812075405427868989841854326668233 / 7999014843682110635297198794200688888549376))) * α_86 + (343655938183232008241677693836479936399239110879772766075 / 524223436795550802594837220176736346999971905536) * α_86 ^ 2 + (225527673027354758253658868843411060519754900351 / 536804799278644021857113313460978019327971231268864) * α_86 ^ 3 + ((-(73131804724337378417555334912553325 / 8204300215840768334054985566925992414803620012228608))) * α_86 ^ 4 + (54270939708620982502804521 / 17590019662762607308213889055489327737338961306218135552) * α_86 ^ 5) :
    f = lmfdb_1_86_a_orbit := by
  apply ModularForm.eq_of_sturm_bound
  intro i hi
  have : i ≤ 7 := by omega
  interval_cases i
  · rw [h_0, lmfdb_1_86_a_orbit_qExpansion_coeff_0]
  · rw [h_1, lmfdb_1_86_a_orbit_qExpansion_coeff_1]
  · rw [h_2, lmfdb_1_86_a_orbit_qExpansion_coeff_2]
  · rw [h_3, lmfdb_1_86_a_orbit_qExpansion_coeff_3]
  · rw [h_4, lmfdb_1_86_a_orbit_qExpansion_coeff_4]
  · rw [h_5, lmfdb_1_86_a_orbit_qExpansion_coeff_5]
  · rw [h_6, lmfdb_1_86_a_orbit_qExpansion_coeff_6]
  · rw [h_7, lmfdb_1_86_a_orbit_qExpansion_coeff_7]


end LeanBridge.QExpansion.LMFDB.W86