import LeanBridge.ForMathlib.QExpansion.IntEval

set_option maxHeartbeats 0
set_option maxRecDepth 4000

/-!
# LMFDB level-1 weight-38 form `1.38.a`, piece 0: integer q-coefficient certificate

Heavy `decide +kernel` over `ℤ` (denominators cleared by the scale `D = 31104`), isolated in its own
module so `lake` schedules it in parallel with the other pieces. Generated by
`scripts/lmfdb_qexp_to_e4e6_v3.sage`.
-/

namespace LeanBridge.QExpansion.LMFDB.W38

open LeanBridge.QExpansion

def f_38_part_0_polyDataZ : List (ℕ × ℕ × ℤ) :=
  [(2, 5, (-7)), (5, 3, (-4)), (8, 1, 11)]

def f_38_part_0_scale : ℤ := 31104

def f_38_part_0_qExpListZ : List ℤ :=
  [0, 31104, 0, (-83980800), (-1105594417152), (-1275944774803200), (-307713284235067392), (-24455257335547315200), (-830825867434681958400), (-13983475252141908966528)]

/-- Integer-arithmetic certificate (the heavy kernel computation). -/
lemma f_38_part_0_evalEisListZ_eq :
    evalEisListZ f_38_part_0_polyDataZ 10 = f_38_part_0_qExpListZ := by
  decide +kernel

end LeanBridge.QExpansion.LMFDB.W38
