import LeanBridge.ForMathlib.QExpansion.IntEval

set_option maxHeartbeats 0
set_option maxRecDepth 4000

/-!
# LMFDB level-1 weight-60 form `1.60.a`, piece 4: integer q-coefficient certificate

Heavy `decide +kernel` over `ℤ` (denominators cleared by the scale `D = 849646227046494955089871876317511680`), isolated in its own
module so `lake` schedules it in parallel with the other pieces. Generated by
`scripts/lmfdb_qexp_to_e4e6_v3.sage`.
-/

namespace LeanBridge.QExpansion.LMFDB.W60

open LeanBridge.QExpansion

def f_60_part_4_polyDataZ : List (ℕ × ℕ × ℤ) :=
  [(0, 10, 149173), (3, 8, (-721925)), (6, 6, 1426210), (9, 4, (-1438810)), (12, 2, 740825), (15, 0, (-155473))]

def f_60_part_4_scale : ℤ := 849646227046494955089871876317511680

def f_60_part_4_qExpListZ : List ℤ :=
  [0, 0, 0, (-156031757844480), 0, (-2286161748425938305024), 263993905104073449799680, (-21526307921464330561781760), 0, (-25782710695509481540980572160)]

/-- Integer-arithmetic certificate (the heavy kernel computation). -/
lemma f_60_part_4_evalEisListZ_eq :
    evalEisListZ f_60_part_4_polyDataZ 10 = f_60_part_4_qExpListZ := by
  decide +kernel

end LeanBridge.QExpansion.LMFDB.W60
