import LeanBridge.ForMathlib.QExpansion.IntEval

set_option maxHeartbeats 0
set_option maxRecDepth 4000

/-!
# LMFDB level-1 weight-32 form `1.32.a`, piece 1: integer q-coefficient certificate

Heavy `decide +kernel` over `ℤ` (denominators cleared by the scale `D = 2985984`), isolated in its own
module so `lake` schedules it in parallel with the other pieces. Generated by
`scripts/lmfdb_qexp_to_e4e6_v3.sage`.
-/

namespace LeanBridge.QExpansion.LMFDB.W32

open LeanBridge.QExpansion

def f_32_part_1_polyDataZ : List (ℕ × ℕ × ℤ) :=
  [(2, 4, 1), (5, 2, (-2)), (8, 0, 1)]

def f_32_part_1_scale : ℤ := 2985984

def f_32_part_1_qExpListZ : List ℤ :=
  [0, 0, 2985984, 1289945088, 119319920640, (-4235797463040), 51696161832960, (-214778437042176), (-1381960215429120), 22397522954158080]

/-- Integer-arithmetic certificate (the heavy kernel computation). -/
lemma f_32_part_1_evalEisListZ_eq :
    evalEisListZ f_32_part_1_polyDataZ 10 = f_32_part_1_qExpListZ := by
  decide +kernel

end LeanBridge.QExpansion.LMFDB.W32
