import LeanBridge.ForMathlib.QExpansion.IntEval

set_option maxHeartbeats 0
set_option maxRecDepth 4000

/-!
# LMFDB level-1 weight-52 form `1.52.a`, piece 3: integer q-coefficient certificate

Heavy `decide +kernel` over `ℤ` (denominators cleared by the scale `D = 22196218073557298577408`), isolated in its own
module so `lake` schedules it in parallel with the other pieces. Generated by
`scripts/lmfdb_qexp_to_e4e6_v3.sage`.
-/

namespace LeanBridge.QExpansion.LMFDB.W52

open LeanBridge.QExpansion

def f_52_part_3_polyDataZ : List (ℕ × ℕ × ℤ) :=
  [(1, 8, 37), (4, 6, (-76)), (7, 4, 6), (10, 2, 68), (13, 0, (-35))]

def f_52_part_3_scale : ℤ := 22196218073557298577408

def f_52_part_3_qExpListZ : List ℤ :=
  [0, 0, 0, (-371504185344), 0, (-59341106533367808), (-19669630876888596480), (-223289449904628301824), 22196218073557298577408, (-320998368167615256330240)]

/-- Integer-arithmetic certificate (the heavy kernel computation). -/
lemma f_52_part_3_evalEisListZ_eq :
    evalEisListZ f_52_part_3_polyDataZ 10 = f_52_part_3_qExpListZ := by
  decide +kernel

end LeanBridge.QExpansion.LMFDB.W52
