import LeanBridge.ForMathlib.QExpansion.IntEval

set_option maxHeartbeats 0
set_option maxRecDepth 4000

/-!
# LMFDB level-1 weight-48 form `1.48.a`, piece 1: integer q-coefficient certificate

Heavy `decide +kernel` over `ℤ` (denominators cleared by the scale `D = 4553155295576064`), isolated in its own
module so `lake` schedules it in parallel with the other pieces. Generated by
`scripts/lmfdb_qexp_to_e4e6_v3.sage`.
-/

namespace LeanBridge.QExpansion.LMFDB.W48

open LeanBridge.QExpansion

def f_48_part_1_polyDataZ : List (ℕ × ℕ × ℤ) :=
  [(0, 8, 20683004439), (3, 6, (-26475769972)), (6, 4, (-43145874222)), (9, 2, 82987040604), (12, 0, (-34048400849))]

def f_48_part_1_scale : ℤ := 4553155295576064

def f_48_part_1_qExpListZ : List ℤ :=
  [0, 0, 4553155295576064, (-283931889821684858880), 0, (-54271349347565658697629696), (-653143782170924593855856640), 115494253835864642892884606976, (-1281599280782272650307367337984), 20458819416275287313312781434880]

/-- Integer-arithmetic certificate (the heavy kernel computation). -/
lemma f_48_part_1_evalEisListZ_eq :
    evalEisListZ f_48_part_1_polyDataZ 10 = f_48_part_1_qExpListZ := by
  decide +kernel

end LeanBridge.QExpansion.LMFDB.W48
