import LeanBridge.ForMathlib.QExpansion.IntEval

set_option maxHeartbeats 0
set_option maxRecDepth 4000

/-!
# LMFDB level-1 weight-56 form `1.56.a`, piece 2: integer q-coefficient certificate

Heavy `decide +kernel` over `ℤ` (denominators cleared by the scale `D = 2640930121969280483328`), isolated in its own
module so `lake` schedules it in parallel with the other pieces. Generated by
`scripts/lmfdb_qexp_to_e4e6_v3.sage`.
-/

namespace LeanBridge.QExpansion.LMFDB.W56

open LeanBridge.QExpansion

def f_56_part_2_polyDataZ : List (ℕ × ℕ × ℤ) :=
  [(2, 8, 535520243), (5, 6, (-1775459492)), (8, 4, 2113257018), (11, 2, (-1042216532)), (14, 0, 168898763)]

def f_56_part_2_scale : ℤ := 2640930121969280483328

def f_56_part_2_qExpListZ : List ℤ :=
  [0, 0, 0, (-1891686309125160960), 2640930121969280483328, 882206097128287981535232, (-109849308213657798482853888), (-34756642606819410661783633920), 0, 13149661406090720205745522999296]

/-- Integer-arithmetic certificate (the heavy kernel computation). -/
lemma f_56_part_2_evalEisListZ_eq :
    evalEisListZ f_56_part_2_polyDataZ 10 = f_56_part_2_qExpListZ := by
  decide +kernel

end LeanBridge.QExpansion.LMFDB.W56
