import LeanBridge.ForMathlib.QExpansion.IntEval

set_option maxHeartbeats 0
set_option maxRecDepth 4000

/-!
# LMFDB level-1 weight-60 form `1.60.a`, piece 0: integer q-coefficient certificate

Heavy `decide +kernel` over `ℤ` (denominators cleared by the scale `D = 76320863395569936138240`), isolated in its own
module so `lake` schedules it in parallel with the other pieces. Generated by
`scripts/lmfdb_qexp_to_e4e6_v3.sage`.
-/

namespace LeanBridge.QExpansion.LMFDB.W60

open LeanBridge.QExpansion

def f_60_part_0_polyDataZ : List (ℕ × ℕ × ℤ) :=
  [(0, 10, 5185148146054337089929901799), (3, 8, (-29127570960776695882435939015)), (6, 6, 66847364844090425453568208790), (9, 4, (-77628150301152982961343694430)), (12, 2, 45298749138702621325196259475), (15, 0, (-10575540866917705024914736619))]

def f_60_part_0_scale : ℤ := 76320863395569936138240

def f_60_part_0_qExpListZ : List ℤ :=
  [0, 76320863395569936138240, 0, (-11292501761605949770082025719273226240), (-43995982329457061433497160127482030981120), (-106461857800478962407207786956721508488118272), 3689272070753580465435465308619094883680911360, (-1075303579808655309693348106076140433991177338880), 0, (-2119688344775079031298971690810658923156536906055680)]

/-- Integer-arithmetic certificate (the heavy kernel computation). -/
lemma f_60_part_0_evalEisListZ_eq :
    evalEisListZ f_60_part_0_polyDataZ 10 = f_60_part_0_qExpListZ := by
  decide +kernel

end LeanBridge.QExpansion.LMFDB.W60
