import LeanBridge.ForMathlib.QExpansion.IntEval

set_option maxHeartbeats 0
set_option maxRecDepth 4000

/-!
# LMFDB level-1 weight-58 form `1.58.a`, piece 0: integer q-coefficient certificate

Heavy `decide +kernel` over `ℤ` (denominators cleared by the scale `D = 210706707456`), isolated in its own
module so `lake` schedules it in parallel with the other pieces. Generated by
`scripts/lmfdb_qexp_to_e4e6_v3.sage`.
-/

namespace LeanBridge.QExpansion.LMFDB.W58

open LeanBridge.QExpansion

def f_58_part_0_polyDataZ : List (ℕ × ℕ × ℤ) :=
  [(1, 9, (-3540108840342349)), (4, 7, 13555834518766966), (7, 5, (-19426850646344952)), (10, 3, 12346632975821650), (13, 1, (-2935508007901315))]

def f_58_part_0_scale : ℤ := 210706707456

def f_58_part_0_qExpListZ : List ℤ :=
  [0, 210706707456, 0, 3119607386323851474063360, (-30366036773865782758323781632), 10812167491378727361088838154240, 2954954619185605144916898147729408, (-276607800326845063651889996698705920), 0, 37796238628782203956564820027167810560]

/-- Integer-arithmetic certificate (the heavy kernel computation). -/
lemma f_58_part_0_evalEisListZ_eq :
    evalEisListZ f_58_part_0_polyDataZ 10 = f_58_part_0_qExpListZ := by
  decide +kernel

end LeanBridge.QExpansion.LMFDB.W58
