import LeanBridge.ForMathlib.QExpansion.IntEval

set_option maxHeartbeats 0
set_option maxRecDepth 4000

/-!
# LMFDB level-1 weight-58 form `1.58.a`, piece 1: integer q-coefficient certificate

Heavy `decide +kernel` over `ℤ` (denominators cleared by the scale `D = 6657850340278272`), isolated in its own
module so `lake` schedules it in parallel with the other pieces. Generated by
`scripts/lmfdb_qexp_to_e4e6_v3.sage`.
-/

namespace LeanBridge.QExpansion.LMFDB.W58

open LeanBridge.QExpansion

def f_58_part_1_polyDataZ : List (ℕ × ℕ × ℤ) :=
  [(1, 9, (-60505365806)), (4, 7, (-29224446403)), (7, 5, 452935234653), (10, 3, (-576175666873)), (13, 1, 212970244429)]

def f_58_part_1_scale : ℤ := 6657850340278272

def f_58_part_1_qExpListZ : List ℤ :=
  [0, 0, 6657850340278272, 1407079370237596139520, 0, (-53963048230716028260188160), (-113958485809370909489674321920), (-35963491227433636047406549696512), (-1918994707940208369604882090426368), 14555100667932350796790549929000960]

/-- Integer-arithmetic certificate (the heavy kernel computation). -/
lemma f_58_part_1_evalEisListZ_eq :
    evalEisListZ f_58_part_1_polyDataZ 10 = f_58_part_1_qExpListZ := by
  decide +kernel

end LeanBridge.QExpansion.LMFDB.W58
