import LeanBridge.ForMathlib.QExpansion.IntEval

set_option maxHeartbeats 0
set_option maxRecDepth 4000

/-!
# LMFDB level-1 weight-40 form `1.40.a`, piece 2: integer q-coefficient certificate

Heavy `decide +kernel` over `ℤ` (denominators cleared by the scale `D = 866843099136`), isolated in its own
module so `lake` schedules it in parallel with the other pieces. Generated by
`scripts/lmfdb_qexp_to_e4e6_v3.sage`.
-/

namespace LeanBridge.QExpansion.LMFDB.W40

open LeanBridge.QExpansion

def f_40_part_2_polyDataZ : List (ℕ × ℕ × ℤ) :=
  [(1, 6, (-1)), (4, 4, 3), (7, 2, (-3)), (10, 0, 1)]

def f_40_part_2_scale : ℤ := 866843099136

def f_40_part_2_qExpListZ : List ℤ :=
  [0, 0, 0, 5159780352, 866843099136, (-65198984527872), 2026926835236864, (-37847886683701248), 475772036019388416, (-4151825639720091648)]

/-- Integer-arithmetic certificate (the heavy kernel computation). -/
lemma f_40_part_2_evalEisListZ_eq :
    evalEisListZ f_40_part_2_polyDataZ 10 = f_40_part_2_qExpListZ := by
  decide +kernel

end LeanBridge.QExpansion.LMFDB.W40
