import LeanBridge.ForMathlib.QExpansion.IntEval

set_option maxHeartbeats 0
set_option maxRecDepth 4000

/-!
# LMFDB level-1 weight-24 form `1.24.a`, piece 0: integer q-coefficient certificate

Heavy `decide +kernel` over `ℤ` (denominators cleared by the scale `D = 124416`), isolated in its own
module so `lake` schedules it in parallel with the other pieces. Generated by
`scripts/lmfdb_qexp_to_e4e6_v3.sage`.
-/

namespace LeanBridge.QExpansion.LMFDB.W24

open LeanBridge.QExpansion

def f_24_part_0_polyDataZ : List (ℕ × ℕ × ℤ) :=
  [(0, 4, (-29)), (3, 2, (-14)), (6, 0, 43)]

def f_24_part_0_scale : ℤ := 124416

def f_24_part_0_qExpListZ : List ℤ :=
  [0, 124416, 0, 24343234560, 1502961205248, 5555934581760, (-122238636392448), (-18319912611840), 2750369318830080, (-1082465916092928)]

/-- Integer-arithmetic certificate (the heavy kernel computation). -/
lemma f_24_part_0_evalEisListZ_eq :
    evalEisListZ f_24_part_0_polyDataZ 10 = f_24_part_0_qExpListZ := by
  decide +kernel

end LeanBridge.QExpansion.LMFDB.W24
