import LeanBridge.ForMathlib.QExpansion.IntEval

set_option maxHeartbeats 0
set_option maxRecDepth 4000

/-!
# LMFDB level-1 weight-62 form `1.62.a`, piece 3: integer q-coefficient certificate

Heavy `decide +kernel` over `ℤ` (denominators cleared by the scale `D = 1468404249933025602699264`), isolated in its own
module so `lake` schedules it in parallel with the other pieces. Generated by
`scripts/lmfdb_qexp_to_e4e6_v3.sage`.
-/

namespace LeanBridge.QExpansion.LMFDB.W62

open LeanBridge.QExpansion

def f_62_part_3_polyDataZ : List (ℕ × ℕ × ℤ) :=
  [(2, 9, 13), (5, 7, (-16)), (8, 5, (-30)), (11, 3, 56), (14, 1, (-23))]

def f_62_part_3_scale : ℤ := 1468404249933025602699264

def f_62_part_3_qExpListZ : List ℤ :=
  [0, 0, 0, (-185752092672), 0, 1370850443919360, 8274141215981568000, 7478497947676449964032, 1468404249933025602699264, 66140836565233142071296000]

/-- Integer-arithmetic certificate (the heavy kernel computation). -/
lemma f_62_part_3_evalEisListZ_eq :
    evalEisListZ f_62_part_3_polyDataZ 10 = f_62_part_3_qExpListZ := by
  decide +kernel

end LeanBridge.QExpansion.LMFDB.W62
