import LeanBridge.ForMathlib.QExpansion.IntEval

set_option maxHeartbeats 0
set_option maxRecDepth 4000

/-!
# LMFDB level-1 weight-66 form `1.66.a`, piece 0: integer q-coefficient certificate

Heavy `decide +kernel` over `ℤ` (denominators cleared by the scale `D = 72099168165181366272`), isolated in its own
module so `lake` schedules it in parallel with the other pieces. Generated by
`scripts/lmfdb_qexp_to_e4e6_v3.sage`.
-/

namespace LeanBridge.QExpansion.LMFDB.W66

open LeanBridge.QExpansion

def f_66_part_0_polyDataZ : List (ℕ × ℕ × ℤ) :=
  [(0, 11, (-560837728640199360896429459)), (3, 9, 2541995689680934387572702151), (6, 7, (-4487320262543167425409262786)), (9, 5, 3818363935889098484008476026), (12, 3, (-1538561199713159493248971627)), (15, 1, 226359565326493407973485695)]

def f_66_part_0_scale : ℤ := 72099168165181366272

def f_66_part_0_qExpListZ : List ℤ :=
  [0, 72099168165181366272, 0, (-372975805262362328725380760972394496), (-2659989806140895469063836598454770991104), 8334328845159557613469927989309396873756672, (-4818093331931903207818730425378671119503982592), 626783777601068952764805042062487755539060948992, 0, 638820250567736746191392201470963590619086853054464]

/-- Integer-arithmetic certificate (the heavy kernel computation). -/
lemma f_66_part_0_evalEisListZ_eq :
    evalEisListZ f_66_part_0_polyDataZ 10 = f_66_part_0_qExpListZ := by
  decide +kernel

end LeanBridge.QExpansion.LMFDB.W66
