import LeanBridge.ForMathlib.QExpansion.IntEval

set_option maxHeartbeats 0
set_option maxRecDepth 4000

/-!
# LMFDB level-1 weight-68 form `1.68.a`, piece 3: integer q-coefficient certificate

Heavy `decide +kernel` over `ℤ` (denominators cleared by the scale `D = 76966912894271992217941159657416425472`), isolated in its own
module so `lake` schedules it in parallel with the other pieces. Generated by
`scripts/lmfdb_qexp_to_e4e6_v3.sage`.
-/

namespace LeanBridge.QExpansion.LMFDB.W68

open LeanBridge.QExpansion

def f_68_part_3_polyDataZ : List (ℕ × ℕ × ℤ) :=
  [(2, 10, 1394895544443469), (5, 8, (-7039027540137317)), (8, 6, 14146796444812786), (11, 4, (-14155179538049146)), (14, 2, 7051602179991857), (17, 0, (-1399087091061649))]

def f_68_part_3_scale : ℤ := 76966912894271992217941159657416425472

def f_68_part_3_qExpListZ : List ℤ :=
  [0, 0, 0, 311435422343671823990784, 0, (-21661188378658820268222635311104), (-7795747062602600544071207564083200), (-237717969271688894652765637365989376), 76966912894271992217941159657416425472, (-2927202671840482231991347607228959948800)]

/-- Integer-arithmetic certificate (the heavy kernel computation). -/
lemma f_68_part_3_evalEisListZ_eq :
    evalEisListZ f_68_part_3_polyDataZ 10 = f_68_part_3_qExpListZ := by
  decide +kernel

end LeanBridge.QExpansion.LMFDB.W68
