import LeanBridge.ForMathlib.QExpansion.IntEval

set_option maxHeartbeats 0
set_option maxRecDepth 4000

/-!
# LMFDB level-1 weight-70 form `1.70.a`, piece 1: integer q-coefficient certificate

Heavy `decide +kernel` over `ℤ` (denominators cleared by the scale `D = 838924527888270782882283257856`), isolated in its own
module so `lake` schedules it in parallel with the other pieces. Generated by
`scripts/lmfdb_qexp_to_e4e6_v3.sage`.
-/

namespace LeanBridge.QExpansion.LMFDB.W70

open LeanBridge.QExpansion

def f_70_part_1_polyDataZ : List (ℕ × ℕ × ℤ) :=
  [(1, 11, 7067106765281342141041498765), (4, 9, (-35442006769449679134695110633)), (7, 7, 70930497200479337427163674306), (10, 5, (-70810237683426381555396386386)), (13, 3, 35261477016806756662874698561), (16, 1, (-7006836529691375540988374613))]

def f_70_part_1_scale : ℤ := 838924527888270782882283257856

def f_70_part_1_qExpListZ : List ℤ :=
  [0, 0, 838924527888270782882283257856, 860458847883590978010800662920560640, 0, (-108984794723990192255707359537251338357309440), 41847246759690349116913645897819495290686668800, 10527428064238392095586733800423165952309774516224, (-990427268039202721588351241280128506295646047698944), 29300565469015336485360318125154300234815935139020800]

/-- Integer-arithmetic certificate (the heavy kernel computation). -/
lemma f_70_part_1_evalEisListZ_eq :
    evalEisListZ f_70_part_1_polyDataZ 10 = f_70_part_1_qExpListZ := by
  decide +kernel

end LeanBridge.QExpansion.LMFDB.W70
