import LeanBridge.ForMathlib.QExpansion.IntEval

set_option maxHeartbeats 0
set_option maxRecDepth 4000

/-!
# LMFDB level-1 weight-40 form `1.40.a`, piece 1: integer q-coefficient certificate

Heavy `decide +kernel` over `ℤ` (denominators cleared by the scale `D = 12039487488`), isolated in its own
module so `lake` schedules it in parallel with the other pieces. Generated by
`scripts/lmfdb_qexp_to_e4e6_v3.sage`.
-/

namespace LeanBridge.QExpansion.LMFDB.W40

open LeanBridge.QExpansion

def f_40_part_1_polyDataZ : List (ℕ × ℕ × ℤ) :=
  [(1, 6, 4295), (4, 4, (-8853)), (7, 2, 4821), (10, 0, (-263))]

def f_40_part_1_scale : ℤ := 12039487488

def f_40_part_1_qExpListZ : List ℤ :=
  [0, 0, 12039487488, (-11181244022784), 0, 828571804316467200, 18652366042693632000, (-248829318998895624192), (-3484948491811537551360), 63917460732863840256000]

/-- Integer-arithmetic certificate (the heavy kernel computation). -/
lemma f_40_part_1_evalEisListZ_eq :
    evalEisListZ f_40_part_1_polyDataZ 10 = f_40_part_1_qExpListZ := by
  decide +kernel

end LeanBridge.QExpansion.LMFDB.W40
