import LeanBridge.ForMathlib.QExpansion.IntEval

set_option maxHeartbeats 0
set_option maxRecDepth 4000

/-!
# LMFDB level-1 weight-52 form `1.52.a`, piece 0: integer q-coefficient certificate

Heavy `decide +kernel` over `ℤ` (denominators cleared by the scale `D = 4839497736192`), isolated in its own
module so `lake` schedules it in parallel with the other pieces. Generated by
`scripts/lmfdb_qexp_to_e4e6_v3.sage`.
-/

namespace LeanBridge.QExpansion.LMFDB.W52

open LeanBridge.QExpansion

def f_52_part_0_polyDataZ : List (ℕ × ℕ × ℤ) :=
  [(1, 8, (-1589028971633357)), (4, 6, 5642355704074508), (7, 4, (-7392897133296870)), (10, 2, 4214840240268380), (13, 0, (-875269839412661))]

def f_52_part_0_scale : ℤ := 4839497736192

def f_52_part_0_qExpListZ : List ℤ :=
  [0, 4839497736192, 0, 3682839370675951813754880, (-10897580100687325076826095616), (-980984227604206792971120427008), 373886034415093822036600166547456, (-5817495762611734403918689990410240), 0, (-1028490966326509616592692876727705600)]

/-- Integer-arithmetic certificate (the heavy kernel computation). -/
lemma f_52_part_0_evalEisListZ_eq :
    evalEisListZ f_52_part_0_polyDataZ 10 = f_52_part_0_qExpListZ := by
  decide +kernel

end LeanBridge.QExpansion.LMFDB.W52
