import LeanBridge.ForMathlib.QExpansion.IntEval

set_option maxHeartbeats 0
set_option maxRecDepth 4000

/-!
# LMFDB level-1 weight-68 form `1.68.a`, piece 2: integer q-coefficient certificate

Heavy `decide +kernel` over `ℤ` (denominators cleared by the scale `D = 2254890026199374772009994911838371840`), isolated in its own
module so `lake` schedules it in parallel with the other pieces. Generated by
`scripts/lmfdb_qexp_to_e4e6_v3.sage`.
-/

namespace LeanBridge.QExpansion.LMFDB.W68

open LeanBridge.QExpansion

def f_68_part_2_polyDataZ : List (ℕ × ℕ × ℤ) :=
  [(2, 10, (-872186440602877982647519)), (5, 8, 4370333975189227640373095), (8, 6, (-8987159011677522413876230)), (11, 4, 9461337589925981225865310), (14, 2, (-5081601842561915858356715)), (17, 0, 1109275729727107388642059)]

def f_68_part_2_scale : ℤ := 2254890026199374772009994911838371840

def f_68_part_2_qExpListZ : List ℤ :=
  [0, 0, 0, 1174817576351138162929168369582080, 2254890026199374772009994911838371840, 15285898575586699525520566330606498086912, 5688815572677058342438786673437782080225280, 394911886957779228726427501820372497842831360, 0, 7637804904181512455455534074457590566310106890240]

/-- Integer-arithmetic certificate (the heavy kernel computation). -/
lemma f_68_part_2_evalEisListZ_eq :
    evalEisListZ f_68_part_2_polyDataZ 10 = f_68_part_2_qExpListZ := by
  decide +kernel

end LeanBridge.QExpansion.LMFDB.W68
