import LeanBridge.ForMathlib.QExpansion.IntEval

set_option maxHeartbeats 0
set_option maxRecDepth 4000

/-!
# LMFDB level-1 weight-34 form `1.34.a`, piece 0: integer q-coefficient certificate

Heavy `decide +kernel` over `ℤ` (denominators cleared by the scale `D = 6912`), isolated in its own
module so `lake` schedules it in parallel with the other pieces. Generated by
`scripts/lmfdb_qexp_to_e4e6_v3.sage`.
-/

namespace LeanBridge.QExpansion.LMFDB.W34

open LeanBridge.QExpansion

def f_34_part_0_polyDataZ : List (ℕ × ℕ × ℤ) :=
  [(1, 5, (-1)), (4, 3, (-2)), (7, 1, 3)]

def f_34_part_0_scale : ℤ := 6912

def f_34_part_0_qExpListZ : List ℤ :=
  [0, 6912, 0, (-153031680), (-531492765696), (-203540485824000), (-18358746161872896), (-569172590616913920), (-7159911003130429440), (-32696294445406036224)]

/-- Integer-arithmetic certificate (the heavy kernel computation). -/
lemma f_34_part_0_evalEisListZ_eq :
    evalEisListZ f_34_part_0_polyDataZ 10 = f_34_part_0_qExpListZ := by
  decide +kernel

end LeanBridge.QExpansion.LMFDB.W34
