import LeanBridge.ForMathlib.QExpansion.IntEval

set_option maxHeartbeats 0
set_option maxRecDepth 4000

/-!
# LMFDB level-1 weight-62 form `1.62.a`, piece 0: integer q-coefficient certificate

Heavy `decide +kernel` over `ℤ` (denominators cleared by the scale `D = 810404756517888`), isolated in its own
module so `lake` schedules it in parallel with the other pieces. Generated by
`scripts/lmfdb_qexp_to_e4e6_v3.sage`.
-/

namespace LeanBridge.QExpansion.LMFDB.W62

open LeanBridge.QExpansion

def f_62_part_0_polyDataZ : List (ℕ × ℕ × ℤ) :=
  [(2, 9, (-189882324625451553577)), (5, 7, 814085965860012518143), (8, 5, (-1302963950400531185751)), (11, 3, 923199301253846797285), (14, 1, (-244438992087876576100))]

def f_62_part_0_scale : ℤ := 810404756517888

def f_62_part_0_qExpListZ : List ℤ :=
  [0, 810404756517888, 0, (-281500421193400708016764416000), (-1868666142450297823384897245413376), 226317410202434954991177249502525440, 367331583231544511331490565744171679744, 48011565880021567929622280664161006592000, 0, 136271194446476622363662494776594349889233920]

/-- Integer-arithmetic certificate (the heavy kernel computation). -/
lemma f_62_part_0_evalEisListZ_eq :
    evalEisListZ f_62_part_0_polyDataZ 10 = f_62_part_0_qExpListZ := by
  decide +kernel

end LeanBridge.QExpansion.LMFDB.W62
