import LeanBridge.ForMathlib.QExpansion.IntEval

set_option maxHeartbeats 0
set_option maxRecDepth 4000

/-!
# LMFDB level-1 weight-70 form `1.70.a`, piece 2: integer q-coefficient certificate

Heavy `decide +kernel` over `ℤ` (denominators cleared by the scale `D = 61852227592146428280344980035207168`), isolated in its own
module so `lake` schedules it in parallel with the other pieces. Generated by
`scripts/lmfdb_qexp_to_e4e6_v3.sage`.
-/

namespace LeanBridge.QExpansion.LMFDB.W70

open LeanBridge.QExpansion

def f_70_part_2_polyDataZ : List (ℕ × ℕ × ℤ) :=
  [(1, 11, (-11466068567437700807177)), (4, 9, 62228902538461555674005), (7, 7, (-137445744153895098590106)), (10, 5, 153624502905292969798058), (13, 3, (-86497040665558362485933)), (16, 1, 19555447943136636411153)]

def f_70_part_2_scale : ℤ := 61852227592146428280344980035207168

def f_70_part_2_qExpListZ : List ℤ :=
  [0, 0, 0, 16463928662877712967255627661312, 61852227592146428280344980035207168, 196977743523700061776301105068948586496, (-78621072637829445633967602022275241476096), (-24430541593090302794472446926742269967990784), 0, (-213033800274108767928148229928935700598276227072)]

/-- Integer-arithmetic certificate (the heavy kernel computation). -/
lemma f_70_part_2_evalEisListZ_eq :
    evalEisListZ f_70_part_2_polyDataZ 10 = f_70_part_2_qExpListZ := by
  decide +kernel

end LeanBridge.QExpansion.LMFDB.W70
