import LeanBridge.ForMathlib.QExpansion.IntEval

set_option maxHeartbeats 0
set_option maxRecDepth 4000

/-!
# LMFDB level-1 weight-58 form `1.58.a`, piece 3: integer q-coefficient certificate

Heavy `decide +kernel` over `ℤ` (denominators cleared by the scale `D = 61849618725892591190016`), isolated in its own
module so `lake` schedules it in parallel with the other pieces. Generated by
`scripts/lmfdb_qexp_to_e4e6_v3.sage`.
-/

namespace LeanBridge.QExpansion.LMFDB.W58

open LeanBridge.QExpansion

def f_58_part_3_polyDataZ : List (ℕ × ℕ × ℤ) :=
  [(1, 9, 2), (4, 7, 1), (7, 5, (-15)), (10, 3, 19), (13, 1, (-7))]

def f_58_part_3_scale : ℤ := 61849618725892591190016

def f_58_part_3_qExpListZ : List ℤ :=
  [0, 0, 0, (-46438023168), 0, 1780433808261120, 3757601372913008640, 1182711758486273261568, 61849618725892591190016, (-673705395364019904184320)]

/-- Integer-arithmetic certificate (the heavy kernel computation). -/
lemma f_58_part_3_evalEisListZ_eq :
    evalEisListZ f_58_part_3_polyDataZ 10 = f_58_part_3_qExpListZ := by
  decide +kernel

end LeanBridge.QExpansion.LMFDB.W58
