import LeanBridge.ForMathlib.QExpansion.IntEval

set_option maxHeartbeats 0
set_option maxRecDepth 4000

/-!
# LMFDB level-1 weight-70 form `1.70.a`, piece 4: integer q-coefficient certificate

Heavy `decide +kernel` over `ℤ` (denominators cleared by the scale `D = 41042169323223946778279472192321786740736`), isolated in its own
module so `lake` schedules it in parallel with the other pieces. Generated by
`scripts/lmfdb_qexp_to_e4e6_v3.sage`.
-/

namespace LeanBridge.QExpansion.LMFDB.W70

open LeanBridge.QExpansion

def f_70_part_4_polyDataZ : List (ℕ × ℕ × ℤ) :=
  [(1, 11, 958183), (4, 9, (-3988123)), (7, 7, 7627206), (10, 5, (-8534710)), (13, 3, 5349379), (16, 1, (-1411935))]

def f_70_part_4_scale : ℤ := 41042169323223946778279472192321786740736

def f_70_part_4_qExpListZ : List ℤ :=
  [0, 0, 0, (-6483491042623488), 0, (-13996008502701236158464), 5396426071179715323887616, 1466037611550321177280905216, 0, 45395299705594581557266467520512]

/-- Integer-arithmetic certificate (the heavy kernel computation). -/
lemma f_70_part_4_evalEisListZ_eq :
    evalEisListZ f_70_part_4_polyDataZ 10 = f_70_part_4_qExpListZ := by
  decide +kernel

end LeanBridge.QExpansion.LMFDB.W70
