import Verso
import VersoManual
import VersoBlueprint

open Verso Verso.Genre Verso.Genre.Manual Informal

tex_prelude r#"\def\C{\mathbb{C}}
\def\R{\mathbb{R}}
\def\Q{\mathbb{Q}}
\def\Z{\mathbb{Z}}
\def\F{\mathbb{F}}
\def\H{\mathbb{H}}
\def\HH{\mathcal{H}}
\def\integers{\mathcal{O}}
\def\SL{\textrm{SL}}
\def\GL{\textrm{GL}}
\def\PSL{\textrm{PSL}}
\def\PGL{\textrm{PGL}}
\def\ASL{\textrm{ASL}}
\def\AGL{\textrm{AGL}}
\def\ASp{\textrm{ASp}}
\def\Sp{\textrm{Sp}}
\def\PSp{\textrm{PSp}}
\def\SO{\textrm{SO}}
\def\PSO{\textrm{PSO}}
\def\PO{\textrm{PO}}
\def\PGO{\textrm{PO}}
\def\SU{\textrm{SU}}
\def\PSU{\textrm{PSU}}
\def\SOPlus{\textrm{SO}^+}
\def\SOMinus{\textrm{SO}^-}
\def\GO{\textrm{O}}
\def\Orth{\textrm{O}}
\def\GOPlus{\textrm{O}^+}
\def\OPlus{\textrm{O}^+}
\def\OrthPlus{\textrm{O}^+}
\def\GOMinus{\textrm{O}^-}
\def\OrthMinus{\textrm{O}^-}
\def\OMinus{\textrm{O}^-}
\def\GU{\textrm{GU}}
\def\Unitary{\textrm{U}}
\def\CSp{\textrm{GSp}}
\def\GSp{\textrm{GSp}}
\def\CSO{\textrm{GSO}}
\def\GSO{\textrm{GSO}}
\def\CSOPlus{\textrm{GSO}^+}
\def\GSOPlus{\textrm{GSO}^+}
\def\CSOMinus{\textrm{GSO}^-}
\def\GSOMinus{\textrm{GSO}^-}
\def\CSU{\textrm{GSU}}
\def\GSU{\textrm{GSU}}
\def\CO{\textrm{GO}}
\def\GOrth{\textrm{GO}}
\def\COPlus{\textrm{GO}^+}
\def\GOrthPlus{\textrm{GO}^+}
\def\COMinus{\textrm{GO}^-}
\def\GOrthMinus{\textrm{GO}^-}
\def\CU{\textrm{GU}}
\def\GUnitary{\textrm{GU}}
\def\OmegaPlus{\Omega^+}
\def\OmegaMinus{\Omega^-}
\def\Spin{\textrm{Spin}}
\def\SpinPlus{\textrm{Spin}^+}
\def\SpinMinus{\textrm{Spin}^-}
\def\PSOPlus{\textrm{PSO}^+}
\def\POPlus{\textrm{PO}^+}
\def\PGOPlus{\textrm{PO}^+}
\def\PU{\textrm{PU}}
\def\PGU{\textrm{PU}}
\def\PSOMinus{\textrm{PSO}^-}
\def\POMinus{\textrm{PO}^-}
\def\PGOMinus{\textrm{PO}^-}
\def\POmega{\textrm{P}\Omega}
\def\POmegaPlus{\textrm{P}\Omega^+}
\def\POmegaMinus{\textrm{P}\Omega^-}
\def\PGammaL{\textrm{P}\Gamma\textrm{L}}
\def\PSigmaL{\textrm{P}\Sigma\textrm{L}}
\def\PSigmaSp{\textrm{P}\Sigma\textrm{Sp}}
\def\PGammaU{\textrm{P}\Gamma\textrm{U}}
\def\AGammaL{\textrm{A}\Gamma\textrm{L}}
\def\ASigmaL{\textrm{A}\Sigma\textrm{L}}
\def\ASigmaSp{\textrm{A}\Sigma\textrm{Sp}}
\def\Dic{\textrm{Dic}}
\def\SD{\textrm{SD}}
\def\OD{\textrm{OD}}
\def\He{\textrm{He}}
\def\HS{\textrm{HS}}
\def\McL{\textrm{McL}}
\def\Ru{\textrm{Ru}}
\def\Co{\textrm{Co}}
\def\Aut{\operatorname{Aut}}
\def\Out{\operatorname{Out}}
\def\End{\operatorname{End}}
\def\Gal{\operatorname{Gal}}
\def\Hom{\operatorname{Hom}}
\def\Ord{\operatorname{Ord}}
\def\Pic{\operatorname{Pic}}
\def\Reg{\operatorname{Rec}}
\def\Res{\operatorname{Res}}
\def\sgn{\operatorname{sgn}}
\def\Spec{\operatorname{Spec}}
\def\Sym{\operatorname{Sym}}
\def\trace{\operatorname{trace}}
\def\ideal#1{\mathfrak{ #1 }}
\def\classgroup#1{Cl(#1)}
\def\modstar#1#2{\left( #1/#2 \right)^\times}
\def\card#1{\# #1}
\def\Sha{\text{Ш}}
\def\smallsetminus{\setminus}"#
